### ISSUE TITLE
Unstagging error from Travis lead to empty feedstock

### ISSUE THREAD

**Issue by Faylixe** [conda-forge/staged-recipes#10001]
Package `stempeg` associated feedstock is empty leading to error in package depending to it.
Next to the `stempeg` PR merging the CI failed and the feedstock repository was created but not filled with recipe nor CI scripts.

- Target feedstock: https://github.com/conda-forge/stempeg-feedstock/
- Associated PR: https://github.com/conda-forge/staged-recipes/pull/9998

Any help would be greatly appreciated as it is blocking other package development.

**Comment by s-weigand** [comment]
@conda-forge/staged-recipes
Same problem here:

- Target feedstock: https://github.com/conda-forge/flake8-nb-feedstock
- Associated PR: #10006 
- Travis build: https://travis-ci.org/conda-forge/staged-recipes/builds/604469685

**Comment by chrisburr** [comment]
It looks like a travis bug: https://docs.travis-ci.com/user/enterprise/troubleshooting-guide/#user-accounts-are-stuck-in-syncing-state

```
 * Travis: checking if there's a syncing already.................... * Travis is being synced by somebody else. Ignoring

 * Travis repo settings are not writable, syncing (takes a few seconds).....................Traceback (most recent call last):

  File "/home/travis/miniconda/bin/conda-smithy", line 10, in <module>

    sys.exit(main())

  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/cli.py", line 485, in main

    args.subcommand_func(args)

  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/cli.py", line 215, in __call__

    ci_register.add_project_to_travis(owner, repo)

  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/ci_register.py", line 397, in add_project_to_travis

    travis_wait_until_synced(ignore=False)

  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/ci_register.py", line 331, in travis_wait_until_synced

    raise RuntimeError("Syncing has not finished for two minutes now.")

RuntimeError: Syncing has not finished for two minutes now.
```

@conda-forge/core Can someone raise the issue with travis using the conda-forge organisation?

**Comment by Faylixe** [comment]
The issue appears to be solved, or at least my target feedstock repository has been fixed and well populated so I close this one.
