### ISSUE TITLE
public mirror of anaconda.org/conda-forge ?

### ISSUE THREAD

**Issue by Tagar** [conda-forge/staged-recipes#10132]
Is there is a public mirror of `anaconda.org/conda-forge` ?

We found that anaconda.org default channels are also available on continuum.io as 
  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch

to workaround 
https://github.com/conda/conda/issues/9430

but can't find a similar mirror for conda-forge..

Thanks!

**Comment by Tagar** [comment]
We got details from Cisco Talos why they blacklisted whole `anaconda.org` domain.

![image](https://user-images.githubusercontent.com/3013418/68706815-c4c3ac00-054d-11ea-9675-9dd467076867.png)

See details at 

https://www.virustotal.com/gui/domain/anaconda.org/relations

**Comment by Tagar** [comment]
There are multiple conda-forge packages with multiple phishing atachments

See for example 

https://www.virustotal.com/gui/url/220df9fa6f6b8dce9e119703b4e9837b00a336b2717f5a0d419651a85b9ee7c7/detection

**Comment by isuruf** [comment]
> There are multiple conda-forge packages with multiple phishing atachments

Given example is not a conda-forge package

**Comment by msarahan** [comment]
Indeed, given example is a spammer who is abusing the site.  We will remove them when we are able, but that's a never ending struggle.  The conda-forge (and anaconda and rdkit) hits here are false positives.

**Comment by isuruf** [comment]
You can use https://conda-static.anaconda.org which has only a few channels.

**Comment by Tagar** [comment]
Thank you @msarahan and @isuruf 

Unfortunately Cisco Talos has blacklisted `anaconda.org` in its entirety so conda-static.anaconda.org  is not usable too

All enterprises that use this Cisco intrusion prevention service will have anaconda.org completely down 

They have blacklisted it 3 days and the updated list propagated to us yesterday night.

**Comment by Tagar** [comment]
@msarahan Yep those that have just 1 count looks like false positives.

And those that were detected as specious / malicious / phishing by 4-6 virus scanner programs look like valid abuses .. 

Perhaps `conda-forge` can crawl https://www.virustotal.com/gui/domain/anaconda.org/relations regularly and blocks with high count ?

**Comment by isuruf** [comment]
> Perhaps conda-forge can crawl https://www.virustotal.com/gui/domain/anaconda.org/relations regularly and block uploads/ packages with high count of suspicions ?

I don't understand what you are saying here. There aren't any conda-forge packages with high counts of suspicions.

**Comment by Tagar** [comment]
@isuruf look at that virus total report and try to follow those links that have 4-6 red flags

This for example 
https://anaconda.org/heyopler/putlockershq-watch-doctor-sleep-2019-full-or-free-123movies/notebook

All those links start with "heyopler" so it might be just one bad / compromised actor here

**Comment by Tagar** [comment]
See "detections" column I posted earlier 

![image](https://user-images.githubusercontent.com/3013418/68711538-0ad13d80-0557-11ea-9f44-94800489c6b1.png)

**Comment by isuruf** [comment]
But that is from `heyopler` not from `conda-forge`.

**Comment by isuruf** [comment]
`conda-forge` URLs startwith https://anaoconda.org/conda-forge

**Comment by Tagar** [comment]
Yes you're right .. it's still under `anaconda.org` and that domain remains blocked..  

Any chance that heyopler can be deleted? 

Also please submit a dispute ticket at 
https://talosintelligence.com/reputation 
as this can only come from owners.. 

Thank you!

**Comment by isuruf** [comment]
Please open an issue at https://github.com/ContinuumIO/anaconda-issues/. We at conda-forge, don't control `anaconda.org`.
