### ISSUE TITLE
Package conda-standalone

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#10160]
Would be great to have a package for [`conda-standalone`]( https://github.com/AnacondaRecipes/conda-standalone-feedstock ). This is needed for [`constructor` version `3.0.1`]( https://github.com/conda/constructor/blob/0b37021e535989f36cf9dbb98c281a68cb7dc672/conda.recipe/meta.yaml#L25 ).

**Comment by hadim** [comment]
@jakirkham I would be happy to do it myself but since this is not a conventional package, I am not sure how to do it. If you provide me some guidance to get started that would be great unless you want to do it yourself.

**Comment by hadim** [comment]
Here is a first attempt: https://github.com/conda-forge/staged-recipes/pull/10166

**Comment by jakirkham** [comment]
Thanks for doing that! 😀

Closed by PR ( https://github.com/conda-forge/staged-recipes/pull/10166 )
