### ISSUE TITLE
Package jupyter_bokeh

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#10172]
Would be great to have a package for [`jupyter_bokeh`]( https://github.com/bokeh/jupyter_bokeh ). This is needed for Bokeh to produce plots in JupyterLab.

**Comment by hmaarrfk** [comment]
do we have an example of jupyter lab extension packages?

**Comment by bollwyvl** [comment]
PR opened here:
https://github.com/conda-forge/staged-recipes/pull/11728

I didn't put the labextension in it, or any flavor of node/lab dependencies: I've not found that re-packaging node tarballs has given me a lot of value, as I usually doing out-of-band, full Lab builds (either packaged or checked in). There's some stuff with native JS modules on the horizon for Lab, but for now... as PRd, it at least works with notebook classic!

**Comment by jakirkham** [comment]
Thanks Nick! 😄

**Comment by bollwyvl** [comment]
No problem! I've been experimenting with a pretty [heavy constructor](https://github.com/gt-coar/gt-coar-lab) and this was in the column of  "quick wins to make pretties". Some of the hard stuff is going to be... hard.
