### ISSUE TITLE
Add script for building locally on docker

### ISSUE THREAD

**Issue by douglowe** [conda-forge/staged-recipes#10189]
I am told that the feedstock has a script called build-locally.py, for building using docker. Please could this be added to the staged-recipes repository, as I am finding that the run_docker_build.sh script is not working for me anymore.

**Comment by scopatz** [comment]
This would be great to have! PRs welcome!

**Comment by carterbox** [comment]
Please see 6362bc43261508e35915b4c7efec9678e9c3194a.
