### ISSUE TITLE
personal access token expired for azure

### ISSUE THREAD

**Issue by beckermr** [conda-forge/staged-recipes#10182]
It looks like the travis CI runs are failing with some warning about an expired token on azure:
https://travis-ci.org/conda-forge/staged-recipes/builds/613074173#L975

@conda-forge/core can you take a look?

**Comment by mariusvniekerk** [comment]
Guess i need to go regenerate that token

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/conda-forge/staged-recipes/pull/10185 ).
