### ISSUE TITLE
Package pyglet

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#1029]
This seems like a super neat library that would be great to package, which I only now have heard of. Basically a Python interface to the OpenGL library. Looks like it can be used as a `matplotlib` backend too.

**Comment by mwcraig** [comment]
This would be great to have. @CatherineH is giving a talk about https://github.com/CatherineH/pyglet_helper at SciPy Friday, so perhaps we could get both in here by then. 

@CatherineH -- I can help with pyglet_helper if you want.

**Comment by mwcraig** [comment]
Oops, just realized that this is an issue, not a PR. Will try to get a pyglet recipe worked up later today.

**Comment by jakirkham** [comment]
Yeah, I didn't have time to do it yet, but wanted to make sure it was listed as something worth doing.
