### ISSUE TITLE
staged recipes broken on travis 403 errors

### ISSUE THREAD

**Issue by beckermr** [conda-forge/staged-recipes#10438]
Alright @conda-forge/core @conda-forge/staged-recipes, it appears that staged-recipes will be broken until someone can diagnose the 403 error we are getting on travis-ci.com. 

It appears that when we ask travis-ci.com to make sure repos build only with yaml [here](https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/ci_register.py#L463) in conda-smithy, we are getting a 403 HTTP code, meaning we don't have permission. 

@ocefpaf tried to reset update the permissions/keys/whatever, but it is still not working. 

Can someone on @conda-forge/core look into this? I think you all are the only ones with keys.

**Comment by chrisburr** [comment]
This looks identical to https://github.com/conda-forge/staged-recipes/issues/5846 with the error response:
```
{
  "@type": "error",
  "error_type": "insufficient_access",
  "error_message": "operation requires create_request access to repository",
  "resource_type": "repository",
  "permission": "create_request",
  "repository": {
    "@type": "repository",
    "@href": "/repo/6246397",
    "@representation": "minimal",
    "id": 6246397,
    "name": "staged-recipes",
    "slug": "conda-forge/staged-recipes"
  }
}
```

**Comment by ocefpaf** [comment]
> @ocefpaf tried to reset update the permissions/keys/whatever, but it is still not working.

Yep. Not sure it is related to that. @isuruf and @mariusvniekerk, do you have an idea on how to debug this?

**Comment by beckermr** [comment]
Bump here @conda-forge/core. I know we are all very busy, but any help you can provide would be appreciated!

**Comment by beckermr** [comment]
Looks like @chrisburr moved us back to .org and this fixed things. I guess this means this is an upstream issue with Travis?

**Comment by hmaarrfk** [comment]
the keys encrypted for .org and .com are not compatible.

**Comment by beckermr** [comment]
@ocefpaf is writing Travis to see if this is a bug on their end.

**Comment by isuruf** [comment]
It's not a travis-ci issue anymore.

**Comment by beckermr** [comment]
I’m not following but glad you all are on it. Thanks!

**Comment by beckermr** [comment]
Now we are getting drone errors. I guess we need to go through and reencrypt all of the keys or something?

```
Traceback (most recent call last):
  File ".travis_scripts/create_feedstocks.py", line 161, in <module>
    drone_sync()
  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/ci_register.py", line 163, in drone_sync
    response.raise_for_status()
  File "/home/travis/miniconda/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://cloud.drone.io/api/user/repos?async=true
+++python .travis_scripts/trigger_travis_build.py conda-forge/staged-recipes
b'access denied'
```

**Comment by beckermr** [comment]
This appears resolved. Thanks @ocefpaf! Closing!
