### ISSUE TITLE
Suggest that folks give their PRs meaningful names

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [conda-forge/staged-recipes#10487]
I've noticed recently that a number of PRs to staged-recipes are titled something like:

"added meta.yaml file"

As opposed to something like:

Add my_nifty_package, version 1.2.3

It makes it hard to browse through the PRs and know what they are.

I suggest that we add to the PR checklist:

 [ ] Give the PR a meaningful name, with the name of the package being proposed in it.

-CHB

@conda-forge/staged-recipes

**Comment by beckermr** [comment]
Feel free to send a PR with this change!

**Comment by ChrisBarker-NOAA** [comment]
Done in #10489

Thanks.
