### ISSUE TITLE
Package neuralcoref

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/staged-recipes#10517]
[neuralcoref](https://github.com/huggingface/neuralcoref) is a nice addition to the [spacy ecosystem](https://spacy.io/universe/project/neuralcoref). 

Building it presents some challenges, which make it a good candidate for conda(-forge) building:
- it does a cython build against `pxd` files 
  - which are not distributed in the `spacy` tarball
- it downloads an (unversioned) model from s3
  - which it stores in `~/.neuralcoref_cache`
- it ships its tests
  - which really only test whether spacy will recognize it

I'm presently taking a look at addressing those problems, and think it might end up requiring 3 packages and a fairly explicit `conda-build-config.yaml`:
- `neuralcoref-model`
  - `noarch: generic`
  - downloaded from s3
  - copied to `$PREFIX/share/neuralcoref_cache`
- `spacy-cython-sources`
  - `noarch: python`?
  - extracted from the github tag tarball
  - should probably be upstreamed as a multiple input/output of @conda-forge/spacy-feedstock
  - used as a build dependency of...
- `neuralcoref`
  - the python + cython build of the package itself
  - uses `neuralcoref-model` to test

Happy for feedback while I start plumbing! :wrench:

**Comment by bollwyvl** [comment]
Having some issues finding a combination of spacy/neuralcoref which can actually run the [hello world](https://spacy.io/universe/project/neuralcoref) with out segfaulting after building...

**Comment by oblute** [comment]
@bollwyvl i built and added this package to the conda-forge a week or so ago - the feedstock is here https://github.com/conda-forge/neuralcoref-feedstock

**Comment by bollwyvl** [comment]
Awesome! Thanks so much!
