### ISSUE TITLE
[package request] pythonocc-core

### ISSUE THREAD

**Issue by HalfManHalfChicken** [conda-forge/staged-recipes#10525]
My new year wish is that pythonocc-core can maintain a package on conda-forge:

* Compatibility with a much larger python eco system
* ability to leverage power automatic update tools to avoid hassle when deploying to various architecture
* ensured binary compatibility with other's software

Thank you very much.

**Comment by looooo** [comment]
I guess it's good to wait for the 7.4 release of pythonocc-core.
