### ISSUE TITLE
conda-forge "miniconda" installer

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#1063]
Packages needed. Below is a list of everything that we typical install/miniconda plus a few things gives you. Everything checked off is done. Anything in progress or ready to go has a PR. The rest are not yet done. I could use reviews and/or help with any PRs that are open. PRs welcome for anything else that is not done. In addition to this effort to package everything needed in Miniconda, there is an effort to create a Miniconda installer ( please see this repo https://github.com/loriab/anvil ). It is my hope that these to efforts join to create a `conda-forge` installer.

* [x] anaconda-client ( https://github.com/conda-forge/staged-recipes/pull/1061 )
* [x] conda ( https://github.com/conda-forge/staged-recipes/pull/656 )
* [x] conda-build ( https://github.com/conda-forge/staged-recipes/pull/1065 )
* [x] conda-env ( https://github.com/conda-forge/staged-recipes/pull/1064 )
* [x] constructor ( https://github.com/conda-forge/staged-recipes/pull/1078 )
* [X] clyent
* [X] jinja2
* [x] libconda ( https://github.com/conda-forge/staged-recipes/pull/1077 )
* [X] markupsafe
* [X] ncurses
* [x] nsis ( https://github.com/conda-forge/staged-recipes/pull/1089 )
* [X] openssl
* [X] patchelf
* [X] pip
* [X] pycosat
* [X] pycrypto
* [X] python
* [X] python-dateutil
* [X] pytz
* [X] pyyaml
* [X] readline
* [X] requests
* [X] setuptools
* [X] six
* [X] sqlite
* [X] tk
* [X] xz
* [X] yaml
* [X] zlib
* [x] ruamel_yaml ( https://github.com/conda-forge/staged-recipes/pull/1066 )
* [x] wheel ( https://github.com/conda-forge/staged-recipes/pull/1060 )

xref: https://github.com/conda-forge/conda-forge.github.io/issues/90

**Comment by jakirkham** [comment]
I might give `conda-build` a try in a moment.

**Comment by jakirkham** [comment]
Tagging you on here @jjhelmus because of our discussion w.r.t. to caching in issue ( https://github.com/conda-forge/staged-recipes/issues/610 ).

**Comment by jakirkham** [comment]
Now down to 2 packages, which have working PRs and have already been reviewed. Once merged we should be ready to package and distribute the `conda-forge` stack.

**Comment by loriab** [comment]
Wow, those checkboxes ticked off quickly. Sorry to disappear for a while (my main project decided to rewrite their CMake, which is always a time drain), but I'm still glad to chip in, however is convenient.

**Comment by jakirkham** [comment]
> Wow, those checkboxes ticked off quickly.

We've been very motivated. 😄

> Sorry to disappear for a while (my main project decided to rewrite their CMake, which is always a time drain)

No worries. Rewriting build scripts is always painful.

> I'm still glad to chip in, however is convenient.

Great! I think we should migrate your work on [anvil]( https://github.com/loriab/anvil ) over here and make sure you have permissions on it. Then we can sort out the remaining issues (e.g. build on all CIs, deploying installers, and other issues). How does that sound?

**Comment by loriab** [comment]
Gave the transfer a try but rejected b/c I'm not admin on conda-forge organization. Shall I try transferring it to your individual account, then you can migrate it to conda-forge? It looks like individuals are allowed to accept or reject initiated transfers.

**Comment by jakirkham** [comment]
Sure that sounds reasonable. Please let me know when you have tried to transfer it and I can try to figure out what I need to do on my end.

**Comment by loriab** [comment]
Ok, that attempt was rejected b/c you've got a fork of loriab/anvil. The GitHub state of your fork looks to be even with my upstream. I can try to transfer again after you delete your fork, or I'll do whatever else you suggest. Even if you'd rather start afresh on conda-forge org with a new repo of the existing contents and no history, that's fine too.

**Comment by jakirkham** [comment]
Oops. 😳 Sorry about that. I have deleted the fork now.

**Comment by loriab** [comment]
Thanks, transfer request initiated.

**Comment by jakirkham** [comment]
Thanks @loriab. I have moved it into the org as this [repo]( https://github.com/conda-forge/conda-forge-anvil ). Currently I have prefixed it with `conda-forge-` as we do with some other org repos. Though we can certainly discuss naming and have placed it in issue ( https://github.com/conda-forge/conda-forge-anvil/issues/1 ). Also I have created the `conda-forge-anvil` team, which I have invited you to join.

**Comment by loriab** [comment]
Great, thank you, @jakirkham. And sure, I'm not attached to the name.

**Comment by jakirkham** [comment]
Also I have added a few people to the repo ( @pelson @ocefpaf @mwcraig @jjhelmus ) based on past interest/org role. Given configuring CIs is part of the work required, it seemed like admin privileges on the repo would be necessary to get this done and have given them to the `conda-forge-anvil` team. If other people are interested in helping maintain, please let us know and we can add you.

**Comment by jakirkham** [comment]
> Great, thank you, @jakirkham.

Thank you for putting this altogether.

> And sure, I'm not attached to the name.

Me neither. Honestly `anvil` seems fine to. Just worried we lose track of it. Really whatever people agree on I'm 👍.

**Comment by jakirkham** [comment]
🎉 All of these are now packaged and released! 🎉

Thanks everyone for your help. If anyone would like to help maintain these packages (who is not already), please consider signing up as a maintainer on the relevant feedstock. All further discussion on making an conda-forge installer should be directed to this [repo]( https://github.com/conda-forge/conda-forge-anvil ) where that work is being pursued. Thanks again. 😄
