### ISSUE TITLE
Add language labels to PRs

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/staged-recipes#10653]
It would be awesome if something could read the recipe, extract some of the used language info (eg `compiler('c')` or `python` somewhere in the recipe) and then put up a label that exposes that information. This way we could search for PRs that are from a particular language, potentially to the exclusion of others.

**Comment by CJ-Wright** [comment]
@conda-forge/staged-recipes thoughts? Would this be helpful?

**Comment by beckermr** [comment]
I think the stale-bot would be most helpful, closing **half** of the open PRs.

See https://github.com/conda-forge/cfep/pull/18

**Comment by carterbox** [comment]
This PR will add a GitHub actions which adds language labels based on mentions to the corresponding teams. https://github.com/conda-forge/staged-recipes/pull/18030
