### ISSUE TITLE
Linking to libraries 

### ISSUE THREAD

**Issue by jan-janssen** [conda-forge/staged-recipes#10652]
Hi @conda-forge/help-c-cpp, 

I have some issue with submitting packages to conda which link to libraries, for example: 

- https://github.com/conda-forge/staged-recipes/pull/10146
- https://github.com/conda-forge/staged-recipes/pull/10403
- https://github.com/conda-forge/siesta-feedstock/issues/9

The behaviour is always the same. Instead of linking to a library like `lib.so` conda tries to link to `lib.so.4` which breaks the compatibility and causes the pull request to fail. 

Is this an issue with the upstream code and the way they link to the library or is there something I can change in the pull requests? 

Best, 

Jan

**Comment by jan-janssen** [comment]
As far as I understand this might be related to pinning of packages, but even for packages which have pinning like the `openmpi` package, there are packages which have this issue, like https://github.com/conda-forge/lammps-feedstock/issues/36

**Comment by scopatz** [comment]
Depending on what you are linking to, this is usually something you can change in the build scripts or via patches, if really needed.

**Comment by jan-janssen** [comment]
@scopatz I am still confused is it a compiler option I can set in the `build.sh` script or is it something I should define in the `meta.yaml` file? Maybe the par splice case is the easiest: 
https://github.com/conda-forge/staged-recipes/pull/10403

```
Warning: rpath /home/conda/staged-recipes/build_artifacts/parsplice_1576039214069/_build_env/lib is outside prefix /home/conda/staged-recipes/build_artifacts/parsplice_1576039214069/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p (removing it)
Warning: rpath /home/conda/staged-recipes/build_artifacts/parsplice_1576039214069/_build_env/lib is outside prefix /home/conda/staged-recipes/build_artifacts/parsplice_1576039214069/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p (removing it)
Warning: rpath /home/conda/staged-recipes/build_artifacts/parsplice_1576039214069/_build_env/lib is outside prefix /home/conda/staged-recipes/build_artifacts/parsplice_1576039214069/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p (removing it)
Warning: rpath /home/conda/staged-recipes/build_artifacts/parsplice_1576039214069/_build_env/lib is outside prefix /home/conda/staged-recipes/build_artifacts/parsplice_1576039214069/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p (removing it)
  ERROR :: $RPATH/liblammps.so.0 not in prefix_owners
  ERROR :: lib/libdb_cxx-6.1.so not in prefix_owners
  ERROR :: $RPATH/liblammps.so.0 not in prefix_owners
  ERROR :: lib/libdb_cxx-6.1.so not in prefix_owners
  ERROR :: $RPATH/liblammps.so.0 not in prefix_owners
  ERROR :: lib/libdb_cxx-6.1.so not in prefix_owners
  ERROR :: $RPATH/liblammps.so.0 not in prefix_owners
  ERROR :: lib/libdb_cxx-6.1.so not in prefix_owners
WARNING (parsplice): dso library package conda-forge::boost-cpp-1.70.0-h8e57a91_2 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (parsplice): dso library package conda-forge::lammps-2019.08.07-py37_mpich_5 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
```

**Comment by scopatz** [comment]
That seems like liblampps is not in the host or run deps.  That or you should set `export CFLAGS="${CFLAGS} -llammps"` or similar

**Comment by jan-janssen** [comment]
I tried it, and with Lammps I guess the issue is that the library is in the python path rather than the lib path, but for example with libdb I tried `export CFLAGS="${CFLAGS} -ldb"` and `export CFLAGS="${CFLAGS} -ldb_cxx"` but both did not work to resolve the issue with the path. The error message is still the same as above.

**Comment by scopatz** [comment]
Hmm that is pretty strange.  Have you tried asking the library authors?

**Comment by isuruf** [comment]
This is an issue with the `lammps` package. It only copies `liblammps.so` to `$PREFIX/lib`, but the `liblammps.so.1` symlink is not copied.

**Comment by jan-janssen** [comment]
Thanks a lot. The pull request is now ready for review https://github.com/conda-forge/staged-recipes/pull/10675
