### ISSUE TITLE
Package ACE (ADAPTIVE Communication Environment)

### ISSUE THREAD

**Issue by traversaro** [conda-forge/staged-recipes#10707]
It would be great to have a port for the ACE (ADAPTIVE Communication Environment) library ( http://www.cs.wustl.edu/~schmidt/ACE.html ).

Useful links: 
* Repology: https://repology.org/project/ace-framework/versions
* vcpkg port: https://github.com/microsoft/vcpkg/tree/master/ports/ace

Previous PRs: 
* https://github.com/conda-forge/staged-recipes/pull/2410
* https://github.com/conda-forge/staged-recipes/pull/9914

FYI @jwillemsen

**Comment by jwillemsen** [comment]
When you add a new port to this project, please add it to the list of files to be updated as part of the release, see https://github.com/DOCGroup/ACE_TAO/blob/51b85b2ebbb5a05216d4ff4f0e47773bc929fc05/ACE/docs/bczar/bczar.html#L385

**Comment by jwillemsen** [comment]
For installing the files, see MPC/prj_install.pl, that is used by make install for vcpkg, see https://github.com/microsoft/vcpkg/blob/f272b0c9846d24c2b77a5fb60e1061d397384acb/ports/ace/portfile.cmake#L207. That should also work on Windows as far as I know.

**Comment by jwillemsen** [comment]
ACE 6.5.8 is available now
