### ISSUE TITLE
 AppVeyor build failed

### ISSUE THREAD

**Issue by rpanai** [conda-forge/staged-recipes#10931]
I see that continuous-integration  AppVeyor is failing for many PRs and my 3 in particular. What can we do about it?

**Comment by xhochy** [comment]
My suggestion would be to get rid of AppVeyer on staged-recipes. We only use Azure Pipelines in new recipes nowadays. I think the teething problems with Azure+Windows are all sorted out. cc @conda-forge/staged-recipes

**Comment by beckermr** [comment]
cc @conda-forge/core

**Comment by isuruf** [comment]
There are some issues with azure still. Let's just remove https://github.com/conda-forge/staged-recipes/blob/master/.appveyor.yml#L21-L24 for now

**Comment by jakirkham** [comment]
Could you please clarify what issues still remain?

**Comment by isuruf** [comment]
https://github.com/conda-forge/conda-forge.github.io/issues/703

**Comment by jakirkham** [comment]
Is that actually a blocker? It seems like the solution is to not use MSBuild IIUC, which is largely the case anyways. Are there important exceptions to this?

**Comment by isuruf** [comment]
Yes. I don't understand why we'd need to drop support for appveyor when it's just a matter of removing 4 lines and there are cases where appveyor is needed.

**Comment by isuruf** [comment]
There are packages that have only MSbuild solutions. Not all packages use cmake.

**Comment by xhochy** [comment]
AppVeyor recovered in the meantime.
