### ISSUE TITLE
build_steps.sh fails on Circle CI with `CONFIG: unbound variable`

### ISSUE THREAD

**Issue by klauer** [conda-forge/staged-recipes#11064]
cc @conda-forge/staged-recipes 
Related issue: #9961

https://github.com/conda-forge/staged-recipes/blob/922ab7167f25004a993c7df2d3125ed1258858c6/.circleci/build_steps.sh#L48

Excerpt from Circle CI output (e.g., https://circleci.com/gh/conda-forge/staged-recipes/38062#tests/containers/0 ):
```
+ CI_SUPPORT=/home/conda/.ci_support
/home/conda/staged-recipes/.circleci/build_steps.sh: line 48: CONFIG: unbound variable
```

**Comment by jakirkham** [comment]
Try `CONFIG=linux64`.

**Comment by beckermr** [comment]
Is this a problem with something local or with the CI scripts on this repo?

**Comment by klauer** [comment]
This is using staged-recipe's Circle CI for a Python recipe. Please see the linked log in the report above.

**Comment by isuruf** [comment]
You should merge with master. We dropped CircleCI a while ago.
