### ISSUE TITLE
DSO Warnings Used to Fail

### ISSUE THREAD

**Issue by scopatz** [conda-forge/staged-recipes#11081]
And now they don't seem to.  CC @isuruf

**Comment by isuruf** [comment]
Example?

**Comment by scopatz** [comment]
It was on the whois PR, but locally and I didn't push it up

**Comment by isuruf** [comment]
How did you build locally?

**Comment by scopatz** [comment]
conda build

**Comment by isuruf** [comment]
You need to add `--error-overlinking`

**Comment by scopatz** [comment]
This was an issue CI, where I noticed it. Sorry, I  was
