### ISSUE TITLE
broken again

### ISSUE THREAD

**Issue by beckermr** [conda-forge/staged-recipes#11084]
see https://github.com/regro/cf-scripts/issues/888

I suspect this might be a change in conda-smithy

cc @conda-forge/core @conda-forge/staged-recipes

**Comment by isuruf** [comment]
https://github.com/conda-forge/conda-smithy/blob/93a3ffaa1457a2f36e37dd971e77e436426c2ae6/conda_smithy/ci_register.py#L504-L508 needs to check that the env var exist before adding it.

**Comment by beckermr** [comment]
Yup. I filed an issue against this yesterday. https://github.com/conda-forge/conda-smithy/issues/1262

I didn't think it was causing huge issues but now it is

**Comment by jakirkham** [comment]
It sounds like your proposal is to remove `spyrmsd` (since it is already converted). If so, SGTM 🙂

**Comment by beckermr** [comment]
Bug fix is merged. Should be fixed here once we get a smithy release.

**Comment by beckermr** [comment]
Now I am seeing a git commit error.

**Comment by hhslepicka** [comment]
Thanks @beckermr for the fix.
