### ISSUE TITLE
We don't need to build example

### ISSUE THREAD

**Issue by pelson** [conda-forge/staged-recipes#113]
Each time a PR is submitted, example is built. We really don't need to do that.
We could just remove the recipe before conda-build-all in the CI scripts (e.g. https://github.com/conda-forge/staged-recipes/blob/master/appveyor.yml#L72).

**Comment by ocefpaf** [comment]
If you are not on it I can send a PR.

**Comment by pelson** [comment]
Thanks @ocefpaf. Nope, I wasn't on it. I'm mostly writing todo lists at the moment :smile:
