### ISSUE TITLE
Package pysimdjson

### ISSUE THREAD

**Issue by synapticarbors** [conda-forge/staged-recipes#11390]
https://pysimdjson.tkte.ch/
https://github.com/TkTech/pysimdjson
https://pypi.org/project/pysimdjson

**Comment by bollwyvl** [comment]
one disadvantage is that this bundles a copy of `simdjson.cpp`... I don't know if it can be linked somehow in the build instead.

as an alternative, there's also https://github.com/gerrymanoim/libpy_simdjson

it's upstream, libpy, seems mighty interesting in its own right. i gave it a quick try with grayskull, and ran into some issues around the use of `filesystem`... might investigate more.

**Comment by TkTech** [comment]
@bollwyvl do not link against anything other than the bundled simdjson.cpp. pysimdjson occasionally includes patches that are not yet upstream, and will soon include patches specific to Python (ex: PyMalloc allocator).

**Comment by bollwyvl** [comment]
@tktech thanks for the information! It'll be helpful when somebody comes along that needs it!

**Comment by bollwyvl** [comment]
This looks like it can be closed: https://github.com/conda-forge/pysimdjson-feedstock

**Comment by dopplershift** [comment]
Closed by #12852.
