### ISSUE TITLE
Clarification on noarch: python and a within-setup.py OS contingency?

### ISSUE THREAD

**Issue by maphew** [conda-forge/staged-recipes#11393]
The conda forge docs on [`noarch: python`](https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python) says this setting is for _"makes pure-Python packages that only need to be built once."_ On the surface that fits, [our project](https://github.com/conda-forge/staged-recipes/pull/11380) is pure python.

There are further relevant conditions:

- [ ] No OS-specific build scripts
- [x] If console_script entry_points are defined in setup.py or setup.cfg, they are also listed in the build section of meta.yaml
- [x] Only console_script entry points have to be listed in meta.yaml. Other entry points do not conflict with noarch and therefore do not require extra treatment. 

I've checked the items I know we comply with already. The one I'm seeking clarification on is _"No OS-specific build scripts"_. We don't have separate build scripts, but there is a Windows specific `console_script` contingency in setup.py:

~~~python
    # (use python.exe instead of pythonw.exe in order to show console msgs)
    if platform.system() == 'Windows':
        x = entry_points['console_scripts']
        x.append('leo-messages = leo.core.runLeo:run')
        entry_points.update({'console_scripts': x})
~~~
The whole function is here: https://github.com/leo-editor/leo-editor/blob/a2a434902c9adb42e0b225604a2e374d620d1ece/setup.py#L125-L149

This setup.py works fine on Linux and Mac systems when used with `pip`  and `python setup.py {...}`. So I believe it remains truly noarch in practice. I would like to be kind to the CI and tell it not to build separately for each OS, but maybe this isn't noarch enough?

_I believe this issue is relevent to the @conda-forge/staged-recipes team. Please feel free to add others or redirect if I picked the wrong target._

**Comment by isuruf** [comment]
This package is not noarch, since the package contents need to be different for windows.
