### ISSUE TITLE
Skip CI requests

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#1148]
Trying to keep track of these in one place.
1. Make `[ci skip]` work in PRs for CircleCI. ( [ref](https://discuss.circleci.com/t/ci-skip-does-not-work-in-pull-requests/5308) )
2. Have `[circle skip]` to skip CircleCI specifically. ( [ref](https://discuss.circleci.com/t/adding-circle-skip-to-commit-message-to-skip/2778/1) )
3. Have `[travis skip]` to skip Travis CI specifically. ( https://github.com/travis-ci/travis-ci/issues/5032 )

**Comment by jakirkham** [comment]
Appears CircleCI now respects `[ci skip]` on pull requests, but not `[skip ci]` yet.

**Comment by smithsp** [comment]
What is the placement of these strings?  In a commit message, or in a pull request title?  What about [skip appveyor]?

**Comment by CJ-Wright** [comment]
In the commit message.

**Comment by CJ-Wright** [comment]
I don't know if appveyor has a skip. @jakirkham does appveyor have a skip?

**Comment by smithsp** [comment]
https://github.com/conda-forge/staged-recipes/#3-how-do-i-exclude-a-platform

**Comment by CJ-Wright** [comment]
Not the same, that skips the CI forever. We just want to skip the CI temporally. (eg the only change you made was removing a comment).  The CIs will all run as proper when we go to merge (or one puts in another commit without those in the message)

**Comment by CJ-Wright** [comment]
Just for ease of reference `[skip appveyor]` is listed in the `Readme` as @smithsp found.

**Comment by smithsp** [comment]
It is odd that I added those strings in my commit message, but https://github.com/conda-forge/staged-recipes/pull/4540 still triggered circleci and appveyor builds.

**Comment by CJ-Wright** [comment]
It seems they can be a bit fickle.

**Comment by jakirkham** [comment]
Probably should add that the ones listed in the OP are all ones that don’t work, but we or others have requested the CIs add them.

**Comment by smithsp** [comment]
Note that I found https://www.appveyor.com/docs/how-to/filtering-commits/ which indicates the `[skip appveyor]` (or `[skip ci]`) directive must be in the git commit title line for appveyor.  My latest commit in #4560 seems to confirm this.

**Comment by jakirkham** [comment]
That's correct. Also issue ( https://github.com/appveyor/ci/issues/1865 ) may be of interest w.r.t. AppVeyor's commit filtering.

**Comment by croth1** [comment]
Does anybody have an overview of the current status? 
- travis, appveyor: it looks like travis and appveyor have implemented specific skips. 
- circle: was an update last month: https://discuss.circleci.com/t/adding-circle-skip-to-commit-message-to-skip/2778/19, but I don't know the progress
- azure: I have no data

I think it would be interesting to collect all of these in the documentation: http://conda-forge.org/docs/maintainer/infrastructure.html#skipping-ci-builds

It would be also interesting to have instructions to skip mac and windows but not linux, etc.

**Comment by ceholden** [comment]
Just came across an update for Azure on their issue tracker ([post](https://github.com/Microsoft/azure-pipelines-agent/issues/858#issuecomment-475768046)) -- they've just enabled skipping for commit messages with `[skip ci]` and a few other tags

**Comment by kynan** [comment]
Is there any update on this? The [docs]() mention `[ci skip] ***NO_CI***` as the tag to include, but that [doesn't seem to have any effect for Azure](https://github.com/conda-forge/wmctrl-feedstock/pull/7/checks).

Can I still safely push a commit without triggering a new build and new packages to be published?

**Comment by kynan** [comment]
Ideally, I'd like the linter to still run on my recipe, but be sure that no builds will be triggered.

**Comment by beckermr** [comment]
It doesn't work for azure pull requests but it does work on the master branch of the feedstock.

**Comment by kynan** [comment]
OK. Just to make sure I understand correctly: when I want to skip CI I should be committing directly commit to master and not make a PR?

**Comment by beckermr** [comment]
Nope. Still use prs. It is just that ci skip in prs may not work. However prs do not upload packages so this isn't an issue.
