### ISSUE TITLE
CI status

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/staged-recipes#115]
Travis-CI failed during the merge of #100 and I had to re-start it.  I Wonder if we should send the status e-mail to the mailing list, or to a few project managers.

**Comment by pelson** [comment]
I'd be happy for this to mail me/you/anybody else directly.

**Comment by jakirkham** [comment]
Could we maybe have it open an issue?
Travis CI emails make it hard to find emails not sent by robots. :stuck_out_tongue_winking_eye:

**Comment by ocefpaf** [comment]
A lot has change since then and I guess we ade peace with the current state of the notifications and how to find CI failures.
