### ISSUE TITLE
AppVeyor badge

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/staged-recipes#116]
AppVeyor badge appears to be broken. @pelson is staged-recipes still in your account? I cannot see the master logs either.

**Comment by pelson** [comment]
https://ci.appveyor.com/project/conda-forge/staged-recipes/branch/master

It is the badge that is wrong, not the account itself. 

https://raw.githubusercontent.com/conda-forge/staged-recipes/master/README.md

**Comment by pelson** [comment]
Closed by #123
