### ISSUE TITLE
create_feedstock.py using wrong feedstock name

### ISSUE THREAD

**Issue by duncanmmacleod** [conda-forge/staged-recipes#11669]
@conda-forge/staged-recipes, the `create_feedstock.py` script is [trying to create feedstocks with the wrong name](https://travis-ci.com/github/conda-forge/staged-recipes/jobs/336494841#L1101), ignoring the new `extra/feedstock-name` key:

https://github.com/conda-forge/staged-recipes/blob/028acbe0a91a0fc1961c460116503e3c9d323a7f/.travis_scripts/create_feedstocks.py#L35-L47

I think this needs to do something similar to what is done now in `conda-smithy`:

https://github.com/conda-forge/conda-smithy/blob/360b332df9ae771e1ce6ebff6fff6eaa82d87103/conda_smithy/utils.py#L15-L22

```python
def get_feedstock_name_from_meta(meta):
    """Resolve the feedtstock name from the parsed meta.yaml."""
    if "feedstock-name" in meta.meta["extra"]:
        return meta.meta["extra"]["feedstock-name"]
    elif "parent_recipe" in meta.meta["extra"]:
        return meta.meta["extra"]["parent_recipe"]["name"]
    else:
        return meta.name()
```

Is importing from `conda_smithy` kosher in the staged-recipes scripts? Or should this function just be copied across and manually kept up-to-date?

**Comment by duncanmmacleod** [comment]
cc @xhochy, who has helped me previously with this issue

**Comment by xhochy** [comment]
I would copy over code to keep this indepedent of smithy but would defer that decision to someone who hacked more on these scripts.
