### ISSUE TITLE
Package R Studio

### ISSUE THREAD

**Issue by owen-synergy** [conda-forge/staged-recipes#11877]
It would be good to have a package for [R Studio](https://github.com/rstudio/rstudio).  The only apparent conda install [available](https://anaconda.org/r/rstudio) seems to be almost 2 years out of date.

I'm not even an R developer but I think having an up to date R Studio recipe would go a long way towards getting more R users and developers into the conda / conda-forge community.

**Comment by brendanf** [comment]
This has been [requested before](https://github.com/ContinuumIO/anaconda-issues/issues/11102#issuecomment-509866738), but apparently it is a really difficult task.

**Comment by sshockwave** [comment]
The recipe [rstudio-desktop](https://anaconda.org/conda-forge/rstudio-desktop) has been added. Does this solve your issue? @owen-synergy

**Comment by roaldarbol** [comment]
Is `rstudio-desktop` being maintained? The current version is about one year older than the newest version of RStudio even though last upload was 3 months ago.

**Comment by mfansler** [comment]
@roaldarbol it does appear to have fallen behind. This isn't really the place for that discussion. If you require a newer version, then it would be better directed [to the feedstock](https://github.com/conda-forge/rstudio-feedstock/issues). PRs are also welcome! E.g., there are [several autotick versions](https://github.com/conda-forge/rstudio-feedstock/pulls) that need troubleshooting.

**Comment by roaldarbol** [comment]
Thanks @mfansler! This is all a bit new to me, so good to be pointed to the right location. :-) I'll add an issue there instead.
