### ISSUE TITLE
Package terraform-ls

### ISSUE THREAD

**Issue by dhirschfeld** [conda-forge/staged-recipes#11940]
[`terraform-ls`](https://github.com/hashicorp/terraform-ls) is the language server powering the new Visual Studio Code extension:
* https://www.hashicorp.com/blog/announcing-the-terraform-visual-studio-code-extension-v2-0-0/

**Comment by dhirschfeld** [comment]
Some references:
* https://github.com/hashicorp/terraform-ls/pull/98
* https://github.com/hashicorp/terraform-ls/issues/88
* https://github.com/hashicorp/terraform-ls/pull/45

**Comment by dhirschfeld** [comment]
I won't have time in the next few weeks so I've opened this issue so I don't forget.

Ping @conda-forge/terraform, in case anyone beats me to it...

**Comment by hadim** [comment]
I would also be interested in that package!

**Comment by dhirschfeld** [comment]
I use it mostly from VSCode and IIUC the `terraform` extension there will download and install the language server for you so I'm not too fussed about having on CF these days.

**Comment by hadim** [comment]
Actually, my usage is the same, I didn't know the extension were coming with ls by default and so I was using a custom installed one.

So I don't really need a conda package anymore xD

**Comment by dhirschfeld** [comment]
Since there isn't a strong reason to have it on CF I'll go ahead and close...
