### ISSUE TITLE
Maintainer user name parser does not recognize hexadecimal values

### ISSUE THREAD

**Issue by henrykironde** [conda-forge/staged-recipes#11987]
I think the recipe reader does not recognize maintainer user names if they are hexadecimal for example 0x00bb1 the user has to quote the name as '0x00b1'

ref: https://github.com/conda-forge/staged-recipes/pull/11984/commits/25c87a344eb6695306440e6fde34fbbf0519fb8e

**Comment by henrykironde** [comment]
@conda-forge/staged-recipes

**Comment by jakirkham** [comment]
We only add maintainers after the recipe has been merged into `staged-recipes` and converted. It doesn't look like that has happened with `keras-resnet` yet. Does that make sense or am I missing something else being asked here? 🙂

**Comment by isuruf** [comment]
We are using yaml. If it's ambiguous, use quotes.

**Comment by henrykironde** [comment]
@jakirkham I think so. I do believe in cases like this, there should be some documentation to let users know that there are some edge cases when it comes to the recipe section and the `Conda` linter will not accept that as good value. Honestly, it was a hard to catch stealth problem especially with no explicit error message. However, I do thank you for looking it to it

**Comment by isuruf** [comment]
PRs welcome to https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/lint_recipe.py#L719-L730

**Comment by jakirkham** [comment]
Oh I missed the bit about thing being related to recipe parsing. Yeah I'm not sure why this causes issues. Maybe something to do with [hexadecimal support in YAML]( https://yaml.org/type/int.html )? As Isuru said, adding quotes should workaround the issue.

In addition to the linter, we could also add documentation here ( https://github.com/conda-forge/conda-forge.github.io ). Maybe somewhere in [the maintainer documentation]( https://conda-forge.org/docs/maintainer/00_intro.html ) would make sense? Thoughts/suggestions welcome 🙂
