### ISSUE TITLE
Strategizing for deployment of longer prefix packages

### ISSUE THREAD

**Issue by msarahan** [conda-forge/staged-recipes#1201]
Testing conda-build 2.0 (as defined as the next release to have the long prefixes) is pretty painful.  There's stuff in there so far that is making prefixes longer (primarily stuff for allowing parallel builds - package names that get too long).  When and how should we start building packages with longer (255-character) prefix length?

At Continuum, @ilanschnell has been working with the master branch of conda-build, and making packages with the longer prefix length there.  I'm at the point where I don't think I can actually create a release that passes all tests unless we seed conda-forge with long-prefix packages.  It's an awkward chicken/egg thing.

I think I need to get conda-build to a trustworthy state (I think master is pretty close now), then build out several packages on conda-forge with that, then finish up creating the python api (which has ended up being a pretty big refactor).

Any thoughts or preferences on how to make this transition?

**Comment by jakirkham** [comment]
Have we figured out how to get info on existing packages that have a prefix and did not already have this metadata included?

xref: https://github.com/Anaconda-Platform/support/issues/44

**Comment by msarahan** [comment]
I've thought a little bit about that.  If we collect all of the packages in a given index, and check for the ```has_prefix``` file in the info folder, we should be able to parse that file and just check the length of the prefixes that ought to be replaced.  Only binary prefixes are relevant, of course.

This is something perhaps best run server-side, because otherwise you have to download all of the packages in the index to do it.

CC @ilanschnell

**Comment by msarahan** [comment]
See https://github.com/conda/conda-build/pull/1195

**Comment by jakirkham** [comment]
Should add this discussion was already occurring in issue ( https://github.com/conda-forge/conda-forge.github.io/issues/171 ). Is it alright if we close this and continue there?

**Comment by jakirkham** [comment]
Closing to consolidate discussion into issue ( https://github.com/conda-forge/conda-forge.github.io/issues/171 ).
