### ISSUE TITLE
Package cargo-license

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/staged-recipes#12278]
`cargo-license` is used in a growing number of packages to satisfy license packaging requirements, and should probably be used in more.

Installing _it_ takes a non-trivial amount of CI resources, and the windows build has issues (not sure if this matters, much, as doing a linux build seems to pull in all the crates, but then again, I'm just using it).

It would be lovely to package this up, testing it on itself, and potentially add a light-weight, conda-build-aware wrapper that can, given a directory with a `Cargo.toml` and a directory of licenses:
- catch crates that have missing licenses in `meta.yaml` or in license directory
- catch licenses for crates that are no longer used

There are also packages that can 80% _find_ the licenses, but I haven't looked into it much.

cc @conda-forge/pysyntect @conda-forge/texlab @conda-forge/geckodriver @conda-forge/ytop (probably others)

**Comment by isuruf** [comment]
There's a WIP PR in https://github.com/conda-forge/staged-recipes/pull/11844.
