### ISSUE TITLE
Add networkx

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#1259]
Add a feedstock for the `networkx` library.

**Comment by whart222** [comment]
FWIW, I just realized that the next release of pyomo could leverage networkx.

**Comment by jakirkham** [comment]
Cool, do you want to try packaging it? Should be pretty easy since it is just Python.

**Comment by whart222** [comment]
Sure.  Probably next week.

**Comment by synapticarbors** [comment]
Working on a recipe in #1812

**Comment by synapticarbors** [comment]
Closed via #1812
