### ISSUE TITLE
Empty feedstock repository

### ISSUE THREAD

**Issue by jdb78** [conda-forge/staged-recipes#12655]
@conda-forge/staged-recipes the feedstock for pytorch-forecasting (merged PR #12452) seems to be empty. See the repo here: https://github.com/conda-forge/pytorch-forecasting-feedstock

Interestingly, the merged PR can only be found in the [closed PRs](https://github.com/conda-forge/staged-recipes/pulls?q=is%3Apr+is%3Aclosed) when [searching for it](https://github.com/conda-forge/staged-recipes/pulls?q=is%3Apr+is%3Aclosed+pytorch-forecasting). I wonder if something went wrong in the feedstock creation.

Many thanks for looking into this issue!

**Comment by beckermr** [comment]
this happens from time to time. we run out of api requests or hit a race condition and the feedstock doesn't get made fully.  I have rekicked the staged-recipes ci job. it should fix it.

**Comment by jdb78** [comment]
Thanks a lot!! It worked :)
