### ISSUE TITLE
rdata-feedstock is empty

### ISSUE THREAD

**Issue by vnmabus** [conda-forge/staged-recipes#12696]
Hello @conda-forge/staged-recipes team, and thanks for your efforts.

The rdata feedstock was created yesterday, but for some reason it is empty. Other feedstocks created before and after this one have the proper contents, so I am asking if there was any problem with the recipe or if this is a temporary condition.

Thank you for your attention.

**Comment by beckermr** [comment]
this should be fixed now - feel free to reopen the issue if you are still having trouble!
