### ISSUE TITLE
Should build all run on merged PRs (accepting recipes for feedstocks)?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#127]
Seems like this might not be necessary (unless I am missing something). Skipping running these builds would shorten our build queue on all CIs if we fast finish them.

**Comment by pelson** [comment]
Agreed. For AppVeyor at least, we could just include the necessary message in the commit: https://github.com/conda-forge/staged-recipes/blob/master/.CI/create_feedstocks.py#L126

@ocefpaf raised this somewhere yesterday, but I can't find it now.

**Comment by ocefpaf** [comment]
Here https://github.com/conda-forge/conda-forge.github.io/issues/45

**Comment by pelson** [comment]
Closed by that PR.

**Comment by jakirkham** [comment]
So we made some more improvements in the PRs above. The first one fixed Travis CI to fast finish one of its Matrix items. The second one was suppose to fix Circle CI and AppVeyor, but it only fixed Circle CI (though it does completely skip builds on `master`). The third one final fixed AppVeyor so that it would fast finish builds on `master`. In short, this problem is resolved on all fronts, but there is still room for improvement with AppVeyor.
