### ISSUE TITLE
package proto-plus

### ISSUE THREAD

**Issue by tswast** [conda-forge/staged-recipes#12814]
https://github.com/googleapis/proto-plus-python

Needed for 2.0 versions of [`google-cloud-bigquery-storage`](https://github.com/conda-forge/google-cloud-bigquery-storage-feedstock/pull/14/) and [`google-cloud-bigquery`](https://github.com/conda-forge/google-cloud-bigquery-feedstock/pull/52).

**Comment by marcelotrevisani** [comment]
Closing this as the package already exists
https://github.com/conda-forge/proto-plus-feedstock

**Comment by tswast** [comment]
Oops, I should have marked https://github.com/conda-forge/staged-recipes/pull/12818 as closing this issue. Thanks for looking into it @marcelotrevisani !
