### ISSUE TITLE
Add pypy

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#1282]
Add a package for PyPy.

**Comment by Juanlu001** [comment]
PyPy3 5.9 is out, with improved support for many scientific packages:

https://morepypy.blogspot.com.es/2017/10/pypy-v59-released-now-supports-pandas.html

How can we add PyPy support to the existing feedstocks though? In other words: what would be the roadmap to achieve something like this?

```
$ conda create -n pypy3 "pypy3=5.9"
$ conda install numpy scipy matplotlib jupyter -n pypy3 -c conda-forge
```

**Comment by Juanlu001** [comment]
To clarify: I just tested PyPy3 5.9 + NumPy + matplotlib + SciPy + IPython + Jupyter + Astropy on a Linux Mint 18.2 machine and everything worked, but I had to

1. Download a portable version of PyPy from https://github.com/squeaky-pl/portable-pypy
2. Create a virtual environment
3. Install some system packages: `libfreetype6-dev` and `libpng12-dev` for matplotlib, `libopenblas-dev` for SciPy.
4. Install all the packages using pip: `pip install numpy && pip install matplotlib && ...`

so I would really like to have all of this inside conda :)

**Comment by jakirkham** [comment]
Honestly I have no idea what this will take as I don't know how we are going to go about tracking things built for use with PyPy vs. CPython. Would be great to hear from some other people.

cc @msarahan @mingwandroid @kalefranz

**Comment by jakirkham** [comment]
Probably worth resurrecting this since PR ( https://github.com/conda-forge/staged-recipes/pull/5027 ) will add `pypy`. In particular, how we package things like `numpy` that depend on `pypy` instead of `python` (CPython).

cc @CJ-Wright @dougalsutherland @mictadlo

**Comment by CJ-Wright** [comment]
Do we need to add pypy versions to our build matrix?
Do noarch packages need to have a separate pypy build?

**Comment by kalefranz** [comment]
I’m guessing there will be problems with conda for noarch python and pypy right now. I don’t know exactly what they are yet, but I’m pretty sure they’ll be there. We’ll just need some patches to conda to support it. No reason we can’t probably. 

Ideally we’d enforce environment exclusivity between python (i.e. cpython) and pypy. We don’t have the greatest way to do that right now. Everybody on the core team *hates* features right now. They’re just so broken in so many ways.

**Comment by jakirkham** [comment]
We have pypy2.7 and pypy3.5. So closing this out as that was the original issue. The discussion of how to handle PyPy built packages is a good one and we should have it, but it probably belongs over at `conda`/`conda-build` first.
