### ISSUE TITLE
Packaging pyorc

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#12937]
Would be good to add a package for [`pyorc`]( https://pypi.org/project/pyorc/ ), which provides Python bindings to the Apache ORC C++ library.

**Comment by synapticarbors** [comment]
This has been packaged: https://github.com/conda-forge/pyorc-feedstock

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/conda-forge/staged-recipes/pull/13658 )
