### ISSUE TITLE
package datetuil

### ISSUE THREAD

**Issue by janschulz** [conda-forge/staged-recipes#1306]
dateutil is in default but not available for py3.5.

**Comment by janschulz** [comment]
Ok, `python-dateutil` is available (even in conda-forge), `dateutil` is not.  I've actually no clue what dateutil is now what :-( But it seems for my app, I need python-dateutil, so I'm closing it here.

**Comment by jakirkham** [comment]
So, there is [`python-dateutil`]( https://pypi.python.org/pypi/python-dateutil/ ) on PyPI, which we [have]( https://github.com/conda-forge/python-dateutil-feedstock ). This is named identically to what it is named in the Python world.

Also there is no [`dateutil`]( https://pypi.python.org/pypi/dateutil/ ) on PyPI. However, this is [`dateutils`]( https://pypi.python.org/pypi/dateutils/ ), which we [have]( https://github.com/conda-forge/dateutils-feedstock ) too.

What is the package you are looking for?

**Comment by janschulz** [comment]
I was doing a `conda install dateutil` which is in default but not for py35 (windows). Seems `tvoverlord` was looking for `python-dateutil`, so this is fine now.

Sorry for the noise... :-/

**Comment by jakirkham** [comment]
No worries.

We have been having upload issues ( https://github.com/conda-forge/status/issues/4 ) of late. So I wanted to know if we were encountering it on those feedstocks so that we could rebuild them. Glad to hear that is not the case.
