### ISSUE TITLE
Add cffi

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#1330]
Packaging [cffi](https://bitbucket.org/cffi/cffi).

**Comment by synapticarbors** [comment]
This is also going to require a feedstock for pycparser:

https://github.com/eliben/pycparser
https://pypi.python.org/pypi/pycparser

**Comment by synapticarbors** [comment]
Added PR for pycparser https://github.com/conda-forge/staged-recipes/pull/1336

**Comment by jakirkham** [comment]
`pycparser` is now added. Thanks for doing that @synapticarbors . Also PR ( https://github.com/conda-forge/staged-recipes/pull/1338 ) has been added for `cffi`.
