### ISSUE TITLE
Package atheris

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/staged-recipes#13406]
Google opensourced a python-fuzzer called atheris, see [announcement](https://opensource.googleblog.com/2020/12/announcing-atheris-python-fuzzer.html).

It's LLVM-based, so it sounds like conda(-forge) would be excellently positioned to package this as an easy fuzzing integration experience for the CI of various projects (already utilizing conda).

Here's the [repo](https://github.com/google/atheris), and of course it's already on [PyPI](https://pypi.org/project/atheris/).

CC @beckermr @isuruf @jakirkham @scopatz

**Comment by bollwyvl** [comment]
Previous attempts:
- https://github.com/conda-forge/staged-recipes/pull/16333
- https://github.com/conda-forge/staged-recipes/pull/16590

It looks like this would need https://llvm.org/docs/LibFuzzer.html to be added. @conda-forge/llvmdev @conda-forge/llvm-meta thoughts on where this might live?

**Comment by bollwyvl** [comment]
I've got linux-64 sorta working over here: https://github.com/conda-forge/staged-recipes/pull/17943

Any feedback appreciated!
