### ISSUE TITLE
nodejs conda package?

### ISSUE THREAD

**Issue by goanpeca** [conda-forge/staged-recipes#1349]
Do we consider useful having a nodejs package, kinda like what was done here 

https://anaconda.org/javascript/nodejs

This could be very useful for the lektor package as it would greatly simplify installation...

**Comment by jakirkham** [comment]
Please see this [feedstock]( https://github.com/conda-forge/nodejs-feedstock ). 😉

**Comment by goanpeca** [comment]
Oops :-p

**Comment by jakirkham** [comment]
Also maintainers welcome. 😄

**Comment by jakirkham** [comment]
No worries. This place can kind of be a zoo. I've accidentally reproposed things in PRs here that were already feedstocks (even after searching a day or two before).
