### ISSUE TITLE
Add recipes for missing ignition libraries

### ISSUE THREAD

**Issue by traversaro** [conda-forge/staged-recipes#13551]
In few cases in the last months I had explain to interested users which ignition robotics libraries (a set of C++ libraries for robotics, see https://ignitionrobotics.org/) were still missing from conda-forge . As this info may be useful to anyone interested in this, especially for people interesting in adding the missing recipes, I think it is useful to report it and track it in this repo.

The Ignition libraries still not packaged in conda-forge are (see https://ignitionrobotics.org/libs for the complete list): 
* [x] [ignition-rendering](https://github.com/ignitionrobotics/ign-rendering) done in https://github.com/conda-forge/staged-recipes/pull/13677, feedstock https://github.com/conda-forge/libignition-rendering4-feedstock 
* [x] [ignition-sensors](https://github.com/ignitionrobotics/ign-sensors) fixed in https://github.com/conda-forge/staged-recipes/pull/14313 
* [x] [ignition-gui](https://github.com/ignitionrobotics/ign-gui), depends on ignition-rendering, fixed in https://github.com/conda-forge/staged-recipes/pull/14323 
* [x] [ignition-gazebo](https://github.com/ignitionrobotics/ign-gazebo/), depends on ignition-gui, ignition-rendering and ignition-sensors, ongoing in https://github.com/conda-forge/staged-recipes/pull/14331 .
* [ ] [ignition-launch](https://github.com/ignitionrobotics/ign-launch), depends on ignition-gazebo 
* [ ] [ignition-utils](https://github.com/ignitionrobotics/ign-utils) (however, this is a new library that still needs to be released)

Note that the naming schema for Ignition libraries in conda forge is `libignition-<library-name><major-version>` .

cc @Tobias-Fischer @wolfv @mabelzhang @JShep1

**Comment by JShep1** [comment]
I just opened a PR adding `ign-rendering` to `conda-forge` [here](https://github.com/conda-forge/staged-recipes/pull/13677).

Admittedly, it's my first contribution to `conda-forge` so I followed the contribution guidelines as closely as I could and there might be a few mistakes in that PR.  But once I get the feedback and solidify the process, I'll open more PRs for the remaining packages.

Do you have any advice for me for that PR (like things I may have done wrong or who I need to ping to get it in)? @traversaro

**Comment by traversaro** [comment]
> Do you have any advice for me for that PR (like things I may have done wrong or who I need to ping to get it in)? @traversaro

Hi @JShep1 , thanks for working on the recipe. My suggestion is to iterate on the PR until the CI passes, and if you have any doubt feel free to ping me, @Tobias-Fischer or @wolfv . Once the PR is ready, you will need someone with merge permissions. For C/C++ libraries you can ping the `@conda-forge/help-c-cpp`, and in practice for robotics-related library I typically ping also @wolfv that as part of the [core conda-forge team](https://conda-forge.org/docs/orga/governance.html) can merge new recipes.

**Comment by traversaro** [comment]
If you have any question, feel free also to pass by https://gitter.im/RoboStack/Lobby .

**Comment by traversaro** [comment]
This is completed with https://github.com/conda-forge/staged-recipes/pull/14446 . If anyone is interested in this, for apt/homebrew feature parity, it could make sense to have a `ignition-metackages-feedstock` repo that produces all metapackages like `ignition-dome`, `ignition-edifice` that install all the versions corresponding to a given release, but I think the fundamental problem of having ignition libraries in conda-forge has been now fixed.

**Comment by wolfv** [comment]
awesome!
