### ISSUE TITLE
Package PySide6

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/staged-recipes#13573]
https://pypi.org/project/PySide6/

It probably needs Qt6

**Comment by KevinUTAT** [comment]
I am a little surprised that such a big update to Pyside/Qt still haven't been added to Conda

**Comment by dopplershift** [comment]
@KevinUTAT Qt is a huge build that is challenging to get complete on our CI systems within time allotments. Help is definitely welcome over at: https://github.com/conda-forge/qt-feedstock/issues

**Comment by jschueller** [comment]
@hmaarrfk you can close this one, see
https://github.com/conda-forge/pyside2-feedstock/pull/136

**Comment by hmaarrfk** [comment]
Very nice
