### ISSUE TITLE
Feedstock conversion failing for package arn 

### ISSUE THREAD

**Issue by BastianZim** [conda-forge/staged-recipes#13696]
Hi, the arn feed stock (https://github.com/conda-forge/staged-recipes/pull/13671) has been stuck in the staged-recipes folder for more than 12 hours with circleCI not being able to convert it to a proper feedstock.

Packages that were added later are successfully merged, it's only this one that's stuck.

I tried investigating it but it seems to be a server error.

Error: https://github.com/conda-forge/staged-recipes/runs/1707908677?check_suite_focus=true#step:4:809

Repo was created here: https://github.com/conda-forge/arn-feedstock

Edit: Failed again here: https://github.com/conda-forge/staged-recipes/runs/1708173237?check_suite_focus=true#step:4:808

**Comment by BastianZim** [comment]
Pinging @conda-forge/core

**Comment by beckermr** [comment]
Looks like circle is choking. Either our token is expired or there is a deeper problem.

**Comment by BastianZim** [comment]
There were a couple of other packages successfully converted after this, could that still happen with an expired token? 

Should I just keep an eye on it and ping again after after the weekend in case it didn't work?

**Comment by chrisburr** [comment]
Other feedstocks are fine so I think it's a deeper issue with that repository.

**Comment by beckermr** [comment]
We can turn off builds in the circle ui and delete the web hook in the repo and then try again.

**Comment by beckermr** [comment]
Alright. I deleted all webhooks and stopped building it in the ui. Let's try again.

**Comment by BastianZim** [comment]
Worked, thank you!

**Comment by chrisburr** [comment]
Thanks @beckermr! 🍰
