### ISSUE TITLE
Do not import .DS_Store with .ci_support/build_all.py

### ISSUE THREAD

**Issue by BastianZim** [conda-forge/staged-recipes#13823]
Hi,

Currently, when testing packages locally (As described in https://conda-forge.org/docs/maintainer/adding_pkgs.html#running-tests-locally-for-staged-recipes) the `.ci_support/build_all.py` script imports all files and folders in the `recipes` directory when building the packages. 
This generally isn't a problem because only recipe folders should be added to the directory in the first place, but macOS automatically and continuously creates [`.DS_Store`](https://en.wikipedia.org/wiki/.DS_Store) files in every folder, which are then also included and cause the build to fail.

Error output:
```zsh
...
python /home/conda/staged-recipes-copy/.ci_support/build_all.py
Building .DS_Store with conda-forge/label/main
Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
WARNING conda_build.config:arch(318): Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
Traceback (most recent call last):
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 177, in <module>
    build_all(os.path.join(root_dir, "recipes"), args.arch)
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 101, in build_all
    build_folders(recipes_dir, folders, arch, channel_urls)
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 139, in build_folders
    G = construct_graph(recipes_dir, worker=worker, run='build',
  File "/home/conda/staged-recipes-copy/.ci_support/compute_build_graph.py", line 400, in construct_graph
    raise ValueError("Specified folder {} does not exist".format(recipe_dir))
ValueError: Specified folder /home/conda/staged-recipes-copy/recipes/.DS_Store does not exist

```

I thought I had fixed this with https://github.com/conda-forge/staged-recipes/pull/13555 but it is still happening. 
As far as I understand the code, there are two ways to exclude them:

1. Remove all `.DS_Store` files from `staged-recipes-copy` by adding `find ~/staged-recipes-copy -name ".DS_Store" -delete` in line 26 at https://github.com/conda-forge/staged-recipes/blob/d1e97aceeaf20b7fa1b2738fcb3476518fad0c45/.scripts/build_steps.sh#L24-L27
2. Make `python /home/conda/staged-recipes-copy/.ci_support/build_all.py` only import directories.

The first option is fairly easy to implement and clean because it also removes `.DS_Store` files added to the recipe folders and subfolders themselves but it takes quite some time to execute, since it needs to scan the whole directory and all subdirectories.

I would therefore suggest the second option where it could be implemented like this:
```python
with os.scandir(recipes_dir) as dir_list:
    folders = [dir_obj.name for dir_obj in dir_list if dir_obj.is_dir()]
```
which could be included instead of https://github.com/conda-forge/staged-recipes/blob/d1e97aceeaf20b7fa1b2738fcb3476518fad0c45/.ci_support/build_all.py#L28

There are multiple ways to check if something is a file or folder but `os.scandir`seems to be the fastest: https://stackoverflow.com/a/59938961/9599354

If there is any interest, I'd be happy to create a PR for either option.

**Comment by BastianZim** [comment]
Pinging @conda-forge/staged-recipes

**Comment by isuruf** [comment]
Let's go with option 1. (there's a depth argument to `find` command to not go into subdirectories)
