### ISSUE TITLE
RDkit 2020.09.4 release issues with Conda-forge build and other modules (Python3-saml)

### ISSUE THREAD

**Issue by AlDossetter** [conda-forge/staged-recipes#13879]
What:
Fresh install on Ubuntu 20.04 with miniconda3, python 3.7 RDKit installs ok but Python3-saml has become incompatible.
First noted with 2020.09.04 but after experiments found first version where break occurred - 2020.03.6

Terse:
Demonstrated with
python3-saml

Some issues with rpy2 but:

$ conda install -c conda-forge rpy2
appears to install and work ok on Ubuntu 20.04 (not Mac OSX)

TERSE:
Up to, and including rdkit==2019.09.3 python3-saml==1.9.0 would install and work together

With a python 3.7 condo env:

$ conda install -c conda-forge rdkit==2020.03.6 -y
$ conda install -c conda-forge python3-saml
Python3-saml failed to install with multiple conflicts
- there are references to Python 3.8 - did we miss something and RDkit is Python3.8 now?

rdkit==2020.09.3 and rdkit==2020.09.4 also are incompatible

Good News - There is compatibility with (this is a section of our build script)

pip install mod_wsgi==4.7.1
pip install -i https://pypi.anaconda.org/OpenEye/simple OpenEye-toolkits
conda install -c conda-forge rpy2 -y
conda install -c conda-forge scikit-learn==0.21.3 -y
conda install -c conda-forge matplotlib==3.3.3 -y
For addition clarity:

pip install python3-saml

does not work - this is PEP517 related but it does reveal that libxml2 and libxmlsec might be the issue
[Spent about a day try to work around this one without success]
These are the results on Ubuntu 20, on Mac OSX Catalina things are worse (that will required another day of experimentation - Rdkit 2018 appears stable here with all other module combinations)

Issue also logged on Github rdkit/conda-forge

Tagging @jaimergp as requested

**Comment by jaimergp** [comment]
This reproduces the issue:

```
$> conda create -n saml-test -c conda-forge -c defaults --strict-channel-priority python3-saml

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package _libgcc_mutex conflicts for:
xmlsec[version='>=0.6.0'] -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex[version='*|0.1',build='conda_forge|main']
python -> libgcc-ng[version='>=9.3.0'] -> _libgcc_mutex[version='*|0.1',build='conda_forge|main']

Package ca-certificates conflicts for:
defusedxml[version='>=0.5.0'] -> python -> ca-certificates
isodate[version='>=0.5.0'] -> python -> ca-certificates
python -> ca-certificates
Note that strict channel priority may have removed packages required for satisfiability.
```

I think we need to either: 

* bring (at least) `xmlsec` over to conda-forge ([Anaconda recipe here](https://github.com/AnacondaRecipes/aggregate/blob/master/xmlsec-feedstock/recipe/meta.yaml))
* ask Anaconda to build `xmlsec` for GCC 9

**Comment by jaimergp** [comment]
@AlDossetter can you check if your issue is resolved now?

**Comment by AlDossetter** [comment]
I can confirm RDkit 2020.09.04 and Python3-saml (latest) install together in the same miniconda3 / python 3.7.
Used Miniconda3 4.8.3 (Miniconda3-py37_4.8.3-Linux-x86_64.sh) on Ubuntu 20.04 AWS image. 

Explored our entire Miniconda3 build and this did complete after adjustments to rpy2 source (conda install -c conde-forge rpy2) and matplotlib 3.3.3 took a little while to install after resolving dependancies.
We have not fully tested with both unittest and functionality though, but usually this is ok after a clean build.
Thanks a bunch.
