### ISSUE TITLE
Package  robotics-toolbox-python 

### ISSUE THREAD

**Issue by traversaro** [conda-forge/staged-recipes#13970]
The Robotics Toolbox for Python ( https://github.com/petercorke/robotics-toolbox-python)  is a python library for Robotics, the Python port of the Peter Corke's Robotics Toolbox for MATLAB (https://github.com/petercorke/robotics-toolbox-matlab).

It is already available on pip, so it should be possible to generate it via [grayskull](https://github.com/conda-incubator/grayskull).

The project also have an integration with ROS ( https://github.com/petercorke/robotics-toolbox-python/wiki/ROS ) so it could be a good use case for RoboStack @wolfv @Tobias-Fischer . However, as the ros package are lazy loaded, it can be added to conda-forge with no strange dependency problems.

**Comment by wolfv** [comment]
great!

**Comment by Tobias-Fischer** [comment]
Hi @petercorke @jhavl - there is clearly interest in your toolbox on conda-forge; I didn't make it up in our conversations ;).

I might chat to you again; I'll give a technical talk in March about conda etc and the toolbox might be a good showcase for the talk.

**Comment by Tobias-Fischer** [comment]
@traversaro - this is done, I think we can close this issue.

**Comment by traversaro** [comment]
> 
> 
> @traversaro - this is done, I think we can close this issue.

Sure! For reference, this is the PR that closed the issue: https://github.com/conda-forge/staged-recipes/pull/14250 and this is the resulting feedstock: https://github.com/conda-forge/roboticstoolbox-python-feedstock .
