### ISSUE TITLE
Feedstock missing after recipe was added (and merged)

### ISSUE THREAD

**Issue by deepcharles** [conda-forge/staged-recipes#13973]
Hello @conda-forge/staged-recipes

First of all, thanks for your good work.

I maintain a [package](https://pypi.org/project/loadmydata/) and I recently added a recipe (see #13943) that was merged a few days ago. However the associated feedstock was not created.

It says in the docs to ping you if the feedstock creation takes more than a day or so, so here I am.

Many thanks.

**Comment by chrisburr** [comment]
GitHub makes this hard to verify but I think this is what has happened:

* You made https://github.com/conda-forge/staged-recipes/pull/13943 using your fork's `master` branch
* At some point your fork's `master` branch was force pushed to match `conda-forge/staged-recipes:master` (see [here](https://github.com/conda-forge/staged-recipes/pull/13943#event-4321127177))
* This force push seems to be a result of the `pull` app you have installed

This sequence caused GitHub to mark the PR as "merged" as the PR's branch now matched with what was in `conda-forge/staged-recipes:master`.

The best thing to do is to make a new PR (from a dedicated branch). You can find the original contents from before the force push by going to: https://github.com/conda-forge/staged-recipes/tree/e3380f165a62f0604adcfd82efd072506167046d/recipes/loadmydata

**Comment by deepcharles** [comment]
Thanks for the quick and detailled answer. 

I'll do what you recommend now.
