### ISSUE TITLE
Idea for Google Season of Docs

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/staged-recipes#14133]
Staged-recipes have some guidelines for the submitter to (README, recipe example, and links to documentation on how to contribute with packages [1]). However, we have no documentation on how to review PRs for new packages. Staged-recipes team and core members rely on "institutional knowledge" for these reviews. This causes a few issues:

1. reviews are a bit disconnected as rules/recommendations change with time;
2. it becomes really hard to recruit new reviewers;
3. little to no connection between the staged-recipes teams (Python, R, C++, etc).

A successful Google Season of Docs would be to create a new entry on our documentation page with review guidelines based on this institutional knowledge.

[1] https://conda-forge.org/docs/maintainer/adding_pkgs.html

hackmd link: https://hackmd.io/PhIgy8eSTAmM5bT451SXUw

**Comment by ForgottenProgramme** [comment]
This got covered in Outreachy, I suppose.
