### ISSUE TITLE
Make additional refinements to the README/FAQ

### ISSUE THREAD

**Issue by mwcraig** [conda-forge/staged-recipes#1414]
These items are consolidated from a more basic PR to move the FAQ into the README so that it is easier to find.
- [ ] Remove the ["long answer" response](https://github.com/conda-forge/staged-recipes/pull/1413#discussion_r76658209) to the question about dependencies. 
- [ ] Expand the discussion of [if or when to include running tests](https://github.com/conda-forge/staged-recipes/pull/1413#discussion_r76658691)
- [x] Add Q&A about [excluding python versions](https://github.com/conda-forge/staged-recipes/pull/1413/files#r76657466)
- [ ] Give some options for checking [whether a package needs `numpy x.x`](https://github.com/conda-forge/staged-recipes/pull/1413/files#r76657466)

**Comment by jakirkham** [comment]
So we have the FAQ. Trying to understand if the rest of these are still relevant (e.g. `numpy x.x` is not a thing for instance). Thoughts @asmeurer?

**Comment by asmeurer** [comment]
You're in a better position than I am to know if all the frequently asked questions are in there. I think it answered whatever question I had back when I requested it.

**Comment by mwcraig** [comment]
You can close this, I think...things have evolved quite a bit in the time since it was opened.
