### ISSUE TITLE
Feedstock conversion failing

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#14351]
https://github.com/conda-forge/staged-recipes/runs/2172383498?check_suite_focus=true

cc @conda-forge/core @conda-forge/staged-recipes

**Comment by chrisburr** [comment]
It’s probably something with windows style line endings again.

**Comment by chrisburr** [comment]
Will probably be fixed by c2717f3

**Comment by jakirkham** [comment]
Thanks Chris! Looks like there's another one that had the same issue ( https://github.com/conda-forge/staged-recipes/pull/14357 )

**Comment by jakirkham** [comment]
Think I found the issue. PR ( https://github.com/conda-forge/staged-recipes/pull/14358 ) fixed this for me locally

**Comment by jakirkham** [comment]
Canceled existing runs and restarting on `master`.

Here's the build: https://github.com/conda-forge/staged-recipes/runs/2177645810?check_suite_focus=true

**Comment by jakirkham** [comment]
Seems to be clearing this out. Going to go ahead and close. Though it may still take a bit before everything is cleared

**Comment by jakirkham** [comment]
Ok that cleared out a decent chunk, but not all of them. Starting a new job to clear some more

Here's the build: https://github.com/conda-forge/staged-recipes/runs/2177938400?check_suite_focus=true

**Comment by beckermr** [comment]
It will restart itself nicely now so no need to babysit and do it by hand.

**Comment by jakirkham** [comment]
Yeah we were just getting a lot of people asking about what was going on. Plus things were pretty backed up. So was trying to clear them out to address those issues

**Comment by jakirkham** [comment]
Prodding again here: https://github.com/conda-forge/staged-recipes/runs/2178186195?check_suite_focus=true

**Comment by beckermr** [comment]
Your efforts here are greatly appreciated!

github retries the build every ~15-20 minutes or so

**Comment by jakirkham** [comment]
Yep I let it do it's thing the 3rd time. My guess is this is close to being done

**Comment by jakirkham** [comment]
Looks like it cleared ( https://github.com/conda-forge/staged-recipes/commit/30838191bd9610c4379daee349b09c1b02ddaa18 ) 😄

**Comment by jakirkham** [comment]
@conda-forge/staged-recipes @conda-forge/core, FYI for the fix mentioned above to work, we need to ask people merge or rebase with the latest `master` branch on `staged-recipes`. Thanks! 😄
