### ISSUE TITLE
conda-forge tooling

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/staged-recipes#1443]
Is there a single document describing the roles of the different tools in conda-forge work together, not from a user perspective but a developer perspective? (conda-smithy, conda-anvil etc).

**Comment by jakirkham** [comment]
Not yet. That would be useful.

Though the Readme for conda-smithy is improving. linux-anvil is just the Docker image. There isn't much to that per se.

What other pieces are you interested in understanding?

**Comment by SylvainCorlay** [comment]
I would be interested in reusing some of these tools in other contexts and contribute back to it.

**Comment by jakirkham** [comment]
We have been working on the docs on the webpage. I don't think it explains everything, but it does explain some things and provide some guidelines. As such I think I will close this out. That isn't to say this is done, but more this is a WIP project with some objectives completed. We should probably specify new issues over at the webpage with clear actionables for additional documentation.
