### ISSUE TITLE
Wrong permissions for extracted tar files

### ISSUE THREAD

**Issue by gqmelo** [conda-forge/staged-recipes#1475]
When trying to build a [recipe for lbzip2](https://github.com/conda-forge/staged-recipes/pull/1468) I did not have permission to execute `configure`:

```
+ ./configure --prefix=/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho
/opt/conda/conda-bld/work/lbzip2-2.5/conda_build.sh: line 4: ./configure: Permission denied
Command failed: /bin/bash -x -e /opt/conda/conda-bld/work/lbzip2-2.5/conda_build.sh
```

The problem is that `run_docker_build.sh` runs as superuser, so tar uses `--preserve-permissions` as default, as opposed to `--no-same-owner` for regular users.

In my case specifically the files contained in the tar have uid and gid that do not exist on the docker image, so tar fails to preserve file permissions.

So either `run_docker_build.sh` should run as a regular user or `conda-build` should extract tar files forcing the **--no-same-owner** option.

**Comment by msarahan** [comment]
The latter might not be a bad idea, but I'm also of the mind that running containers as root is bound to cause problems like this.  I'd rather have the container run as a normal user, and have conda-build force this as a fall-back.

**Comment by gqmelo** [comment]
>  I'd rather have the container run as a normal user

Yes, me too. Actually I don't think we should touch ```conda-build```, it is just using a default behaviour. Users should not be using ```conda-build``` as root.
I'll try to test something on the lbzip2 recipe

**Comment by gqmelo** [comment]
Well, I've successfully refactored the run_docker_script.sh on the ```lbzip2``` branch. Please take a look and let me know if I should create another PR with these changes

**Comment by jakirkham** [comment]
xref: https://github.com/conda-forge/conda-smithy/issues/212

**Comment by jakirkham** [comment]
IMHO we should not be running as `root` in the Docker container. So I feel these changes should move into the [`Dockerfile`]( https://github.com/conda-forge/docker-images/blob/6117de26505e522fe2ffc4d87ee1b3ba655ed20a/linux-anvil/Dockerfile ). Though there is a bit of disagreement about that still.
