### ISSUE TITLE
Add svn

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#1495]
Need a package for `svn`. Already have `git` and `mercurial`.

**Comment by stuertz** [comment]
Would be glad if that package would contain also the svn includes (header files), so one could build pysvn on top of the svn package. The conda default package does not include the header.

**Comment by jakirkham** [comment]
Yeah, that was the plan. Was also somewhat interested in `pysvn`. Unfortunately I haven't had lots of time to play with this of late.

**Comment by jakirkham** [comment]
FWIW `svn`'s dependencies have now been packaged.

**Comment by scopatz** [comment]
PR is here BTW: https://github.com/conda-forge/staged-recipes/pull/11782
