### ISSUE TITLE
`noarch` artifacts are not uploaded

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/staged-recipes#15222]
Azure artifacts are only uploaded for [platform-specific](https://github.com/conda-forge/staged-recipes/blob/master/.azure-pipelines/azure-pipelines-linux.yml#L27) packages. `noarch` packages are hence not included and cannot be tested locally. [Example](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=334508&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=24e3a636-0ef4-598e-772b-bef72c15bbf0&l=10).

@conda-forge/staged-recipes, is this worth a PR?

**Comment by beckermr** [comment]
yes if you are willing!
