### ISSUE TITLE
Add ISSUE_TEMPLATE for package requests

### ISSUE THREAD

**Issue by BastianZim** [conda-forge/staged-recipes#15327]
It might be nice to have issues automatically labelled for package requests, bug reports etc.
Grayskull does the same here: https://github.com/conda-incubator/grayskull/tree/main/.github/ISSUE_TEMPLATE

**Comment by BastianZim** [comment]
@conda-forge/core Thoughts? As that might require a CFEP (Since the stale label did).

**Comment by beckermr** [comment]
Probably not. Cfeps are good for some things and not for others. Make a PR?

**Comment by BastianZim** [comment]
Sure, will do.

**Comment by beckermr** [comment]
What do you mean?

**Comment by BastianZim** [comment]
Just the template just add a label but otherwise be the same as the current approach or also offer some additional advice? Some initial thoughts here: https://github.com/conda-forge/staged-recipes/pull/15328/files

**Comment by beckermr** [comment]
Ahhh this looks fine.

**Comment by BastianZim** [comment]
Ok, just wanted to check also because of CFEP.
