### ISSUE TITLE
Running `create-feedstocks-on-merge` on Travis' Linux container infrastructure

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#154]
Unless I am mistaken, this step merely lints the recipe. It would be good if we just change this build to run on the Linux container infrastructure. The reason being this will start [a lot faster]( https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments ) and thus give users feedback more quickly on whether the recipe is acceptable.

**Comment by pelson** [comment]
Yes, I agree.
