### ISSUE TITLE
travis api error

### ISSUE THREAD

**Issue by beckermr** [conda-forge/staged-recipes#15891]
Not sure what this is about, but it is blocking staged recipes:

```
Traceback (most recent call last):
  File "/home/runner/miniconda/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/home/runner/miniconda/lib/python3.7/site-packages/conda_smithy/cli.py", line 666, in main
    args.subcommand_func(args)
  File "/home/runner/miniconda/lib/python3.7/site-packages/conda_smithy/cli.py", line 291, in __call__
    ci_register.travis_configure(owner, repo)
  File "/home/runner/miniconda/lib/python3.7/site-packages/conda_smithy/ci_register.py", line 502, in travis_configure
    response.raise_for_status()
  File "/home/runner/miniconda/lib/python3.7/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.travis-ci.com/repo/20663660/setting/builds_only_with_travis_yml
```

**Comment by tyrius02** [comment]
This has been occurring all day today (15-Aug) for the [new] pyannote.metrics-feedstock. The action itself reports success despite the fact that the feedstock isn't created and/or set up properly.

**Comment by beckermr** [comment]
Well we may need to turn Travis off then. We are using an admin on the repo to make the api calls. Further, nobody at Travis wrote me back after my support ticket. I'm not sure what else to do here. 

Cc @conda-forge/core

**Comment by ocefpaf** [comment]
Yeah, we don't have many choices here :-/

**Comment by isuruf** [comment]
@beckermr, the extra admin user is supposed to be a different user that is not an org-wide admin. AFAIK, cf-blacksmithy is an org-wide admin.

**Comment by beckermr** [comment]
Why would that matter? This worked fine for the past few days. Travis changed something again.

**Comment by isuruf** [comment]
Travis syncing stuff is flaky. When a user has admin access to 5000+ repos and the repos are checked in a random order, it's pure chance that travis finds out that the user has admin access to a repo. That's why we setup a way to have a bot-user that is not an org-wide admin, so that it doesn't have admin access to 5000+ repos.

**Comment by beckermr** [comment]
I've also verified that cf-blacksmithy is properly listed as an admin user on the repo.

**Comment by isuruf** [comment]
Sure, but travis doesn't know that and the API requests run out before travis can know that. See my comment above

**Comment by beckermr** [comment]
Ahhhh. We'll need to remove one of the bots from admin on conda forge I guess.

**Comment by beckermr** [comment]
Don't remove cf-blacksmithy just yet. This will break other things and I need to look at it

**Comment by beckermr** [comment]
ok cf-blacksmithy removed - let's see what happens

**Comment by beckermr** [comment]
This is still not working. Let's let it ride a bit more and hopefully it will work.

**Comment by beckermr** [comment]
A feedstock converted ~2 hours ago, so maybe travis is having trouble with this specific repo.

**Comment by beckermr** [comment]
Let’s wait a few hours for the GitHub token to reset and try again.

**Comment by tyrius02** [comment]
I don't know if it's specifically my feedstock, pyannote.metrics. That one certainly fails. Maybe we should remove it (and the existing repo) and see if the rest are created properly.

**Comment by beckermr** [comment]
It is all of them unfortunately. :(

**Comment by jakirkham** [comment]
Travis is investigating

**Comment by jakirkham** [comment]
This appears to be resolved. Closing...
