### ISSUE TITLE
Python debug

### ISSUE THREAD

**Issue by duncanwp** [conda-forge/staged-recipes#1593]
It would be useful to have a python-dbg package, ideally with versions of a few common packages compiled against it as well. 

I'm not sure how this would fit in with your framework though, I guess it could be treated as another python version to build against..? 

This has been discussed in core anaconda here: https://github.com/ContinuumIO/anaconda-issues/issues/80 but it doesn't look like anything came of it.

**Comment by patricksnape** [comment]
It would likely be implemented as a feature I imagine. However, I still don't think we've quite ratified the best ways to kick off multiple builds with multiple features. I'm not sure that our current CI architecture could cope with doubling the amount of builds.

**Comment by tadeu** [comment]
This was discussed before in a PR thread: https://github.com/conda-forge/staged-recipes/pull/961

**Comment by duncanwp** [comment]
Ah, I didn't spot that - thanks!  

As far as I can see it was left with @dfroger to move the pull request to the python feedstock. Have you had any luck with that?

**Comment by pelson** [comment]
I'm definitely supportive of having some debug builds of within conda-forge. Features may be a good way of doing it, but I presume we may want more control of *which* packages we want to install that have debug enabled (e.g. sometimes we want to be able to debug Python and numpy but not pandas). Is that the case?

**Comment by tadeu** [comment]
@pelson Unfortunately, when using a debug version of `python`, all binary modules must be built with debug support too, because, for example, it changes the byte structure of `PyObject`s.

**Comment by dfroger** [comment]
I'm sorry for the long inactivity... I create a pull request [here](https://github.com/conda-forge/python-feedstock/pull/86) to the python feedstock.
