### ISSUE TITLE
[Package request] r-pzfx 0.3.0

### ISSUE THREAD

**Issue by mjsteinbaugh** [conda-forge/staged-recipes#16047]
# The requested package

- _Package name_: r-pzfx
- _Version (If a specific one is required)_: 0.3.0
- _URL_: https://cran.r-project.org/package=pzfx
- _Available via (GitHub Releases, PyPI, etc.)_: https://github.com/Yue-Jiang/pzfx
- _Additional comments_: Current build on `pkgs/r` channel is old, stuck at v0.2.0.

# Before submitting
- [x] Verify that the package does not already exist (Also check with _hyphens_ vs. _underscores_ and added identifiers like `python-` and `r-`). *Doesn't exist in conda-forge, but is in pkgs/r (see above).*
- [x] Check that no previous [issue](https://github.com/conda-forge/staged-recipes/issues) exists and that no [PR](https://github.com/conda-forge/staged-recipes/pulls) is currently open. 

I'm looking into submitting a pull request using [conda_r_skeleton_helper](https://github.com/bgruening/conda_r_skeleton_helper).

Thanks,
Mike

**Comment by mfansler** [comment]
@mjsteinbaugh I didn't see anything in the PR queue, so I submitted one.
