### ISSUE TITLE
Use only python 2 for conda builds

### ISSUE THREAD

**Issue by jarifibrahim** [conda-forge/staged-recipes#1611]
I'm trying to add a few recipes to conda-forge but all the CI tests fail as my package is written for python 2 and conda is trying to build it against python 3. Is there a work around for this?

```
Fetching package metadata .........
Resolving distributions from 1 recipes... 
Computed that there are 3 distributions from the 1 recipes:
Resolved dependencies, will be built in the following order: 
    ocw-1.2.0-py27_0 (will be built: True)
    ocw-1.2.0-py34_0 (will be built: True)
    ocw-1.2.0-py35_0 (will be built: True)
```

**Comment by dopplershift** [comment]
In the `meta.yml` file, you need this:
```yml
build:
   skip: True  # [py3k]
```

**Comment by jakirkham** [comment]
Thanks @dopplershift.

**Comment by mfripp** [comment]
This solution is incompatible with `noarch: python`. If you want to keep using that option, you can just specify `python <3` in the requirements section instead. See https://github.com/conda-forge/conda-forge.github.io/issues/486.
