### ISSUE TITLE
[Package request] multi-model-server and model-archiver

### ISSUE THREAD

**Issue by BastianZim** [conda-forge/staged-recipes#16507]
# Some links to get started
- [Currently available conda-forge packages](https://conda-forge.org/feedstock-outputs/)
- [The conda-forge docs](https://conda-forge.org/docs/maintainer/adding_pkgs.html#the-staging-process)
- [Grayskull](https://github.com/conda-incubator/grayskull) - to automatically generate a recipe for packages on PyPI
- [The conda r skeleton helpers](https://github.com/bgruening/conda_r_skeleton_helper) - to automatically generate a recipe for packages on CRAN

# The requested package

- _Package name_: multi-model-server and model-archiver
- _Version (If a specific one is required)_:
- _URL_: https://github.com/awslabs/multi-model-server
- _Available via (GitHub Releases, PyPI, etc.)_: GitHub Releases
- _Additional comments_: Both come from the same repo and building _multi-model-server_ also builds _model-archiver_, so somehow those two have to be separated. 

# Before submitting
- [x] Verify that the package does not already exist (Also check with _hyphens_ vs. _underscores_ and added identifiers like `python-` and `r-`).
- [x] Check that no previous [issue](https://github.com/conda-forge/staged-recipes/issues) exists and that no [PR](https://github.com/conda-forge/staged-recipes/pulls) is currently open.

**Comment by sodre** [comment]
@BastianZim, I added multi-model-server and archiver to conda-forge. You will need JAVA_HOME set, but other than that it should work as expected.

**Comment by BastianZim** [comment]
Awesome, thank you!
