### ISSUE TITLE
Add serf

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#1663]
Add [Apache Serf](https://serf.apache.org/). Requires APR. ( https://github.com/conda-forge/staged-recipes/issues/1662 )

**Comment by pmlandwehr** [comment]
(Not to be confused with [serf](https://pypi.org/project/serf/) in PyPI.

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/conda-forge/staged-recipes/pull/11714 ).
