### ISSUE TITLE
Why tensorflow for windows is 1.14?

### ISSUE THREAD

**Issue by MaverickMeerkat** [conda-forge/staged-recipes#16849]
Hi, is there any reason why the default tensorflow version for windows OS is 1.14? 
If I install through pip I get 2.7 - most recent documentations of Keras/Tensorflow are not supported on 1.14... 

![image](https://user-images.githubusercontent.com/32735496/140759229-b9693223-41ef-412d-95df-89869f7132c3.png)

**Comment by dopplershift** [comment]
There are variety of challenges building Tensorflow for Windows. See [this relevant issue](https://github.com/conda-forge/tensorflow-feedstock/issues/124) for more information. I'm sure the team would love more help trying to get working builds that complete within our CI time constraints.

**Comment by MaverickMeerkat** [comment]
Not sure I understand. There is no challenges when I install it via pip. Why do they appear when I install it via conda?

**Comment by dopplershift** [comment]
I recommend reading the issue I linked to (and the links contained there) which I'd just be repeating here for you. If you have any additional questions after reading those, please post any such comments on the [linked issue](https://github.com/conda-forge/tensorflow-feedstock/issues/124) in the [`tensorflow-feedback`](https://github.com/conda-forge/tensorflow-feedstock)--or a new issue as appropriate. The staged-recipes repository isn't relevant to existing packages, and continuing the discussion here only serves to spam the staged-recipes reviewers.
