### ISSUE TITLE
Detect `skip: True` and cancel relevant CI

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#170]
It would be nice if we checked if `skip: True` was set for a platform as early as possible and terminate CI.

**Comment by pelson** [comment]
> It would be nice if we checked if skip: True was set for a platform as early as possible and terminate CI.

I agree. The point at which to detect might be at the ```conda smithy``` level. That is, we simply don't register the non-windows feedstocks with AppVeyor. The biggest complication with that is when a recipe *wants* to become supported on windows, it is harder to test in a PR.

The more I think about it, the more I lean towards your suggestion - simply grep for the line:

```
skip: True  # [win]
```

No need to complicate things.

@jakirkham - this would be a change to conda-smithy (https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/templates/appveyor.yml.tmpl#L49) (but could be tested in any non-Windows feedstock). Interested in having a go?

**Comment by jakirkham** [comment]
> I agree. The point at which to detect might be at the ```conda smithy``` level. That is, we simply don't > register the non-windows feedstocks with AppVeyor. The biggest complication with that is when a > recipe *wants* to become supported on windows, it is harder to test in a PR.

> The more I think about it, the more I lean towards your suggestion - simply grep for the line:

> ```
> skip: True  # [win]
> ```
> No need to complicate things.

I would be ok with this if you could test PRs, but you're right. It is tricky. Though if you think of a way we could try, I'd be happy to work on it.

> ...this would be a change to conda-smithy...

Ah, so my thought was that it would also be useful to have these changes for staged-recipes too. Do they end up sharing this code?

> Interested in having a go?

Sure, I'll try to come up with something.

**Comment by pelson** [comment]
Thinking about this a little more, the earliest point that you know you can skip a build is after resolving dependencies (e.g. ```skip: True  # [py34]```). For that reason, conda-smithy renders the build matrix appropriately. On Windows this results in an entirely empty matrix of builds on ```appveyor.yml``` which prevents the build taking place altogether.

In short, other than doing the same thing on OSX and Linux, I don't think we can do an awful lot more than we are already.

**Comment by jakirkham** [comment]
> In short, other than doing the same thing on OSX and Linux, I don't think we can do an awful lot more than we are already.

Was just going through issues here and categorizing them. Yeah, I think I agree. We have done a lot in this direction through various PRs and tweaks. There are probably more optimizations we could find if we felt a need. Though I think we have largely resolved the need for any improvement in this area. So, I'm going to close this out.

**Comment by pelson** [comment]
Just to update on this, we do now avoid matrix items which cannot be resolved (coming in conda-build-all 0.13), and avoid matrix items which are explicitly skipped.

We will have to watch out for the former, particularly when feedstocks are created alongside their dependencies at the same time (their CI will dodge the unresolvable matrix items).
