### ISSUE TITLE
[Package request]

### ISSUE THREAD

**Issue by rachelemason** [conda-forge/staged-recipes#17239]
# Some links to get started
- [Currently available conda-forge packages](https://conda-forge.org/feedstock-outputs/)
- [The conda-forge docs](https://conda-forge.org/docs/maintainer/adding_pkgs.html#the-staging-process)
- [Grayskull](https://github.com/conda-incubator/grayskull) - to automatically generate a recipe for packages on PyPI
- [The conda r skeleton helpers](https://github.com/bgruening/conda_r_skeleton_helper) - to automatically generate a recipe for packages on CRAN

# The requested package

- _Package name_: r-spatialreg
- _Version (If a specific one is required)_:
- _URL_: https://cran.r-project.org/web/packages/spatialreg/index.html
- _Available via (GitHub Releases, PyPI, etc.)_: CRAN
- _Additional comments_:

# Before submitting
- [ ] Verify that the package does not already exist (Also check with _hyphens_ vs. _underscores_ and added identifiers like `python-` and `r-`).
- [ ] Check that no previous [issue](https://github.com/conda-forge/staged-recipes/issues) exists and that no [PR](https://github.com/conda-forge/staged-recipes/pulls) is currently open.

**Comment by mfansler** [comment]
@rachelemason this should now be available with `conda install -c conda-forge r-spatialreg`

| Name | Downloads | Version | Platforms |
| --- | --- | --- | --- |
| [![Conda Recipe](https://img.shields.io/badge/recipe-r--spatialreg-green.svg)](https://anaconda.org/conda-forge/r-spatialreg) | [![Conda Downloads](https://img.shields.io/conda/dn/conda-forge/r-spatialreg.svg)](https://anaconda.org/conda-forge/r-spatialreg) | [![Conda Version](https://img.shields.io/conda/vn/conda-forge/r-spatialreg.svg)](https://anaconda.org/conda-forge/r-spatialreg) | [![Conda Platforms](https://img.shields.io/conda/pn/conda-forge/r-spatialreg.svg)](https://anaconda.org/conda-forge/r-spatialreg) |

**Comment by rachelemason** [comment]
Just installed it, thanks!!
