### ISSUE TITLE
[Package request] r-fastverse

### ISSUE THREAD

**Issue by mfansler** [conda-forge/staged-recipes#17439]
## The requested package

- _Package name_: `r-fastverse` (aka, `fastverse` on CRAN)
- _Version (If a specific one is required)_: latest
- _URL_: https://sebkrantz.github.io/fastverse/
- _Available via (GitHub Releases, PyPI, etc.)_: CRAN
- _Additional comments_: 
  The following dependencies must be built first:
  - [x] `r-kit`
  - [x] `r-collapse`

  All packages require compilation.

## Checklist
- [x] Verify that the package does not already exist (Also check with _hyphens_ vs. _underscores_ and added identifiers like `python-` and `r-`).
- [x] Check that no previous [issue](https://github.com/conda-forge/staged-recipes/issues) exists and that no [PR](https://github.com/conda-forge/staged-recipes/pulls) is currently open.

**Comment by dbast** [comment]
Now available https://anaconda.org/conda-forge/r-fastverse
