### ISSUE TITLE
run_test.py keeps getting called repeatedly

### ISSUE THREAD

**Issue by valgur** [conda-forge/staged-recipes#1751]
The Windows builds at #1750 keep failing in an odd way for Python 3.4 specifically. The `run_test.py` file gets called several times in parallel (instead of just once) when testing starts and in some cases called so many times that the CI job gets stuck indefinitely until the 60 min limit is reached.

Take a look at the logs at https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.7831/job/5dd7lvicp5gs368q and https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.7833/job/wehcvsr2q92eyc0k around line 1650.

Any ideas what might be the cause or how to go about debugging it?

**Comment by patricksnape** [comment]
Actually it looks like your `multiprocessing` tests are [misbehaving](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.7831/job/5dd7lvicp5gs368q#L2050). The forking model doesn't exist on Windows so you have to be very careful when using `multiprocessing`.

**Comment by valgur** [comment]
It was indeed due to some kind of `multiprocessing` problem. I don't fully comprehend the reason yet but following a [Python 2 issue](http://bugs.python.org/issue10845) referenced in the source repo, I changed the `run_test.py` calling `unittest.main()` to running `python -m estnltk.run_tests` from `run_test.sh` and `run_test.bat`. This has somehow resolved the multiprocessing problem. Thanks a lot for the hint!
