### ISSUE TITLE
exclude windows os platform support

### ISSUE THREAD

**Issue by raudipra** [conda-forge/staged-recipes#17955]
### General comment:

Hi @conda-forge/staged-recipes, I've submitted [PR](https://github.com/conda-forge/staged-recipes/pull/17954) of our library but always stuck on win_64 win check. It is expected since we don't plan to support Windows on our library. I've specified the build skip selector to unix yet it still runs the win_64 win check.

How do I get rid of this check?

**Comment by chrisburr** [comment]
On staged-recipes the `win_64` is always there due to CI limitations however it does nothing if the recipe is marked as skipping windows.

See https://github.com/conda-forge/staged-recipes/pull/17954/files/070c425fd9a1a3cd79c0211161c3a315374ca4aa#r800208632 for how to fix this specific PR.
