### ISSUE TITLE
cuda_compiler_version is "None" even in cuda builds

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/staged-recipes#18005]
cuda_compiler_version correctly gets inserted correctly into the CI jobs of staged-recipes:

<details>
<summary><code>++ cat /home/conda/staged-recipes-copy/.ci_support/linux64_cuda110.yaml</code></summary>

```
c_compiler:
- gcc
cxx_compiler:
- gxx
fortran_compiler:
- gfortran
c_compiler_version:
- 9
cxx_compiler_version:
- 9
fortran_compiler_version:
- 9
cudnn:
- 8
cdt_name:
- cos7
target_platform:
- linux-64
channel_sources:
- conda-forge
docker_image:
- quay.io/condaforge/linux-anvil-cuda:11.0
cuda_compiler_version:
- 11.0
```

</details>

but when the `meta.yaml` is rendered, the value isn't there.

I puzzled for a while why
```
  skip: true  # [not linux]
  skip: true  # [cuda_compiler_version == "None"]
```

ended up skipping _all_ cuda builds, until I removed the second line and [ran into](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=457141&view=logs&j=251aaabc-0e07-5144-b266-6bec7c06d403&t=4fe67fbf-3741-526d-9898-07821d0893c0&l=350) resolver errors:

```
Mamba failed to solve:
 - nvcc_linux-64 None.*
 - python 3.8.* *_cpython
 - glog
 - gxx_linux-64 9.*
 - pybind11
 - gflags 2.2.*
 - gflags
 - python
 - cmake >=3.12
 - glog 0.5.*
```

**Comment by h-vetinari** [comment]
Side note: the question label should IMO be removed. It's just that there wasn't a better issue type to choose from.

**Comment by BastianZim** [comment]
Another side note: Do you know of a better label because I‘m in the process of adding different issue types and cannot come up with more.

**Comment by h-vetinari** [comment]
How about "bugs in staged-recipes" or "staged-recipes CI issues"?

**Comment by h-vetinari** [comment]
Will be fixed by https://github.com/conda-forge/staged-recipes/commit/8bbc3bebe6eeedbf4cd88fdea770d52427920e53 (originating from https://github.com/conda-forge/staged-recipes/pull/16257; though I've picked it into https://github.com/conda-forge/staged-recipes/pull/16943 and #17303 already)

**Comment by h-vetinari** [comment]
> Edit: You should also be able to choose a blank issue if nothing fits.

Never noticed that one, cool thanks!
