### ISSUE TITLE
Add OpenEXR

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#1802]
It would be great to have a package for OpenEXR.

cc @patricksnape

**Comment by jakirkham** [comment]
@SylvainCorlay, saw you have a package for this in QuantStack. Was wondering if you would be willing to contribute the recipe. 😄

**Comment by SylvainCorlay** [comment]
Ok i will check it out. I am off the grid for a few days but will look at it when I am back.

**Comment by aaronang** [comment]
Fixed in #6913. This is my first time building a package for conda. I am looking forward to receiving feedback 😁
