### ISSUE TITLE
Recipe update did not result in update on Anaconda

### ISSUE THREAD

**Issue by venaturum** [conda-forge/staged-recipes#18216]
### Bug:

The [piso feedstock recipe](https://github.com/conda-forge/piso-feedstock) was updated late January for package version 0.8.0

It's just come to my attention that conda forge reports 0.7.0 as the latest package

@conda-forge/staged-recipes  How do I resolve this?

**Comment by isuruf** [comment]
CI was not triggered for some reason. Push an empty commit and CI will start.

**Comment by venaturum** [comment]
thanks @isuruf, worked a treat!
