### ISSUE TITLE
Feedstocks not converted once in main

### ISSUE THREAD

**Issue by bandersen23** [conda-forge/staged-recipes#18287]
### Bug:

I’ve had three recipes stuck in the `main` branch for 3-4 days and haven’t been built by CI yet. 

They are `griffe`, `mkdocstrings-python`, and `mkdocstrings-python-legacy`. 

It looks like a 403 error on Travis CI when I look at the GitHub actions log. @conda-forge/core - could you check this out?

**Comment by beckermr** [comment]
I deleted the conda-forge/mkdocstrings-python-legacy-feedstock repo to see if that helps.

**Comment by beckermr** [comment]
That didn't work. @chrisburr You've had success here before. Any ideas?

**Comment by chrisburr** [comment]
We ended up needing to open a ticket as it was a bug on their side. I'll make a reproducer and report it again.

**Comment by q-posev** [comment]
I suppose this issue is related to the following in the output log of the `Create feedstocks` workflow:
```
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--without-appveyor', '--without-webservice', '--feedstock_directory', '/tmp/tmphbfrna8u__feedstocks/trexio-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1.
```
Does it prevent the recently added packaged (e.g. `trexio`) from being bushed to the `conda-forge` feedstock?

**Comment by chrisburr** [comment]
Here is the previous issue https://github.com/conda-forge/staged-recipes/issues/15891. I've opened a support ticket with Travis and will follow up here when I get a response.

> Does it prevent the recently added packages (e.g. trexio) from being pushed to the conda-forge feedstock?

Yes, we can't push code to feedstocks before the various CI providers have been registered successfully.

**Comment by bandersen23** [comment]
Thanks for looking into this @chrisburr and @beckermr!

**Comment by bandersen23** [comment]
@chrisburr and @beckermr - I noticed all but `mkdocstrings-python-legacy` were built today - any thoughts on why that one isn't built yet?

**Comment by beckermr** [comment]
I'm not sure. Let's wait a few hours and see what happens. It's failed on both circle and Travis. I reset everything just now so maybe it will go through.

**Comment by bandersen23** [comment]
@beckermr Still no luck...

**Comment by jakirkham** [comment]
Possibly related to this ( https://github.com/conda-forge/status/issues/126 )?

**Comment by bandersen23** [comment]
No worries! Any timeline for it getting migrated?

**Comment by chrisburr** [comment]
I chased them up this morning (~8 hours ago) but no response yet.

**Comment by jakirkham** [comment]
Given we are seeing some feedstocks convert and others not, wonder if it is worth deleting the partially converted feedstocks and then rerunning conversion. Just in case they have some funky state, which is causing us hang ups for whatever reason.

**Comment by beckermr** [comment]
I did that previously and yes we should try again!

**Comment by bandersen23** [comment]
Should I resubmit the recipe in a new PR?

**Comment by beckermr** [comment]
Nope. We'll keep working on it. So sorry for the delay.

**Comment by jakirkham** [comment]
Looks like a bunch of them just cleared. Though `mkdocstrings-python-legacy` is still in there. Maybe let's give it a bit and see if it also clears.

**Comment by beckermr** [comment]
Something's out of sync and the job to make the feedstocks is running twice. Hopefully the tokens are ok.

**Comment by jakirkham** [comment]
Agreed. The [last job that ran]( https://github.com/conda-forge/staged-recipes/runs/5549037172?check_suite_focus=true ) didn't actually start until after the commit was pushed to remove the already converted recipes ( https://github.com/conda-forge/staged-recipes/commit/c0f27204bcd1295e4dbd94d1bea3b12c688183b2 ). There was [a job before that]( https://github.com/conda-forge/staged-recipes/actions/runs/1984910316 ) that canceled itself (seems there was [one just recently like that]( https://github.com/conda-forge/staged-recipes/actions/runs/1984971593 ) as well).

**Comment by jakirkham** [comment]
Actually I don't think it is anything too weird. It took ~20mins to complete the conversion jobs and our cron jobs run every 10 minutes. That's just enough time to have 2 overlapping jobs like that. Probably less of an issue now that we have cleared a bunch of recipes out.

Though if we were looking to change things, we could run less frequently. Or somehow adjust the cron job to skip if one is already running. Though we are kind of already doing that in the job, but maybe there is a way GH Actions could handle that for us (alleviating the need for the job to even run).

**Comment by jakirkham** [comment]
It just [ran on `mkdocstrings-python-legacy`]( https://github.com/conda-forge/staged-recipes/runs/5549240643?check_suite_focus=true ) and failed again. Only took ~2mins to run being the only recipe. Went ahead and just deleted that repo to start fresh. Maybe a 2nd fresh start will do better?

**Comment by jakirkham** [comment]
It seems to be stuck on [CircleCI]( https://github.com/conda-forge/staged-recipes/runs/5549462927?check_suite_focus=true#step:6:901 )?

**Comment by BastianZim** [comment]
> Though if we were looking to change things, we could run less frequently. Or somehow adjust the cron job to skip if one is already running. Though we are kind of already doing that in the job, but maybe there is a way GH Actions could handle that for us (alleviating the need for the job to even run).

There is https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/ but last time I discussed it with @beckermr it seemed like it doesn't have all the features that we'd need.

**Comment by beckermr** [comment]
The code should already skip duplicate jobs. I wonder if that broke.

**Comment by jakirkham** [comment]
Not from what I could tell. It seemed to behave as expected. Please see this comment ( https://github.com/conda-forge/staged-recipes/issues/18287#issuecomment-1067606809 )

**Comment by beckermr** [comment]
Ohhh great! Then I was confused. Yay!

**Comment by bandersen23** [comment]
Since every other feedstock seems to be created, it seems easiest to remove the recipe and to push it... would that fix it? Would that fully reset the CI jobs?

**Comment by beckermr** [comment]
It would not. This is an issue in the circle and or Travis backends. We can make the feedstock without those services but we'd prefer not to.

**Comment by bandersen23** [comment]
I understand that. Any further thoughts on this?

**Comment by beckermr** [comment]
So I cannot even get this feedstock to build by hand in the circle ci app online.

**Comment by bandersen23** [comment]
That's odd... I just checked and was able to build it locally with `boa` so I don't think there's a problem with the recipe?

```bash
conda mambabuild mkdocstrings-python-legacy
```

**Comment by beckermr** [comment]
no I mean circleci running on the repo at all.

**Comment by beckermr** [comment]
We can edit the ci scripts on staged-recipes.

**Comment by isuruf** [comment]
Yes, let's disable circle-ci for now, convert mkdocstrings-python-legacy and re-enable circle-ci

**Comment by beckermr** [comment]
I'll do this tonight when staged-recipes activity has died down a bit.

**Comment by beckermr** [comment]
OK done!. We are so sorry for the delay with this one and thank you for waiting!

**Comment by jakirkham** [comment]
Thanks Matt! 😄

**Comment by bandersen23** [comment]
Thank you so much! No worries.
