### ISSUE TITLE
Suggestions to include in the template-example or FAQ

### ISSUE THREAD

**Issue by MSeifert04** [conda-forge/staged-recipes#1837]
Maybe it's because it was my first recipe but two comments seemed rather trivial. Maybe it would be worth it to include those in the example?
- `license_family`-keyword: Many licenses belong to a family: GPL, Apache, BSD, ... and I've noticed several PRs where it was suggested to include it.
- `toolchain`-build requirement. I've no idea what this is used for but I was asked to include it because the package contains compiled code.

I've read the FAQ and the template and even parts of the `meta.yaml`-conda-specifications and I wouldn't have guessed to include these two. 😄

**Comment by jakirkham** [comment]
Fixed item 2 by merging PR ( https://github.com/conda-forge/staged-recipes/pull/1674 ). As for the other point, PRs welcome. 😄

**Comment by MSeifert04** [comment]
I'm not that good at short and precise instructions but I gave it a shot in #1838. 

If you, or anybody else, has a better idea I wouldn't mind closing that PR again. 😄

**Comment by MSeifert04** [comment]
I'll close this since both issues have been adressed. Thanks!

**Comment by jakirkham** [comment]
Thanks for helping address them. 😄
