### ISSUE TITLE
Package request: deepspeed

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/staged-recipes#18420]
### Package name

deepspeed

### Package version

Newest

### Package website

https://github.com/microsoft/DeepSpeed#installation

### Package availability

PyPI, Github

### Additional comments

Encountered https://github.com/microsoft/DeepSpeed in the context of possible integration with AllenNLP, whose feedstock I maintain.

The [requirements](https://github.com/microsoft/DeepSpeed/tree/master/requirements) look doable, but there'd be several optional installs to take care of.

Previously: #14699

### Package is not available

- [X] The package is not available on conda-forge.

### No previous issues or open PRs

- [X] No previous issue exists and no PR has been opened.

**Comment by hadim** [comment]
Available at https://github.com/conda-forge/deepspeed-feedstock
