### ISSUE TITLE
Package request: datastock

### ISSUE THREAD

**Issue by Didou09** [conda-forge/staged-recipes#18594]
### Package name

datastock

### Package version

Newest

### Package website

1.Pypi: `https://pypi.org/project/datastock/`

2. github: `https://github.com/ToFuProject/datastock`

### Package availability

1. Pypi

### Additional comments

This is a new package, aimed at data handling and easy subclassing and vizualisation.

It will soon be a necessary dependency of `conda-forge/tofu`
(it is the most generic part of the code, extracted to be made available to a wider public, documentation to come soon)

### Package is not available

- [X] The package is not available on conda-forge.

### No previous issues or open PRs

- [X] No previous issue exists and no PR has been opened.

**Comment by dopplershift** [comment]
Done in #18597.
