### ISSUE TITLE
Package request: pyyaml-include

### ISSUE THREAD

**Issue by TheCodingLand** [conda-forge/staged-recipes#19383]
### Package name

pyyaml-include

### Package version

Newest

### Package website

1. Github: https://github.com/tanbro/pyyaml-include

### Package availability

1. https://pypi.org/project/pyyaml-include/

### Additional comments

This package is a dependency to Copier, project templating / scaffoling tool;.

### Package is not available

- [X] The package is not available on conda-forge.

### No previous issues or open PRs

- [X] No previous issue exists and no PR has been opened.

**Comment by thewchan** [comment]
This is available: https://github.com/conda-forge/pyyaml-include-feedstock
