### ISSUE TITLE
OSX64 build returns: xcrun: command not found

### ISSUE THREAD

**Issue by apatsekin** [conda-forge/staged-recipes#19380]
### General comment:

Hey guys! While trying to `build-locally.py` example recipe (by copying it into separate dir with new name so it's not ignored) I get this error:
```
# python3 build-locally.py osx64
...
ERROR: CONDA_BUILD_SYSROOT or SDKROOT has to be set for cross-compiling
/home/conda/staged-recipes/build_artifacts/simplejson_1656039226257/_build_env/etc/conda/activate.d/activate_clang_osx-64.sh: line 116: xcrun: command not found
```

OS: Ubuntu 20.04
python 3.8

**Comment by isuruf** [comment]
Are you trying to compile for macOS on a Linux machine?

**Comment by apatsekin** [comment]
> Are you trying to compile for macOS on a Linux machine?

yep, I assumed that's what conda's cross-compilation is for?
