### ISSUE TITLE
Long running quiet Travis builds terminated

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#195]
For an example of this problem, see [PR]( https://github.com/conda-forge/staged-recipes/pull/192#issuecomment-200672029 ) and [this build]( https://travis-ci.org/conda-forge/staged-recipes/jobs/118118277#L3466 ).

Travis CI doesn't like it if something doesn't produce output for 10 mins. While this can be the sign of a hang, there are perfectly reasonable scenarios where it isn't a hang, but a silent long running command. Unfortunately, there is no simple way to change the time limit (unless this has changed recently :pray:).

One way to workaround this is to use [`travis_wait`]( https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received ), which is essentially a hack that writes to disk periodically. We could try to run conda build through this, but IIRC it gobbles up stdout, which is really unhelpful not too mention this would need to go in the CI and thus affect *all* recipes in the staging area, which I really don't like. If we have to add it to feedstocks that need it as a workaround, that could be ok until we come up with something better. Just as long as we verify that this let's the build complete correctly and is not merely hiding some more serious problem. In other words, have submitters try and then remove before merging.

Alternatively, we could come up with some background process that does a similar thing to `travis_wait`.

Any other thoughts on this problem? Other potential solutions?

**Comment by pelson** [comment]
10mins with output must be pretty rare. It looks like the HDF5 case might have been a problematic ``cache`` test, so I guess the question is, do we invest our time in solving this issue?

**Comment by jakirkham** [comment]
Nope, especially as that was not the issue for that case. If this becomes a frequent problem, we can always revisit this.
