### ISSUE TITLE
Recipes that use SSE/AVX instructions

### ISSUE THREAD

**Issue by patricksnape** [conda-forge/staged-recipes#196]
Some recipes utilise intrinsics such as SSE and AVX. Enabling these intrinsics greatly improves the speed of many applications. However, most applications do not guard against a particular intrinsic not existing at run time and will simply crash if the architecture it is run on does not support a given instruction.

For example, OpenCV supports up to SSE 4.1 instructions - yet it is feasible that someone may download OpenCV on an older Linux box that does not support SSE 4.1. Therefore, I imagine we want to do something like the proposal in #80 whereby we have features for different SSE levels - where supported?

**Comment by jakirkham** [comment]
This is a good idea. However, I'm trying to get these various concerns addressed in this issue ( https://github.com/conda-forge/conda-forge.github.io/issues/49 ). So, closing as a dup so that we can keep the discussion in one place.
