### ISSUE TITLE
create-feedstocks GH runner failing

### ISSUE THREAD

**Issue by coroa** [conda-forge/staged-recipes#19890]
### Bug:

The create-feedstocks runner is currently failing to run, since the explicitly requested conda version is not available for the latest python version 3.9.2.

First appeared at:
https://github.com/conda-forge/staged-recipes/runs/7611073233?check_suite_focus=true#step:6:491

```
++ mamba update -n base --yes --quiet 'conda<4.13' mamba
Encountered problems while solving:
  - package conda-4.10.0-py38h578d9bd_0 requires python >=3.8,<3.9.0a0, but none of the providers can be installed

Error: Process completed with exit code 1.
```

The conda version constraint
https://github.com/conda-forge/staged-recipes/blob/cbb2fded42da308ff0afaff0d0831e61d7991206/.github/workflows/scripts/create_feedstocks#L35
was introduced recently in commit https://github.com/conda-forge/staged-recipes/commit/ae413687dbf443d874d99d34b9e1ae849ae5039f

@conda-forge/staged-recipes

**Comment by beckermr** [comment]
This is fixed.
