### ISSUE TITLE
Versions of Visual Studio on AppVeyor

### ISSUE THREAD

**Issue by jochym** [conda-forge/staged-recipes#1994]
I am dealing with strange compilation failures on AppVayor. The package compiles fine on py35 but not on py27 and py34. It seems the versions of Visual studio for 2.7 and 3.4 are 9.0 and 10.0 while for 3.5 it is 14.0. It seems possible that this is the reason for compilation errors. Is there any way to sync the versions over environments? (BTW the packages are feedstock-spglib and staged-recipes/phonopy).
Or maybe it is possible to specify version of VS for the build? I was unable to find the answer.

**Comment by ocefpaf** [comment]
@jochym unfortunately that is not strange :unamused: 

Each Python version is complied against a different version of MSVisual Studio (the `vc`s). Python 3.5 is the most modern one (`vc14`), so your is software probably using something that either does not exists on `vc 9` (Python 2.7) and `vc 10` (Python 3.4). Sometimes it is possible to patch and make it backwards compatible but I do not understand enough about Windows to help you with that.

The "easy" path is to `skip` the other builds and open an issue in the feedstock later asking for help.

**Comment by jochym** [comment]
Thanks! I have got my answer - on windows you need to keep whole toolchain in sync with python. Sorry for bothering you! I have used skip method but was hoping for extending the availability of the package to other win environments.
