### ISSUE TITLE
Build failing due to no output logs

### ISSUE THREAD

**Issue by souravsingh** [conda-forge/staged-recipes#2018]
I am working on building a recipe for Gensim, but the Travis build errors due to not receiving output for 10 minutes. Here is the recent build report for Travis-https://travis-ci.org/conda-forge/staged-recipes/builds/179534183

Would it be possible to increase the timeout time for Travis?

@jakirkham

**Comment by jakirkham** [comment]
Travis CI doesn't provide us a way to do that. I can't find it right now, but there is an issue on travis-ci's support repo about providing users a way to extend this. My recommendation would be no different than Travis CI's, which is try to increase the verbosity for the build. We can discuss more in your PR. Could you please provide a link to the PR?

**Comment by jakirkham** [comment]
Closed so we can move discussion back to the PR in question.
