### ISSUE TITLE
Linter not failing builds properly

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#202]
This has happened a few times lately. We really need to straighten this out so we get proper failures pre-merge not failed deployments post-merge. Even if we look carefully, we may miss something the linter doesn't and we don't want to be doing a post-merge scramble to fix everything.

**Comment by pelson** [comment]
<@pelson added the label: ```less justification needed```> :stuck_out_tongue_winking_eye:

**Comment by pelson** [comment]
A PR closed this issue, but I'd like to keep an eye on it. If somebody sees a lint not trigger a CI to fail, please shout.

**Comment by jakirkham** [comment]
Thanks for fixing this, @pelson. :smile:

Sorry for being pedantic.
