### ISSUE TITLE
Soften demands of linter to have tests present

### ISSUE THREAD

**Issue by dschreij** [conda-forge/staged-recipes#2022]
See [the Google group](https://groups.google.com/a/continuum.io/forum/?utm_medium=email&utm_source=footer#!msg/conda/is7_mN0RYww/4XDncOh_CQAJ) for a previous discussion of this issue.

Recently I have noticed that the linter's demands to have a test present in the recipe have become quite strict. If there is no entry in the `meta.yaml` file to test the built recipe, the linter fails it completely. I am a strong advocate of good test practices, but I am bumping into a particular situation now where doing tests simply seem impossible.

For one, some modules may require a graphical/windowing environment to function correctly, which not all CI's provide. An example of this is [sdl2_gfx](https://github.com/conda-forge/staged-recipes/pull/1945), which is an add-on for sdl2 which extends it by offering the possibility to perform more advanced drawing operations.  Likewise, sdl2_gfx's dependency glew has two executables `glewinfo` or `visualinfo` that can be called for the sake of testing, but both fail because the CI's don't provide an OpenGL context. So it's terribly difficult to test these packages.

On a similar note, [sdl2_mixer](https://github.com/conda-forge/staged-recipes/pull/1938) provides audio capabilities to sdl2, and mainly has dependencies to encode and decode audio formats. Besides the fact that many of these decoding libraries don't provide standalone tests, the problem is that most CI's don't provide an audio environment, so if there are tests, they can't be run.

It wouldn't be a problem that the linter fails recipes due to the absence of tests, but a failed lint gives the impression that the whole recipe has failed building, and therefore these recipes don't seem to be picked up by reviewers (as far as I can tell) even though their build operations on the CI's completed without any errors.

Shortly put: is it possible to make the linter's testing demands lest stringent in some special cases like these?

**Comment by jakirkham** [comment]
@dschreij , we even use file existence tests. In some cases, that may be the only kind of test that is possible. My recommendation would be to try those in your cases and see how that goes.

**Comment by dschreij** [comment]
I have implemented some tests in the lines of those used by the [boost recipe](https://github.com/conda-forge/boost-feedstock/blob/dac7c7058a4c3b9f874ae11c89d0fcaeb1f41f0d/recipe/meta.yaml#L34-L36), which you referred me to in another thread, and that seems to work perfectly. I think we can close this (non-)issue?

**Comment by jakirkham** [comment]
Going to close as the issue was resolved by having file tests.
