### ISSUE TITLE
create sub-team julia-help

### ISSUE THREAD

**Issue by ngam** [conda-forge/staged-recipes#20386]
### General comment:

We are in the early stages of supporting julia packages with packaged artifacts. We would like to ask for the creation of a julia-help team as part of staged-recipes. This team should include @mkitti and myself, @ngam (others familiar with our proposal including @isuruf and @ocefpaf are welcome to join, but they are already part of core; @MilesCranmer too). The idea is to make sure any new julia-related package plays well with the rest of the ecosystem we are creating and we provide them with support and guidance. This is critical in the early stages as not everything is documented.

Helpful links:
- preliminary strategy for packaging the python interface to a julia package: https://github.com/conda-forge/pysr-feedstock/pull/43
   - TLDR: package the python part, dump the julia part, isolate and ensure interop at least superficially
- on naming julia-packages: https://github.com/conda-forge/conda-forge.github.io/issues/1822
   - TLDR: `julia-<lowercase-sans-jl>`

Thoughts, @conda-forge/staged-recipes @conda-forge/core?

We will also file a CFEP once we establish a decent enough strategy with a few packages working well together (or before if you think it is better)

--

More info

julia-centric packages in circulation:
- https://github.com/conda-forge/julia-feedstock
- https://github.com/conda-forge/juliaup-feedstock
- https://github.com/conda-forge/jill-feedstock
- https://github.com/conda-forge/pysr-feedstock
- https://github.com/conda-forge/xbitinfo-feedstock

julia-centric staged-recipes:
- https://github.com/conda-forge/staged-recipes/pull/20380
- https://github.com/conda-forge/staged-recipes/pull/20379

--

Challenges, WIP, etc.

- proper interoperability in distributed binaries

**Comment by beckermr** [comment]
Done. Note this team is not a subteam of staged recipes since that would give write access to staged-recipes.

**Comment by beckermr** [comment]
I am going to close this issue as done. Feel free to reopen if you need more help.
