### ISSUE TITLE
Multiple packages using the same recipe

### ISSUE THREAD

**Issue by ilya-lavrenov** [conda-forge/staged-recipes#20419]
### General comment:

I have cmake project which has install rules and content is distributed among several components.
For example, on debian system we provide lib**library** and lib**library**-dev packages for our library. So, we can already have 2 packages.
Next, our project has a plugin architecture, so the **library** can load multiple lib**plugin_a**, lib**plugin_b** etc. Using cmake install rules, we can assign different components to different plugins.
Using cpack, we can create multiple package using per-component packaging. 

How does it work for conda?

I see that even for CUDA and OpenCV (see https://github.com/conda-forge/opencv-feedstock/blob/main/recipe/meta.yaml) the only one package is created with all the libraries (OpenCV has extra / auxiliary packages, but libs are in a single one), while in Debian, other distributions OpenCV has module architecture where user can select only specific modules to install

The question is more interesting when **library** has Python API, which needs to be compiled per-minor python version. In this case putting everything into a single packages does not look good IMO, because better to generate *library* (or several) packages, while Python API extensions are built / run on top of it.

Please, advice.

**Comment by isuruf** [comment]
See conda-build docs https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html
