### ISSUE TITLE
OSError: [Errno 13] Permission denied: '/MaSuRCA-3.2.1_09012016'

### ISSUE THREAD

**Issue by mictadlo** [conda-forge/staged-recipes#2042]
I run into `OSError: [Errno 13] Permission denied: '/MaSuRCA-3.2.1_09012016'` which I described here https://github.com/bioconda/bioconda-recipes/issues/3017

**Comment by jakirkham** [comment]
No idea how to help here. Not entirely sure what the issues is or how it relates to staged-recipes generally. Could you please try creating a PR for the package in question and then someone can assist you from there?
