### ISSUE TITLE
Package request: pycobertura

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/staged-recipes#20481]
### Package name

pycobertura

### Package version

Newest

### Package website

https://github.com/aconrad/pycobertura

### Package availability

PyPI, GH tags

### Package is not available

- [X] The package is not available on conda-forge.

### No previous issues or open PRs

- [X] No previous issue exists and no PR has been opened.

**Comment by synapticarbors** [comment]
closed by #20629
