### ISSUE TITLE
Package request: rio-stac

### ISSUE THREAD

**Issue by Ariana-B** [conda-forge/staged-recipes#20902]
### Package name

rio-stac

### Package version

Newest

### Package availability

https://pypi.org/project/rio-stac/

### Package is not available

- [X] The package is not available on conda-forge.

### No previous issues or open PRs

- [X] No previous issue exists and no PR has been opened.

**Comment by thewchan** [comment]
PR made: https://github.com/conda-forge/staged-recipes/pull/21326
