### ISSUE TITLE
Resolve naming of mad/libmad

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#2093]
Need to fix the directory name or the package name of mad/libmad to be consistent in both cases.

cc @dschreij

xref: https://github.com/conda-forge/staged-recipes/pull/2027#discussion_r92912164

**Comment by dschreij** [comment]
Done! I renamed the folder to libmad, see https://github.com/conda-forge/staged-recipes/pull/2094.
Sorry for the inconvenience.

**Comment by dschreij** [comment]
I will likely have to do the same for https://github.com/conda-forge/staged-recipes/pull/2079 (ogg vs libogg), so I'm on that now.

**Comment by jakirkham** [comment]
Thanks @dschreij . Would be curious to hear your thoughts on issue ( https://github.com/conda-forge/staged-recipes/issues/1073 ), which is the underlying cause of this problem.

**Comment by jakirkham** [comment]
Merged PR ( https://github.com/conda-forge/staged-recipes/pull/2095 ) to rename ogg/libogg too. I think we are in good shape to clear at staged-recipes now. Thanks @dschreij .

**Comment by jakirkham** [comment]
These did the trick. staged-recipes is now clear. Thanks @dschreij .
