### ISSUE TITLE
Removal of build_capi-feedstock in favor of build-capi-feedstock

### ISSUE THREAD

**Issue by horta** [conda-forge/staged-recipes#2100]
Hello,

I would like to request the removal of https://github.com/conda-forge/build_capi-feedstock since now we have https://github.com/conda-forge/build-capi-feedstock with appropriate naming...

**Comment by jakirkham** [comment]
How would we like to proceed @conda-forge/core?

**Comment by CJ-Wright** [comment]
Archive the old one and give the new one outputs which recreates the old name? I wish that we could send deprecation warnings for packages.

**Comment by jakirkham** [comment]
Have archived the old one. The rest IMHO is up to the maintainer.
