### ISSUE TITLE
`nodejs` not getting linked in subsequent conda build envs

### ISSUE THREAD

**Issue by lgpage** [conda-forge/staged-recipes#2117]
`nodejs` gets installed and linked in the first conda test env (`py27`), but does not get linked in any of the following conda envs. I am guessing it has to do with `nodejs` being a `noarch_python` build.

I also tested builds locally with `conda-build-all v1.0.1` and `conda-build v2.0.12` and all consecutive builds pass. Note, in the CircleCI report:
> The following packages will be DOWNGRADED due to dependency conflicts:
    conda-build: 2.0.12-py35_0 defaults --> 1.21.14-py35_0 defaults

If I use `conda-build v1.21.14` the builds fail locally as well.

More details in #2065
This may also apply to other `noarch_python` built packages, c.f. #2067

**Comment by scopatz** [comment]
Thanks for reporting this, @lgpage.

**Comment by lgpage** [comment]
I can confirm that this behaviour is no longer present with `conda-build 2` and this issue can be closed.
