### ISSUE TITLE
Package request: r-timechange

### ISSUE THREAD

**Issue by mfansler** [conda-forge/staged-recipes#21192]
### Package name

r-timechange

### Package version

`>=0.1.1`

### Package website

1. CRAN: https://cran.r-project.org/package=timechange
2. GitHub: https://github.com/vspinu/timechange/

### Package availability

CRAN

### Additional comments

This package is required for [latest `r-lubridate`](https://github.com/conda-forge/r-lubridate-feedstock/pull/20).

The `r-timechange` package redistributes part of CCTZ, a Google C++11 library that has Apache 2.0 license. It may be preferable to also add a `libcctz` recipe and depend on this, rather than vendor the CCTZ subset.

Also, may need to be careful that there is no clobbering with [the `r-rcppcctz` package](https://github.com/conda-forge/r-rcppcctz-feedstock), which is an Rcpp version of CCTZ.

### Package is not available

- [X] The package is not available on conda-forge.

### No previous issues or open PRs

- [X] No previous issue exists and no PR has been opened.

**Comment by thewchan** [comment]
https://github.com/conda-forge/staged-recipes/pull/21319
