### ISSUE TITLE
Package request: qiskit-aer

### ISSUE THREAD

**Issue by 1ucian0** [conda-forge/staged-recipes#21376]
### Package name

qiskit-aer

### Package version

Newest

### Package website

* Website - https://qiskit.org/documentation/apidoc/aer.html
* GitHub - https://github.com/Qiskit/qiskit-aer/

### Package availability

* PyPI - https://pypi.org/project/qiskit-aer/
* GitHub release - https://github.com/Qiskit/qiskit-aer/releases

### Additional comments

Previous attempt: https://github.com/conda-forge/staged-recipes/pull/18847

### Package is not available

- [X] The package is not available on conda-forge.

### No previous issues or open PRs

- [X] No previous issue exists and no PR has been opened.

**Comment by leofang** [comment]
Qiskit Aer is already live (#21404), this can be closed now.
