### ISSUE TITLE
Package request: anaconda-clean

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/staged-recipes#21437]
### Package name

anaconda-clean

### Package version

Newest

### Package website

https://github.com/ContinuumIO/anaconda-clean

### Package availability

https://anaconda.org/anaconda/anaconda-clean

### Additional comments

Would help users migration from the main channel.

### Package is not available

- [X] The package is not available on conda-forge.

### No previous issues or open PRs

- [X] No previous issue exists and no PR has been opened.

**Comment by BastianZim** [comment]
Added it in #21453
