### ISSUE TITLE
Switch to Miniconda 3 to avoid UnicodeDecodeErrors

### ISSUE THREAD

**Issue by Juanlu001** [conda-forge/staged-recipes#215]
As reported at https://github.com/pelson/Obvious-CI/issues/58, conda has some open issues regarding non-ASCII text on Python 2 which don't appear anymore on Python 3:

https://github.com/conda/conda/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+unicode+OR+ascii

Specifically, https://github.com/conda/conda/issues/1486 appeared to bite us after submitting https://github.com/conda-forge/staged-recipes/pull/214.

Would it be possible to use Miniconda 3 for staged-recipes?

**Comment by jakirkham** [comment]
Thanks for adding here, as well.

**Comment by pelson** [comment]
:+1:. The magic line is at https://github.com/conda-forge/staged-recipes/blob/master/.CI/build_all#L8 and https://github.com/conda-forge/staged-recipes/blob/master/.CI/create_feedstocks#L6

**Comment by pelson** [comment]
I've submitted a PR to address this at #217

**Comment by pelson** [comment]
Hope that does the trick for you @Juanlu001.
We are already doing this for all of the feedstocks:
 * https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/templates/travis.yml.tmpl#L33
 * https://github.com/pelson/Obvious-CI/blob/master/obvious-ci.docker/linux64_obvci/Dockerfile#L19

And on Windows, the miniconda being installed depends on the Python which is being used for building: https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/templates/appveyor.yml.tmpl#L55

**Comment by Juanlu001** [comment]
Great, thanks! This is no longer a problem for #214 since we are now using a tarball instead of the git repository, but I am glad we embraced the future (and present) of Python :)
