### ISSUE TITLE
Enabled "Update branch" button on PRs

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#21697]
GitHub has an option to show a button to [update a branch if it is out-of-date]( https://github.blog/changelog/2022-02-03-more-ways-to-keep-your-pull-request-branch-up-to-date/#always-have-the-option-to-update ). Since this can sometimes be useful to pick up CI changes in a PR, went ahead and enabled it. Note that there is no need to keep branches up-to-date (that would be a headache). Just an option should it be useful.

Note: No action is need here. This is purely informative (or if questions come up).

cc @conda-forge/core @conda-forge/staged-recipes

**Comment by beckermr** [comment]
Thank you!
