### ISSUE TITLE
Package request: grunnur

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#21808]
### Package name

grunnur

### Package version

Newest

### Package website

https://github.com/fjarri/grunnur

### Package availability

1. https://pypi.org/project/grunnur/
2. https://github.com/fjarri/grunnur

### Additional comments

This will be needed for `reikna` in the future

### Package is not available

- [X] The package is not available on conda-forge.

### No previous issues or open PRs

- [X] No previous issue exists and no PR has been opened.

**Comment by rxm7706** [comment]
@jakirkham grunnur is available now
https://anaconda.org/conda-forge/grunnur

**Comment by jakirkham** [comment]
Thanks @rxm7706! 🙏
