### ISSUE TITLE
Conda generated package version is in not confirmatory to PyPi version.

### ISSUE THREAD

**Issue by wxguy** [conda-forge/staged-recipes#21965]
### Bug:

@conda-forge-admin, please ping conda-forge/staged-recipes
@conda-forge/staged-recipes

I have created an application `wrfplot` which is located at https://pypi.org/project/wrfplot/. The corresponding conda package is located at https://anaconda.org/conda-forge/wrfplot. I can install the package from conda-forge and it does the intended purpose. However, the METADATA under the `dist.info` directory file created by conda somehow says `0.0.0` always. This is causing the the application to show version as `0.0.0` always. This is not the case with PyPi which `PKG-INFO` file which is the release version. 

I feel that something went wrong with the conda package generation process. Or am I missing something???

**Comment by ocefpaf** [comment]
The problem is upstream. The sdist uploaded to PyPI does not have the version info. See https://github.com/wxguy/wrfplot/blob/v0.8.7/pyproject.toml#L6-L8.

**Comment by wxguy** [comment]
Thank you for your response. I have used ![setuptools-git-versioning](https://pypi.org/project/setuptools-git-versioning) for managing version control in sdist. You can have a look at the source code https://github.com/wxguy/wrfplot/blob/v0.8.7/pyproject.toml#L10-L11. Moreover, here is the `PKG-INFO` file content from PyPi released version of my software:

```
Metadata-Version: 2.1
Name: wrfplot
Version: 0.8.7
Summary: Command line application to plot WRF model output data
......
.......
```

and here is the `PKG-INFO` file content which is located inside `*.egg-info`:

```
Metadata-Version: 2.1
Name: wrfplot
Version: 0.8.7
Summary: Command line application to plot WRF model output data
...
...
```

However, here is the content of the `METADATA` file content from `*.egg-info` direct tory of the conda package:

```
Metadata-Version: 2.1
Name: wrfplot
Version: 0.0.0
Summary: Command line application to plot WRF model output data
Home-page: https://github.com/wxguy/wrfplot
...
...
```
Clearly, there is an issue with conda packaging. How does the conda build process pick up the version information from the sdist package released from PyPi?

**Comment by ocefpaf** [comment]
> Clearly, there is an issue with conda packaging. How does the conda build process pick up the version information from the sdist package released from PyPi?

You are shipping that egginfo in the sdist, not letting the package build it properly. Without the git tree or the `_version.py`, anyone trying to build it properly won't have the version info.

**Comment by wxguy** [comment]
Thank you for your feedback again. As per your suggestion, I have removed the `egg-info` directory from the sdist package in PyPi. However, there is a new directory called `wrf-0.0.0-dist-info`  created during the new build Again, the METADATA file indicates the version as `0.0.0`. 

I do have the `_version.py` both in sdist and GitHub. I still believe, there is some issue. I have also checked other packages from conda-forge. They do have `egg-info` file embedded in it. There is no version-related documentation in `conda` documentation which makes it hard to debug what went wrong.

**Comment by ocefpaf** [comment]
> It should be there in the conda documentation somewhere.

It is not about conda. If you are using `setuptools-git-versioning` you need the git repo info to extract the version and source distributions won't have that. The correct way to publish a source distribution is to write the version file using setuptools_scm. Conda has nothing to do with this. Conda, pip, etc will only read the metadata that is provided and, for `setuptools-git-versioning`, that means you would have to ship the whole git repo (or at least the tags).
