### ISSUE TITLE
package bzip2

### ISSUE THREAD

**Issue by lexual** [conda-forge/staged-recipes#2223]
It appears bzip2 is not available from conda-forge, only from continuum.

I will attempt to package bzip2 to fix this.

**Comment by msarahan** [comment]
Please start with https://github.com/conda-forge/staged-recipes/pull/1977

**Comment by jakirkham** [comment]
Yep, please feel free to take that PR over.

**Comment by lexual** [comment]
How do I do that? I can't push to the original person's branch. Or do we close, and do I open a new branch starting with the original author's work?

**Comment by msarahan** [comment]
The latter is what usually happens. We'll just close that PR and point to yours when you open it.

**Comment by jakirkham** [comment]
Anything we can do to help, @lexual?

**Comment by lexual** [comment]
Looks like it builds OK on Linux, but not OS-X & Windows.
Wasn't too sure how to debug those other ones.

See the very last messages here:

https://github.com/conda-forge/staged-recipes/pull/1977#issuecomment-270201089

I did have a commit to make the linter happy here: https://github.com/lexual/staged-recipes/tree/new_bzip2

**Comment by rolando** [comment]
Worth noting that anaconda's version only provides a static library so it's not useful for packages that want to use the shared library.
