### ISSUE TITLE
Package request: rdma-core libraries

### ISSUE THREAD

**Issue by kkraus14** [conda-forge/staged-recipes#22306]
### Package name

rdma-core

### Package version

Newest

### Package website

https://github.com/linux-rdma/rdma-core

### Package availability

GitHub Releases

### Additional comments

This is a userspace library interface to various kernel modules so I'm not sure if it's even possible to package this or if this needs to be a CDT, in which case we're limited to CentOS 7 versioning which is quite old and no longer supported by many downstream projects.

This came up in https://github.com/conda-forge/ucx-split-feedstock/pull/111

Wanted to open an issue to capture exploration / discussion.

cc @jakirkham @pentschev

### Package is not available

- [X] The package is not available on conda-forge.

### No previous issues or open PRs

- [X] No previous issue exists and no PR has been opened.

**Comment by jakirkham** [comment]
Peter submitted PR ( https://github.com/conda-forge/staged-recipes/pull/22869 ) to add this
