### ISSUE TITLE
Package request: traefik

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/staged-recipes#22314]
### Package name

traefik

### Package version

Newest

### Package website

- https://traefik.io
- https://github.com/traefik/traefik

### Package availability

- https://github.com/traefik/traefik/releases/tag/v2.9.8

### Additional comments

This package is a dependency for https://pypi.org/project/jupyterhub-traefik-proxy/

### Package is not available

- [X] The package is not available on conda-forge.

### No previous issues or open PRs

- [X] No previous issue exists and no PR has been opened.

**Comment by manics** [comment]
This is blocked by a dependency on go 1.19
https://github.com/traefik/traefik/blob/v2.9.8/go.mod#L3

There are several PRs attempting to get 1.19 building but none are passing yet
https://github.com/conda-forge/go-feedstock/pulls

**Comment by bollwyvl** [comment]
One of the go 1.19+ PRs is now green: https://github.com/conda-forge/go-feedstock/pull/174

**Comment by bollwyvl** [comment]
Started this (linux-only) over on #22850.

**Comment by bollwyvl** [comment]
Also a strawman up on #22853 for `jupyterhub-server-proxy`. And found some stuff :blush:
