### ISSUE TITLE
Inconsistent compiler versions in staged-recipes vs. package-feedstock

### ISSUE THREAD

**Issue by jan-janssen** [conda-forge/staged-recipes#22620]
### Bug:

I build a conda-forge package for a module which is a bit picky about compiler settings. It worked fine on the staged-recipes: 
https://github.com/conda-forge/staged-recipes/pull/22502
But it failed once the feedstock was rerendered: 
https://github.com/conda-forge/flux-core-feedstock
So I have the feeling the compiler version are inconsistent. I am not sure how many packages are effected by this, but it would be great to have consistent versions.

**Comment by isuruf** [comment]
A PR was just merged to upgrade to gcc 12. cc @h-vetinari, @conda-forge/core

**Comment by beckermr** [comment]
Let's watch it. If this is a one-off, we can help make the change in the affected feedstocks. If a bunch of stuff starts to fail, we can back it out.

**Comment by h-vetinari** [comment]
Hey @jan-janssen, sorry about the breakage.

You managed to fall into a short windows where we merged but haven't updated staged-recipes yet (yes of course the versions should be consistent).

To get back to what was the state of affairs until yesterday, you can add the following to `recipe/conda_build_config.yaml` and rerender:
```
c_compiler_version:            # [unix]
  - 11                         # [linux]
  - 14                         # [osx]
cxx_compiler_version:          # [unix]
  - 11                         # [linux]
  - 14                         # [osx]
```

**Comment by jan-janssen** [comment]
That's fine with me - I just thought I bring it up as it might have effected other users as well. Thanks for the quick reply.
