### ISSUE TITLE
Package request: less

### ISSUE THREAD

**Issue by corneliusroemer** [conda-forge/staged-recipes#22777]
### Package name

less

### Package version

Newest

### Package website

https://github.com/gwsw/less

### Package availability

Github releases

### Package is not available

- [X] The package is not available on conda-forge.

### No previous issues or open PRs

- [X] No previous issue exists and no PR has been opened.

**Comment by tetov** [comment]
Not entirely sure why it's needed but I'd like to tackle this to become better at packaging c for conda cross-platform. :).

**Comment by tetov** [comment]
@corneliusroemer: Could you tell me more about your use case? Any requests for which regex engine to use?

**Comment by manics** [comment]
less is already available for Windows: https://anaconda.org/conda-forge/m2-less

**Comment by corneliusroemer** [comment]
@tetov No preference for which regex engine to use. Use case is for example installation of less via `micromamba` docker image - we include it in Nextstrain docker runtime which we try to mirror in our conda runtime, but less is one of the packages missing so far. Reduced Dockerfile complexity. Also as @manics mentions, nice to have on Windows.
