### ISSUE TITLE
Add csvkit

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/staged-recipes#2278]
Per [the docs](https://csvkit.readthedocs.io/en/749/), "csvkit is a suite of command-line tools for converting to and working with CSV, the king of tabular file formats." Continuum has [the `0.9.1` version.](https://anaconda.org/anaconda/csvkit) There might be some weird versioning issue. (Is the new version `1.0.2` or `749`?

**Comment by pmlandwehr** [comment]
In progress - see https://github.com/conda-forge/staged-recipes/pull/2458

**Comment by synapticarbors** [comment]
Closed via https://github.com/conda-forge/staged-recipes/pull/2611
