### ISSUE TITLE
Is license correct?

### ISSUE THREAD

**Issue by sanbales** [conda-forge/staged-recipes#22880]
### General comment:

The [LICENSE file](https://github.com/conda-forge/staged-recipes/blob/main/LICENSE) lists "Copyright 2023 Alibaba AdaFlow. All rights reserved."  Is this correct?

**Comment by sanbales** [comment]
Looks like this was done in error: https://github.com/conda-forge/staged-recipes/pull/22538#issuecomment-1517562822

Just bringing it up in case no one that can fix this is aware of it.

**Comment by BastianZim** [comment]
Thanks for raising this! I'm looking at it and it's definitely wrong, I'm just trying to figure out what we had before? 🤔
The merge created the file: https://github.com/conda-forge/staged-recipes/pull/22538/files#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7

**Comment by isuruf** [comment]
Thanks. It's hard to find out which commit deleted the file and which added the new file because of the hundreds of merge commits in the repo. I restored the file from a commit earlier in the year.
