### ISSUE TITLE
Block recipe PRs that already have a feedstock.

### ISSUE THREAD

**Issue by moorepants** [conda-forge/staged-recipes#2310]
I just submitted a second feedstock for pydy: #2304 not remembering that I submitted one six months ago. Maybe there should be an automatic warning or prevention if a feedstock of the same name already exists.

**Comment by jakirkham** [comment]
Yep, this has come up before. There was even a script written to do this. Maybe join in the discussion over there. Closing to consolidate the discussion.

xref: https://github.com/conda-forge/conda-forge.github.io/pull/195
