### ISSUE TITLE
Last three recipes have failed on merge into master

### ISSUE THREAD

**Issue by moorepants** [conda-forge/staged-recipes#2311]
Seems like we've hit an api limit in:

https://travis-ci.org/conda-forge/staged-recipes/builds/196331121

```
GitHub API Rate Limit Info:

---------------------------

Currently remaining 5000 out of 5000.

Will reset in 0:59:59.349455.

Calculating the recipes which need to be turned into feedstocks.

No local changes to save

Current branch master is up to date.

No stash found.

On branch master

Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean

GitHub API Rate Limit Info:

---------------------------

Currently remaining 5000 out of 5000.

Will reset in 0:59:58.597998.
```

**Comment by moorepants** [comment]
Actually that says that 5000 are remaining, so maybe we haven't hit the limit. Not sure why master is failing. This is the error:

```
Repository created, please edit conda-forge.yml to configure the upload channels

and afterwards call 'conda smithy register-github'

fatal: Cannot update paths and switch to branch 'master' at the same time.

Did you intend to checkout 'upstream_with_token/master' which can not be resolved as commit?

Switched to a new branch 'master'

CI Summary for conda-forge/jupyter-matplotlib-feedstock (can take ~30s):

 * Travis doesn't know about the repo, synching (takes a few seconds).

Unable to register the repo on Travis

(Is it down? Is the "conda-forge" name spelt correctly? [note: case sensitive])

Fetching package metadata .........

Fetching package metadata .........

Fetching package metadata .........

Fetching package metadata ...........

Fetching package metadata ...........

Re-rendered with conda-smithy 2.0.1.

No changes made. This feedstock is up-to-date.

On branch master

nothing to commit, working directory clean

Traceback (most recent call last):

  File ".CI/create_feedstocks.py", line 203, in <module>

    subprocess.check_call(['git', 'commit', '-am', "Re-render the feedstock after CI registration."], cwd=feedstock_dir)

  File "/Users/travis/miniconda/lib/python2.7/subprocess.py", line 541, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['git', 'commit', '-am', 'Re-render the feedstock after CI registration.']' returned non-zero exit status 1
```

**Comment by ocefpaf** [comment]
The only solution is to wait  ;-p

**Comment by moorepants** [comment]
Got it. But should the message say "Currently remaining 0 out of 5000"?

**Comment by ocefpaf** [comment]
I read your message not the error  (only on the phone now). I will take a better look tomorrow.

**Comment by minrk** [comment]
It looks like the `ipympl` recipe is in a folder called `jupyter-matplotlib` and build is failing because `conda-forge/ipympl-feedstock` was created, but a later part of the code is checking for and failing to find `conda-forge/jupyter-matplotlib-feedstock`.

I opened #2312 to fix this by renaming the `jupyter-matplotlib` folder to ipympl, so the two match, which should let things start building again. #2313 should fix the bug in earnest, but that should get more careful review, since I'm not as confident that there aren't other points where a mismatch could cause breakdown.

**Comment by moorepants** [comment]
The merge commit on master failed. I also have two empty feedstocks:

https://github.com/conda-forge/yeadon-feedstock
https://github.com/conda-forge/opty-feedstock

I'm not sure how these get fixed.

**Comment by jakirkham** [comment]
It is a good point @minrk, but it definitely slips below the radar. Really this should be handled programmatically. Either the linter should be catching the directory/package name mismatches as this is trivial to do programmatically and it is easy for human reviewers to miss or we should just always use the package name as the directory name shouldn't really matter. Oddly enough I think adding this to the linter is easier.

xref: https://github.com/conda-forge/staged-recipes/issues/1073
