### ISSUE TITLE
Homebrew formulas

### ISSUE THREAD

**Issue by stefan-balke** [conda-forge/staged-recipes#233]
Hi there,

I'm running into one dependency after the other.

Most of the time I Google for "homebrew formular packagexyz"
and copy parts from there.

Why not write a wrapper for those formulas?

**Comment by ocefpaf** [comment]
`homebrew` is an OS X solution and a 1-to-1 correspondence to a conda recipe is not easy. Note that even the conda `skeleton` for PyPI and CRAN are just helpers and they do not provide a solution to all Python and R packages.

I usually look into RPM specfiles and/or homebrew recipes to get some ideas and inspirations, but I don't think we'll have a universal wrapper for that soon.

**Comment by stefan-balke** [comment]
Well, yes it is an OS X solution.

I'm thinking more of a litte web tool. Brew formula in - conda suggestion out.

Won't be fully automatic but a starting point to speed up package generation.

**Comment by ocefpaf** [comment]
> Won't be fully automatic but a starting point to speed up package generation.

I am not against it. I just don't think anyone have the free cycles to do such a tool.

**Comment by msarahan** [comment]
You could also look to conda skeleton for design ideas:

http://conda.pydata.org/docs/build_tutorials/pkgs.html
https://github.com/conda/conda-build/blob/master/conda_build/main_skeleton.py
https://github.com/conda/conda-build/blob/master/conda_build/pypi.py

**Comment by pelson** [comment]
Hi @stefan-balke - I think this is a neat idea, though it may suffer from not being general enough to transcend beyond OSX. That said, I don't think this is really an issue for staged-recipes, so I'll go ahead and close it. As @msarahan said, might be an interesting one to raise over at https://github.com/conda/conda-build/
