### ISSUE TITLE
Travis CI outage

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/staged-recipes#2335]
It seems that the feedstock creation builds in the master branch fell between the cracks... They weren't cancelled by travis and are not starting.

@conda-forge/core I guess that a new build would probably complete while these cannot even be cancelled.

**Comment by nicoddemus** [comment]
I'm experiencing the same thing... has been two days on some of the feedstocks I maintain.

I'm restarting the jobs manually, will post back here.

**Comment by nicoddemus** [comment]
There's a "Restart job" button on the right side of each job line in the Travis build page. After clicking on it, the button changes to "Cancel job" and the "Cancel build" appears. Here's one of the feedstocks I've restarted this way: https://travis-ci.org/conda-forge/pytest-cpp-feedstock/builds/197160552

**Comment by SylvainCorlay** [comment]
Yeah I know about this but it does not apply to the staged recipes jobs
that fell between the cracks in the travis ci outage.

No means to stop or restart unlike usual builda.

**Comment by ocefpaf** [comment]
> No means to stop or restart unlike usual builda.

Not true. That was already done.

> Yeah I know about this but it does not apply to the staged recipes jobs
that fell between the cracks in the travis ci outage.

Nope. All we need to do is to wait now.

**Comment by nicoddemus** [comment]
Oh sorry, indeed I was speaking for the feedstocks and not for the staged-recipe's jobs. Sorry about the noise.

**Comment by ocefpaf** [comment]
> Oh sorry, indeed I was speaking for the feedstocks and not for the staged-recipe's jobs. Sorry about the noise.

No problem. That is not noise!

**Comment by SylvainCorlay** [comment]
It is really odd that I could not restart the build while I do it without issues on feedstocks. Thanks for kicking it.
