### ISSUE TITLE
Package request: playwright-python

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/staged-recipes#23382]
### Package name

playwright-python

### Package version

Newest

### Package website

https://github.com/microsoft/playwright-python

### Package availability

1. https://pypi.org/project/playwright/#files
2. https://github.com/microsoft/playwright-python/releases/tag/v1.36.0
3. https://anaconda.org/microsoft/playwright

### Additional comments

This is a dependency for `nbconvert`, replacing the relatively unmaintained `pyppeteer`.

The build is fairly "untidy", as it downloads a bunch of binary blobs and repacks them in `setup.py`... and may well download custom `chromium`, etc. binaries.

A number of attempts in the past have tried to package this, but have all been [closed](https://github.com/conda-forge/staged-recipes/pulls?q=is%3Apr+playwright+is%3Aclosed).

### Package is not available

- [X] The package is not available on conda-forge.

### No previous issues or open PRs

- [X] No previous issue exists and no PR has been opened.

**Comment by pavelzw** [comment]
There actually is already https://anaconda.org/microsoft/playwright but this doesn't support osx-arm64.

**Comment by bollwyvl** [comment]
But as it is not on `conda-forge`, it can't be used as a dependency for `conda-forge` packages.

**Comment by pavelzw** [comment]
seems to be fixed now https://github.com/conda-forge/playwright-python-feedstock

**Comment by mxschmitt** [comment]
@jan-janssen do you know why there is now

https://github.com/conda-forge/playwright-python-feedstock/

and

https://github.com/conda-forge/playwright-feedstock

? Maybe use the one without Python, since it seems more aligned how Playwright is usually getting shipped?

**Comment by bollwyvl** [comment]
The latter is the original, `nodejs`-based package.

**Comment by jan-janssen** [comment]
> ? Maybe use the one without `python` as a suffix, since it seems more aligned how Playwright is usually getting shipped/called?

In principle we could also do it the other way around like having a `playwright-nodes` package and a `playwright` package for the python interface. I primarily followed the naming of the Github repositories https://github.com/microsoft/playwright and https://github.com/microsoft/playwright-python .
