### ISSUE TITLE
problem with build of new recipe:  scikit-rf

### ISSUE THREAD

**Issue by arsenovic** [conda-forge/staged-recipes#2344]
hi, 
  i just made a recipe( https://github.com/conda-forge/staged-recipes/pull/2323), but it is failing with an error i do not understand.

**Comment by jakirkham** [comment]
It seems there is an [answer]( https://github.com/conda-forge/staged-recipes/pull/2323#pullrequestreview-20155037 ). Am going to close this so as to keep conversation in that PR.
