### ISSUE TITLE
Packaging clarabel Python package and Clarabel.cpp that are both interfaces of the same Clarabel.rs rust library.

### ISSUE THREAD

**Issue by traversaro** [conda-forge/staged-recipes#23725]
### General comment:

Hello everyone! I am interested in packaging the clarabel python package (https://pypi.org/project/clarabel/) and the Clarabel.cpp C++ package (https://github.com/oxfordcontrol/Clarabel.cpp), that are both interfaces of the same Clarabel.rs rust library (https://github.com/oxfordcontrol/Clarabel.rs).

I am opening an issue before a PR because this is the first case in which I am packaging two libraries (in Python and C++) that share the backend library written in Rust. It is safe to just package them indipendently, or the two copies of the rust library that somehow they include could create conflicts if both are loaded in memory by the same process? 

For example, let's say for example (this is not the case at the moment) that casadi (a C++ library) adds Clarabel.cpp as a possible QP solver. It would be save then to load in a Python executable both the casadi python bindings (that  would link transitively with Clarabel.cpp) and the clarabel Python package?

I am not sure who can provide valuable input on this, but I guess that @conda-forge/rerun-sdk mantainers could have the same problem once the rerun C++ SDK is released, but if there is anyone that has an input on this, any reply or additional info

**Comment by traversaro** [comment]
Reading a bit about Rust mangling (see https://internals.rust-lang.org/t/crate-disambiguators-and-reproducibility/11659 for a nice Discourse post with links to the actual Rust source code), I think I am able to answer myself:  Rust symbols mangling include an hash that depends on a lot of aspect of the crate being compiled and its dependencies (see https://github.com/rust-lang/cargo/blob/c22380da3215bd45e3ca08dbd7af4f0090d972b0/src/cargo/core/compiler/context/compilation_files.rs#L550). This ensure that symbols names as seen by the linker will be different, unless they are exactly identical. 

Now that I understood a bit about how cargo/rust compilation model works, I have another question: for reproducibility, should we ensure that a Cargo.lock file is used to build Rust code, either in the upstream repo (as done for example by pixi, see https://github.com/prefix-dev/pixi/blob/f38415ecee5e0469ade3e5d652bbac9bccef0c9f/Cargo.lock) or if the upstream repo does not contain a Conda.lock, should we mantain it in the feedstock?

**Comment by baszalmstra** [comment]
Thats a very good point @traversaro !

It would be good to always include a `Cargo.lock` file next to the recipe. Since the dependencies are not from conda-forge it will be really hard to reproduce the build if there is no lock file.

**Comment by traversaro** [comment]
I thinked a bit about it, and while non-reproducibility it is not ideal, this is exactly what happens with the conda-forge dependencies: for build, except for dependencies pinned in https://github.com/conda-forge/conda-forge-pinning-feedstock, the solver decides which version to install, and there is no pinned version of them saved anywhere. Even for pinned dependencies, only the version related to ABI compatibility is pinned, but not the precise version (for example ffmpeg=6 is pinned, but it is not describd if 6.0.1 or 6.0.2 should be installed). So even if no `Cargo.lock` is available, this mirrors exactly what we are doing with conda dependencies. 

At this point I do not have any more questions related to C++/Python libraries with Rust dependencies, so I will close the issue, thanks @baszalmstra for chiming in!
