### ISSUE TITLE
Add mdbtools

### ISSUE THREAD

**Issue by snowman2** [conda-forge/staged-recipes#2382]
http://mdbtools.sourceforge.net/

Provide tools to extract data from MS access databases. Would be nice to have these tools available via conda.

**Comment by jakirkham** [comment]
What sort of license are we looking at here? If the licensing is not egregious, packaging it would be ok.

**Comment by snowman2** [comment]
Looks like GPLv2

https://sourceforge.net/projects/mdbtools/

**Comment by pmlandwehr** [comment]
There's a collision here with the pypi listing for  [`mdbtools`](https://pypi.org/project/mdbtools/)

**Comment by snowman2** [comment]
OK. It is no longer something that I would need. So, that is OK.

**Comment by ankostis** [comment]
But the issue has not been solved - maybe rename this package?
