### ISSUE TITLE
Stop cancelling master builds.

### ISSUE THREAD

**Issue by isuruf** [conda-forge/staged-recipes#2383]
It seems somebody is cancelling the builds on master and keeping the latest job. Problem with this is that, master build is never run and feedstocks are not created at all. I've been waiting for a feedstock for one and a half days and it looks like I'll have to wait till the weekend if this keeps happening.

**Comment by isuruf** [comment]
Master build failed. Can somebody restart it? I tried, but it won't start.

**Comment by rolando** [comment]
I think this behavior is related to #2272

**Comment by rolando** [comment]
Not only it takes a long until until a master build is able to run, but also last three builds failed. It seems the same issue as #2311.

CC @conda-forge/core

**Comment by jakirkham** [comment]
Would add that it only needs to run some build on `master` to convert as there is logic to ensure any build on `master` starts with the latest listing of recipes from `staged-recipes`. So we could just as easily cancel all new builds and keep the oldest one.

**Comment by jakirkham** [comment]
> I think this behavior is related to #2272

Nope, it is people manually doing this. There is no such feature like this enabled (or even available to us) on staged-recipes.

**Comment by rolando** [comment]
@jakirkham oh, my bad, I thought it was a beta feature or something as there is no flag that says "cancelled by X".

**Comment by jakirkham** [comment]
Hmm...does Travis CI provide that information somewhere? I know AppVeyor and CircleCI do.

**Comment by rolando** [comment]
It seems the increasing number of PRs plus the master build cancellation delays a lot the creation of feedstocks. It would be nice to prioritize branches over PRs but that has been discarded by travis https://github.com/travis-ci/travis-ci/issues/1155

**Comment by jakirkham** [comment]
The one idea I had to improve this situation with Travis is to do the same thing that we already do for AppVeyor. Namely have outdated builds for a PR cancel themselves. It's still not optimal as we still have to wait for these outdated builds to start and terminate. Then again that has allowed AppVeyor to remain competitive amongst the CIs while Travis has floundered. So maybe that is enough.

To see how this would be done, please take a look at PR ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/52 ). Note this would do nothing to outdated builds on a branch of a feedstock or staged-recipes.

**Comment by jakirkham** [comment]
Seems all recipes have cleared. Maybe we what we should do is discuss adding some sort of policy and then add autocancellation behavior to staged-recipes that is acceptable (e.g. all new builds cancel themselves if there is an old one). That way people don't feel the need to intervene or if they do we have some guidelines about how to do so.

**Comment by scopatz** [comment]
+1 for autocancellation  @jakirkham
