### ISSUE TITLE
Python OSX CI build failing with spurious error

### ISSUE THREAD

**Issue by semuadmin** [conda-forge/staged-recipes#23923]
### Bug:

@conda-forge-admin, please ping conda-forge/staged-recipes

The OSX build step of the staged-recipe CI pipeline (`Azure Pipelines / staged-recipes (osx osx_64)`) is failing with a spurious 'KeyError' message:

```
...
  File "/Users/runner/mambaforge/lib/python3.10/site-packages/boa/core/solver.py", line 80, in to_action
    entry = lookup_dict[get_url_from_channel(c)]
KeyError: 'https://conda.anaconda.org/conda-forge'
##[error]Bash exited with code '1'.
Finishing: Run OSX build
```

The corresponding Windows and Linux pipelines appear to be working OK.

See, for example:

https://github.com/conda-forge/staged-recipes/pull/23918
https://github.com/conda-forge/staged-recipes/pull/23919
https://github.com/conda-forge/staged-recipes/pull/23901
... and others reported

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=775920&view=logs&jobId=1398114c-ad22-59c2-bca2-f3de21ac86a4&j=1398114c-ad22-59c2-bca2-f3de21ac86a4&t=e0781761-34ec-59c7-d16a-2dc06ee05298

**Comment by jaimergp** [comment]
Thanks for creating the issue. I merged a PR that should fix it. Can you update your branch from `main` and re-run? Thanks!

**Comment by semuadmin** [comment]
> Thanks for creating the issue. I merged [a PR](https://github.com/conda-forge/staged-recipes/pull/23926) that should fix it. Can you update your branch from `main` and re-run? Thanks!

on it

**Comment by semuadmin** [comment]
> > Thanks for creating the issue. I merged [a PR](https://github.com/conda-forge/staged-recipes/pull/23926) that should fix it. Can you update your branch from `main` and re-run? Thanks!
>

cooking on gas... 

<img width="927" alt="Screenshot 2023-09-08 at 12 03 04" src="https://github.com/conda-forge/staged-recipes/assets/28569967/47c9578c-8c1e-4176-8ed1-52237a624d02">

**Comment by semuadmin** [comment]
I'm personally happy for this issue to be closed now.

**Comment by ap--** [comment]
Fixed it for #23901 too! Thanks ❤️

**Comment by mikemhenry** [comment]
Also fixed it for https://github.com/conda-forge/staged-recipes/pull/23919 thanks!!! :rocket:

**Comment by jaimergp** [comment]
I'll leave this open during the weekend so people can find an issue in case they hit it too. What we've done is to start using conda-libmamba-solver and drop `boa` (`mambabuild`). When https://github.com/conda-forge/admin-requests/pull/811 is merged, the root-cause incompatibility will be addressed anyway.

The solution moving on is to update your fork branch from this repo's `main`.

**Comment by jaimergp** [comment]
Sounds like we can close this now 💪
