### ISSUE TITLE
Package request: feast 

### ISSUE THREAD

**Issue by Rommel-holmes** [conda-forge/staged-recipes#24047]
### Package name

Feast 

### Package version

0.33.1

### Package website

https://github.com/feast-dev/feast

### Package availability

Pypi
GitHub releases 

### Package is not available

- [X] The package is not available on conda-forge.

### No previous issues or open PRs

- [X] No previous issue exists and no PR has been opened.

**Comment by Rommel-holmes** [comment]
We do have 0.34.1 of feast on conda-forge, but not older version, including 0.33.1

**Comment by mfansler** [comment]
> We do have 0.34.1 of feast on conda-forge, but not older version, including 0.33.1

Anaconda Cloud [shows it is indeed available](https://anaconda.org/conda-forge/feast/files). Please post any further issues/requests regarding this package [to the feedstock directly](https://github.com/conda-forge/feast-feedstock/issues).
