### ISSUE TITLE
staged-recipes linux builds are failing

### ISSUE THREAD

**Issue by isuruf** [conda-forge/staged-recipes#24113]
### Bug:

Since the release of new conda version a couple of hours ago, linux builds are failing with
```
+ setup_conda_rc /home/conda/staged-recipes /home/conda/staged-recipes-copy/recipes /home/conda/staged-recipes-copy/.ci_support/linux64.yaml
Traceback (most recent call last):
  File "/opt/conda/bin/setup_conda_rc", line 7, in <module>
    from conda_forge_ci_setup.build_utils import setup_conda_rc
  File "/opt/conda/lib/python3.10/site-packages/conda_forge_ci_setup/build_utils.py", line 15, in <module>
    from conda_forge_ci_setup.upload_or_check_non_existence import retry_upload_or_check
  File "/opt/conda/lib/python3.10/site-packages/conda_forge_ci_setup/upload_or_check_non_existence.py", line 14, in <module>
    from conda_build.conda_interface import subdir as conda_subdir
  File "/opt/conda/lib/python3.10/site-packages/conda_build/conda_interface.py", line 84, in <module>
    from conda.base.context import (  # noqa: F401
ImportError: cannot import name 'get_prefix' from 'conda.base.context' (/opt/conda/lib/python3.10/site-packages/conda/base/context.py)
```

See for example https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=793801&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823

This is because the docker image has boa installed and boa requires an older conda-build and that version is incompatible with the newer conda.

**Comment by isuruf** [comment]
cc @conda-forge/staged-recipes, @conda-forge/core

**Comment by isuruf** [comment]
Don't think so. We need to either remove `boa` from docker images or have a new boa compatible with `conda-build>=3.25` and `mamba>=1.5.0`

**Comment by isuruf** [comment]
Nvm, yeah, adding a conda constraint on conda-build would fix it.

**Comment by h-vetinari** [comment]
Xref https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/563
