### ISSUE TITLE
Add lzo

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#2428]
Add a conda package for the `lzo` compression library.

ref: http://www.oberhumer.com/opensource/lzo/

**Comment by rolando** [comment]
Here is a WIP PR: #2432 

I opted to build latest release rather than 2.06 because it provides cmake files which ease the build a bit across multiple platforms.

**Comment by jakirkham** [comment]
As long as it is a release, that is fine. We can actually go back and add old versions as needed in the feedstock too. Thanks for doing this, @rolando.

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/conda-forge/staged-recipes/pull/2432 ).
