### ISSUE TITLE
Pre-release packages and packages with no tagged version

### ISSUE THREAD

**Issue by rolando** [conda-forge/staged-recipes#2431]
Are there guidelines about building pre-release or in-development packages?

That would be the case of libraries that had last release X years ago and latest development version contains many bug fixes and improvements but there is no release yet.

At the other hand, there are useful libraries that do not provide a proper versioning. For example: https://github.com/coderforlife/ms-compress

**Comment by jakirkham** [comment]
Not yet. We are discussing dev and rc releases it in this EP ( https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/3 ). Please feel free to join in.
