### ISSUE TITLE
Should we use a different AppVeyor account on staged-recipes

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/staged-recipes#244]
We don't upload anything in staged-recipes. Maybe we leave the conda-forge account for the feedstocks and use another one here? Does it makes sense?

**Comment by jakirkham** [comment]
Related ( https://github.com/conda-forge/conda-forge.github.io/issues/47 ).

**Comment by ocefpaf** [comment]
> Related ( conda-forge/conda-forge.github.io#47 ).

Indeed. But I see splitting staged-recipes as a low hanging fruit.

**Comment by jakirkham** [comment]
Totally agree. The later requires more infrastructure. This just requires that it happens.

**Comment by jakirkham** [comment]
@pelson, does this seem reasonable to you?

**Comment by pelson** [comment]
Yes, makes a lot of sense. We will still be backed up, but at least we reduce the problem by half. A longer term solution needs thinking about though - I'm currently uncertain whether AppVeyor is the tool for the job.

**Comment by pelson** [comment]
Neat idea which is still open to us. For now though, our upgraded AppVeyor subscription is serving us well so I'll go ahead and close this. Let's re-evaluate as necessary.
