### ISSUE TITLE
Add turbodbc

### ISSUE THREAD

**Issue by xhochy** [conda-forge/staged-recipes#2445]
Source: https://github.com/blue-yonder/turbodbc

I would volunteer to package it but have some open questions:

- It would depend on `unixodbc` which is not yet packaged in conda-forge but externally: Should I also add a package for it?
- It may also be helpful to provide two versions of `turbodbc`, one built with `iodbc` and one with `unixodbc`. This would be very roughly similiar to selecting a specific numpy version but I have no idea how this could be done or where I would have to search for documentation. Any pointers are welcome here. If this is not possible, I would default to only the `unixodbc` based version.

**Comment by wesm** [comment]
Yes, you should add a unixodbc package. 

For the iodbc package, it's tricky but you could implement this using conda "features" -- e.g. NumPy navigates this with the mkl, non-MKL, and openblas variants (e.g. https://github.com/conda-forge/numpy-feedstock/blob/master/recipe/meta.yaml#L19). This is more sparsely documented than you would like

**Comment by xhochy** [comment]
Unixodbc recipe: https://github.com/conda-forge/staged-recipes/pull/2453

**Comment by jakirkham** [comment]
More documentation can be found in this [Hackpad]( https://conda-forge.hackpad.com/BLAS-Numpy-Friends-86De62hoNdT ). Sorry it is not clearly visible. Bonus points to anyone that has time to add it to the docs in the webpage repo.

**Comment by napjon** [comment]
HI guys, could we update turbodbc in conda-forge?

**Comment by xhochy** [comment]
WIP at https://github.com/conda-forge/turbodbc-feedstock/pull/2 already

**Comment by napjon** [comment]
ah thanks! I didn't see it.

**Comment by jakirkham** [comment]
Also please raise this sort of issue at the feedstock in the future. Thanks.
