### ISSUE TITLE
Package request: MatchIt

### ISSUE THREAD

**Issue by kideokkwon** [conda-forge/staged-recipes#24567]
### Package name

MatchIt

### Package version

Newest

### Package website

https://github.com/kosukeimai/MatchIt

### Package availability

https://cran.r-project.org/web/packages/MatchIt/index.html

### Additional comments

it looks like this was available in the past (https://anaconda.org/conda-forge/r-matchit) but it looks like it was removed? When trying the following:
`conda install -c conda-forge r-matchit`
it says `PackagesNotFoundError` (in channels conda-forge and defaults)
This also causes issues with another package called `r-cbps`, which says it failed to install because it couldn't find `r-matchit`

### Package is not available

- [X] The package is not available on conda-forge.

### No previous issues or open PRs

- [X] No previous issue exists and no PR has been opened.

**Comment by mfansler** [comment]
This is available and current: https://github.com/conda-forge/r-matchit-feedstock. However, it is currently only built for **linux-64**, **oxs-64**, and **win-64** platforms. Are you on something else (e.g., **osx-arm64**)?

Please post any further issue on [the feedstock](https://github.com/conda-forge/r-matchit-feedstock/issues) directly.
