### ISSUE TITLE
[linux] Build with conda-provided gcc and libgcc

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/staged-recipes#2472]
This came up as I was packaging cling for conda:

 - Cling has a tight dependency constraints on the version of the C runtime. Building cling with the version and gcc provided in the CircleCI container generally results into the build not working at runtime because of a mismatch with the glibc provided at runtime.

   ```
   Warning in cling::IncrementalParser::CheckABICompatibility():
      Possible C++ standard library mismatch, compiled with __GLIBCXX__ '20140120' // The 
      Extraction of runtime standard library version was: '20160609'.
   ```

     Since we have not control over the c runtime available on the client machine, this sort of mismatch will happen all the time. Therefore, **we need to build and link with a conda-provided gcc and libgcc and make the latter a runtime dependency of our package**. It is the only way to guarantee that we won't have this sort of mismatch.

      Furthermore, this will naturally propagate for ABI compatibility across all conda-forge packages. I guess that once we have an OK conda package for gcc and libgcc, this will become a policy for binary packages. Another solution is to **not** have a separate package for libgcc...

- The default channel already provides a package for gcc 4.8. Besides it being old, it also happens to embed the files for libgcc of the same version, including the version-less symlinks, which don't point anymore towards the latest version when installing e.g. libgcc 5.2. I have opened an issue on this [here](https://github.com/ContinuumIO/anaconda-issues/issues/1465#issuecomment-280883923) with more details. A cleaner way to do this would be for gcc to depend on libgcc and libgcc to contain the symlink pointing to the latest version.

**Comment by SylvainCorlay** [comment]
It seems that the only way forward is for anaconda and conda-forge to

 - package a recent version of gcc (why not gcc-6 directly)
 - build all linux binary packages with that package.

I could build a functional cling package with the package for gcc-6 which is available on the `salford_systems` channel.

**Comment by SylvainCorlay** [comment]
cc @msarahan @jakirkham .

**Comment by Camsbury** [comment]
Hi @SylvainCorlay , I'm having this issue currently with the provided Ubuntu binary. Could you let me know how I can get around this issue on Ubuntu 16.04? Is there currently a fix? Do I need to remove anything? Could you point me to the path of the fix? Thanks!

**Comment by jakirkham** [comment]
Sounds like this will be solved once we rebuild with the new compilers. Going to close out to consolidate with existing discussions regarding the conda-forge rebuild.
