### ISSUE TITLE
Add emscripten

### ISSUE THREAD

**Issue by bjodah** [conda-forge/staged-recipes#2507]
This is a placeholder issue (package request) for [emscripten](https://github.com/kripken/emscripten)
A compiler for compiling e.g. C/C++ to javascript.

**Comment by jakirkham** [comment]
Is this something you would be willing to try, @bjodah? Expect most (if not all) of the dependencies are already here.

**Comment by bjodah** [comment]
@jakirkham In theory yes, but due to time constraints I won't be able to for the foreseeable future.

**Comment by jakirkham** [comment]
Opened issue ( https://github.com/conda/conda/issues/7619 ) about targeting WebAssembly as a platform. If you have any thoughts on this, would be good to share them there.

**Comment by jakirkham** [comment]
Appears building LLVM with WebAssembly support and using that with Emscripten is viable. Though it is a bit more experimental these days, it's likely to become the default in the future. So have added PR ( https://github.com/conda-forge/llvmdev-feedstock/pull/42 ) to start building `llvmdev` with WebAssembly support. Will need to rebuild `clangdev` with this option as well.

**Comment by jakirkham** [comment]
Have put up a very WIP PR ( https://github.com/conda-forge/staged-recipes/pull/6476 ).

**Comment by SylvainCorlay** [comment]
https://github.com/conda-forge/emscripten-feedstock
