### ISSUE TITLE
Add newspaper and newspaper3k

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/staged-recipes#2595]
[newspaper](https://newspaper.readthedocs.io/en/latest/user_guide/install.html) is a tool for parsing news data; [installation](https://newspaper.readthedocs.io/en/latest/user_guide/install.html#install) is a bit complicated. There is a self-described "depricated and buggy version" for [py2k](https://pypi.python.org/pypi/newspaper) and newer version for  [py3k](https://pypi.python.org/pypi/newspaper3k) (`newspaper3k`)

**Comment by mdraw** [comment]
newspaper(3k) is already packaged at https://github.com/conda-forge/newspaper3k-feedstock, so I think this can be closed.

**Comment by pmlandwehr** [comment]
Hooray!
