### ISSUE TITLE
Why python package execute failed at windows machine?

### ISSUE THREAD

**Issue by robinzyb** [conda-forge/staged-recipes#26030]
### General comment:

Dear all,
I recently pr a new package https://github.com/conda-forge/staged-recipes/pull/26029
but the test fails for windows.
When I look into the log file, I found the build is successful but the execution is failed with exit code 1. No other error message is shown.

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=914800&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=7c0f8eae-6d6f-51bf-636f-73a1a7fb1bc4&l=1977

**Comment by njzjz** [comment]
```
[noarch_python] Noarch package contains binary script: cp2kdata.exe
```

Need to set entry points: https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html#python-entry-points

**Comment by robinzyb** [comment]
Thanks! it works
