### ISSUE TITLE
Master is broken

### ISSUE THREAD

**Issue by 183amir** [conda-forge/staged-recipes#2615]
I don't know why whenever I merge a recipe here, master becomes broken. Is there something else that I should do besides clicking on merge? https://travis-ci.org/conda-forge/staged-recipes/builds/210962145

**Comment by 183amir** [comment]
ping @conda-forge/staged-recipes

**Comment by jakirkham** [comment]
Normally I just click restart on Travis CI's `master` build. There are a variety of transient networking or poorly behaved API issues (particularly with CI services for some reason). FWICT looking at the log before restarting it, this seems to have been some issue with Travis CI's API.

**Comment by jakirkham** [comment]
I believe this has already been resolved. Am closing it out. Though feel free to reopen if I'm mistaken.
