### ISSUE TITLE
please package haversine

### ISSUE THREAD

**Issue by janschulz** [conda-forge/staged-recipes#262]
haversine 0.4.5
Calculate the distance between 2 points on Earth.

Calculate the distance (in km or in miles) between two points on Earth, located by their latitude and longitude.

https://github.com/mapado/haversine
https://pypi.python.org/pypi/haversine

Fits nicely with basemap and cartopy :-)

**Comment by ocefpaf** [comment]
Will do. But take a look at `pygc`
