### ISSUE TITLE
CircleCI fails randomly to install docker image?

### ISSUE THREAD

**Issue by epruesse** [conda-forge/staged-recipes#2653]
Not sure what this is, but probably not related to my recipe... It worked on my other PR just after.

```
Pulling repository docker.io/condaforge/linux-anvil
Tag latest not found in repository docker.io/condaforge/linux-anvil

docker pull condaforge/linux-anvil returned exit code 1

Action failed: docker pull condaforge/linux-anvil
```

Possibly put `docker pull ... || (sleep 60; docker pull)` or `for n in 1 2 3; do docker pull ... && break; sleep 60; done` into the docker.yml to guard against annoying temporary failures of the service.

**Comment by jakirkham** [comment]
Yeah, I have seen things like this sometimes, but not often with CircleCI. Someone should follow-up with CircleCI if this is a frequent occurrence (my impression ATM is it is not). In the interim, restarting or doing a force push is probably our best bet.

**Comment by epruesse** [comment]
Is there a good place in the docs to inform recipe contributors on the preferred way to trigger a CI re-run? (I've been using `git ammend; git push -f` to do this)

**Comment by ericdill** [comment]
Adding another entry to the FAQ on the readme for staged recipes seems like as good a place as any. Could you submit a PR that adds that?

**Comment by epruesse** [comment]
@ericdill How about this: #2742

**Comment by ericdill** [comment]
Thanks for #2742 @epruesse . I think that addition addresses the low hanging fruit in this issue. Feel free to re-open if there's more that you'd like to discuss :)
