### ISSUE TITLE
Unable to install VMTK from conda forge

### ISSUE THREAD

**Issue by robertclercpredisurge** [conda-forge/staged-recipes#26564]
### Bug:

Hello,

I can't install VMTK 1.5.0 from conda-forge with this command lines :

conda install -c conda-forge vmtk==1.5.0
or
conda install conda-forge::vmtk
or
conda install vmtk

I've any time this error :

`
PackagesNotFoundError: The following packages are not available from current channels:

vmtk
Current channels:

https://conda.anaconda.org/conda-forge
defaults
To search for alternate channels that may provide the conda package you're
looking for, navigate to

https://anaconda.org
and use the search bar at the top of the page.`

**Comment by BastianZim** [comment]
Hi, please open the issue in the feedstock of the package here: https://github.com/conda-forge/vmtk-feedstock
