### ISSUE TITLE
Package request: zellij

### ISSUE THREAD

**Issue by gapplef** [conda-forge/staged-recipes#26640]
### Package name

zellij

### Package version

Newest

### Package website
https://zellij.dev/
https://github.com/zellij-org/zellij

### Package availability
https://github.com/zellij-org/zellij/releases

### Additional comments

Zellij is a new user-friendly terminal multiplexers built with rust.

There was a pull request https://github.com/conda-forge/staged-recipes/pull/16206 opened about 3 years. But it has been staled since then (and closed). Anyone can help to make some change?

### Package is not available

- [X] The package is not available on conda-forge.

### No previous issues or open PRs

- [X] No previous issue exists and no PR has been opened.

**Comment by danielnachun** [comment]
Resolved by https://github.com/conda-forge/staged-recipes/pull/27316.
