### ISSUE TITLE
Adding `.` in package name resulting in deployment issues

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#267]
This is happening with `bob.extension`. Looks like it is an issue with AppVeyor (again). See the [log]( https://travis-ci.org/conda-forge/staged-recipes/jobs/120625851#L270 ) for more details.

**Comment by jakirkham** [comment]
cc @ocefpaf

**Comment by jakirkham** [comment]
Removed from `master` with this PR ( https://github.com/conda-forge/staged-recipes/pull/268 ).

**Comment by jakirkham** [comment]
Prepped for resubmission in this PR ( https://github.com/conda-forge/staged-recipes/pull/269 ).

**Comment by ocefpaf** [comment]
Same as the underscore problem.

`bob.extension-feedstock` becomes `bob-extension-feedstock` in AppVeyor. Fixing this now.

**Comment by jakirkham** [comment]
Thanks, @ocefpaf. :smile:

**Comment by ocefpaf** [comment]
See https://github.com/conda-forge/conda-smithy/pull/116

**Comment by jakirkham** [comment]
Wow, that is the fastest resolution I have ever seen. Thanks guys.
