### ISSUE TITLE
Package request: less

### ISSUE THREAD

**Issue by corneliusroemer** [conda-forge/staged-recipes#27028]
### Package name

less

### Package version

Newest

### Package website

1. https://www.greenwoodsoftware.com/less/download.html
2. https://en.wikipedia.org/wiki/Less_(Unix)

### Package availability

https://www.greenwoodsoftware.com/less/download.html

### Package is not available

- [X] The package is not available on conda-forge.

### No previous issues or open PRs

- [X] No previous issue exists and no PR has been opened.

**Comment by mfansler** [comment]
Duplicate: https://github.com/conda-forge/staged-recipes/issues/22777

**Comment by corneliusroemer** [comment]
Oh sorry, that's embarrassing, that I opened that request 🤦
