### ISSUE TITLE
Package request: gojq

### ISSUE THREAD

**Issue by corneliusroemer** [conda-forge/staged-recipes#27099]
### Package name

gojq

### Package version

Newest

### Package website

https://github.com/itchyny/gojq

### Package availability

https://github.com/itchyny/gojq

### Additional comments

Existing third party availability: https://anaconda.org/dnachun/gojq

Not sure whether this is binary repackaging or a full built from source. Would you be interested in helping adding this package to conda-forge @danielnachun?

### Package is not available

- [X] The package is not available on conda-forge.

### No previous issues or open PRs

- [X] No previous issue exists and no PR has been opened.

**Comment by danielnachun** [comment]
The copy on my channel is built from source and I plan to contribute it along with some other JSON manipulation tools.  I'm just waiting for my other currently open PRs to be reviewed and then I will open one that adds `gojq`.  

I'll also mention here that I am planning to contribute basically all of the packages on my channel to conda-forge or bioconda if they aren't already on those channels - the main limiting factor is getting PRs reviewed.  If you see any other packages on my channel that you think should be added, please feel free to open a package request issue and tag me as you've done here so I know to prioritize submitting those packages!

**Comment by danielnachun** [comment]
Resolved by https://github.com/conda-forge/staged-recipes/pull/27313.
