### ISSUE TITLE
Add recipe for PuLP / pulp

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/staged-recipes#2716]
[`pulp`](https://github.com/coin-or/pulp) is an LP modeler written in python. PuLP can generate MPS or LP files and call GLPK, COIN CLP/CBC, CPLEX, and GUROBI to solve linear problems.

**Comment by jakirkham** [comment]
Solved in PR ( https://github.com/conda-forge/staged-recipes/pull/4203 ).
