### ISSUE TITLE
Handling duplicate package additions

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#272]
If someone tries to add a recipe for a feedstock that is already present, it would be nice if the differences could be placed in a PR against the existing feedstock. Ideally, the PR would ping the user who made the change and, if possible, make them the author of the PR so they could change it as needed.

**Comment by pelson** [comment]
Phew. I'm not sure whether it is worth the complexity. Simply being told that a package already exists and it should be proposed as a pull request there is good enough IMO.

**Comment by jakirkham** [comment]
Sure, it was just another idea that came up when I was thinking about. The linter fix should be sufficient I think to avoid these errors simply.

**Comment by jakirkham** [comment]
Closing due to complexity.
