### ISSUE TITLE
Forced spyder downgrade due to dependency issues?

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/staged-recipes#2720]
Just did a `conda update --all` and saw `spyder` drop from `3.1.3` to `2.1.9` due to dependency conflict with recent versions of `anaconda-navigator`,`jedi`,`pyqt`, `qt`, and `rope` - or so I'm guessing given that they went through downgrades when I updated spyder:

```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    spyder-3.1.3               |           py35_1         3.3 MB  conda-forge

The following packages will be UPDATED:

    spyder:             2.3.9-py35_1  conda-forge --> 3.1.3-py35_1  conda-forge

The following packages will be DOWNGRADED due to dependency conflicts:

    anaconda-navigator: 1.5.1-py35_0              --> 1.2.3-py35_0             
    jedi:               0.10.0-py35_0 conda-forge --> 0.9.0-py35_0  conda-forge
    pyqt:               5.6.0-py35_0  conda-forge --> 4.11.4-py35_2 conda-forge
    qt:                 5.6.2-0                   --> 4.8.7-4                  
    rope:               0.10.5-py35_0 conda-forge --> 0.9.4-py35_1             
```

Anything we can do to solve these conflicts?

**Comment by patricksnape** [comment]
All those are literally pinned in the [meta.yaml](https://github.com/conda-forge/spyder-feedstock/blob/master/recipe/meta.yaml#L26). This should be an issue on the feedstock directly - so can you reopen this on the spyder feedstock please?
