### ISSUE TITLE
conda-forge-linter sending wrong linting message

### ISSUE THREAD

**Issue by eunos-1128** [conda-forge/staged-recipes#27242]
### Bug:

Hi, @conda-forge-admin, please ping conda-forge/staged-recipes

conda-forge-linter sends wrong linting message below.

It says `recipes/example/recipe.yaml` is deleted though any edit has never done. 

Tests fail due to this buggy linting (e.g. #27235, https://github.com/conda-forge/staged-recipes/pull/27207).

![image](https://github.com/user-attachments/assets/3f3c8514-80ae-43ad-bcba-92e23d4ca5fd)

**Comment by eunos-1128** [comment]
Now I noticed that `recipes/example/meta.yaml` has renamed to `recipes/example/recipe.yaml`.

Tests don't fail if both of `recipes/example/meta.yaml` and `recipes/example/recipe.yaml` exist.

**Comment by isuruf** [comment]
cc @nichmor @wolfv

**Comment by eunos-1128** [comment]
It seems this linting comes from replacing conda-build with new builder(rattler-build).

![image](https://github.com/user-attachments/assets/1bafff9c-451a-47d9-b5e7-9e81189a653e)

It says they are working on it.

**Comment by isuruf** [comment]
It's a bug in the linter. You can ignore it for now
