### ISSUE TITLE
put recipe.yaml in another folder

### ISSUE THREAD

**Issue by beckermr** [conda-forge/staged-recipes#27264]
@isuruf would like the recipe.yaml and meta.yaml to be in different folders. We should make a pr or revert the old one to move the new recipes to another folder, maybe example-v1 or similar as before. Sorry for the back and forth here. 

Cc @nichmor

**Comment by jaimergp** [comment]
This needs https://github.com/conda-forge/conda-smithy/pull/2036, right?

**Comment by jaimergp** [comment]
See https://github.com/conda-forge/staged-recipes/pull/27271
