### ISSUE TITLE
two dependent packages is not supported on the same platform when run the pipline test again

### ISSUE THREAD

**Issue by robinzyb** [conda-forge/staged-recipes#27438]
### General comment:

@conda-forge/staged-recipes
Dear all,
        I am maintaining a conda-forge package writting by myself. The feedstock is  https://github.com/conda-forge/cp2kdata-feedstock .
When I update my package in version 0.6.9 and 0.7.0, the pipline test works well. 
However, the pipline test fails when updating to version 0.7.1.
The [log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1013426&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3&l=1032) shows the two packages, pycp2k and transitions, are not support on this platform, thus the conda package test failed.

```shell
export SRC_DIR=/home/conda/feedstock_root/build_artifacts/cp2kdata_1724926355067/test_tmp
import: 'cp2kdata'
import: 'cp2kdata'
+ pip check
pycp2k 0.2.2 is not supported on this platform
transitions 0.7.2 is not supported on this platform
WARNING: Tests failed for cp2kdata-0.7.1-pyhd8ed1ab_0.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3523, in test
    utils.check_call_env(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 404, in check_call_env
    return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/conda/feedstock_root/build_artifacts/cp2kdata_1724926355067/test_tmp/conda_test_runner.sh']' returned non-zero exit status 1.
```
But I never update the two packages and two pipeline tests use same packages as you can check my successful test [log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=962436&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3) for my version cp2kdata 0.7.0.

I am really confused why the two dependent packages are not supported on the same platform when I run the same pipline test? The two dependent packages have same versions and the platforms for the pipeline test are same. 

Many thanks if anyone could answer my question

**Comment by synapticarbors** [comment]
I believe this is due to the release of pip 24.2:
https://ichard26.github.io/blog/2024/08/whats-new-in-pip-24.2/#pip-check-just-got-a-bit-stricter

**Comment by robinzyb** [comment]
Perfect! that solved my problem. Have a great day!
