### ISSUE TITLE
`cuda_compiler_version` missing is blocking staged-recipes

### ISSUE THREAD

**Issue by beckermr** [conda-forge/staged-recipes#27551]
We are still seeing this even after the fix from @isuruf.

see this job: https://github.com/conda-forge/admin-requests/actions/runs/10816964320/job/30009292478

cc @carterbox

**Comment by isuruf** [comment]
This looks like a conda-build bug

**Comment by carterbox** [comment]
I've added a lot of selectors to avoid trying to use cuda_compiler_version in those recipes. I'm going to remove them from staging so that other recipes can be processed, and I will open a new PR for them.

**Comment by carterbox** [comment]
xref: https://github.com/conda-forge/staged-recipes/pull/26580

**Comment by carterbox** [comment]
> This looks like a conda-build bug

Might be this bug: https://github.com/conda/conda-build/pull/5458. The fix is unreleased.

**Comment by carterbox** [comment]
Could try the following approach:

> Define a fallback for version: Adding this to line 2 {% set version = version|default("") %}

**Comment by carterbox** [comment]
It works to add near the top of the recipe.

```yaml
{% set cuda_compiler_version = cuda_compiler_version|default("None") %}
```

**Comment by jakirkham** [comment]
> > This looks like a conda-build bug
> 
> Might be this bug: [conda/conda-build#5458](https://github.com/conda/conda-build/pull/5458). The fix is unreleased.

This is now in conda-build 24.9.0

In the few cases I've tested this, it appears to be fixing past issues. Though please let me know what you find from testing

**Comment by jakirkham** [comment]
Is there anything still left to do here? Or should we close?
