### ISSUE TITLE
Failure deploying rendered feedstocks

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#2778]
Based on this [error]( https://travis-ci.org/conda-forge/staged-recipes/builds/218697277#L572-L600 ) and a few others like it, it looks like we have another problem beyond Travis CI's API being really flaky. Namely [pushing]( https://github.com/conda-forge/staged-recipes/blob/86f8ae061f989130031950e9df86f4f1e3e513a5/.CI/create_feedstocks.py#L206-L208 ) to feedstocks is failing.

The only reason considered for a push to fail before was if the push would be a non-fast-foward push. IOW the feedstock was already created due to a race case at staged-recipes. The solution up to this point was to [fetch]( https://github.com/conda-forge/staged-recipes/blob/86f8ae061f989130031950e9df86f4f1e3e513a5/.CI/create_feedstocks.py#L214-L215 ) the content from the current feedstock and [rebase]( https://github.com/conda-forge/staged-recipes/blob/86f8ae061f989130031950e9df86f4f1e3e513a5/.CI/create_feedstocks.py#L216-L221 ) our changes on top of it (with some error handling for conflicts).

While the error message seems to indicate that fetching upstream has failed, that is misleading. In reality that means that we failed to push the changes in the first place. The fact that it fails fetch upstream too only further confirms that nothing was ever pushed to the feedstock in the first place.

Tried some small tweaks ( https://github.com/conda-forge/staged-recipes/pull/2775 ) ( https://github.com/conda-forge/staged-recipes/pull/2777 ) to try and fix a `git push` issue if the branch and upstream branch were not identified clearly enough, but that does not seem to fix the problem.

Have written up this issue to both let people know about this problem and hopefully help fix what I have thus far been unable to.

cc @conda-forge/core @conda-forge/staged-recipes

**Comment by jakirkham** [comment]
NVM fixed by PR ( https://github.com/conda-forge/staged-recipes/pull/2779 ).

**Comment by ericdill** [comment]
@jakirkham Nice work debugging this. Thanks for getting the feedstock pipeline flowing again! 🎉

**Comment by jakirkham** [comment]
Glad I could help. We still have a lot of failures with Travis CI's API, which I have followed up with them about, but this seems to make the difference between getting a couple recipes converted at a time vs. none.

**Comment by jakirkham** [comment]
This situation should be much better now that we auto retrigger failed conversions. ( https://github.com/conda-forge/staged-recipes/pull/4188 )
