### ISSUE TITLE
Package request: cuSolverMp (add Conda packages)

### ISSUE THREAD

**Issue by billysuh7** [conda-forge/staged-recipes#27809]
### Package name

cusolvermp-feedstock

### Package version

Newest

### Package website

GitHub Repository

### Package availability

GitHub releases

### Additional comments

This package will need to depend on cublasmp-feedstock

Latest version as of now is 0.5.1: https://developer.download.nvidia.com/compute/cusolvermp/redist/

### Package is not available

- [x] The package is not available on conda-forge.

### No previous issues or open PRs

- [x] No previous issue exists and no PR has been opened.

**Comment by ondrejkoboltvan** [comment]
![20241002_145650 (2).jpg](https://github.com/user-attachments/assets/db800ae3-b4a0-4524-bfc9-305a5d1a1b3e)

**Comment by billysuh7** [comment]
Done.
