### ISSUE TITLE
recipe for scilogger - feedstock not created after merge

### ISSUE THREAD

**Issue by otvam** [conda-forge/staged-recipes#27906]
### Bug:

The PR for scilogger (PR #27888) has been merged 24h ago but the feedstock repo was not created.
@conda-forge/staged-recipes 

Best, Thomas

**Comment by ocefpaf** [comment]
Quite odd. Not sure what happened. Pinging @conda-forge/core

**Comment by beckermr** [comment]
The commit you made for scisave appears to have deleted the scilogger recipe: https://github.com/conda-forge/staged-recipes/commit/d7a72bd09a6255254e3a1822aeda430272140d6c

**Comment by beckermr** [comment]
Resubmit the PR and it should work fine.

**Comment by otvam** [comment]
Sorry for the mess!

#27916 is the new PR
