### ISSUE TITLE
Add pandas-datareader

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#2796]
Would be nice to have a package for [`pandas-datareader`]( https://pypi.python.org/pypi/pandas-datareader/ ).

**Comment by jakirkham** [comment]
cc @mrocklin

**Comment by mariusvniekerk** [comment]
@jakirkham we can close this now.

**Comment by jakirkham** [comment]
Indeed. Appears to have been resolved by PR ( https://github.com/conda-forge/staged-recipes/pull/2834 ), which added `pandas-datareader`.
