### ISSUE TITLE
Request for Assistance with dataclass-wizard Issue

### ISSUE THREAD

**Issue by rnag** [conda-forge/staged-recipes#28250]
### General comment:

Dear Admin,

I am unsure if the link below is relevant here, but any suggestions would be greatly appreciated:

https://github.com/conda-forge/dataclass-wizard-feedstock/issues/16

Best regards,
Ritvik

**Comment by mfansler** [comment]
Further discussion for this should go in https://github.com/conda-forge/dataclass-wizard-feedstock/pull/15
