### ISSUE TITLE
Add recipe for nolearn

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/staged-recipes#2827]
[`nolearn`](https://pythonhosted.org/nolearn/) "contains a number of utility modules that are helpful with machine learning tasks. Most of the modules work together with scikit-learn, others are more generally useful."

**Comment by jakirkham** [comment]
There was PR ( https://github.com/conda-forge/staged-recipes/pull/2880 ), but it appears to be closed now. 😞

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/conda-forge/staged-recipes/pull/16860 )
