### ISSUE TITLE
`pixi run lint` fails with missing arguments

### ISSUE THREAD

**Issue by matthewfeickert** [conda-forge/staged-recipes#28321]
### Bug:

In PR https://github.com/conda-forge/staged-recipes/pull/28264/ @bollwyvl added the `lint` `pixi` task

https://github.com/conda-forge/staged-recipes/blob/03d772a99ade0f11e2be9951354249f7e756a058/pixi.toml#L74-L78

which is great. However, the [`.github/workflows/scripts/linter.py`](https://github.com/conda-forge/staged-recipes/blob/03d772a99ade0f11e2be9951354249f7e756a058/.github/workflows/scripts/linter.py) is missing defaults as running the `lint` task as shown in the README

https://github.com/conda-forge/staged-recipes/blob/03d772a99ade0f11e2be9951354249f7e756a058/README.md?plain=1#L83

fails with

```console
$ pixi run lint
✨ Pixi task (lint in conda-smithy): python .github/workflows/scripts/linter.py
    && conda-smithy recipe-lint --conda-forge recipes/*
: (validate all recipes with `conda-smithy`)
usage: linter.py [-h] --owner OWNER --pr-num PR_NUM
linter.py: error: the following arguments are required: --owner, --pr-num
```

and the command does not allow for argument passthrough to the [`.github/workflows/scripts/linter.py`](https://github.com/conda-forge/staged-recipes/blob/03d772a99ade0f11e2be9951354249f7e756a058/.github/workflows/scripts/linter.py).

The current workaround I've been using is simply manually running `conda-smithy recipe-lint` with

```
pixi run --environment conda-smithy conda-smithy recipe-lint --conda-forge recipes/*
```

Example (for PR https://github.com/conda-forge/staged-recipes/pull/28292):

```console
$ pixi run --environment conda-smithy conda-smithy recipe-lint --conda-forge recipes/looptools
recipes/looptools is in fine form
```

It would be nice if this could get fixed though.

**Comment by bollwyvl** [comment]
On it... sorry for the noise. I had something _partially_ working that used the rest of the rules from `linter.py`.

**Comment by bollwyvl** [comment]
[#28322](https://github.com/conda-forge/staged-recipes/pull/28322) is up

**Comment by matthewfeickert** [comment]
Thanks so much, @bollwyvl! You're super fast here and also enabling great things, so thanks for all the work!
