### ISSUE TITLE
Package Maintainer - Track Package Updates

### ISSUE THREAD

**Issue by curtisalexander** [conda-forge/staged-recipes#2875]
Are there some best practices that are recommended for package maintainers?  Specifically, I'm wondering how other maintainers stay on top of updates to packages to ensure they are updating their feedstocks accordingly.

The first (and most naive) solution to come to mind is to periodically scrape pypi's [simple site](https://pypi.python.org/simple/) looking for updates.  But I suspect there is a much better way that I'm not immediately aware of.

**Comment by jakirkham** [comment]
There is a tool called [`feedstockrot`]( https://github.com/axiom-data-science/feedstockrot ) that can help check specific packages against those in conda-forge and point out the outdated ones.

We are also working on a [script]( https://github.com/conda-forge/conda-forge.github.io/pull/375 ) that can help add update PRs. Currently we need to figure out how to handle dependency changes though.

**Comment by curtisalexander** [comment]
`feedstockrot` should be helpful as I will probably only check periodically.  `tick_my_feedstocks.py` definitely looks interesting.

**Comment by jakirkham** [comment]
It sounds like your question is answered. So will close this.

That's not to say that there isn't more work to do in this area (as there definitely is 😄). Instead we should focus on more specific issues or features we would like to see these tools have at their respective homes. Hopefully we can combine them to ultimately solve this issue.

ref: https://github.com/axiom-data-science/feedstockrot
ref: https://github.com/pmlandwehr/tick-my-feedstocks
