### ISSUE TITLE
conda-forge-manager did not update supervisor-feedstock

### ISSUE THREAD

**Issue by sodre** [conda-forge/staged-recipes#2904]
@conda-forge/core 

I was added as a maintainer for supervisor-feedstock about 7 days ago. conda-forge-manager has not yet added me to the team list. Can someone take a look at it?

**Comment by jakirkham** [comment]
That script has been getting rate limited for the past few months. The reason being it tries to check all feedstock teams to see if additions are required. In its current form, it is totally broken and needs to be scrapped.

The best fix I can think of is to handle team updates through a web service that responds to changes in feedstock content. This would allow it to work well below the GitHub rate limit. More details in issue ( https://github.com/conda-forge/conda-forge-webservices/issues/63 ).

Unfortunately I haven't gotten enough buy-in or time to replace it. Though I did add some functionality to `conda-smithy` to add people to teams, which should be helpful in that pursuit. Perhaps making progress requires more interested users like yourself clamoring for it to draw attention to the issue.

**Comment by sodre** [comment]
@jakirkham I took a quick look at the issue you mentioned. I will try to carve sometime to work on fixing some of the pending issues. 

In the meantime, is it possible to force add me to the supervisor-feedstock team ?

**Comment by jakirkham** [comment]
I have manually added you, @sodre.
