### ISSUE TITLE
GH_TOKEN errors

### ISSUE THREAD

**Issue by isuruf** [conda-forge/staged-recipes#2953]
I think the token was revoked by Github because of https://blog.travis-ci.com/2017-05-08-security-advisory
We need to generate a new token and encrypt for this repo.

**Comment by isuruf** [comment]
Here's a failing travis build, https://travis-ci.org/conda-forge/staged-recipes/builds/230253575

**Comment by jakirkham** [comment]
Could you please take a look at this @pelson?

**Comment by jakirkham** [comment]
Sounds like Phil is out at sea. From our discussion, it seems like a reasonable workaround would be to reuse the bot at the webpage repo. So have added PR ( https://github.com/conda-forge/staged-recipes/pull/2957 ) as a workaround for now. This was with a new token and I think I set all the permissions right, but if not I can go back and tweak them.
