### ISSUE TITLE
Replace GitHub token with one from @conda-forge-manager

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#2960]
Currently we are using a token from @conda-forge-coordinator for staged-recipes. We had to do this as the @conda-forge-manager token that we were using at staged-recipes got pulled and we were unable to generate a new token for that bot at the time.[1] So we generated a new token for @conda-forge-coordinator and added it here.[2]

This means periodically we are going to run into rate limiting issues here when the team update and feedstock update script runs like we use to before separating them. Given this, we need to generate a new token for @conda-forge-manager and update it here as soon as we can to fix those issues. This issue serves as a reminder to do this.

cc @conda-forge/core @conda-forge/staged-recipes @pelson

\[1\]: https://github.com/conda-forge/staged-recipes/issues/2953
\[2\]: https://github.com/conda-forge/staged-recipes/pull/2959

**Comment by isuruf** [comment]
Replacing `conda-forge-coordinator`'s token is problematic, because there are already repos created with it and hence associated with the appveyor account. Solution would be to use another bot for the regular tasks of `conda-forge-coordinator`

**Comment by jakirkham** [comment]
We didn't change the [AppVeyor token]( https://github.com/conda-forge/staged-recipes/blob/422e5cf67840fa59fdbbe0922b47fe055117e37a/.travis.yml#L21-L22 ) though. So maybe we are ok on that front. Though I haven't spent much time mucking with the AppVeyor setup and could be not understanding how it works.

**Comment by pelson** [comment]
Just shout if a new token is needed from @conda-forge-manager. We need to think a little about how we share the account details (particularly as all accounts should have 2-factor enabled, and we need to be able to share that also).

**Comment by msarahan** [comment]
Can you have more than one yubikey for a given GitHub account? This may be
a good two factor solution, though setup may be a bit tricky.

**Comment by isuruf** [comment]
> Just shout if a new token is needed from @conda-forge-manager

Can you replace the GH_TOKEN of this repo with one from @conda-forge-manager ?
Also it'll be useful to have a token from @conda-forge-admin set as GH_TOKEN2 to see the rate limits.
