### ISSUE TITLE
Sphinx-contrib packages

### ISSUE THREAD

**Issue by frol** [conda-forge/staged-recipes#302]
I'm wondering what the best way of packaging [Sphinx-contrib extension](https://bitbucket.org/birkenfeld/sphinx-contrib/) would be. I'm actually using only `sphinxcontrib-mockautodoc`, and I have its recipe in our company's recipes repo.

**Comment by ocefpaf** [comment]
@frol I never used `Sphinx-contrib` before so I am not aware what are the challenges we might face. You can submit the recipe you have and we'll iterate from there.

**Comment by frol** [comment]
@ocefpaf OK, I will push the recipe and we will see how it will go.

**Comment by ocefpaf** [comment]
Thanks. Let's close this and move the discuss to the PR.

**Comment by jakirkham** [comment]
Did this already happen somewhere?

My inclination would be to package them separately.

**Comment by frol** [comment]
@jakirham I haven't done it yet. This will need to wait until the next weekend.
