### ISSUE TITLE
Supported/Recommended Python versions to build against?

### ISSUE THREAD

**Issue by Lnaden** [conda-forge/staged-recipes#3020]
What is the conda-forge team's default supported Python versions that packages are built against, and is this documented anywhere?

As the Omnia MD team starts our conda-forge migration, we would like to know what the default Python versions other packages are built against. We have tried to support 2.7, and the most recent two versions of 3.X. With the release of Python 3.6 earlier this year, we have continued supporting Python 3.4 while packages become 3.6 capable, but would like to now drop 3.4 support. We were wondering if conda-forge's defaults had dropped Python 3.4 yet, if not, we will continue supporting it for the time being to be consistent during the migration.

I know `conda` 4.3 will be the last official supported release for Python 3.4 on the Anaconda channel, but I did no know if conda-forge followed the same model or a different one.

Thanks in advance and apologies if this is not the correct repo to raise this issue!

xref: omnia-md/conda-recipes#777

**Comment by isuruf** [comment]
> We have tried to support 2.7, and the most recent two versions of 3.X

That's what conda-forge is also doing. 3.4 was dropped a while back. https://github.com/conda-forge/conda-smithy/pull/421
I don't whether it is documented, but conda-forge supports only 2.7, 3.5 and 3.6 now.

**Comment by Lnaden** [comment]
Thanks! It may be helpful to document this somewhere, but thats the answer I was looking for.
