### ISSUE TITLE
Packages in bioconda

### ISSUE THREAD

**Issue by sebastian-luna-valero** [conda-forge/staged-recipes#3144]
Hello,

I am trying to add [libvips](https://github.com/jcupitt/libvips/issues/673) to conda-forge.

Is it possible to depend on [bioconda](http://bioconda.github.io/) packages for that?

Best regards,
Sebastian

**Comment by synapticarbors** [comment]
Typically to build a package on conda-forge, we only pull from the `conda-forge` and `defaults` channels.

**Comment by jakirkham** [comment]
Yeah, I would agree with @synapticarbors and also add that `bioconda` already depends on `conda-forge`. So this would put both orgs in a weird place if we depend on `bioconda` too. My recommendation would be migrate the dependencies to `conda-forge` if that makes sense. Alternatively add `libvips` to `bioconda`.

**Comment by jakirkham** [comment]
cc @bgruening @johanneskoester

**Comment by johanneskoester** [comment]
Yes, we have decided to put libvips into bioconda.

**Comment by jakirkham** [comment]
Cool, thanks for the follow up. Going to close this then.

**Comment by sebastian-luna-valero** [comment]
Thanks All.
