### ISSUE TITLE
Missing ttf-dejavu/fontconfig dependencies for open-jdk/fastqc

### ISSUE THREAD

**Issue by jrderuiter** [conda-forge/staged-recipes#3164]
If fontconfig or ttf-dejavu are not installed, fastqc (a tool in bioconda) can produce the following error:

java.lang.Error: Probable fatal error:No fonts found
which is identical to the error described here: https://stackoverflow.com/questions/14066525/java-lang-error-probable-fatal-errorno-fonts-found. This issue is at least encountered in the snakemake container used by snakemake-wrappers.

I think this error is not necessarily specific to fastqc, but likely a more general dependency of openjdk which is currently missing.

We can easily fix it for fontconfig by adding the dependency to the fastqc or openjdk recipes. However, for ttf-dejavu there does not seem to be an existing package as far as I can see. I have no experience with creating non-R/Python packages, so was wondering if someone would be prepared to build a ttf-dejavu package or otherwise provide me with pointers on how to do so.

**Comment by rvalieris** [comment]
are sure you are using conda-forge::openjdk ?

dejavu fonts are already included with openjdk: https://github.com/conda-forge/openjdk-feedstock/blob/master/recipe/build.sh#L24

**Comment by jakirkham** [comment]
Please raise this issue on the relevant feedstocks. Thanks.

**Comment by charlesreid1** [comment]
follow-up issue, for those wondering: https://github.com/bioconda/bioconda-recipes/issues/5026
