### ISSUE TITLE
Add PyCUDA

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#3178]
Would be great to have a package for [PyCUDA]( https://pypi.python.org/pypi/pycuda ).

**Comment by jakirkham** [comment]
Raised a similar request with `default` ( https://github.com/ContinuumIO/anaconda-recipes/issues/111 ) in the event it is not possible to build this at `conda-forge`.

**Comment by isuruf** [comment]
See https://github.com/conda-forge/staged-recipes/pull/1775/files

**Comment by jakirkham** [comment]
Probably also linking this in with the larger discussion about GPU support on issue ( https://github.com/conda-forge/conda-forge.github.io/issues/63 ).
