### ISSUE TITLE
Add PyAudio

### ISSUE THREAD

**Issue by chiranthsiddappa** [conda-forge/staged-recipes#3278]
Would like [PyAudio](https://pypi.python.org/pypi/PyAudio) to support [scikit-dsp-comm](https://github.com/mwickert/scikit-dsp-comm).

**Comment by bollwyvl** [comment]
This would be blocked by #3094...

**Comment by jakirkham** [comment]
Solved in PR ( https://github.com/conda-forge/staged-recipes/pull/3547 ) a while back.

**Comment by jakirkham** [comment]
More for history than anything else. PR ( https://github.com/conda-forge/staged-recipes/pull/3273 ) added `scikit-dsp-comm`.
