### ISSUE TITLE
package a latex distribution 

### ISSUE THREAD

**Issue by janschulz** [conda-forge/staged-recipes#359]
The usecase would be that one could install pandoc (already packaged) and latex to get pdf output form nbconvert. For that to work it would be nessesary if the tex distribution would install the binaries into `<env>\Scripts` on windows.

Unfortunately, this seems to be a lot harder than I thought (only tried windows):

**repackage [miktex portable](http://miktex.org/portable)**

miktex directory structure means that the bin dir has to be separate from the script dir in the conda env (bin is in `.\miktex\bin` and it expects the rest of the stuff in `.`, so we end up with a directory structure below the conda env main dir :-/). But this means that we have to add `.\miktex\bin` to the path, which is feasible using `activate.d` scripts, but this again means that one would have to activate such an environment before starting the notebook server (or any other commandline program), which is IMO not gonna work (e.g. who activates the main environment? And my notebook server is installed in an env, but is started by just specifying the complete path to jupyter.exe in that env).

Miktex has the disadvantage that it is only available on windows, but the advantage, that the install size is little because it installs (can install) missing packages automatically.

**texlive**

The portable binary installer installs itself into `./bin/win32`, so that's also not gonna work :-( It seems it is possible to install texlive from source in the required form (setting bindir in the configure step), but just reading the documentation made me too scared to try (and it uses svn, which I don't have installed...). And actually supporting a latex distributions is a bigger job than I want to try...

texlife is available in mac/linux/windows, but installing missing packages is a manual step (or the package gets really big...)...

So, what are the options?

* Use a repackaged miktex portable, use a `activate.d` script and warn user, that they have to use activate (I've actually no clue how that work out in the root environment), if they want to have access to the latex binaries in e.g. `nbconvert`. Maybe get nbconvert, mpl and friends to add the dir if it exist (either upstream or in a patch).
* Try to compile texlive on all platforms, putting the bindir in the dir which is anyway included in the path
* I've no clue if it would be possible to edit the binaries of texlive to remove the `\win32` part?

Any (other) ideas?

**Comment by jakirkham** [comment]
I have to be honest when I read this I was actually terrified. :fearful:

My understanding is LaTeX (e.g. TeX Live) has its own packaging system too, which we would need to integrate with `conda` and `conda-build` somehow. In other words, to make this really usable we would end up needing feedstocks for all the TeX packages so they could be `conda` installable. That feels like a lot of maintenance work. Maybe if we can find a decent way to automate that infrastructure (as we have been discussing about PyPI) then this might not be so bad. Though if we embark on this, TeX Live really feels like where we would want to start looking as it is cross platform.

**Comment by janschulz** [comment]
I actually hoped that this could be separated: both texlive and miktex can be installed on a server and user packages go somewhere under `~`. Unfortunately, the installer assumes that it needs admin rights to install that way (at least for miktex) and the resulting stuff is not installed as "portable"... Anyway, I could even live with having a polluted env from installed tex packages, if `conda install nbconvert` would give my pdf output...

**Comment by jakirkham** [comment]
Just to be clear, I do understand there is a completely valid use case for this. My current thinking is that we just need way more automation to address this properly.

**Comment by ivoflipse** [comment]
We actually have a recipe for Miktex-portable on Windows: https://github.com/ClinicalGraphics/conda-recipes/tree/master/miktex-portable

It's not necessarily pretty, but it has worked out really well for us so far.

**Comment by janschulz** [comment]
@ivoflipse Wow, I didn't think of simple creating batch files for each binary... 

IMO this a great thing to include here (We already use a repackaged pandoc)... Not sure what to do with linux and mac users...

**Comment by jakirkham** [comment]
Here is a [recipe]( https://github.com/pkgw/conda-recipes/tree/a03809015b67b174dc978eb4d0e978a2c0e3b8da/recipes/texlive-core ) for packaging a basic version of TexLive.

**Comment by ocefpaf** [comment]
> Here is a [recipe]( https://github.com/pkgw/conda-recipes/tree/a03809015b67b174dc978eb4d0e978a2c0e3b8da/recipes/texlive-core ) for packaging a basic version of TexLive.

If no one tries that I will give it a go later today. I want to package GMT and that requires Latex too.

**Comment by janschulz** [comment]
@ocefpaf try on windows?

**Comment by ocefpaf** [comment]
> @ocefpaf try on windows?

*nix. I see you have Windows covered :wink:

**Comment by jakirkham** [comment]
Cool. Thanks for trying, @ocefpaf.

**Comment by jakirkham** [comment]
> @ocefpaf try on windows?

If you would like to try TexLive on Windows, @janschulz, please be our guest.

**Comment by CJ-Wright** [comment]
Any interest in looking at this again? I think we have more automation on some fronts.
