### ISSUE TITLE
Add PySide2

### ISSUE THREAD

**Issue by rth** [conda-forge/staged-recipes#3763]
It would be nice if it was possible to make a conda-forge build for PySide2.  

[PySide2 project](https://wiki.qt.io/PySide2) hasn't made a stable release yet, but at the same time other Python packages (QtPy, matplotlib, ipython) are already supporting it,  as far as I understand.

The process of making Python wheels for Pyside2 can be found in  https://github.com/fredrikaverpil/pyside2-wheels (also related https://bugreports.qt.io/browse/PYSIDE-558) and I wonder if some of this work could be adapted for conda-forge.... cc @fredrikaverpil

**Comment by jschueller** [comment]
we dont use wheels at conda forge, only raw cmake. I guess the only problem is the availability of llvm on all our platforms.

**Comment by rth** [comment]
@jschueller Thanks for the feedback!

> we dont use wheels at conda forge, only raw cmake.

 I know, I meant there were a number of setup scripts for building PySide2  in the above linked repo (with Docker, appveyor.sh specifying environment where it worked on different platforms, parameters that were provided to `setup.py` etc) and just wanted to point out that some of that information might be useful for the person who would work on this.

**Comment by jschueller** [comment]
lets see if I can get somewhere with https://github.com/conda-forge/staged-recipes/pull/3765

**Comment by fredrikaverpil** [comment]
@jschueller wow, this looks fantastic. I'll add some comments in the PR.

**Comment by isuruf** [comment]
Fixed in #3765

**Comment by rth** [comment]
Great, thanks @jschueller and everyone else involved for making this happen!

**Comment by fredrikaverpil** [comment]
I second what @rth said. 🎉 I'm refreshing the [pyside2-feedstock AppVeyor build](https://ci.appveyor.com/project/conda-forge/pyside2-feedstock/branch/master), waiting for them to run/complete.
