### ISSUE TITLE
Travis build cancelled on pull request: jenkspy

### ISSUE THREAD

**Issue by nickp60** [conda-forge/staged-recipes#3787]
Hi, I am trying to submit a recipe;  could someone tell me why my jobs on travis are getting canceled?  Sorry for the very basic question.

Here is my PR:
https://github.com/conda-forge/staged-recipes/pull/3771

**Comment by jakirkham** [comment]
Seems like it ran on the latest commit. 😕 We do cancel builds on outdated commits though.

**Comment by nickp60** [comment]
Ok, thanks!
