### ISSUE TITLE
Add R's dplyr (version >= 0.7)

### ISSUE THREAD

**Issue by vsbuffalo** [conda-forge/staged-recipes#3867]
Currently `defaults` is the only channel with R's dplyr package at version 0.7 — conda-forge has version 0.5 only. Using the `defaults` package version leads to issues like [this](https://github.com/conda-forge/conda-forge.github.io/issues/234). The upgrade from 0.5 to 0.7 is important, as it critically changes the behavior of `collect()`.

**Comment by bgruening** [comment]
I think this can be closed.

**Comment by jdblischak** [comment]
> I think this can be closed.

@bgruening Agreed. dplyr 0.7.0 is now available on Anaconda Cloud.

https://anaconda.org/conda-forge/r-dplyr/files?version=0.7.0

@vsbuffalo Could you please confirm and then close the Issue if it has been resolved?

**Comment by jakirkham** [comment]
Going to close this out as it is available. In the future, this sort of issue should be raised on the [`r-dplyr` feedstock]( https://github.com/conda-forge/r-dplyr-feedstock ). If there are other issues, they can be raised at the feedstock as well. Thanks.
