### ISSUE TITLE
Can IRIS do the negation reasoning such as...

### ISSUE THREAD

**Issue by liteng0124** [conda-forge/staged-recipes#387]
IRIS is a reasoning tool (http://iris-reasoner.org/demo) 
I can run a simple demo, for example:
q('a').
p(?X) :- q(?X).
?-p(?X).

I can get the p('a')  as a result.
but if I know p(?X) :- q(?X). Then I want to get the ¬q(?X) :- ¬p(?X). How can I realize this?

**Comment by pelson** [comment]
Hi @liteng0124 - wrong repo I'm afraid. I'm not even sure where to point you. Maybe StackOverflow? Good luck with your question!
