### ISSUE TITLE
packaging git-annex

### ISSUE THREAD

**Issue by notestaff** [conda-forge/staged-recipes#3967]
It would be great if there was a conda-forge package for git-annex.  My attempts at one so far have been unsuccessful.

**Comment by notestaff** [comment]
If you can solve this, you get my big gratitude, plus a $50 bounty: 
https://www.bountysource.com/issues/49351089-packaging-git-annex

I need a git-annex recipe that works on Linux and MacOS (Windows optional), and gets accepted to conda-forge.  This would enable creating a DataLad recipe ( #1720 ), which depends on git-annex.
Thanks a lot!

**Comment by notestaff** [comment]
I've managed to get a working git-annex recipe for Linux (PR #4141 ).  Still working on the Mac version.  I don't know Haskell language and ecosystem, so any help form Haskell experts is welcome.

**Comment by luispedro** [comment]
Git-annex is now on conda-forge [https://github.com/conda-forge/git-annex-feedstock], so this issue should be closed.
