### ISSUE TITLE
Add jupyter-themes

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/staged-recipes#3985]
[`jupyter-themes`](https://github.com/dunovank/jupyter-themes) is a small package for helping to style jupyter notebooks.

**Comment by Adrianzo** [comment]
Yeah! I had it installed... and I was using it... what happened?

OH, apparently it got renamed. See that the dash (`-`) in the middle is removed.

```
$ conda search jupyterthemes
Fetching package metadata .................
jupyterthemes                0.17.9                     py_0  conda-forge     
                                      0.18.0                     py_0  conda-forge     
                                      0.18.2                     py_0  conda-forge 
```

Also, seeing the readme at their [repo](https://github.com/dunovank/jupyter-themes) seems the new command is shorter: `jt`.

**Comment by pmlandwehr** [comment]
[Done](https://github.com/conda-forge/jupyterthemes-feedstock), so closing.
