### ISSUE TITLE
Help needed: librsvg

### ISSUE THREAD

**Issue by jenzopr** [conda-forge/staged-recipes#3991]
Hi all,

a dependency of one of my current projects needs [librsvg](https://wiki.gnome.org/action/show/Projects/LibRsvg?action=show&redirect=LibRsvg). There are several packages in different channels, e.g. from [pkgw](https://github.com/pkgw/conda-recipes/tree/master/recipes/librsvg) or [ostrokach](https://github.com/ostrokach/conda-recipes-extra/tree/master/librsvg) that I could use as templates. I'm wondering why their requirements are different (e.g. all from pkgw are included in ostrokach, who has some additional requirements). Can anyone comment and / or recommend how to start? 

The current version of `librsvg` is `2.41.1`, and since `2.41.0` parts of the code relies on the rust language (`cargo` compiler). I have not seed this one in conda, but a `cargo-lite` is available on PyPI, which could be packaged quickly. Is this advisable? 

Any advice / comment is highly appreciated! Thanks,
Jens

Edit: Maybe @pkgw

**Comment by pkgw** [comment]
I would stick with the most recent stable release before the 2.41 series. I have some interest in getting Rust-based packages into conda-forge, actually, but based on my initial investigations I believe that will require a fair bit of work.

Older versions of librsvg, though, should be pretty straightforward to package. My recipes are generally pretty close to how conda-forge works. It looks like there are a few wrinkles, like the post--link script that is needed, but I think my recipe should be a very good foundation on which to build.

**Comment by jenzopr** [comment]
Just to keep you updated: I untangled the dependencies for librsvg and started writing a recipe for libcroco (taking your recipe, just had to add tests). Currently it runs on CircleCI (in my fork), before I will PR it to conda. After this is done, all dependencies for librsvg are in conda and we can continue with the recipe for librsvg.

**Comment by pkgw** [comment]
Sounds good. I'm afraid that I don't have many useful ideas about testing; a lot of it depends on how much infrastructure the package in question provides. For shared libraries, there's a standard set of quick tests that one can/should use:

```
test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
```

That only provide some superficial safety, but it's better than nothing.

**Comment by jakirkham** [comment]
cc @conda-forge/rust

**Comment by pkgw** [comment]
Right, yes. It turns out I was just lazy and wrong, and conda-forge is already good-to-go with programs that include Rust code. Hopefully [my little elfx86exts submission](https://github.com/conda-forge/staged-recipes/pull/4124) will be a small example of how to build Rust code in a standard context with Cargo ... although I wouldn't be surprised if this package used a different system since it's autotools-based.

**Comment by jenzopr** [comment]
Hey @pkgw !
I continued work on librsvg in my own fork, to remove (obvious) errors during the build and not to pollute the CI plans of conda-forge. 
I ran into an error during configuring of the lib. The last line says:
```
checking for 	gdk-pixbuf-2.0 >= 2.20 	glib-2.0 >= 2.12.0 	gio-2.0 >= 2.24.0 	libxml-2.0 >= 2.7.0 	pangocairo >= 1.32.6 	cairo >= 1.2.0 	cairo-png >= 1.2.0 libcroco-0.6 >= 0.6.1... no
```

Can you have a look at my recipe? You can find it here: https://github.com/jenzopr/staged-recipes/pull/4

Best and thanks,
Jens
