### ISSUE TITLE
Ask to merge the pull request #4007

### ISSUE THREAD

**Issue by matthieujung** [conda-forge/staged-recipes#4020]
Hi all,
Could anyone with write access merge my pull request #4007 to the main repository in order to get a feedstock repository of this package?
All the best,

**Comment by dougalsutherland** [comment]
Please don't make issues like this, it just clutters thing up. In the future, if your PR is languishing you can just add a comment to it and most of the review team will get a notification about it – but yours had only been waiting for less than 24 hours.
