### ISSUE TITLE
Package datashader

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#4028]
Would be nice to have a `conda-forge` package for [`datashader`]( https://github.com/bokeh/datashader ). A data rasterization pipeline for automating the process of creating meaningful representations of large amounts of data.

**Comment by martindurant** [comment]
cc @jbednar

**Comment by jbednar** [comment]
Yes, Crystal Soja also just requested that, and I promised her we'd do it.

**Comment by jakirkham** [comment]
Initial recipe in PR ( https://github.com/conda-forge/staged-recipes/pull/4306 ).
