### ISSUE TITLE
Package colorcet

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#4029]
Would be nice to have a `conda-forge` package for [`colorcet`]( 
https://pypi.python.org/pypi/colorcet ). Provides a collection of perceptually uniform colormaps in pure Python.

**Comment by jakirkham** [comment]
Also a requirement of `datashader`. ( https://github.com/conda-forge/staged-recipes/issues/4028 )

**Comment by jbednar** [comment]
I'm about to release a 1.0 version of colorcet, probably on Monday, so best to hold off until then at least.

**Comment by jbednar** [comment]
Ok, 1.0 is released on the bokeh conda channel, so it's a good time to try to set up a conda-forge feed.

**Comment by jakirkham** [comment]
Would be good to have the PyPI release updated ( https://github.com/bokeh/colorcet/issues/7 ) and the license file packaged in it ( https://github.com/bokeh/colorcet/pull/6 ). We can certainly workaround not having these, but it would make the packaging and maintenance process a bit smoother.

**Comment by jakirkham** [comment]
Initial PR ( https://github.com/conda-forge/staged-recipes/pull/4305 ) for this recipe.
