### ISSUE TITLE
Package numba

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#4030]
Would be nice to have a `conda-forge` package for [`numba`]( https://pypi.python.org/pypi/numba ). A NumPy aware dynamic Python compiler using LLVM.

**Comment by jakirkham** [comment]
Also a requirement of `datashader`. ( https://github.com/conda-forge/staged-recipes/issues/4028 )

**Comment by synapticarbors** [comment]
This is going to require getting `llvmlite` up first.

**Comment by jakirkham** [comment]
Work on `llvmlite` in PR ( https://github.com/conda-forge/staged-recipes/pull/4068 ).

**Comment by jakirkham** [comment]
Now `llvmlite` is in. Would you be interested in giving `numba` a try, @souravsingh?

**Comment by souravsingh** [comment]
Sure, Onit
