### ISSUE TITLE
opencv3

### ISSUE THREAD

**Issue by 183amir** [conda-forge/staged-recipes#407]
Hi everyone,

Are we going to have opencv3 in conda-forge? If yes, could someone who has experience please do it?
Maybe @jakirkham you can do it?

**Comment by jakirkham** [comment]
Probably, but not in the near term. I have some other obligations I need to work on first.

**Comment by jakirkham** [comment]
Issue moved to [conda-forge/opencv-feedstock #5](https://github.com/conda-forge/opencv-feedstock/issues/5) via [**ZenHub.io**](https://www.zenhub.io/)
