### ISSUE TITLE
Packaging nss and nspr

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#4100]
Would be great to have packages for [`nss`]( https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS ) and [`nspr`]( https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSPR ).

**Comment by jakirkham** [comment]
Some work was done on these in PR ( https://github.com/conda-forge/staged-recipes/pull/536 ).

**Comment by marcelotrevisani** [comment]
What was the problem with the the PR #536 ?

**Comment by marcelotrevisani** [comment]
I created two recipes, one for nspr and another one for nss, however it's just for linux

Probably I will need help to create the script for windows and also to adapt the ```build.sh``` to macos. Later I will create a proper pull request for that

**Comment by jakirkham** [comment]
It was failing on CI and I lacked the time/interest to fix it. That said, please feel free to take it over if you like.

Even a Linux only submission would be nice. The feedstock can grow from there.

**Comment by jakirkham** [comment]
Resolved with PR ( https://github.com/conda-forge/staged-recipes/pull/5754 ) and PR ( https://github.com/conda-forge/staged-recipes/pull/5751 ). Thanks @marcelotrevisani :)

**Comment by marcelotrevisani** [comment]
Thanks for review the PR @jakirkham and @isuruf  ! :)
