### ISSUE TITLE
toolchain dependency

### ISSUE THREAD

**Issue by notestaff** [conda-forge/staged-recipes#4151]
The sample recipe says "if your project compiles code (such as a C extension) then add `toolchain` as a build requirement.".  But the toolchain meta-package does not specify any build requirements.   What is the reason for that?  Does this mean that recipes which compile things should add, in addition to the toolchain dependency, their own dependencies on gcc/llvm/binutils?

**Comment by mariusvniekerk** [comment]
the toolchain has a post activate script that ensures that a bunch of environment variables are set correctly.

**Comment by jakirkham** [comment]
Sounds like this was answered. So am closing it out.
