### ISSUE TITLE
upload successfully built staged-recipes to a conda-forge-alpha channel

### ISSUE THREAD

**Issue by notestaff** [conda-forge/staged-recipes#4155]
@conda-forge/core Could successfully built staged-recipes be uploaded to a separate anaconda.org channel, say conda-forge-alpha?  Then they can be used sooner by people who are ok with the risk.  One can add conda-forge-alpha at a lower channel priority than conda-forge, so it would not mask any official packages.

I know I can build packages locally and upload them to my own channel, but the build process won't exactly replicate conda-forge's, so the resulting package won't be the same.  If something works with that package, it may not work with the eventual "official" one.  And sometimes my local builds fail for unclear reasons, while the conda-forge build succeeds.  Also, I don't have a Mac, so can't make a local package to share with colleagues who have Macs.

**Comment by jakirkham** [comment]
Interesting suggestion. Would suggest moving this to the webpage repo so it can get some more visibility. Also that's where we typically discuss decisions that have larger affect on the org.

**Comment by notestaff** [comment]
@jakirkham "webpage repo" is https://github.com/conda-forge/conda-forge.github.io ?

**Comment by jakirkham** [comment]
Yes. Looks like you raised the issue ok over there. So will close this one out. For others coming to this late, this discussion is continued in issue ( https://github.com/conda-forge/conda-forge.github.io/issues/464 ).
