### ISSUE TITLE
cyrus-sasl not in recipes folder

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/staged-recipes#4163]
Is this going to be a problem for the auto feedstock generation? https://github.com/conda-forge/staged-recipes/tree/master/cyrus-sasl
@conda-forge/staged-recipes @conda-forge/core

**Comment by mariusvniekerk** [comment]
Fixing in #4167

**Comment by jakirkham** [comment]
Shouldn't be. Though it will show up on lints of PRs. Otherwise I think it can be ignored. Going to close this since there is a PR already open.
