### ISSUE TITLE
Package libedit

### ISSUE THREAD

**Issue by isuruf** [conda-forge/staged-recipes#4209]
This is so that we can have a libedit pinned to ncurses 5.9 which is the conda-forge pin for now

See https://github.com/conda-forge/octave-feedstock/issues/6 and https://github.com/bioconda/bioconda-recipes/issues/6219

Anaconda recipe is here, https://github.com/AnacondaRecipes/aggregate/tree/master/libedit-feedstock/recipe

cc @jakirkham, @msarahan, @mingwandroid

**Comment by mingwandroid** [comment]
Any reason not to update to ncurses 6 instead?

**Comment by mingwandroid** [comment]
Very little needs rebuilt for that.

**Comment by jakirkham** [comment]
Admittedly we should update to 6. Though I don't have time in the next couple of weeks to look at that. So offered this as a workaround that should have relatively little effect for our ecosystem.

**Comment by isuruf** [comment]
cc @scopatz
