### ISSUE TITLE
Stupid "operator error" or a question: why RTFM "conda skeleton" isn't working?

### ISSUE THREAD

**Issue by yarikoptic** [conda-forge/staged-recipes#4237]
Trying to follow https://github.com/conda-forge/staged-recipes/wiki/Frequently-asked-questions which says to run `conda skeleton pypi your_package_name` but in my case it all boils to conda not knowing about "skeleton" command:

```shell
$> /home/yoh/anaconda-4.4.0-3.6/bin/conda skeleton pypi pymvpa2
usage: conda [-h] [-V] command ...
conda: error: argument command: invalid choice: '/home/yoh/anaconda-4.4.0-3.6/bin/conda' (choose from 'info', 'help', 'list', 'search', 'create', 'install', 'update', 'upgrade', 'remove', 'uninstall', 'config', 'clean', 'package')
```
is there an additional step before to make that command become available somehow?

**Comment by msarahan** [comment]
you need to install conda-build:

conda install conda-build

**Comment by yarikoptic** [comment]
awesome, added to https://github.com/conda-forge/staged-recipes/wiki/Frequently-asked-questions . Thank you @msarahan
