### ISSUE TITLE
Travis CI builds fail

### ISSUE THREAD

**Issue by micknudsen** [conda-forge/staged-recipes#4245]
I have forked the _staged-recipes_ repository and triggered a Travis CI build without any modifications to the code, but it fails:

https://travis-ci.org/micknudsen/staged-recipes/builds/292614495

Is this really the expected behavior?

**Comment by isuruf** [comment]
@jakirkham, this seems to be an issue with the recent conditional build change.

**Comment by jakirkham** [comment]
Is the issue repeatable?

**Comment by isuruf** [comment]
yes

**Comment by jakirkham** [comment]
Is it worth raising to Travis CI or do you think we have a bug in our logic?

**Comment by isuruf** [comment]
I think we should raise an issue in travis-ci

**Comment by jakirkham** [comment]
Ok. Are you happy to follow-up with Travis CI or would you like me to?

**Comment by jakirkham** [comment]
Hmm...we don't seem to check whether the org is `conda-forge`. Is there a way to do that?

**Comment by jdblischak** [comment]
To add another data point, I also observe this behavior of [Travis failing to build on my fork](https://travis-ci.org/jdblischak/staged-recipes/builds/300954346). While not critical, it is convenient to observe the CI results on my fork, especially when the Travis macOS builds are backlogged.

**Comment by jakirkham** [comment]
Is this still an issue?

**Comment by jdblischak** [comment]
> Is this still an issue?

@jakirkham I don't know. I stopped building on my fork of staged-recipes because it stopped being worth it (CircleCI also used to have issues where it wouldn't build the PR since it was already built on the fork; also don't know if this is still an issue)

**Comment by jakirkham** [comment]
A better question is, is this issue worth fixing? Following that, is this an issue that we are able to fix (i.e. not something that is strictly on Travis CI's end)?

**Comment by jakirkham** [comment]
Guessing this is issue ( https://github.com/travis-ci/travis-ci/issues/8721 ). Is that right?

**Comment by jakirkham** [comment]
Closing as it looks like upstream fixed this some time ago. Though please feel free to reopen if that's not correct.
