### ISSUE TITLE
Difficult to find some channel (IRC, list, whatever) where I could seek some interactive community support

### ISSUE THREAD

**Issue by yarikoptic** [conda-forge/staged-recipes#4262]
I could be blind, but looked around and could not find.  And didn't want to pollute this issue tracker with questions (or is that the way?)

**Comment by nehaljwani** [comment]
Maybe this is what you are looking for? https://gitter.im/conda-forge/conda-forge.github.io

**Comment by jakirkham** [comment]
For basic questions, would ask on [gitter]( https://gitter.im/conda-forge/conda-forge.github.io ). That's usually how we ascertain where an issue should go.
