### ISSUE TITLE
Request for PR reviews regarding future feedstocks

### ISSUE THREAD

**Issue by abhi18av** [conda-forge/staged-recipes#4290]
Hi conda-forge team

I've been working hard on adding more languages and tools to conda-forge feedstocks and it's a bit discouraging to see that these seem to be getting unnoticed...

The builds are passing after a lot of tweaks and skips but could you guys help me out with the PRs in case there is something that I've overlooked.

I'd love to them merged and waiting for it anxiously.

Here's the batch of PRs I've been working on 
https://github.com/conda-forge/staged-recipes/pulls/abhi18av

**Comment by croth1** [comment]
@abhi18av, the core team seems to be quite busy in the last weeks. Once you have finished your pull requests, you can ping @conda-forge/core by mentioning them in a comment and you will get a review soonish. I guess core has to work through a long backlog at the moment, so there might be delays. Please do not let this discourage you and keep up the good work! 👍

**Comment by jakirkham** [comment]
The best thing to do to get reviews is to ping @conda-forge/staged-recipes once a PR is passing.

**Comment by isuruf** [comment]
@abhi18av, almost all of the PRs above have no build script that builds the software and installs it to $PREFIX. See https://conda.io/docs/user-guide/tasks/build-packages/build-scripts.html#build-scripts-build-sh-bld-bat

**Comment by abhi18av** [comment]
Thanks for the prompt response and advice @croth1 @jakirkham  and @isuruf !

@isuruf yeah, I never quite understood this part about the scripts ...

However, this could be a great opportunity to try out this project that transpiles to batch and bash 
https://github.com/BYVoid/Batsh

I'll start correcting the builds with jruby first 

https://github.com/conda-forge/staged-recipes/pull/4022
