### ISSUE TITLE
Package duecredit

### ISSUE THREAD

**Issue by yarikoptic** [conda-forge/staged-recipes#4303]
Is used (optionally) but a growing number of packages, including recently merged feedstock PyMVPA.

I am one of the upstream developers and only slowly picking up speed with conda recipes, so if someone could provide it before I do, would be very much appreciated.  In general it should't be too difficult, it does install fine with pip usually (citeproc and lxml are the heaviest dependencies iirc)

**Comment by synapticarbors** [comment]
Needs packages for `citeproc-py` first, and that in turn needs `rnc2rng` as a setup requirement.

**Comment by mscheltienne** [comment]
Hello @yarikoptic! I can give a hand on packaging those on `conda-forge`, but I have some concerns.

`rnc2rng` is available on conda-forge: https://anaconda.org/conda-forge/rnc2rng No issues here.
However, `citeproc-py` is not and is not maintained a lot. The tests are run up to 3.9, and I am seeing issues with compatibility with Python 3.7+. The last commit is a call for maintainers.
As it is, adding an unmaintained package to conda-forge is not a great idea. I see several options:
- get the maintenance of `citeproc-py` up and going again.
- don't depend on `citeproc-py`, and use a less general purpose code/package for `duecredit`.

@smoia For now I am removing `duecredit` from the requirements of `nigsp` in `conda-forge` https://github.com/conda-forge/staged-recipes/pull/21409.

**Comment by smoia** [comment]
Hey there!
If it's not a problem to have a different requirement in the library setup vs conda-forge, I'm happy with that solution.

@yarikoptic, how problematic is it to drop `citeproc-py` from `duecredit`?

**Comment by yarikoptic** [comment]
IIRC citeproc-py provides crucial functionality for duecredit -- formatting of the entries.  
I see tests failing for 3.9 in https://github.com/brechtm/citeproc-py/pull/129 (I just merged it), but seems to be ok in master , 3.6 errored, removing it since EOLed anyways (https://github.com/brechtm/citeproc-py/pull/130), removed.
There is no test-related fixes since 0.6.0 release  and we are green there... @mscheltienne what do you mean by

> and I am seeing issues with compatibility with Python 3.7+.

? I see no issues.  ideally it should just get feedstock in conda-forge. https://anaconda.org/Aramislab/citeproc-py hints there is one elsewhere already.

**Comment by mscheltienne** [comment]
I was just looking through the list of issues, e.g. https://github.com/brechtm/citeproc-py/issues/103

----------------

If I read the code from `duecredit` correctly, `citeproc-py` is only used in one function `io.py` in:
- https://github.com/duecredit/duecredit/blob/03451059445fbf30958165b156a547ae610b6114/duecredit/io.py#L281-L351
To format BibTex files?

Maybe it would be possible to drop this dependency, either in favor of an internal code doing the formatting you need or of another BibTex library, e.g. `bibtexparser` (https://github.com/sciunto-org/python-bibtexparser) which is maintained?

----------------

Also, side note, while I was looking at the code for `duecredit`, my IDE picked up many unused variables and imports. Maybe a `flake8` run/workflow could help improve this point.

**Comment by maxb2** [comment]
> ideally it should just get feedstock in conda-forge. https://anaconda.org/Aramislab/citeproc-py hints there is one elsewhere already.

FYI, I added a `citeproc-py` [feedstock](https://github.com/conda-forge/citeproc-py-feedstock) in [conda-forge](https://anaconda.org/conda-forge/citeproc-py) a while ago.

**Comment by mscheltienne** [comment]
@maxb2 Oh nice! Not sure how I missed it!
Then we can create the recipe for `duecredit` and keep the lack of maintenance of `citeproc-py` as an issue on `duecredit`'s issue tracker.

@yarikoptic @smoia Do you want me to create the recipe and list both of you as maintainers?

**Comment by yarikoptic** [comment]
I don't mind, thank you

**Comment by yarikoptic** [comment]
> Also, side note, while I was looking at the code for duecredit, my IDE picked up many unused variables and imports. Maybe a flake8 run/workflow could help improve this point.

Yeah, lots of things could be improved. Project grew from rapid prototype at a hackathon and didn't see much action recently. PRs are welcome!
