### ISSUE TITLE
R package builds fail on osX

### ISSUE THREAD

**Issue by Cashalow** [conda-forge/staged-recipes#4320]
Hello, 

Since r-base 3.4.2 is available on default, I get the impression that all R recipes are failing on osX when building against this version.

Three of my own https://github.com/conda-forge/staged-recipes/pull/4311 https://github.com/conda-forge/staged-recipes/pull/4310 https://github.com/conda-forge/staged-recipes/pull/4308 as well as other's (https://github.com/conda-forge/staged-recipes/pull/4244 https://github.com/conda-forge/staged-recipes/pull/4240)

Is there a way to prevent building against r-base 3.4.2 ? Or should we package this new version on conda-forge instead ?

**Comment by jdblischak** [comment]
Adding another to the list of affected PRs: https://github.com/conda-forge/staged-recipes/pull/4328

**Comment by jdblischak** [comment]
The error occurs during `R CMD INSTALL --build .`:

```
R CMD INSTALL --build .
dyld: Library not loaded: @rpath/libiconv.2.dylib
  Referenced from: /Users/travis/miniconda/conda-bld/r-ini_1509592631946/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/R/lib/libR.dylib
  Reason: Incompatible library version: libR.dylib requires version 9.0.0 or later, but libiconv.2.dylib provides version 8.0.0
```
https://travis-ci.org/conda-forge/staged-recipes/builds/296072432#L572

As @Cashalow suggested, I also think the errors are related to the new R 3.4.2 update on defaults. Potentially related issues:

https://github.com/conda/conda/issues/6183

https://github.com/ContinuumIO/anaconda-issues/issues/6312

**Comment by Cashalow** [comment]
Thanks @jdblischak ! One more to the list https://github.com/conda-forge/staged-recipes/pull/4340

**Comment by jdblischak** [comment]
Working on a fix for this in https://github.com/conda-forge/conda-smithy/pull/604

**Comment by jdblischak** [comment]
My PR was merged and just released in conda-smithy 2.4.3. I am going to restart the builds for the PRs listed in this issue. If you have an R recipe that you submitted prior to today that failed, you can restart the builds to see if that fixes the problem (and if you don't know how to do that, you can @ mention me here with the link to your PR, and I'll do it).

**Comment by Cashalow** [comment]
Thanks a lot!

**Comment by jdblischak** [comment]
I restarted all the PRs I could find. Unfortunately we can't get too excited yet. Rerendering existing feedstocks has been fixed, but new recipes submitted to staged-recipes are still failing:

https://travis-ci.org/conda-forge/staged-recipes/builds/296072432#L207

**Comment by jdblischak** [comment]
This should finally be fixed. What a pain! Things are working smoothly now, so please don't let this week discourage you from submitting future R recipes to conda-forge.
