### ISSUE TITLE
Package libpostal

### ISSUE THREAD

**Issue by AbdealiJK** [conda-forge/staged-recipes#4370]
LibPostal - https://github.com/openvenues/libpostal
is a common library which is used in the popular pypostal library - https://github.com/openvenues/pypostal

Would be great to have a package for libpostal so that pypostal installation is simpler.

**Comment by Monduiz** [comment]
Is this still happening?

**Comment by xhochy** [comment]
@Monduiz the PR seems to be abandoned, please feel free to pick it up.

**Comment by MichaelMarien** [comment]
I can pick this one up!
