### ISSUE TITLE
cspice is breaking master

### ISSUE THREAD

**Issue by isuruf** [conda-forge/staged-recipes#4372]
```
Error: Failed to render jinja template in /tmp/tmpxodTb3__feedstocks/cspice-feedstock/recipe/meta.yaml:
'sha256' is undefined
```

See https://travis-ci.org/conda-forge/staged-recipes/builds/298890253

cc @conda-forge/staged-recipes, @Juanlu001

**Comment by Juanlu001** [comment]
Apologies to all, my bad. Fixing it right now.

**Comment by Juanlu001** [comment]
Attempt: #4375.
