### ISSUE TITLE
Package GLFW

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#4395]
Would be nice to have a package for [GLFW]( https://github.com/glfw/glfw ).

**Comment by jakirkham** [comment]
cc @ngoldbaum ( as it came up on [gitter]( https://gitter.im/conda-forge/conda-forge.github.io?at=5b2ac8c6aeb8fa0c072f5ca7 ) )

**Comment by hmaarrfk** [comment]
@EricThomson I guess there is interest in GLFW in conda-forge

**Comment by hmaarrfk** [comment]
It requires https://github.com/conda-forge/staged-recipes/issues/7197

**Comment by hmaarrfk** [comment]
@kmuehlbauer you can take the recipe from: https://github.com/ramonaoptics/glfw-feedstock
It might work

**Comment by jakirkham** [comment]
This was done in PR ( https://github.com/conda-forge/staged-recipes/pull/7708 ).
