### ISSUE TITLE
Package pytorch

### ISSUE THREAD

**Issue by AbdealiJK** [conda-forge/staged-recipes#4396]
CC @soumith would you be interested in contributing your conda package for pytorch to conda-forge ?
https://anaconda.org/soumith/pytorch

**Comment by soumith** [comment]
there is already a conda-forge pytorch package i think? or an anaconda channel package. i have no issues if someone took my recipes and put them in conda-forge. They are usually located here: https://github.com/pytorch/builder/tree/master/conda
I'm updating them for the upcoming 0.3 release.

**Comment by jakirkham** [comment]
There is PR ( https://github.com/conda-forge/staged-recipes/pull/3780 ), but it is not done yet.

**Comment by carterbox** [comment]
@conda-forge/help-python, this PR can be closed

https://github.com/conda-forge/pytorch-cpu-feedstock builds both with and without CUDA.
