### ISSUE TITLE
appveyor x86 build failure?

### ISSUE THREAD

**Issue by aleksandervines** [conda-forge/staged-recipes#4421]
I'm having trouble interpreting the output from appveyor. It fails completely on the x86 platform, which for me is weird and as far as I can tell it looks like a conda-forge issue more than with my app (especially since it should skip the build process on python 3).

https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.18696
from:
https://github.com/conda-forge/staged-recipes/pull/4128

It seems to me that this is causing the failure:
```
(C:\bld\r-rmpfr_1510673559831\_b_env) C:\bld\r-rmpfr_1510673559831\work\Rmpfr>"C:\bld\r-rmpfr_1510673559831\_b_env\Scripts\R.exe" CMD INSTALL --build . 
...
Warning: running command 'make -f "Makevars.win" -f "C:/bld/r-rmpfr_1510673559831/_b_env/R/etc/i386/Makeconf" -f "C:/bld/r-rmpfr_1510673559831/_b_env/R/share/make/winshlib.mk" SHLIB="Rmpfr.dll" OBJECTS="Ops.o Summary.o convert.o init.o utils.o"' had status 2
ERROR: compilation failed for package 'Rmpfr'
```

But if it is a problem with my setup, could someone point me in the direction of why?

**Comment by isuruf** [comment]
Can you rebase the PR on top of master?

**Comment by bgruening** [comment]
@isuruf this does not seem to help in https://github.com/conda-forge/staged-recipes/pull/4426

```
bag@bag ~/projects/code/staged-recipes/recipes
 % git rebase origin/master
Aktueller Branch a_few_more ist auf dem neuesten Stand.
bag@bag ~/projects/code/staged-recipes/recipes
 % git push origin a_few_more 
Everything up-to-date
```

**Comment by isuruf** [comment]
@bgruening, your problem is different. Can you open an issue here, https://github.com/conda-forge/r-base-feedstock mentioning that https://github.com/conda-forge/r-base-feedstock/pull/24 might be the problem?

**Comment by bgruening** [comment]
Done: https://github.com/conda-forge/r-base-feedstock/issues/26

**Comment by aleksandervines** [comment]
At first test it seems to have worked to rebase it on master, as it now successfully got to where it should skip the build on Python 3, and succeeded on those.

I still have hickups in the compiling itself, but now I think it's my fault.
