### ISSUE TITLE
Use one appveyor job for each architecture

### ISSUE THREAD

**Issue by isuruf** [conda-forge/staged-recipes#4508]
All the other CI use one job and appveyor limit seems to be 2 hours now.

cc @jakirkham

**Comment by jakirkham** [comment]
Sorry I'm not following the suggestion. What are you proposing? Is there an existing setting or config file change for what you are wanting to do?

As a side note, Windows 32-bit tends to have low usage statistics when looking at package downloads. There is a fair question of when we might want to drop Windows 32-bit support. Of course there are a few weird things like NSIS where this is not possible. However many R packages simply don't support Windows 32-bit at all.

**Comment by isuruf** [comment]
In staged-recipes, there are 6 jobs. I'm proposing to change that to 2 jobs (win-64 and win-32)

**Comment by sodre** [comment]
We removed Win32 support so this is no longer needed.

**Comment by jakirkham** [comment]
Hmm...think we forgot to close this as it was implemented and merged with PR ( https://github.com/conda-forge/staged-recipes/pull/5037 ).
