### ISSUE TITLE
Package MathJax

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#4520]
Would be good to have a package for `mathjax`.

**Comment by jakirkham** [comment]
cc @conda-forge/notebook @conda-forge/sage

**Comment by minrk** [comment]
This shouldn't affect the notebook package, which relies on a vendored mathjax.

**Comment by cbrueffer** [comment]
This was merged in https://github.com/conda-forge/staged-recipes/pull/7722 as far as I see; anything missing or can this issue be closed?

**Comment by jakirkham** [comment]
Thanks Christian! Nope I think that's it. Probably the PR just missed a "Closes" note. Anything else can be taken up in [the feedstock]( https://github.com/conda-forge/mathjax-feedstock ).
