### ISSUE TITLE
trying to use openCV with ipython .... (((

### ISSUE THREAD

**Issue by ZieloneOczy** [conda-forge/staged-recipes#4575]
hello! I am having a hard time trying to use openCV with ipython ... am I doing something wrong?

In [1]: import cv2
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c8ec22b3e787> in <module>()
----> 1 import cv2
ImportError: dlopen(/Users/robertalexander/anaconda/lib/python3.6/site-packages/cv2.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libopenblasp-r0.2.19.dylib
  Referenced from: /Users/robertalexander/anaconda/lib/libopencv_hdf.3.2.0.dylib
  Reason: image not found

**Comment by jakirkham** [comment]
Transferring to the feedstock as the issue does not belong here.

**Comment by jakirkham** [comment]
Issue moved to [conda-forge/opencv-feedstock #99](https://github.com/conda-forge/opencv-feedstock/issues/99) via [**ZenHub**](https://www.zenhub.com/)
