### ISSUE TITLE
CircleCI feedstock setup fails sporadically

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#458]
Related: https://github.com/conda-forge/staged-recipes/pull/395
Related: https://github.com/conda-forge/staged-recipes/pull/460

See this [line]( https://travis-ci.org/conda-forge/staged-recipes/jobs/125990745#L275 ) in the log. For some reason, it is not able to setup the CircleCI queue for the feedstock.

**Comment by pelson** [comment]
Looks like this could be an issue on their end. Did you try re-starting?

**Comment by jakirkham** [comment]
Yeah, I tried a few times when it happened and then opted to remove it. I will try adding again because it seems @ocefpaf had some luck recently.

**Comment by jakirkham** [comment]
Nope this still fails @pelson. See this [line]( https://travis-ci.org/conda-forge/staged-recipes/jobs/126115006#L275 ) in the latest log. I really don't know what is going on here. Is it possible to delete this repo from CircleCI? Maybe there is something off with it.

**Comment by jakirkham** [comment]
So, I have this PR ( https://github.com/conda-forge/staged-recipes/pull/464 ) that we can merge once we fix the CircleCI issue here.

**Comment by ocefpaf** [comment]
> I will try adding again because it seems @ocefpaf had some luck recently.

I had to re-start Travis-CI yesterday. But after a while things were normal.

**Comment by jakirkham** [comment]
Yeah, I restarted this several times yesterday and it didn't work. So, I decided to remove it. I have retried recently and it is still failing. So, I remove it again. There is something off here that goes beyond the usual issues. Not sure why, but there is something more here.

**Comment by ocefpaf** [comment]
I am overwhelmed with some of my day job, but I will take a look at this later. Not sure if I can do any better than you already did though...

**Comment by jakirkham** [comment]
If you have permissions to delete [this]( https://circleci.com/gh/conda-forge/apptools-feedstock ), then that might be enough. I don't have these permissions.

**Comment by ocefpaf** [comment]
I have the same rights as you. But I did find [this](https://twitter.com/circleci/status/536938935843176448). Not sure what to do here...

**Comment by pelson** [comment]
I'll take a look to see if I can add you both as admin.

**Comment by jakirkham** [comment]
Thanks.

Though it looks like we have to ping them though according to this [tweet]( https://twitter.com/circleci/status/594137519048040449 ) for a project to be deleted.

**Comment by pelson** [comment]
Out of interest, what do you expect deleting the repo from circle-ci will help with?

**Comment by jakirkham** [comment]
Well, it is having some issue configuring CircleCI for just this feedstock. So, I am thinking something went sour when it first tried to setup the feedstock. Since it happens to us so reliably with the `apptools-feedstock` and not with any other feedstock, I am wondering if there is something broken with this CircleCI project. Deleting it and recreating it may let us start over fresh and not suffer from what ever configuration mess up has occurred.

**Comment by pelson** [comment]
Has anything else gone through circle since the first apptools failure?

**Comment by pelson** [comment]
It is definitely recreatably timing out with the circle api.

**Comment by jakirkham** [comment]
Yes, `snappy`, which worked fine.

**Comment by jakirkham** [comment]
Hmm...now it happened to `psutil`. Am going to try restarting to see if the issue persists.

**Comment by pelson** [comment]
I've been able to reproduce this on my own machine (apptools and msinttypes). I'll dig a little deeper.

**Comment by jakirkham** [comment]
Restarting with `psutil` has failed. Trying a third time. If it still fails, will remove from the staging area. Maybe it is a general problem with the CircleCI API. Though they don't show any status issues. That doesn't mean there isn't one. Maybe it is worth reporting.

**Comment by jakirkham** [comment]
Worked on the third try. Weird.

**Comment by pelson** [comment]
> If it still fails, will remove from the staging area. 

Please don't. It won't make any difference, and it is a bit hack and slash to solve the problem. Let's find the issue, once solved, these will slot into their own feedstock.

**Comment by pelson** [comment]
I thought for a second it was an expired token, and was able to get it to work with a new one, but now I'm getting the same issue with that token too. I'm pretty confident it is a circle issue.

**Comment by pelson** [comment]
P.S. I will revoke the circle token once we have solved this.

**Comment by jakirkham** [comment]
> Please don't. It won't make any difference, and it is a bit hack and slash to solve the problem. Let's find the issue, once solved, these will slot into their own feedstock.

Doesn't matter. It went on the third try.

**Comment by jakirkham** [comment]
Though if you want to try merging this PR ( https://github.com/conda-forge/staged-recipes/pull/464 ), we can play with `apptools` in the staging area, which we know has caused some issues.

**Comment by jakirkham** [comment]
> I'm pretty confident it is a circle issue.

I think you are right. Just wasn't sure if it was one project or the whole API that was having issues. Now I am leaning towards the latter.

**Comment by pelson** [comment]
I've asked circle here: https://twitter.com/pypelson/status/725344329884139520
This is certainly an issue with circleci (which may of course be related to something we are doing with conda-forge, like registering lots of repos). Even when the registration is working it is taking a good amount of time though, so worth getting to the bottom of.

**Comment by jakirkham** [comment]
> Even when the registration is working it is taking a good amount of time though, so worth getting to the bottom of.

Absolutely. It would be nice to understand what is going on here.

> This is certainly an issue with circleci (which may of course be related to something we are doing with conda-forge, like registering lots of repos).

Maybe, but this only started recently and we have only registered a couple of repos. Not quite following why it has to do with how many we are registering. Though it might be related to how many we have registered already, but that would be pretty horrible if that is the case.

Let's wait and see what they say.

**Comment by pelson** [comment]
> Though it might be related to how many we have registered already, but that would be pretty horrible if that is the case.

I just got a gateway timeout on their website when listing the registered projects. I'd say this was a problem with Circle not handling the high number of repos. I've submitted a change to conda-smithy which works around this fundamental flaw. https://github.com/conda-forge/conda-smithy/pull/147

**Comment by pelson** [comment]
I think this is solved by not checking whether a repo is followed first. Happy to reopen if it re-occurs.

**Comment by jakirkham** [comment]
Seems to have worked just a moment ago.

**Comment by pelson** [comment]
I got redirected from the Twitter post to the mailinglist. They seem to have solved the underlying issue (but we can stick with the fix I proposed anyway). https://discuss.circleci.com/t/circle-api-504-gateway-timeout/3659/1
