### ISSUE TITLE
Package python-libtiff

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#4675]
Would be nice to have a package for the [Python `libtiff` wrapper library]( https://pypi.python.org/pypi/libtiff ). To disambiguate between the C `libtiff` library it wraps, this could be called `python-libtiff`. Though the repo's name is `pylibtiff`, which could be another option.

**Comment by bgruening** [comment]
@jakirkham https://github.com/conda-forge/staged-recipes/pull/11145/files

**Comment by jakirkham** [comment]
Thanks Björn! 😄

**Comment by jakirkham** [comment]
This was done in PR ( https://github.com/conda-forge/staged-recipes/pull/11145 ) and is named `pylibtiff`.
