### ISSUE TITLE
Correcting misnamed feedstock (neovim)

### ISSUE THREAD

**Issue by jprnz** [conda-forge/staged-recipes#4714]
I am interested in adding a recipe for neovim and have a commit nearly ready to stage.
I noticed there is already a feedstock named 'neovim', however this feedstock only contains the python plugin bindings/api--not the editor itself.

For clarity, I would suggest moving the current 'neovim' feedstock to 'neovim-python-client' (mirroring the naming used by the neovim team).

Is this possible?

cc @curtisalexander

**Comment by curtisalexander** [comment]
I don’t know what the ramifications of a name change would be downstream. As the maintainer of the current [neovim feedstock](https://github.com/conda-forge/neovim-feedstock) (i.e. the Python client for neovim), I am ambivalent about the current name.  I would be glad to make a change if it wouldn’t throw others off who already have been utilizing the conda recipe / package. 

Can someone comment on...
1) what it would take to change a recipe name
2) what, if any, consequences there would be for existing users of the package

**Comment by curtisalexander** [comment]
Attn: @conda-forge/core @conda-forge/staged-recipes 

Can someone provide guidance on changing a feedstock name?

**Comment by dougalsutherland** [comment]
My understanding is that it's possible, but it will definitely be confusing for people already using the current `neovim` package. (`conda update` would remove the Python bindings and install the editor, for example.) There are definitely some users: [download count](https://anaconda.org/conda-forge/neovim/files).

One possibility would be:
- name the new package something like `neovim-editor`
- rename the current package to something like `python-neovim`
- make a new metapackage `neovim` that depends on...both? just `python-neovim`, and eventually phase it out?

**Comment by curtisalexander** [comment]
@dougalsutherland Could you clarify your last bullet?

> make a new metapackage neovim that depends on...both? just python-neovim, and eventually phase it out?

I'm getting stuck at the adjustments needed over time for the metapackage.
* Take the current `neovim` package (which is today just the Python client) and set it up to depend on both the editor and the Python bindings
* Then you alter the `neovim` package at some point in the future to...**what exactly?**
* And eventually phase out...**what exactly?**

**Comment by dougalsutherland** [comment]
I think there are two possibilities for a metapackage:

1. `neovim` gets you "everything neovim", i.e. both the editor and the Python bindings.
2. `neovim` is meant for a short-term migration path for whoever's currently using it. It has an `activate` script that says something like "the name `neovim` is deprecated, switch to `python-neovim` or `neovim-editor` depending on which you want." The goal would be that eventually nobody would use the `neovim` name anymore.

I think option 1 is better.

**Comment by lukelbd** [comment]
Any chance of movement on this? Found this thread after running `conda install -c conda-forge neovim` and wondering why `nvim` was not found. A neovim recipe will let me use `nvim` on compute clusters where I do not have sudo privileges.

**Comment by curtisalexander** [comment]
@lukelbd Apologies as I have not had the opportunity to move this forward.  I note that @xhochy built a specific feedstock for [pynvim](https://github.com/conda-forge/pynvim-feedstock).  When/if I have time, I will tinker with trying to build a feedstock for the `neovim` editor specifically.  Then as dougalsutherland notes above, we can try to turn neovim into a meta-package.

If anyone would like to jump in and help move forward, please feel free!

**Comment by xhochy** [comment]
I would rather make a new feedstock `nvim`, archive `neovim` and mark all packages as broken so that they are no longer found. Otherwise this will be confusing to endusers.

**Comment by lukelbd** [comment]
@curtisalexander Friendly ping. Making a new `nvim` feedstock as suggested by @xhochy makes sense to me.

**Comment by xhochy** [comment]
The `nvim` feedstock is available since some time now.
