### ISSUE TITLE
Somebody removed the `scripts` directory

### ISSUE THREAD

**Issue by giacomov** [conda-forge/staged-recipes#4760]
All tests are failing.

It looks like somebody have removed the `scripts` directory from the master...

See for example:

https://circleci.com/gh/conda-forge/staged-recipes/22657?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by giacomov** [comment]
ok, it looks like this is the relevant commit:

https://github.com/conda-forge/staged-recipes/commit/13215528be2adb98eae1303bd21b92054e2e9524

I guess I just need to get the changes in the master in my branches before trying again.

**Comment by CJ-Wright** [comment]
`git rebase` please.

**Comment by dougalsutherland** [comment]
It's been a while for people to see this, so closing it out now.
