### ISSUE TITLE
`noarch` with dep(s) not built on all systems

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/staged-recipes#4787]
What is the policy on `noarch` builds which have dependencies that are not built for all systems? Are these valid `noarch` recipes?
Attn: @scopatz 
@conda-forge/staged-recipes

**Comment by CJ-Wright** [comment]
It would be nice to not propagate dependency OS specific build issues up through all the dependency graph.

**Comment by jakirkham** [comment]
What sort of failure does `conda` give if someone tries to install this `noarch` package with missing dependencies? Even a dummy example would be productive for understanding this behavior.

**Comment by dougalsutherland** [comment]
So, if you make a `noarch` package depending on a package only available on a different python version, it's pretty reasonable:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - stupid-dummy-dep -> enum34 -> ordereddict -> python 2.6*
Use "conda info <package>" to see the dependencies for each package.
```

If you make a `noarch` package with a dependency only available on a different architecture:
```
PackageNotFoundError: Packages missing in current channels:

  - stupid-dummy-maconly -> stupid-dummy

We have searched for the packages in the following channels:
[...]
```

(Here `stupid-dummy-maconly` is the `noarch` package, and `stupid-dummy` is the package that's only built on Mac, where I tried to install `stupid-dummy-maconly` on Linux.)

So pretty informative error messages, IMO.

**Comment by jakirkham** [comment]
Agreed. Thanks for experimenting with this, @dougalsutherland.

**Comment by CJ-Wright** [comment]
Awesome! I guess this needs some docs somewhere?

**Comment by scopatz** [comment]
probably the docs repo :)

**Comment by scopatz** [comment]
Though an additional comment in the example would be good too.

**Comment by jakirkham** [comment]
I think we resolved this satisfactorily. Happy to close @CJ-Wright?

**Comment by CJ-Wright** [comment]
Yes, although I was going to keep this open until the docs got written.

**Comment by jakirkham** [comment]
Ah sorry. Missed the other doc point. Yeah feel free to keep this open if it helps you.

**Comment by mbargull** [comment]
How would you be able to get this through the selector linting on `staged-recipes`? On the feedstock you can do a rerender and thus won't need a selector with missing Windows dependencies. Is it currently possible to make this use case work for new recipes on `staged-recipes`?
Very recent example: https://github.com/conda-forge/staged-recipes/pull/4860.

**Comment by mbargull** [comment]
Would you have to use `[skip appveyor]` commit messages?

**Comment by dougalsutherland** [comment]
@mbargull Right, just don't put <code>skip: true &nbsp;# [win]</code>. `[skip appveyor]` in the commit message avoids running it on Windows where it won't work anyway, but if you didn't do that we would also be able to just ignore the red X. :)

**Comment by mbargull** [comment]
> we would also be able to just ignore the red X. :)

I tend to forget that "human factor" -- thanks for reminding me 😄.
If you think it's reasonable, I'd suggest to put a note on `[skip appveyor]` when the docs are added.

**Comment by jakirkham** [comment]
Closing as this is now documented thanks to PR ( https://github.com/conda-forge/conda-forge.github.io/pull/567 ).

Thanks everyone :)
