### ISSUE TITLE
Docs not up to date? Where is the docker script to run tests locally?

### ISSUE THREAD

**Issue by tiagoantao** [conda-forge/staged-recipes#4799]
According to the documentation here: https://conda-forge.org/docs/testing.html it is possible to run docker tests for staged recipes, but the script to run it does not exist. Indeed the `scripts` directory is missing. Any ideas on how to test with docker? Is the documentation out of date?

**Comment by dougalsutherland** [comment]
It's in `.circleci/run_docker_build.sh` now. Will send a PR to update the docs, thanks....

**Comment by tiagoantao** [comment]
Thanks @dougalsutherland , I am closing this
