### ISSUE TITLE
Package Python debug binaries

### ISSUE THREAD

**Issue by xoviat** [conda-forge/staged-recipes#4812]
lldb scripting support is disabled on Windows because it requires the Python debug binaries. This requires discussion about how these should be packaged.

**Comment by xoviat** [comment]
Note: I may be able to get around this.

**Comment by dougalsutherland** [comment]
Related:
- https://github.com/ContinuumIO/anaconda-issues/issues/80
- https://github.com/conda-forge/staged-recipes/pull/961
- https://github.com/conda-forge/staged-recipes/issues/1593
- https://github.com/conda-forge/python-feedstock/issues/73
- https://github.com/conda-forge/python-feedstock/pull/86

**Comment by xoviat** [comment]
Duplicate 1593
