### ISSUE TITLE
print out list of built packages at end of PR build phase

### ISSUE THREAD

**Issue by djsutherland** [conda-forge/staged-recipes#5039]
It'd be easier to notice at a glance when packages are unexpectedly skipped because of a missing dependency if, at the end of the build, we printed out the list of built packages. This used to be relatively easy to tell from build times for different components of the matrix, but now that everything's on just one or two builds with #5037 (a huge net positive!), that doesn't work anymore.

Recent example where this might have been useful: https://github.com/conda-forge/staged-recipes/pull/4808#issuecomment-361988130.

This should be really easy, just the appropriate `ls` or `dir` command at the end of the build script; I'll send a PR later, just noting it down for myself now. :)

**Comment by jakirkham** [comment]
Sure. Sounds totally reasonable.

FWIW `conda-build-all` notes the combinations of packages that will be built in the beginning. Not sure if that helps the problem being run into here or not. Just figured it's worth noting. :)

**Comment by dougalsutherland** [comment]
...you know what, I've definitely seen that plenty of times, just forgot that it was there.

I still might send a PR with an `ls -l` at the end, though, since it might be an extra vague check that files are actually being included in the package and so on.

**Comment by jakirkham** [comment]
No worries. Certainly not the first person to say that either. :) Guess that just points out we do need this listed somewhere else too. ;) At the end of the log seems like a fine place to me as well.

**Comment by jaimergp** [comment]
Closed by https://github.com/conda-forge/staged-recipes/pull/26647
