### ISSUE TITLE
AppVeyor broken on staged-recipes

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#508]
Appears AppVeyor has stopped working on staged-recipes. Am seeing error messages like this when trying to restart anything.

    Cannot read last commit information from GitHub repository

See the following related issues.

* http://help.appveyor.com/discussions/problems/197-cannot-read-last-commit-information-from-github-repository
* http://help.appveyor.com/discussions/problems/1369-cannot-read-last-commit-information-from-github-repository-nikolayitopenjudgesystem-unauthorized

**Comment by jakirkham** [comment]
@ocefpaf, could you please take a look at this?

**Comment by jakirkham** [comment]
Not sure what the issue was here, but it seems to have resolved itself.

**Comment by ocefpaf** [comment]
:confused:

**Comment by jakirkham** [comment]
Unfortunately, I have no log for you as it wasn't like builds started and then failed with this message. Instead builds simply didn't start at all and if one tried to start them manually one would get this error message. Just as mysteriously as it started, it ended. Really no clue what was happening.

**Comment by ocefpaf** [comment]
I experience that before. It is probably to due to stress we are putting on these services. I usually just wait it out.

**Comment by jakirkham** [comment]
Yeah, that's basically what I did.
