### ISSUE TITLE
survminer for R version 3.4.0

### ISSUE THREAD

**Issue by pk1110** [conda-forge/staged-recipes#5081]
Hi,

I am able to download the 'survminer' package but get an error " Warning in install.packages :
  unable to move temporary installation ‘C:\Programmer\R\R-3.4.0\library\file3adc7af69de\survminer’ to ‘C:\Programmer\R\R-3.4.0\library\survminer’

Does survminer work with R version 3.4.0.  I am using R studio v 1.0.153.  Thanks

**Comment by isuruf** [comment]
I don't know why you decide to file this here, but this is clearly not the place.
