### ISSUE TITLE
Package kubernetes

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/staged-recipes#5104]
Python bindings for [kubernetes](https://github.com/kubernetes-client/python)

**Comment by sodre** [comment]
It would also be great to get the kubernetes binaries in conda-forge.

**Comment by sodre** [comment]
it looks like #3125 took care of the python bindings. Are you interested in packaging the bins?

**Comment by pmlandwehr** [comment]
Nope - if we've got the python bindings I'm perfectly happy. Closing.
