### ISSUE TITLE
AppVeyor (but not Travis or CircleCI) fails with "wrong version" in Perl module import test

### ISSUE THREAD

**Issue by vinjana** [conda-forge/staged-recipes#5169]
The AppVeyor results in https://github.com/conda-forge/staged-recipes/pull/5148 deviate from those of Travis and CircleCI. When importing the Perl module the testing script in AppVeyor fails with the remark, the wrong version 3.73 (of Common::Sense) is found. In both Travis and CircleCI the correct version 3.74 is returned.

Smells like a problem with your build and test environment on AppVeyor. I'd be grateful for your assistance with this!

**Comment by isuruf** [comment]
Let's discuss in the PR
