### ISSUE TITLE
AppVeyor speed-up!

### ISSUE THREAD

**Issue by frol** [conda-forge/staged-recipes#519]
@jakirkham @ocefpaf 
Feodor Fitsner (founder of AppVeyor) reached me, and after a short conversation, he suggested to bump CPU speed for Conda-Forge projects. He asks for an account which is used for Conda-Forge, so he can apply the changes. Is it `conda-forge`? (I will forward the information via e-mail)

**Comment by msarahan** [comment]
Nice!  Thanks for that, @frol!  I'm pretty sure conda-forge is the account, but one of the other guys, perhaps @pelson too, knows for sure.

**Comment by ocefpaf** [comment]
Thaks @frol and extend the Thanks to Feodor!

The account I log in to use AppVeyor is `conda-forge` (all lower case).

**Comment by jakirkham** [comment]
That sounds awesome. Thanks for this @frol. Thanks Feodor.

**Comment by frol** [comment]
I have forwarded the account name and the link to this thread to Feodor, so he may show up here.

Thank you all for your kind words to me, though I must admit that I have done minimal work to make this happen.

Cheers!

**Comment by frol** [comment]
> Oh, well. You guys are already running on "Pro" Hyper-V environment as "conda-forge" is on Premium FOSS plan :-/

> -Feodor Fitsner, AppVeyor

It seems that there is no more speed-up possible :(

**Comment by pelson** [comment]
> It seems that there is no more speed-up possible :(

Technically there is further parallelism that we can achieve - depends on your usecase (speeding up compile time vs speeding up total build time of feedstock)

**Comment by frol** [comment]
Here is @FeodorFitsner on GitHub.
