### ISSUE TITLE
Pull request failing with different errors on Circle-Ci and AppVeyor.

### ISSUE THREAD

**Issue by KelSolaar** [conda-forge/staged-recipes#5221]
Hi,

I have multiple errors [on my recipe pull request](https://github.com/conda-forge/colour-science-feedstock/pull/2) with Circle-Ci and AppVeyor:

-  Circle-Ci: [[Errno 13] Permission denied: '/feedstock_root/build_artefacts'](https://circleci.com/gh/conda-forge/colour-science-feedstock/9)
- AppVeyor: [The batch file cannot be found.](https://ci.appveyor.com/project/conda-forge/colour-science-feedstock/build/1.0.9/job/5t25xlvkyjm0r8sg)

The linter and travis-ci are fine though: https://travis-ci.org/conda-forge/colour-science-feedstock/builds/343709063

I'm paging @ocefpaf since he is watcher on the repository.

Any help would be welcome!

Cheers,

Thomas

**Comment by ocefpaf** [comment]
Please post the issue only in the feedstock. This is not related to staged-recipes.

**Comment by KelSolaar** [comment]
Oh sorry about that @ocefpaf, as it seemed to be infrastructure related I thought here was the good place.

Cheers,

Thomas

**Comment by ocefpaf** [comment]
No problem. But due to the noise here issues like this one are likely to be missed.

**Comment by KelSolaar** [comment]
Thanks for letting me know!
