### ISSUE TITLE
code_aster: finite element solver for structural analysis

### ISSUE THREAD

**Issue by ghost** [conda-forge/staged-recipes#5233]
[coed_aster](https://www.code-aster.org/spip.php?rubrique2) is a very powerful software, which can be manipulated through python, for structural FEA analysis. It interfaces smoothly with gmsh and paraview, which we are also trying to add to conda-forge. 

To the mantainers and owners of the repo, do you think this would be a valuable addition to conda-forge, or is the package too broad?

I would be much interested in seeing: gmsh -> code_aster -> paraview

code_saturne is the twin for CFD!

**Comment by looooo** [comment]
as it is slightly related: we are providing some cad-related packages (mainly freecad, netgen, occt, calculix)
we are definetly very interested in gmesh, as it is used in freecad too, and maybe there are more packages which could be shared.
ref:
https://github.com/FreeCAD/FreeCAD_Conda

**Comment by alen12345** [comment]
@looooo i am trying to add these packages: gmsh, code_aster, code_saturne, paraview; which are all related to structural engineering. I am building gmsh at the moment, so happy to share!

**Comment by looooo** [comment]
@alen12345  
netgen is in: https://github.com/conda-forge/netgen-feedstock
libmed is coming: https://github.com/conda-forge/staged-recipes/pull/5588 (I saw gmsh uses it too)

**Comment by carterbox** [comment]
https://github.com/conda-forge/code-aster-feedstock
