### ISSUE TITLE
using conda-build3 for PR

### ISSUE THREAD

**Issue by looooo** [conda-forge/staged-recipes#5318]
is it possible to setup a branch of staged recipes which is based on:
- conda-build=3.*
- conda-smithy=3.*

**Comment by msarahan** [comment]
I think @isuruf has been doing this at https://github.com/conda-forge/zlib-feedstock/pull/18

**Comment by looooo** [comment]
I guess this was a misunderstanding.
My idea was to have a brnach of conda-forge/staged-recipes which is setup to work with conda-smithy3 and conda-build3. No idea if that makes much sense.

**Comment by msarahan** [comment]
I think that makes a lot of sense, actually.  Thanks for proposing it.  I think again @isuruf has done the work here, and it's at https://github.com/conda-forge/staged-recipes/pull/5274

As for when people should start basing new work on that branch, I'm not completely sure.  I'm inclined to say that it should wait until we have the core foundation rebuilt.  @jakirkham did good work on that at https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/27

**Comment by jakirkham** [comment]
So I don't think we should have another branch for this. We should simply finish up the work to go to conda-build 3. If you would like to help with this work @looooo, you would certainly be welcome. As far as that goes, I think @msarahan has provided all the relevant resources to look into.

**Comment by looooo** [comment]
I don't know how much I can help you there. But I will have a look at this issue.
