### ISSUE TITLE
How long does it take before a package is included in a conda-forge feedstock until it is available in conda?

### ISSUE THREAD

**Issue by endrebak** [conda-forge/staged-recipes#5321]
This might be something to add to the faq. 

I have added r-spatest: https://github.com/conda-forge/r-spatest-feedstock, but `conda install -c conda-forge r-spatest` still does not work. Is there more action necessary on my part?

Thanks :)

**Comment by looooo** [comment]
you have to re-render the feedstock. There are some files missing.
to do so (assuming conda-forge is added to the channel section of the .condarc)
```
conda install conda-smithy
cd <recipe>
conda smithy rerender
```

**Comment by endrebak** [comment]
Thanks for your reply.

```
conda smithy rerender
Fetching package metadata .................
Fetching package metadata .................
Fetching package metadata ...................
Fetching package metadata ...................

Re-rendered with conda-smithy 2.4.5.

No changes made. This feedstock is up-to-date.
```

I guess this means that no action on my part is necessary and I should just wait for r-spatest to be made available conda? It has been two weeks since it was added. I dunno how long the average lag is?

**Comment by endrebak** [comment]
The package r-spatest is visible here: https://conda-forge.org/feedstocks/

**Comment by looooo** [comment]
https://github.com/conda-forge/r-spatest-feedstock/blob/master/recipe/meta.yaml#L19
is this the right way to skip win 32? Maybe conda-smithy is confused by this. I had a similar problem recently.

**Comment by looooo** [comment]
https://github.com/conda-forge/r-spatest-feedstock/pull/1
win32 is ok, but the comma was not.

**Comment by endrebak** [comment]
Now I have merged. Hoping this will add `r-spatest` to conda. Anyways, does this not mean that the linting does not work (did not catch the comma error)? Whom should I report this to?

**Comment by looooo** [comment]
absolutely.  Maybe not closing this issue and calling
@conda-forge/staged-recipes

**Comment by endrebak** [comment]
It worked! Thank you!

**Comment by ocefpaf** [comment]
The linting does work but there was no rule for the comma. See https://github.com/conda-forge/conda-smithy/issues/706
