### ISSUE TITLE
Automating boiler plate

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#535]
There is quite a bit of boiler plate that goes into recipes. It is a pain making sure it is right for bother reviewers and reviewees (?). We should move towards automating this by using all means at our disposal (e.g. jinja, scripts, metapackages, etc.). The hope is that most of this (if not all) of this could be removed. What I would like us to do here is figure out what and how. One step in this direction would be taking a hard look at this [script](https://gist.github.com/183amir/0e868e045dde66d671f16870f6cf184f) by @183amir, which converts PyPI packages into conformant recipes.

cc @msarahan @ocefpaf @pelson

**Comment by 183amir** [comment]
@jakirkham I don't have an automation script that converts pypi packages into conformant recipes.
I have some codes lying around that would ease these process though.

**Comment by jakirkham** [comment]
Ah, automation was a poor choice of word there. I will correct it. I just meant you can point it to a PyPI package and generate a conformant recipe here.

**Comment by 183amir** [comment]
I think `conda skeleton` is already doing a good job on that and we can apply several checks and modifications to its output so that it meets conda-forge standards.

**Comment by 183amir** [comment]
Also, a while ago I opened an issue here: https://github.com/conda-forge/conda-smithy/issues/149 to discuss common functionality to manage feedstocks.

**Comment by jakirkham** [comment]
> Also, a while ago I opened an issue here: https://github.com/conda-forge/conda-smithy/issues/149 to discuss common functionality to manage feedstocks.

Yeah, @pelson has been out, but I think he is back soon (today or tomorrow).

**Comment by jakirkham** [comment]
> I think `conda skeleton` is already doing a good job on that and we can apply several checks and modifications to its output so that it meets conda-forge standards.

I also agree with that as an option.

**Comment by jakirkham** [comment]
Another option might be the little known jinja templates like this [one for setuptools]( https://github.com/conda/conda-build/blob/7933152502f4ccc6077326a9dcb422754f13baba/conda_build/templates/setuptools.yaml ).

**Comment by jakirkham** [comment]
So was able to cobble something together yesterday using the aforementioned template with some tweaks @msarahan's PR that will generate a recipe from a source directory. See this [comment]( https://github.com/conda/conda-build/pull/908#issuecomment-216679510 ) for details. It would be better still if we had a `use_pypi` function in `conda-build` that acts like `use_setuptools` this combined with @msarahan's work could create a more general `conda skeleton pypi` that we could customize the end result for.

**Comment by msarahan** [comment]
Thanks for working on this.  It will definitely help.  I think we also
really need to address automated cleanup of recipes, though, because a lot
of what we do is just pulling in existing recipes.

**Comment by jakirkham** [comment]
Yeah, that is true. We need `conda smithy rerender-lint` or similar.

**Comment by jakirkham** [comment]
Also take a look at this issue ( https://github.com/conda/conda-build/issues/914 ). I think we could clean up `conda-build` a bit to use what you wrote and get recipe generation as a benefit into a custom template as a benefit.

**Comment by jakirkham** [comment]
More boiler plate that needs to live somewhere is [CI parallelism]( https://github.com/conda-forge/staged-recipes/pull/531/files/8d97b7ba1b38350dee5af0f89571002f3418715b#r62072250 ).

**Comment by 183amir** [comment]
off topic question. Do we have a place that explains our recipe guidelines? Things that our linter doesn't catch.

**Comment by jakirkham** [comment]
We have this issue ( https://github.com/conda-forge/staged-recipes/issues/139 ), which is sort of a grab bag of everything. We are working on making it official guidelines in this PR ( https://github.com/conda-forge/conda-forge.github.io/pull/95 ). Might be somewhere to pull things from or adding thing too. The document was more a rally of the troops type document to encourage the large scale addition of things from common Continuum repos to conda-forge. Though there is some stuff about style and workflows too. If you would like to take a look and provide feedback, please do. A fresh set of eyes would be nice.

**Comment by jakirkham** [comment]
Is there a good way to have some environment variables set when a package is installed or the environment is activated? I'm thinking of writing a meta compiler package so we can avoid some cruft in our recipes.

**Comment by scopatz** [comment]
I was also looking into this today and it doesn't seem like there is :(

**Comment by jakirkham** [comment]
Yeah, I didn't think so either, but maybe there is something that is undocumented.

**Comment by msarahan** [comment]
package installed: post-link scripts
http://conda.pydata.org/docs/building/build-scripts.html
env activated: "saved env vars"
http://conda.pydata.org/docs/using/envs.html#saved-environment-variables

**Comment by jakirkham** [comment]
Are those actually sourced though?

**Comment by jakirkham** [comment]
Ah, sorry, I see now. Thanks. I didn't know about that.

**Comment by msarahan** [comment]
be very careful with both of them.  Conda has very little (read: None) error handling for these.  We have had major problems when they don't work, for example, because packages aren't installed in the order you expect (topological/dependency sort vs. alphabetical).  People talk about them practically as expletives.  Still, if you need to do things at install time or at activation time, they are good tools.

**Comment by jakirkham** [comment]
The main point here is to configure clang so we aren't doing the copy-pasta dance everytime someone wants C++11 support.

**Comment by jakirkham** [comment]
post-link scripts don't get sourced though, right?

**Comment by msarahan** [comment]
No, they are run, but not sourced.  This kind of stinks for the build application, because the build environment isn't truly activated.

We could change, that, though.  I think doing so would be a nice consistency improvement.

**Comment by jakirkham** [comment]
Well, I know this still won't work right without some changes, but maybe you can take a look at what I got and we can discuss the appropriate changes upstream.

**Comment by jakirkham** [comment]
Here is a PR ( https://github.com/conda-forge/staged-recipes/pull/578 ) with the recipe. FWIW, this will work if the environment is re-activated after install. I have tried this with a real build yet. Though some tests are in order.

**Comment by jakirkham** [comment]
Much of the discussion here is stale. `conda skeleton` and conda-forge have converged a bit on best practices as well. Automated updated PRs have lightened maintenance burden a bit. There is still more room for work, but this issue IMHO can be closed. So will close it. Feel free to reopen if you see something that still needs to be done.
