### ISSUE TITLE
Versioned libraries and pinning

### ISSUE THREAD

**Issue by giacomov** [conda-forge/staged-recipes#5355]
This might be a beginner's question, but I couldn't find any documentation on this problem, although I saw issues open about this (like #475).

When I build a C++ package, it links to whatever version of a library gets pulled by `conda build`, unless I pin to a version (of course). So let's say it links my products to `libCLHEP.so.2.2.0.8`.

If a user downloads the package and gets a newer version, then the link breaks. 

Of course, I can fix this by pinning to a specific library version in my `meta.yaml` file, but this is overly restrictive. In fact, my software can work with say any CLHEP >= 2.2. But adding that to `meta.yaml` will not work because the links happens with the versioned library.

I looked for some kind of flags for the linker so that it links against `libCLHEP.so` instead of `libCLHEP.so.2.2.0.8` but couldn't find one...

how can I solve this problem?

**Comment by jakirkham** [comment]
We track pinnings at a [global level]( https://github.com/conda-forge/conda-forge-pinning-feedstock ). Here is a [full list]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml ) of everything pinned. If you think a package needs to be pinned and is not or would like to recommend a pinning, please raise over at that feedstock. Thanks.

**Comment by giacomov** [comment]
Thanks for your answer, but I do not understand how that answers my question.

I know about those pinnings, but unless we want to put in the global pinnings every single package with dynamic libraries that is ever going to be part of conda-forge, I don't see how that solves the problem I mentioned... Can you be more specific, or point me to some documentation about this problem?

**Comment by jakirkham** [comment]
As noted before, this isn't the right place to discuss this. Please move the discussion over to the previously noted feedstock. Thanks.
