### ISSUE TITLE
build broken

### ISSUE THREAD

**Issue by dougalsutherland** [conda-forge/staged-recipes#5373]
Travis builds have been failing for the past bunch of builds; [example](https://travis-ci.org/conda-forge/staged-recipes/jobs/351972608#L825).

Seems like `genesis-pyapi-feedstock` ([exists but is empty](https://github.com/conda-forge/genesis-pyapi-feedstock)), and something about [the build logic in that case](https://github.com/conda-forge/staged-recipes/blob/master/.travis_scripts/create_feedstocks.py#L145) is not working.

CC @conda-forge/core

**Comment by jakirkham** [comment]
All clear now. Thanks @dougalsutherland. :)
