### ISSUE TITLE
Add vmd-python

### ISSUE THREAD

**Issue by Eigenstate** [conda-forge/staged-recipes#5452]
Hi,

Can someone take a look at my recipe I added last week? It's been passing all the checks for a while.
#5282 

vmd-python is Visual Molecular Dynamics built as a Python C extension. It's used for loading and analyzing molecular dynamics simulations in a variety of file formats.
My main motivation for putting vmd-python in conda-forge is simplifying installation of this library as it is now a dependency for other software that we wish to distribute, and it's complicated for the average user to build (especially on OSX + homebrew setups).

Thanks!

**Comment by dougalsutherland** [comment]
#5282 merged.
