### ISSUE TITLE
update or remove asteval package

### ISSUE THREAD

**Issue by newville** [conda-forge/staged-recipes#5453]
The feedstock for the asteval package is about a year out of date.  I made a  PR to update it to the latest version (0.9.12), but it is incorrectly failing the Appveyor CI tests:  https://github.com/conda-forge/asteval-feedstock/pull/6

To be clear, asteval is a pure python package that depends on `six`, `numpy`, and `setuptools`.  It definitely passes all tests for Py27, Py35, and Py36.   For the PR today, I re-rendered the recipe with the latest conda-smithy. Tests pass everywhere except Appveyor CI, which gives an error message of

    'conda.exe' is not recognized as an internal or external command, operable program or batch file. 
    Command exited with code 1

The appveyor recipe is the standard conda-forge recipe from "conda smithy".    It definitely specifies this `conda.exe` command that cannot be found.  I don't understand how this error could possibly  be related to the package being tested.   The CI is broken, not the package.

Please either fix the conda tools so that appveyor works, or remove appveyor from the required standard integration tools -- it is definitely not working correctly.   If fixing this is not possible, please remove the out-of-date asteval from conda-forge package.

**Comment by CJ-Wright** [comment]
That PR was merged, closing.
