### ISSUE TITLE
Add pre-commit to conda-forge

### ISSUE THREAD

**Issue by sodre** [conda-forge/staged-recipes#5454]
https://pre-commit.com

I am mostly keeping track of the package request.

**Comment by justcalamari** [comment]
I'm testing that pinging @conda-forge/staged-recipes works

**Comment by CJ-Wright** [comment]
@jtratner could you try pinging staged here?

**Comment by asottile** [comment]
I don't know anything about conda, but is this what you're looking for? https://github.com/conda-forge/pre_commit-feedstock CC @nicoddemus

**Comment by sodre** [comment]
Yes! Thank you!
