### ISSUE TITLE
Package helm

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#5463]
Would be nice to have a package for [`helm`]( https://helm.sh/ ). A package manager for Kubernetes.

**Comment by jakirkham** [comment]
Maybe of interest @sodre. ;)

**Comment by sodre** [comment]
I like it! can you assign it to me. That way I won't lose track of it

**Comment by jakirkham** [comment]
Thought you might. :) Sure, assigned.

**Comment by sodre** [comment]
I started the packaging of helm, but right away I ran into an issue. In order to build from source we need to have "hg" in conda-forge. 

Until that is added, would it be sufficient to bundle just the binaries?

**Comment by sodre** [comment]
ignore this previous post. I was looking for "hg" instead of mercurial. I will get back to packaging it soon.
