### ISSUE TITLE
Package asciidoc

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#5484]
Would be great to have a package for [`asciidoc`]( http://asciidoc.org/ ). Useful as some packages build docs with `asciidoc`.

**Comment by carlodri** [comment]
@jakirkham I can give it a try, assign it to me. I might need help on the way, as usual...

**Comment by jakirkham** [comment]
Thanks @carlodri. Have added you. Please feel free to ask for help. :)

**Comment by carlodri** [comment]
@jakirkham I'm having a look at the package: it seems like it is almost R.I.P., and only py2k is working.

it looks like the "modern" way to go is [`asciidoctor`](https://asciidoctor.org/). Should we rather move in that direction?

**Comment by jakirkham** [comment]
It looks like it is [still alive]( https://github.com/asciidoc/asciidoc/graphs/contributors ). 😕

As to the Python 2 point, the same is true of Mercurial, but it remains widely used. So it's not a barrier, but yes the project should be encouraged to look at Python 3 support given Python 2's EOL in 2 years.

That said, am not opposed to having other tools that provide equivalent functionality.

**Comment by carlodri** [comment]
@jakirkham when you wish, the recipe should be ready (at least for review)

**Comment by carlodri** [comment]
package ready: https://github.com/conda-forge/asciidoc-feedstock

this issue can be closed.

**Comment by jakirkham** [comment]
Thanks again, @carlodri. :)
