### ISSUE TITLE
Out of the box cookiecutter recipe not accepted. 

### ISSUE THREAD

**Issue by rutgerhofste** [conda-forge/staged-recipes#5625]
I used [Cookiecutter](https://github.com/audreyr/cookiecutter) for my boilerplate pythonpackage code and pushed the package to [Pypi](https://pypi.org/project/aqueduct3/). Next I used [Conda Skeleton](https://conda.io/docs/user-guide/tutorials/build-pkgs-skeleton.html) to create a [recipe](https://github.com/rutgerhofste/aqueduct3/blob/master/conda/aqueduct3/meta.yaml). 

However when I make a pull request using this recipe I get the following [errors](https://github.com/conda-forge/staged-recipes/pull/5624).   

Is there a reason why "out of the box" cookiecutter plus conda skeleton doesn't work? The step-by-step instructions in the tutorial start by copying the meta.yaml file from the examples folder however there is no section with "I already have a conda recipe generated by conda skeleton, how do I make it suitable for conda-forge"

[Github](https://github.com/rutgerhofste/aqueduct3)

**Comment by jakirkham** [comment]
Thanks for raising.

Short answer is we recommend users start with the [`example` recipe]( https://github.com/conda-forge/staged-recipes/blob/ca1db5f80ffee72d43a0efc960746f15f026601b/recipes/example/meta.yaml ). This is tailored towards `conda-forge`'s needs with detailed comments explaining what each part does and how to change it as  needed.

The more general questions raised here are basically covered in issue ( https://github.com/conda-forge/conda-forge.github.io/issues/565 ). So will close this out. Though feel free to add anything we missed in that issue. Thanks.
