### ISSUE TITLE
Appveyor failing on non-windows packages

### ISSUE THREAD

**Issue by ChristopherHogan** [conda-forge/staged-recipes#5646]
PRs with 
```
build:
  skip: true  # [win]
```
are failing on Appveyor with
```
Traceback (most recent call last):
189  File ".ci_support\build_all.py", line 80, in <module>
190    build_all(args.recipes_dir, args.arch)
191  File ".ci_support\build_all.py", line 70, in build_all
192    conda_build.api.build(list(d.keys()), config=config)
193  File "C:\Miniconda36-x64\lib\site-packages\conda_build\api.py", line 197, in build
194    raise ValueError('No valid recipes found for input: {}'.format(recipe_paths_or_metadata))
195ValueError: No valid recipes found for input: []
196
```
See #5639, #5643, and #5644.

**Comment by carlodri** [comment]
I think you have to skip it manually with the `[skip appveyor]` tag trailing the commit message. See for instance the last commits in this PR: https://github.com/conda-forge/staged-recipes/pull/5487

**Comment by jdblischak** [comment]
Thanks for collating all these PRs, @ChristopherHogan. It was useful to know that my PR wasn't the only one.

> I think you have to skip it manually with the [skip appveyor] tag trailing the commit message.

@carlodri Do you know when this requirement was added? In the past, I've submitted recipes which skip Windows without skipping the AppVeyor build. If this is a new requirement, we should make note of this in the docs:

https://conda-forge.org/docs/meta.html#excluding-a-platform

**Comment by carlodri** [comment]
@jdblischak actually, this is explicitly stated [here](https://github.com/conda-forge/staged-recipes#3-how-do-i-exclude-a-platform), although not in the link you mention.

To be honest, I also have a far memory of a time where Appveyor was automatically skipped when excluding `[win]`, but I'm definitely not sure.

**Comment by carlodri** [comment]
`win32` support will terminate in the very near future

**Comment by nsoranzo** [comment]
@carlodri I'm aware, but that doesn't help until it's actually removed from AppVeyor.

**Comment by carlodri** [comment]
yes, it doesn't help, sorry! I just thought you didn't know about the EOL.

**Comment by jdblischak** [comment]
> actually, this is explicitly stated here, although not in the link you mention.

@carlodri That line about skipping Appveyor was added [8 months ago](https://github.com/conda-forge/staged-recipes/commit/86b902319783ebc886c7005f019ab2c62560326c) and doesn't mention anything about the jobs failing:

> Additionally, when pushing commits for a recipe that excludes Windows, put `[skip appveyor]` in the commit message to prevent CI tests on Windows from even starting.

Here's an example PR from 2 months ago (#5172)  that was skipped on Windows without skipping the Appveyor builds. The builds run fine and end once it is determined that there are no recipes to build:

https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.21402/job/pqjmsbillql2edxq#L166

So I think this is a recent change in behavior, at least in the last 2 months.
