### ISSUE TITLE
Remove toolchain from example

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/staged-recipes#5683]
The example has a discussion of using toolchain if the code compiles c/c++. Should most likely remove that and replace that with something about `{{ compiler('c') }}`?

**Comment by msarahan** [comment]
until we have the lower-level infrastructure built with the new compilers, should hold off.  Ideally, all of a given new recipe's deps should be built with the new compilers before making that switch.

Alternatively, you could make this change, but make a compiler package that is essentially only toolchain for now.  We could swap that out at some later time for the new compilers, but the recipe wouldn't require any changes; only a re-render and rebuild.

**Comment by CJ-Wright** [comment]
Hmm, I like option 2 (since it prevents us from having to do more recipe edits down the line), but I don't know if the packages or the maintainers would appreciate the compiler moving underneath their feet.

**Comment by msarahan** [comment]
sure, that's probably fine.  If the lower nodes in the graph are rebuilt with the new compilers, the leaves may need to be rebuilt to properly use the new lower nodes, but the leaves built against old stuff also should not break when the newer upstreams are put in.  Hopefully, anyway...

**Comment by isuruf** [comment]
> So why wouldn't be ok to just recommend the new compilers at staged-recipes outright? Typically these are things that nothing in conda-forge depend on. So using the new compilers on new packages here won't mess up dependency chains as these would be leafs. In the rare case where we are packaging something lower level, careful review by reviewers will be needed.

One reason is that mixing C++ runtimes won't work. gcc 4.x ABI and gcc 5+ ABI are incompatible. For eg: if you want to pass a `std::string` from the new package to a library built with gcc 4.x, it will give linking errors. For C, it shouldn't matter much.

**Comment by jakirkham** [comment]
So this is an honest question as I don't do lots of `staged-recipes` reviewing these days. Are there that many C++ packages getting added these days that are exposing a C++ ABI to other libraries/applications or is it mostly things like Python and R packages that merely bind to lower level libraries already in our stack?

**Comment by jakirkham** [comment]
Given the recent changes to how we deal with `compiler` in `conda-forge`, this seems like a safe thing to do.

**Comment by isuruf** [comment]
Toolchain is changed to compiler now.
