### ISSUE TITLE
Package snakeviz

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#5713]
Would be nice to have a PyPI package for [`snakeviz`]( https://pypi.org/project/snakeviz/ ). A web application for viewing Python profiling information in the browser.

**Comment by gforsyth** [comment]
Created https://github.com/conda-forge/snakeviz-feedstock today, so this can be closed out

**Comment by cbrueffer** [comment]
Added in https://github.com/conda-forge/staged-recipes/pull/8039
