### ISSUE TITLE
How to determine which versions of R a package builds for?

### ISSUE THREAD

**Issue by CurtLH** [conda-forge/staged-recipes#5745]
It seems that some R packages are built for 3.3.2 and 3.4.1, where other R packages build for just one version or the other.  However, when constructing the `recipe/meta.yaml`, there isn't a section to select which version of R that the package should be build for in the same way as with a Python package.

How are the versions that an R package builds for determined?

**Comment by jakirkham** [comment]
Would move this to the webpage repo, @CurtLH. This repo is pretty noisy. So this question is likely to get lost here.

**Comment by CurtLH** [comment]
Thanks for the suggestion.  I moved my question to [conda-forge.github.io issues](https://github.com/conda-forge/conda-forge.github.io/issues/580).
