### ISSUE TITLE
Missing `license_file` possibly being ignored?

### ISSUE THREAD

**Issue by synapticarbors** [conda-forge/staged-recipes#5749]
I've noted in two recent recipes where the `license_file` is manually packaged, but the syntax in:

https://conda-forge.org/docs/meta.html#packaging-the-license-manually

is not used (just the file name appears and that file is not in the source distribution), that no errors are being emitted during the build process. 

This seems like it might be an error, although possibly at the conda level. I can elevate this issue to the conda folks once others chime in can say that it's not a problem at the conda-forge level.

see:
https://github.com/conda-forge/staged-recipes/pull/5740
https://github.com/conda-forge/staged-recipes/pull/5742

cc @conda-forge/staged-recipes

**Comment by isuruf** [comment]
New feature. See 4th bullet point in bug fixes, https://github.com/conda/conda-build/releases/tag/3.8.0

**Comment by jakirkham** [comment]
Thanks @synapticarbors and @isuruf.

*sigh*, I can see why that was done, but it makes it that much harder to diagnose what is happening at review time.
