### ISSUE TITLE
Package pigar

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#5773]
Would be great to have a `conda` package for [`pigar`]( https://pypi.org/project/pigar/ ). A neat little tool for generating (rough) requirements based on `import`s in a codebase.

**Comment by marcelotrevisani** [comment]
I will try to create a recipe for that

Just one more thing, the build in conda-forge/staged-recipes is failing since the commit c1427fb
Do you know what's happening ?

**Comment by jakirkham** [comment]
No worries. Got it covered with PR ( https://github.com/conda-forge/staged-recipes/pull/5774 ). Always happy to have another reviewer and/or maintainer though. 😉

Think that was fixed with PR ( https://github.com/conda/conda-build/pull/2856 ), which will be available once PR ( https://github.com/conda-forge/conda-build-feedstock/pull/48 ) is merged. Does this sound right @msarahan?
