### ISSUE TITLE
Package LAMMPS

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/staged-recipes#5784]
@conda-forge/pyiron any interest in putting in a LAMMPS recipe?

**Comment by jan-janssen** [comment]
@CJ-Wright we have a LAMMPS recipe at https://github.com/pyiron/lammps but I never managed to build it on Windows.

**Comment by CJ-Wright** [comment]
Hmm ok, you could skip the windows build on conda-forge.

**Comment by jan-janssen** [comment]
@CJ-Wright I give it a shot on the weekend, but maybe you can tell me how to hash a specific tag from a git repository, so it is compatible to the conda forge build process. I know how to do it for static downloads, but is it also possible for git checkouts? Like in https://stackoverflow.com/questions/22546878/possible-to-do-conda-build-from-github-branch

**Comment by CJ-Wright** [comment]
Can you use the tarball from github? https://github.com/lammps/lammps/releases

**Comment by jan-janssen** [comment]
@CJ-Wright I could not resist ;-)

**Comment by jan-janssen** [comment]
The recipe https://github.com/conda-forge/staged-recipes/pull/5790 passed the tests and can be merged. Still I am not sure if conda-forge is the right place for these codes. For example we have quite a few C, C++ or Fortran codes which we use as part of our research and which we interface in http://pyiron.org but for now we host them on our own conda channel:

- https://github.com/pyiron/atat
- https://github.com/pyiron/ovito
- https://github.com/pyiron/atomsk
- https://github.com/pyiron/randspg

All these tools are useful for atomistic simulation with a particular focus on solid states. After migrating lammps the rest should be simple.

**Comment by CJ-Wright** [comment]
We'd be more than happy to have the other projects, too! Conda has a specialist in working with C, C++ and Fortran codes.

**Comment by jan-janssen** [comment]
@CJ-Wright I guess we can close this issue now as Lammps is merged https://github.com/conda-forge/staged-recipes/pull/5790 - I am going to create the pull requests for the other packages in the upcoming weeks, now that I know how to structure them.

**Comment by CJ-Wright** [comment]
Great! Thank you very much!
