### ISSUE TITLE
Package SNAP for Python

### ISSUE THREAD

**Issue by CurtLH** [conda-forge/staged-recipes#5849]
According to http://snap.stanford.edu/snappy/index.html:

> Snap.py is a Python interface for SNAP. SNAP is a general purpose, high performance system for analysis and manipulation of large networks. SNAP is written in C++ and optimized for maximum performance and compact graph representation. It easily scales to massive networks with hundreds of millions of nodes, and billions of edges.
> 
> Snap.py provides performance benefits of SNAP, combined with flexibility of Python. Most of the SNAP functionality is available via Snap.py in Python. 

Here is the GitHub repo for [snap-python](https://github.com/snap-stanford/snap-python) and [snap](https://github.com/snap-stanford/snap).  However, I'm not sure on the proper way to bundle C++ code within the recipe.

**Comment by sodre** [comment]
Hi @curtlh, I packaged igraph which has a similar structure. You can use that as a starting point.

I'm happy to help get snap merged.
