### ISSUE TITLE
Package libharu

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#5855]
Would be great to have a package of [libharu]( https://github.com/libharu/libharu ), "a free, cross platform, open-sourced software library for generating PDF".

**Comment by xylar** [comment]
Can be closed now.

**Comment by xhochy** [comment]
Fixed by https://github.com/conda-forge/staged-recipes/pull/11129

**Comment by jakirkham** [comment]
Thank you all 😄
