### ISSUE TITLE
package jekyll

### ISSUE THREAD

**Issue by bgruening** [conda-forge/staged-recipes#5978]
Would be great to package https://github.com/jekyll/jekyll, a simple, blog-aware, static site generator perfect for personal, project, or organization sites.

**Comment by jakirkham** [comment]
Agreed. This would be a great addition. :)

**Comment by phil-blain** [comment]
Just to document, these are the steps that I needed as of June 2019 to install jekyll inside a conda environment under Ubuntu 14.04 using the conda-forge ruby : 
```shell
$ conda config --get channels
--add channels 'defaults'   # lowest priority
--add channels 'conda-forge'   # highest priority
$ conda config --get channel_priority
--set channel_priority strict
$ conda create -n ruby
$ conda activate ruby
$ conda install ruby 
# compilers are needed for building gem native extensions
$ conda install gcc_linux-64 gxx_linux-64  
# the path to the compilers are hard coded to the build environment of conda-forge
#  (/home/conda/.../) so we need to fix them
$ cd $(gem environment gemdir)
$ cd ../../$(basename $PWD)/$(gem environment platform | sed -e 's/.*://')
$ mv rbconfig.rb rbconfig.rb.bu
$ perl -pe 's/\/\S*?\/_build_env\/bin\///g' rbconfig.rb.bu > rbconfig.rb 
$ gem install bundler jekyll
```

**Comment by jakirkham** [comment]
> ```bash
> ...
> # the path to the compilers are hard coded to the build environment of conda-forge
> #  (/home/conda/.../) so we need to fix them
> $ cd $(gem environment gemdir)
> $ cd ../../$(basename $PWD)/$(gem environment platform | sed -e 's/.*://')
> $ mv rbconfig.rb rbconfig.rb.bu
> $ perl -pe 's/\/\S*?\/_build_env\/bin\///g' rbconfig.rb.bu > rbconfig.rb 
> ...
> ```

Maybe this patch should be applied to the `ruby` package. Thoughts @conda-forge/ruby?

**Comment by scopatz** [comment]
Yeah, I think we need that in the ruby package

**Comment by jakirkham** [comment]
Thanks @sodre ! 😀
