### ISSUE TITLE
Packaging NumPy's allocation_tracking tools

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#6062]
Within NumPy's source tree, there is an [allocation_tracking]( https://github.com/numpy/numpy/tree/master/tools/allocation_tracking ) tool, which would be useful to package. How should we go about doing this?

**Comment by mariusvniekerk** [comment]
Should we do this in the numpy feedstock as an additional output?

**Comment by jakirkham** [comment]
That sounds reasonable to me. Thoughts @conda-forge/numpy?

**Comment by rgommers** [comment]
Let's wait for the outcome of https://github.com/numpy/numpy/pull/11315

**Comment by jakirkham** [comment]
As NumPy has support for tracemalloc (usable with Python 3.6+) and that is already the minimum Python version supported in conda-forge, this seems sufficient for tracking memory allocations.
