### ISSUE TITLE
Package HMMER

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#6341]
Would be great to have a package for [`HMMER`]( http://hmmer.org/ ).

**Comment by bgruening** [comment]
https://bioconda.github.io/recipes/hmmer/README.html

**Comment by jakirkham** [comment]
Cool. Happy for it to stay in bioconda if that is best. Didn't actually know it was there.

**Comment by jakirkham** [comment]
Should probably add that part of the reason I was thinking about this is they had mentioned PowerPC builds were hard to achieve. This is something conda-forge plans on adding soon. ( https://github.com/conda-forge/conda-smithy/pull/763 ) Would PowerPC support be in scope for bioconda as well? If so, we can move this discussion to an issue over to bioconda.
