### ISSUE TITLE
Package QCachegrind

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#6379]
Would be great to have a package for [`qcachegrind`]( https://github.com/KDE/kcachegrind ) (included in `kcachegrind`) for viewing profiling results from `valgrind`.

**Comment by xhochy** [comment]
Defaults has a recipe for it: https://github.com/AnacondaRecipes/aggregate/tree/master/qcachegrind-feedstock

**Comment by timkpaine** [comment]
@isuruf can close, thanks!
