### ISSUE TITLE
Build order for NSLS-II software stack

### ISSUE THREAD

**Issue by ericdill** [conda-forge/staged-recipes#641]
https://github.com/NSLS-II/auto-build-tagged-recipes/blob/master/dependencies.ipynb, cell [186] is the actual build order.

This is the build order for the NSLS-II software stack as defined by `networkx.topological_sort()`.  I suppose I'll just start at the top and work my way down!  

Build Order
- [x] mongoquery #816 
- [x] slacker #815
- [x] tinydb #814 
- [x] xraylib #597
- [x] scikit-beam #595
- [x] ncurses  # Package already on conda-forge
- [x] readline  # Package already on conda-forge
- [ ] epics-base #640 
- [ ] pcaspy
- [x] xray-vision #687
- [ ] pyepics
- [x] hdf5  # Package already on conda-forge
- [x] slicerator #665 
- [x] pims
- [x] atom
- [x] tzlocal
- [x] channelarchiver
- [x] doct  #612 
- [x] boltons #560
- [x] pymongo
- [x] h5py  # Package already on conda-forge
- [x] tifffile  # Package already on conda-forge
- [ ] filestore
- [ ] metadatastore
- [ ] databroker
- [ ] csxtools
- [x] m4  # Package already on conda-forge
- [x] autoconf  # Package already on conda-forge
- [x] automake  # Package already on conda-forge
- [x] libtool  # Package already on conda-forge
- [x] pkg-config  # Package already on conda-forge
- [x] gettext  # Package already on conda-forge
- [x] glib  # Package already on conda-forge
- [ ] cairo-gobject
- [ ] gobject-introspection
- [ ] py3cairo
- [ ] pygobject3
- [x] prettytable
- [ ] ophyd
- [ ] eiger-io
- [x] fabio
- [ ] hdf5-lz4 #669
- [ ] hgtools
- [x] keyring #664
- [x] yasm  # Package already on conda-forge
- [x] x264  # Package already on conda-forge
- [x] ffmpeg  # Package already on conda-forge
- [x] event-model #663
- [ ] trackpy
- [x] kiwisolver
- [ ] enaml
- [ ] pyxrf
- [ ] super_state_machine
- [x] historydict #662
- [ ] bluesky
- [x] args #659 (thanks @janschulz !)
- [ ] characteristic
- [x] gsl  # Package already on conda-forge
- [ ] hkl
- [ ] album
- [ ] suitcase
- [ ] chxtools
- [x] git  # Package already on conda-forge
- [ ] pyasn1-modules
- [ ] service_identity
- [ ] datamuxer
- [x] emcee #639 
- [x] lmfit #639 
- [ ] analysis
- [ ] pyolog
- [ ] collection
- [x] clint #659 (thanks @janschulz !)
- [ ] ixstools

Two questions:
1. A non-trivial portion of this list is basically linux-only.  Is that ok? 
2. Are there any recipes in this list that I should _not_ add?

cc @tacaswell @heroux

edit: I'm also sort of using this as a personal notepad, I hope that's ok!

**Comment by janschulz** [comment]
bolton: https://github.com/conda-forge/staged-recipes/pull/560

**Comment by janschulz** [comment]
@ericdill Do you want to become comaintainer for clint and args? I am basically only packaging it because of twine and I fear that I won't see any upstream problems/...

**Comment by ericdill** [comment]
@janschulz That seems sensible.  Could you also add @licode and @tacaswell (coworkers who graciously volunteered to occasionally do package maintenance duties for our stack)

**Comment by janschulz** [comment]
@ericdill done

**Comment by licode** [comment]
Please also add tomopy. https://github.com/tomopy/tomopy

**Comment by CJ-Wright** [comment]
Can I get pyFAI packaged?

**Comment by ericdill** [comment]
@danielballan @tacaswell @licode Do you want this issue left open?

**Comment by ericdill** [comment]
There's also a better place to see the current dependencies for the NSLS-II stack at https://github.com/NSLS-II/lightsource2-recipes/blob/master/notebooks/dependencies.ipynb (Specifically the heading "List the build order for a serial build (i.e., one build at a time)" which I am unable to link directly to for some unknown reason)

**Comment by danielballan** [comment]
Yeah, let's keep this open as long as conda-forge doesn't mind.

**Comment by licode** [comment]
prettytable already exists in conda-forge, so we can remove that item from the list.

**Comment by jakirkham** [comment]
Done. :smile:

**Comment by jakirkham** [comment]
There were a few others that had been done too. So I went ahead and checked those off.

**Comment by licode** [comment]
thanks a lot.

**Comment by licode** [comment]
channelarchiver is included. https://github.com/conda-forge/staged-recipes/pull/1088

**Comment by jakirkham** [comment]
Yep, I checked the box, @licode. 😄

**Comment by ericdill** [comment]
no action in almost a year so I'll closet his
