### ISSUE TITLE
Package file

### ISSUE THREAD

**Issue by tseemann** [conda-forge/staged-recipes#6412]
The Unix `file` command is standard on Linux and MacOS however it is not in the `busybox` image used for testing in Bioconda, so any projects that depend on it can not be properly tested.

Code is here: http://darwinsys.com/file/

CC: @slugger70 @bgruening

**Comment by mrakitin** [comment]
This looks interesting to me to work within a Python Packaging Sprint in NYC happening tonight (10/03/2019).
