### ISSUE TITLE
Package pyrobuf

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#6423]
Would be good to have a package of [`pyrobuf`]( https://pypi.org/project/pyrobuf/ ), a fast Cython implementation of Google's Protobuf.

**Comment by hmaarrfk** [comment]
I keep getting stuck at `-fno-plt` any idea?

**Comment by hmaarrfk** [comment]
I have a feeling this will be fixed with: https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/10
