### ISSUE TITLE
travis build for ubuntu?

### ISSUE THREAD

**Issue by zhaofeng-shu33** [conda-forge/staged-recipes#6549]
In `.travis.yml` it has `ubuntu` configuration :
    os: linux
However, in `build_all` script, it downloads miniconda suitable for `mac`.
    curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh

It cannot pass the build for linux, error is:
    /home/travis/miniconda.sh: line 324: md5: command not found

I suggest ` os: linux` should be removed from `.travis.yml`.

**Comment by jakirkham** [comment]
This is intentional. We use macOS to build in PRs and Linux when we do conversions of packages. There are some historical reasons for this that are not particularly interesting.

Without more context I can't advise on the `md5` point. My guess is the script should be `openssl md5 ...`.

**Comment by jakirkham** [comment]
Closing as this appears to be answered. Please feel free to raise additional questions though.
