### ISSUE TITLE
FYI GitHub service issues

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#660]
More [info]( https://status.github.com/messages ).

cc @ocefpaf

**Comment by jakirkham** [comment]
Sorry, @jschueller, your addition is in limbo because of this ( https://github.com/conda-forge/staged-recipes/pull/579 ).

**Comment by jschueller** [comment]
they are back to normal, will the script recover ?

**Comment by jakirkham** [comment]
Yep and then it changed in the last 5 minutes to delays.

**Comment by jakirkham** [comment]
If this gives you any relief, @jschueller, it appears to have triggered on [Travis CI]( https://travis-ci.org/conda-forge/staged-recipes/builds/132322056 ). Will have to see how this affects automation on that end.

**Comment by jakirkham** [comment]
Yeah, I have had connectivity issues where I am too so I thought maybe it was time to mess with some things. Wrong decision. 😳

**Comment by jakirkham** [comment]
Appears to be stable for almost the last hour. Think it is probably resolved. Closing...
