### ISSUE TITLE
New submitters can't "ping @conda-forge/staged-recipes"

### ISSUE THREAD

**Issue by guyer** [conda-forge/staged-recipes#6644]
According to [the README](https://github.com/conda-forge/staged-recipes/blob/master/README.md#12-my-pull-request-passes-all-checks-but-hasnt-received-any-attention--how-do-i-call-attention-to-my-pr--what-is-the-customary-amount-of-time-to-wait), "If your PR is passing all checks, but has not been acted on by the staged recipes maintainers for 1 week, you can ping `@conda-forge/staged-recipes` to request action.", but non-members of the`conda-forge` organization can't @mention `@conda-forge/staged-recipes` and new submitters aren't invited to join `conda-forge` until after their feedstock has been accepted.

**Comment by jakirkham** [comment]
This has come up before. Unfortunately there is not too much we can do about it *directly* given GitHub's permission model. There may be ways we can improve things indirectly (e.g. a bot does the pinging, other helpful individuals in the org ping, etc.). This has largely been discussed before, but I can't find the issue ATM. Maybe someone else can. cc @conda-forge/core

**Comment by CJ-Wright** [comment]
There was some discussion on my PR discussing the help teams https://github.com/conda-forge/staged-recipes/pull/5456

**Comment by jakirkham** [comment]
Maybe we could allow users to request to join `all-members` somehow.

**Comment by chrisburr** [comment]
Could we automatically add anyone who authors a PR?

**Comment by jakirkham** [comment]
Possibly. Would they understand what is happening and why?

**Comment by chrisburr** [comment]
The [pull request template](https://raw.githubusercontent.com/conda-forge/staged-recipes/master/.github/pull_request_template.md) and/or linter bot's message could explain what's going on?

**Comment by beckermr** [comment]
This has been fixed via the admin server hook: https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-ping-team
