### ISSUE TITLE
Conversion failing

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#6659]
Looks like conversion started failing yesterday and has not been working since. Linking to the first log below.

cc @conda-forge/core @conda-forge/staged-recipes

ref: https://travis-ci.org/conda-forge/staged-recipes/builds/426812270

**Comment by scopatz** [comment]
It seems like a URL is getting filled out wrong:

```
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.travis-ci.org/repo/conda-forge%2Fstaged-recipes/requests
```

Shouldn't the `%2F` be replaced by `/`

**Comment by jakirkham** [comment]
That actually ends up being correct usage, but agree it's a little counterintuitive.

ref: https://developer.travis-ci.com/resource/repository#find

**Comment by jakirkham** [comment]
Am starting to wonder if this may be related to the Travis CI GitHub App issue ( https://github.com/conda-forge/conda-forge.github.io/issues/644 ).

**Comment by mcflugen** [comment]
@jakirkham I notice that after new recipes are merged, although a `*-feedstock` repository is created, the feedstock repository is not populated.

For example see:
* https://github.com/conda-forge/pytest-xvfb-feedstock
* https://github.com/conda-forge/bz2file-feedstock
* https://github.com/conda-forge/r-tufte-feedstock
* https://github.com/conda-forge/pydoe2-feedstock
* https://github.com/conda-forge/jupyter-repo2docker-feedstock
* https://github.com/conda-forge/r-tangram-feedstock
* https://github.com/conda-forge/pyemir-feedstock
* https://github.com/conda-forge/grave-feedstock
* https://github.com/conda-forge/radical.entk-feedstock
* https://github.com/conda-forge/sedflux-feedstock

Is this the same problem that you're describing here? If so, and [#644](conda-forge/conda-forge.github.io#644) is the source of the problem, is this something that individual feedstock maintainers can fix on a repository-by-repository basis or does it need to be done organization-wide? I would really love to get this working again!

**Comment by jakirkham** [comment]
Yes, this is the same issue, @mcflugen.

I'm not sure if issue ( https://github.com/conda-forge/conda-forge.github.io/issues/644 ) is the cause, but it may be a way to solve this problem. It is also something we need to solve by the end of the month (ideally sooner). So it may be the best path forward.

Well issue ( https://github.com/conda-forge/conda-forge.github.io/issues/644 ) involves making a fix to [`conda-smithy`]( https://github.com/conda-forge/conda-smithy ). Anyone that has time is welcome to start a PR over there. Have not looked deeply into the specific changes required, but they would need to happen in [this file]( https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/ci_register.py ). Am fuzzy on the API needed. So this likely requires inspecting what [Travis CI's migration tool]( https://github.com/travis-ci/travis_migrate_to_apps ) is doing and using the same web API from there.

**Comment by jasongrout** [comment]
Looks like this may be fixed? I noticed that several repos were created with files now.

**Comment by mcflugen** [comment]
Yep. This appears to be working for me now! 💥💥💥

**Comment by jasongrout** [comment]
It's a bit confusing, actually, since the file noted above (https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/ci_register.py) hasn't been touched.

**Comment by jasongrout** [comment]
(and conda-forge/conda-forge.github.io#644 and https://github.com/conda-forge/conda-smithy don't seem to have any updates either)

**Comment by mcflugen** [comment]
Well, things started to work after I got an alert saying that a conda-forge organization owner approved the Travis CI application to access private data in conda-forge so I'm guessing it was a permissions problem (which may be related to conda-forge/conda-forge.github.io#644).

**Comment by scopatz** [comment]
Interesting - GitHub Services were deprecated, which Travis used to rely on.  They then had to migrate (to webhooks?) and so I ma guessing that we got held up because of that.

**Comment by scopatz** [comment]
Glad it is working now!

**Comment by jakirkham** [comment]
The new feedstocks seem to still be using the old, deprecated GitHub Services. So not sure.

That said, the Travis CI GitHub App is enabled for the org, which the new feedstocks have been registered with as well. Would be interesting to know which step triggers the addition to the Travis CI GitHub App. In any event, that is most likely what fixed it.

Now it's just a matter of migrating the existing feedstocks to the Travis CI GitHub App as well.

**Comment by isuruf** [comment]
Yes, it's still using the old services for new feedstocks. I was playing with permissions today morning. Not sure what fixed it. :smile:
