### ISSUE TITLE
Windows Python 3.5 CI Failure 

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#666]
No idea why this is happening. Just trying to get the discussion to happen in one place so maybe we can learn something and fix it.

cc @ericdill @astrofrog @ocefpaf

**Comment by astrofrog** [comment]
@Cadair - is this similar to the issue you were seeing the other day?

Log here: https://ci.appveyor.com/project/conda-forge/glueviz-feedstock/build/1.0.2/job/ml85k10o4db2eqb8

**Comment by jakirkham** [comment]
Try pinning `setuptools` to `20.7.0`.

**Comment by jakirkham** [comment]
Ok, that's not the issue, but it was worth trying. Can confirm this fixed the issue with `pillow`. Add the following to `build` and `run` requirements.

`    - vs2015_runtime 14.00.23026.0 0   # [win and py35]`

@msarahan, it appears that the recent rebuild of `vs2015_runtime` with build number `1` is breaking things. Can it be pulled until we can figure out why and fix it?

**Comment by jakirkham** [comment]
See this PR for an example. ( https://github.com/conda-forge/pillow-feedstock/pull/12 )

**Comment by msarahan** [comment]
I'm pretty sure this is a red herring, and I'm hesitant to pull the package until we can prove what the cause is.  You have a correlation, but not causation, IMHO.  That PR adds the OpenMP runtimes, as requested by @patricksnape in https://github.com/ContinuumIO/anaconda-issues/issues/798.  There is nothing else to it (version bump aside).

I'm going to try to repeat this issue locally to try to figure it out.

**Comment by jakirkham** [comment]
Ok, feel free to experiment. I'm just letting you know that this one package has made the difference between things working or not.

**Comment by msarahan** [comment]
Confirming that I do not see the issue locally, after cloning the repo and unpinning vs2015_runtime in build and runtime sections.  I'll keep thinking on this - what we really need is a better way to debug appveyor.

**Comment by jakirkham** [comment]
Well, you can try playing with some things on top of this PR ( https://github.com/conda-forge/pillow-feedstock/pull/13 ). It demonstrates the issue we are seeing.

**Comment by jakirkham** [comment]
cc @kalefranz

**Comment by astrofrog** [comment]
In case it helps debugging, it's possible to just log in to the AppVeyor worker directly: http://www.appveyor.com/docs/how-to/rdp-to-build-worker

**Comment by janschulz** [comment]
I have the same problem locally: It ends with a popup which says this:

```
---------------------------
python.exe - Anwendungsfehler
---------------------------
Die Anwendung konnte nicht korrekt gestartet werden (0xc0000142). Klicken Sie auf "OK", um die Anwendung zu schließen. 
---------------------------
OK   
---------------------------
```

[basically: python couldn't be started correctly]

Last liens of  `conda build recipe` (on a py35 root enviornment without any python versions set):

```
C:\portabel\miniconda\conda-bld\work {git}{hg}
{lamb} call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
# error happens before the next line appears
Command failed: C:\Windows\system32\cmd.exe /c call bld.bat
```
[The `lamb` comes from cmder, which sets the prompt to that but does not work when a batch files echos the commands...]

**Comment by janschulz** [comment]
I also created a new py35 environment and it has the same problem: the python in there is basically not runnable... I can't even run `conda list` because that calls the pip in the env which again is using the python in the env...

Downgrading to the mentioned version above fixes it:

```
c:\data\external\conda-packages\twine-feedstock (master)
λ conda create -n test35 python=3.5
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ................
Solving package specifications: .........

Package plan for installation in environment C:\portabel\miniconda\envs\test35:

The following NEW packages will be INSTALLED:

    pip:            8.1.1-py35_1
    python:         3.5.1-4
    setuptools:     21.2.1-py35_0
    vs2015_runtime: 14.00.23026.0-1
    wheel:          0.29.0-py35_0

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|##################################################| 100%
#
# To activate this environment, use:
# > activate test35
#

c:\data\external\conda-packages\twine-feedstock (master)
λ activate test35
Deactivating environment "C:\portabel\miniconda"...
Activating environment "C:\portabel\miniconda\envs\test35"...

c:\data\external\conda-packages\twine-feedstock (master)
[test35] λ python

# same error

[test35] λ conda list
# packages in environment at C:\portabel\miniconda\envs\test35:
#
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\portabel\miniconda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\portabel\miniconda\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\portabel\miniconda\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\portabel\miniconda\lib\site-packages\conda\cli\main_list.py", line 273, in execute
    json=args.json, show_channel_urls=args.show_channel_urls)
  File "C:\portabel\miniconda\lib\site-packages\conda\cli\main_list.py", line 185, in print_packages
    add_pip_installed(prefix, installed, json=json)
  File "C:\portabel\miniconda\lib\site-packages\conda\pip.py", line 106, in add_pip_installed
    for pip_pkg in installed(prefix, output=output):
  File "C:\portabel\miniconda\lib\site-packages\conda\pip.py", line 47, in installed
    args = pip_args(prefix)
  File "C:\portabel\miniconda\lib\site-packages\conda\pip.py", line 26, in pip_args
    pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
  File "C:\portabel\miniconda\lib\subprocess.py", line 629, in check_output
    **kwargs).stdout
  File "C:\portabel\miniconda\lib\subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\portabel\\miniconda\\envs\\test35\\Scripts\\pip.exe', '-V']' returned non-zero exit status 3221225794

[test35] λ conda install vs2015_runtime=14.00.23026.0=0
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ................
.Solving package specifications: .........

Package plan for installation in environment C:\portabel\miniconda\envs\test35:

The following packages will be DOWNGRADED:

    vs2015_runtime: 14.00.23026.0-1 --> 14.00.23026.0-0

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%

c:\data\external\conda-packages\twine-feedstock (master)
[test35] λ python
Python 3.5.1 |Continuum Analytics, Inc.| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
```

**Comment by patricksnape** [comment]
I also cannot replicate it locally. Though I am seeing it on my [appveyor builds](https://ci.appveyor.com/project/jabooth/conda-dlib/build/job/58isp76d29m5l3qr)

**Comment by janschulz** [comment]
I'm on Win7, 64bit

**Comment by astrofrog** [comment]
@jakirkham - just out of interest, is there a mechanism to deploy this kind of fix to all feedstocks?

**Comment by janschulz** [comment]
@astrofrog as the fix needs to go into the recipe (because it happens in the env which `conda build` creates from the recipe), I think either each recipe needs to include that restriction (not good because AFAIK there is no "not this version", only pinning it to a version which works, but which then can't be updated?) or a workaround for this needs to go into a conda-build (or python) package in the conda-forge channel or continuum needs to pull/fix the vs2015_runtime package. 

This would have helped: https://github.com/conda/conda/issues/2067 because that file would be under the feedstock control, so it could be automatically be pushed by the conda smithy daemon.

And basically each failed build needs to be restarted?

**Comment by Korijn** [comment]
Our appveyor builds are crashing on this as well.

**Comment by msarahan** [comment]
I have pulled this package for the time being.  Sorry for the disruption.
I  will investigate today.  I believe the build worker used to build this
package may have an out-of-date VS 2015 installation (one older than the
one that was used to build Python.)

**Comment by jakirkham** [comment]
Beyond people's attempt to debug this further, which I really do appreciate. I see two main questions coming to the forefront.
<br>

1. How can we quickly protect feedstocks against this in the future?
2. How do we create `vsXXXX_runtime` so it will work with AppVeyor?

Addressing 2: This actually seems pretty simple. We generate them here at conda-forge using AppVeyor. We could use a [strategy]( https://github.com/conda-forge/staged-recipes/pull/363#issuecomment-214781601 ) that @ukoethe suggested to us before or we could follow the [strategy]( https://github.com/conda-forge/staged-recipes/pull/363#issuecomment-214785089 ) that Continuum uses. If we generate them here, they should be compatible with AppVeyor as they have come from it. This should also help us stay on top of breaks and address them quickly. There is a different question of how well those do on different Windows platforms, which I'd like to hear from someone else on this point.

Addressing 1: We have come up with several packages (or are still designing a few) that should help us control the packaging process, CI configuration, etc. One of these is the `vc` package, which we have [released]( https://github.com/conda-forge/vc-feedstock ). However, we are still exploring how best to use this. The `vc` package is designed to replace `python` for VC runtime selection. This would be the ideal place to pin this as it would be used as a build and run dependency for all Windows packages. We are still exploring the best way to use this package. When we know more, we will come up with some best practices for using this and update all of you.

<br>
I appreciate everyone coming together to understand this issue and find it's scope. Let's share some thoughts on these and figure out how we can improve on our packaging process going forward.

**Comment by janschulz** [comment]
RE 1: As far as I understand the problem here, the fix has to hook into the conda-build process between reading the package recipe and then installing the packages. This is, as far as I know, currently only possible by a) patching conda or conda build (to not install a certain package = blacklist) or b) by changing the recipe.

If conda would gain a blacklist or pinning (-> conda/conda#2067), a `conda-forge-environment` package could be constructed and installed in each CI service. The package could then use a postinstall script to set such a blacklist.

**Comment by pelson** [comment]
> Addressing 1: We have come up with several packages (or are still designing a few) that should help us control the packaging process, CI configuration, etc. 

Agreed. We can control a lot in the meta packages we have developed recently. I don't think it would be *easy* to control the msvs runtime version though - we may have needed to patch conda-build from the packages that we developed. A bit yucky 😕 .

**Comment by jakirkham** [comment]
Going to close this as the original issue is resolved. We should break out other discussion in new issues as needed. Thanks everyone.

**Comment by janschulz** [comment]
So who is doing the "breaking out other discussion in new issues"?

**Comment by jakirkham** [comment]
This is getting pretty philosophical here. :neckbeard: (sorry best I can find)

Basically, in reverse order, anything else worth discussing and anyone who feels these other points worthy of discussion.

**Comment by janschulz** [comment]
Ok, I created https://github.com/conda/conda/issues/2585 about the problem of dependencies of conda  getting updated and leaving the root environment in a broken state.
