### ISSUE TITLE
RFC: Adding projects with very long test suites

### ISSUE THREAD

**Issue by ericdill** [conda-forge/staged-recipes#675]
So here's a fun one.  `fabio` is a library that abstracts away the various specs for a number of scientific data formats common at synchrotrons and some other facilities.  The test suite for this library downloads a bunch of files and makes sure that it can open them.  As such, the test suite takes quite a while.  On my i7 ssd laptop it took ~10 minutes.  Opening this issue to figure out the best way to proceed.

1. Should I just skip running the test suite?
1. Run the test suite and clog up CI?
1. Some other option I haven't thought of?

[recipe] (https://github.com/ericdill/staged-recipes/blob/add-fabio/recipes/fabio/meta.yaml)

**Comment by dopplershift** [comment]
I thought the idea on tests wasn't to run the package tests (because of time, packages shipping with failing tests, etc.) but just a set of tests that tries to ensure the package isn't broken.

**Comment by pelson** [comment]
I generally agree with this approach @dopplershift. There is definitely a gray line though, and really it has to be a judgement call on whether there is insufficient confidence in the built package to warrant the cost of running the entire test suite.
