### ISSUE TITLE
Package pyviz panel

### ISSUE THREAD

**Issue by rsignell-usgs** [conda-forge/staged-recipes#6776]
It would be great to have the pyviz widgets package `panel` on `conda-forge`:
https://github.com/pyviz/panel
https://pypi.org/project/panel/
currently it only seems to exist only on the `jbednar` and `pyviz` channels. 
cc: @jbednar

**Comment by jbednar** [comment]
Panel is not yet released, but when we do release it, we can put it on conda-forge.   Soon, I hope!

**Comment by rsignell-usgs** [comment]
@jbednar, okay, great news!
