### ISSUE TITLE
Feedstock not populated for PR #6654

### ISSUE THREAD

**Issue by vivek-bala** [conda-forge/staged-recipes#6781]
We were asked from @marcelotrevisani in #6648 to create a new pull request, since he reverted that one in #6651. PR #6648 created the feedstock repo which did not get deleted when reverting. As a result, the new PR https://github.com/conda-forge/staged-recipes/pull/6654 fails since the linter [finds an existing feedstock](https://github.com/conda-forge/staged-recipes/pull/6654#issuecomment-420308598).

There hasn't been much response in PR #6654, hence opening a ticket.

**Comment by iparask** [comment]
cc @conda-forge/staged-recipes @conda-forge/core

**Comment by jakirkham** [comment]
Closing as this appears to be resolved. Feel free to ping us if not.
