### ISSUE TITLE
Package request: PyQt5

### ISSUE THREAD

**Issue by astrofrog** [conda-forge/staged-recipes#684]
One of the packages that is currently missing from the default or conda-forge channels are Qt5 and PyQt5, and this is one that various people are providing for various platforms/versions:

```
     abergeron/pyqt5           |    5.4.1 | conda           | osx-64         
     andreas-h/pyqt5           |    5.3.2 | conda           | linux-64, win-64, osx-64
     asmeurer/pyqt5            |    5.3.2 | conda           | osx-64         
     astrofrog/pyqt5           |    5.5.0 | conda           | linux-64       
     avalentino/pyqt5          |    5.3.2 | conda           | linux-64, win-64, osx-64
     bpentz/pyqt5              |      5.6 | conda           | win-64         
     dmazzella/pyqt5           |    5.3.1 | conda           | osx-64         
     dsdale24/pyqt5            |    5.3.2 | conda           | linux-64, win-64, osx-64
     ebenolson/pyqt5           |    5.5.0 | conda           | linux-64       
     ericdill/pyqt5            |    5.4.1 | conda           | linux-64       
     hadim/pyqt5               |    5.4.1 | conda           | linux-64       
     inso/pyqt5                |      5.6 | conda           | linux-64, win-32, win-64
     ipa/pyqt5                 |    5.5.0 | conda           | linux-armv6l   
     jdreaver/pyqt5            |    5.4.1 | conda           | linux-64       
     m-labs/pyqt5              |    5.5.1 | conda           | linux-64, win-32, win-64
     mmcauliffe/pyqt5          |    5.5.1 | conda           | linux-64, win-64, osx-64
     nicoddemus/pyqt5          |    5.4.1 | conda           | linux-64       
     nmearl/pyqt5              |    5.5.0 | conda           | linux-64, osx-64
     spyder-ide/pyqt5          |    5.5.0 | conda           | linux-64, osx-64
```

It may be that this would require too much computational time for what we can do here, in which case we should just close this package request, but otherwise I think it would be nice to have a set of well-maintained centralized recipes for PyQt5, Qt5, and dependencies.

**Useful links:**

conda-recipes qt5 recipe: https://github.com/conda/conda-recipes/tree/master/qt5
conda-recipes pyqt5 recipe: https://github.com/conda/conda-recipes/tree/master/python/pyqt5

cc @ccordoba12 @ericdill

**Comment by msarahan** [comment]
Build time is the main issue, but it is already in progress:

https://github.com/conda-forge/staged-recipes/pull/606

**Comment by ccordoba12** [comment]
@astrofrog, please close this one :-)

I think there's no way to create packages for Qt5/PyQt5 on conda-forge because of the one hour running time limitation of CI services.

**Comment by astrofrog** [comment]
@ccordoba12 @msarahan - will Continuum be able to provide builds of Qt5/PyQt5 in the default channel?

**Comment by ccordoba12** [comment]
Yes, we're working on it :-)
