### ISSUE TITLE
Package responder

### ISSUE THREAD

**Issue by carlodri** [conda-forge/staged-recipes#6873]
https://github.com/kennethreitz/responder

depends on #6871 and #6872

**Comment by mkuklik** [comment]
currently this is blocked because it requires pre-release version (1.0.0b1) of apispec.

**Comment by carlodri** [comment]
yup, that's why I asked for this: https://github.com/conda-forge/apispec-feedstock/issues/20

**Comment by carlodri** [comment]
package is ready.
