### ISSUE TITLE
Tensorflow-probability

### ISSUE THREAD

**Issue by dirmeier** [conda-forge/staged-recipes#6903]
Hey,

it would make sense to add `tensorflow-probability` here as well.  (Or am I overlooking it?)

Cheers,
Simon

**Comment by sodre** [comment]
@dirmeier, this was added as part of #7724. If you encounter issues, please let me know by opening an issue in the feedstock.

**Comment by dirmeier** [comment]
Ah right, I forgot that I opened this here, too. Thanks
