### ISSUE TITLE
Continuous integration fails due to missing 'conda-bld'

### ISSUE THREAD

**Issue by padix-key** [conda-forge/staged-recipes#7013]
I have created a pull request to add the package `biotite` to conda-forge (#7012).  However, Appveyor and Travis CI fail due to the missing directory `conda-bld`:

Appveyor: `The system cannot find the path specified: 'C:\\Miniconda36-x64\\conda-bld'
Command exited with code 1`

Travis CI: `No such file or directory: '/Users/travis/miniconda/conda-bld'`

Circle CI finished successfully .

**Comment by jakirkham** [comment]
Presumably fixed in PR ( https://github.com/conda-forge/staged-recipes/pull/7009 ).
