### ISSUE TITLE
Travis CI and Cirle CI build failure

### ISSUE THREAD

**Issue by bwohlberg** [conda-forge/staged-recipes#7040]
The CI builds for PR #7039 appear to be failing due to a build failure of the dependency ``pygraphviz``:
-  [Travis CI](https://travis-ci.org/conda-forge/staged-recipes/builds/454263005?utm_source=github_status&utm_medium=notification)
-  [Circle CI](https://circleci.com/gh/conda-forge/staged-recipes/31620?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

It isn't clear why ``pygraphviz`` is being built at all since it's available as a package on conda-forge, and that package seems to install without problems when tested within a local conda environment. Is this a bug in the build system, or some subtle error in the PR recipe?

**Comment by hajapy** [comment]
See https://github.com/conda-forge/staged-recipes/pull/7038, which I think would fix the issue you're seeing.

**Comment by bwohlberg** [comment]
Thanks for the suggestion! Adding ``--no-deps`` in the script line did indeed resolve the issue.
