### ISSUE TITLE
packages imagemagick

### ISSUE THREAD

**Issue by janschulz** [conda-forge/staged-recipes#707]
This is needed for the mpl tests

There is a windows build machinery for appveyor here: https://github.com/ImageMagick/ImageMagick-Windows

@VDBWRAIR and @kalefranz have conda packages for linux on anaconda.org, maybe one of you could submit a recipe here?

https://github.com/VDBWRAIR/conda-recipes/tree/master/recipes/imagemagick
https://github.com/kalefranz/conda-packages/tree/master/capp/imagemagick

cc: @tacaswell bc mpl :-)

**Comment by jakirkham** [comment]
cc @isuruf

**Comment by isuruf** [comment]
This is in conda-forge now. https://github.com/conda-forge/imagemagick-feedstock

**Comment by jakirkham** [comment]
Nice catch! Sorry must have missed that. Have you tried building Octave with it?

**Comment by isuruf** [comment]
No. `imagemagick` was added after `octave` and haven't had time.

**Comment by jakirkham** [comment]
Ok. No worries. Just ran into someone that was asking about image processing with Octave so was a bit curious.
