### ISSUE TITLE
package ffmpeg

### ISSUE THREAD

**Issue by janschulz** [conda-forge/staged-recipes#708]
This is needed for mpl tests (and mpl animation support...)

I found the following recipes 
* in conda-forge https://github.com/conda/conda-recipes/tree/master/ffmpeg
* not sure if repackaged or build from source: https://anaconda.org/groakat/ffmpeg-shared/
* repackaged binaries for all major platforms: https://github.com/menpo/conda-ffmpeg

CC: @groakat @menpo

**Comment by janschulz** [comment]
It seems only the windows version is missing: https://github.com/conda-forge/ffmpeg-feedstock/issues/7

**Comment by groakat** [comment]
I build then some long time ago. I think the OSX and Linux version were build from scratch (including all dependencies, which are additional conda packages). I also remember there was a hack that I needed in OSX to avoid some compile errors. I did it in a hurry and probably not in the best way. I am happy to assist, if you want to make a proper package out of it.

The Windows version used precompiled stuff and copied it over, if I remember correctly.

**Comment by jakirkham** [comment]
@groakat, we actually have ffmpeg for OSX and Linux. Though we could probably use help with the upkeep if you would be willing to be a maintainer.

**Comment by groakat** [comment]
That is interesting. Maybe I should link my projects to yours. 

Unfortunately, I am very pressed with time at the moment and cannot commit to anything that takes up more than a few hours.

So the issue for you guys is that you have no Windows version, right?

What I did was to hard-link against the Zeranoe builds, by downloading a .7z file from their server, unzip it and copy over the files into the `%SCRIPTS` folder:

meta.yaml:

    package:
      name: ffmpeg-shared
      version: 2.8.0

    source:
      fn: ffmpeg-20140827-git-9e8ab36-win64-shared.7z[win]
      url: http://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-20140827-git-9e8ab36-win64-shared.7z [win]
      sha1: 39c2bcb9465ce15cfd3badc1b7bb0b83718c4cac[win]
      fn: ffmpeg-2.8-snapshot.tar.bz2 [osx]
      url: http://www.rennert.io/dep_sources/ffmpeg-2.8-snapshot.tar.bz2 [osx]
    	
    build:
        number: 0
    	  
    requirements:
      build:
        - 7za			[win]
        - x264
        - fdk-aac
        - libvpx
        - libogg
        - libvorbis
        - opus
        - lame
        - yasm
      run:
        - x264
        - fdk-aac
        - libvpx
        - libogg
        - libvorbis
        - opus
        - lame
     #   - ffmpeg-shared

    about:
      home: https://www.ffmpeg.org/
      license: "Various (see Copyright file from the aspell6-en source)"
      summary: "A complete, cross-platform solution to record, convert and stream audio and video."


bld.bat:

	7za x %SRC_DIR%\ffmpeg-20140827-git-9e8ab36-win64-shared.7z -o%SRC_DIR%
	mkdir %SCRIPTS%
	copy %SRC_DIR%\ffmpeg-20140827-git-9e8ab36-win64-shared\bin %SCRIPTS%
	copy %SRC_DIR%\ffmpeg-20140827-git-9e8ab36-win64-shared\ff-prompt.bat %SCRIPTS%
