### ISSUE TITLE
Unpin conda-build in appveyor ? 

### ISSUE THREAD

**Issue by msarahan** [conda-forge/staged-recipes#716]
Seems like it is unpinned in other ci scripts. Do we feel OK unpinned for Windows? 

More generally, how do you want to handle pinning wrt new conda-build releases? 

Cc @jakirkham @pelson  @ocefpaf

**Comment by jakirkham** [comment]
We want to switch over to [conda-forge-build-setup-feedstock]( https://github.com/conda-forge/conda-forge-build-setup-feedstock ). Then we want to handle as much CI stuff through that as possible. Initially the idea was to have a package with activate scripts, but we have decided it should be a package with callable scripts. We have been playing with it as time allows. However, it is not quite ready for prime time. Before worrying about, we should make sure this package will work as a drop-in replacement for the existing CI scripts. Ideally I would work on this today, but am going to be in meetings pretty much all day. So, I don't think it is going to happen. If you want to give it a try, please do.

As far as addressing unpinning, I'd be ok doing this in staged-recipes. Though I think the general feeling is we are tired of having to do this in two places and we are tired of having `conda-smithy` releases tied to CI pinnings. So, I doubt a corresponding pinning release of `conda-smithy` would be made. That means that people who have errors on AppVeyor with this pinning in the feedstock are going to need to remove it manually. Though this is just my opinion. Let's see what others have to say.

**Comment by msarahan** [comment]
Sounds reasonable to me.  I'm aware of at least one PR ( #679 ) that seems to be held up by pinning.  Just trying to keep things moving...

**Comment by patricksnape** [comment]
I've been removing the `1.20.0` pinning in various recipes and all seems well for Windows builds. For example, see [this OpenCV build](https://ci.appveyor.com/project/conda-forge/opencv-feedstock/build/1.0.35) where pinning has been removed and everything is passing.

**Comment by pelson** [comment]
We are now pinning this in the conda-forge-build-setup distribution: https://github.com/conda-forge/conda-forge-build-setup-feedstock/blob/master/recipe/run_conda_forge_build_setup_win#L16

I'm in favour of removing that pinning if everything is now building as expected :+1:

**Comment by jakirkham** [comment]
Please see this PR ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/22 ). Going to close this so the discussion can migrate over there.
