### ISSUE TITLE
activate-binutils_linux-64.sh not sourced with conda-build 3.17

### ISSUE THREAD

**Issue by sebastian-luna-valero** [conda-forge/staged-recipes#7167]
Hi,

I am using `.circleci/run_docker_build.sh` locally to build a new conda recipe using `gfortran_linux-64` and I noticed that `activate-binutils_linux-64.sh` is sourced with version 3.16 of `conda-build` but not with version 3.17.

I am using the exported `$GFORTRAN` environment variable in a `Makefile` and therefore it only works with `conda-build 3.16`. 

Can someone confirm this behaviour?

Is this the right forum to report the issue or should I open an issue in the `conda-build` repository?

Best regards,
Sebastian

**Comment by msarahan** [comment]
3.17.0 or 3.17.1? The latter might fix this.

**Comment by sebastian-luna-valero** [comment]
Thanks @msarahan 

Indeed:
* 3.17.0 fails
* 3.17.1 works

Many thanks!
