### ISSUE TITLE
Feedstock generation failing

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#720]
See this [log]( https://travis-ci.org/conda-forge/staged-recipes/jobs/135600952 ). Note this is **not** an API throttling issue.

cc @pelson @ocefpaf

**Comment by patricksnape** [comment]
``AttributeError: 'RuntimeError' object has no attribute 'message'``

**Comment by msarahan** [comment]
That's python 2 vs. 3.  In 3, you should just treat the exception object like a string, directly printing it or whatever.

**Comment by jakirkham** [comment]
Yep, it's masking the real error though, which is going to make it hard to figure out what is going on without a release inbetween.

**Comment by jakirkham** [comment]
Going to try a simple renaming fix to see if this helps. Will reopen if it fails.

**Comment by jakirkham** [comment]
Yep, fixed. Simple naming issue. Only required the time to look at it. 😄
