### ISSUE TITLE
jsonnet feedstock creation failed

### ISSUE THREAD

**Issue by nelson-liu** [conda-forge/staged-recipes#7273]
Hi!

#7263 was recently merged, but it looks like the feedstock creation failed ( https://travis-ci.org/conda-forge/staged-recipes/builds/467629729 ). anything i can do on my side to help?

cc: @scopatz (original reviewer)

**Comment by scopatz** [comment]
I'll try to fix it.

**Comment by scopatz** [comment]
should be fixed now

**Comment by nelson-liu** [comment]
thanks!
