### ISSUE TITLE
Finding feedstock for package

### ISSUE THREAD

**Issue by epruesse** [conda-forge/staged-recipes#7714]
Is there a good way to determine the feedstock repo given a package name?

The best I can come up with at the moment is grabbing lbcfgraph, loading the `artifacts/<package>/conda-forge/linux-64/<package>-<build>.json` and traversing via the `parent_recipe`.

**Comment by jakirkham** [comment]
Probably worth moving this to a higher traffic area. Would it be alright to move this issue to the webpage repo?

**Comment by epruesse** [comment]
Re-issued it there.
