### ISSUE TITLE
AppVeyor is failing for almost every single package recipe

### ISSUE THREAD

**Issue by allanleal** [conda-forge/staged-recipes#7786]
AppVeyor is currently failing for many projects with the following message:

~~~
An unexpected error has occurred. Conda has prepared the above report.
Upload successful.
Sorry, we tried running command for 3 times and all attempts were unsuccessful!
Command exited with code 1
~~~

Would you please check what is going on? This is failing even after specifying `skip true` for `win`.

**Comment by chrisburr** [comment]
I think this has been fixed now, if I'm mistaken reopen this issue with a link to an example and I'll take a look.
