### ISSUE TITLE
Package jupyterlab-hub

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#7882]
Would be nice to have a package for [jupyterlab-hub]( https://github.com/jupyterhub/jupyterlab-hub ). This would be more or less a helper package for managing this [install process]( https://github.com/jupyterhub/jupyterlab-hub#installation ).

**Comment by jakirkham** [comment]
@blink1073, if you are able to advise the best way to go about this, that would be very helpful. 😄

**Comment by blink1073** [comment]
Lab extensions don't yet lend themselves to being conda packages, see discussion [here](https://github.com/jupyterlab/jupyterlab/issues/2065).  About the best you could do is put the 'npm pack' tarball of the source package in a known location so it would be picked up by a 'jupyter lab build' after install: '<prefix>/share/jupyter/lab/extensions'.

**Comment by jakirkham** [comment]
This was since upstreamed into JupyterLab.
