### ISSUE TITLE
Add NEURON

### ISSUE THREAD

**Issue by orena1** [conda-forge/staged-recipes#8026]
Can you please help with adding [NERUON](https://www.neuron.yale.edu/neuron/) ?
There is an attempt of the developers but it seems that XQuartz is making problems.
https://github.com/neuronsimulator/nrn/issues/111

I wonder if you guys have expertise that can help, thanks.

**Comment by chrisburr** [comment]
It seems like this already exists [here](https://github.com/conda-forge/neuron-feedstock)? If there are problems with that build you can open an issue in that repository.

While checking I notice the last Linux builds didn't deploy correctly, I've opened an issue about it: https://github.com/conda-forge/neuron-feedstock/issues/4
