### ISSUE TITLE
Dependency-respecting build order is not followed when there are multiple packages in one PR

### ISSUE THREAD

**Issue by pvanheus** [conda-forge/staged-recipes#8071]
I am packaging a [dtool](https://dtool.readthedocs.io/en/latest/) which is composed of a set of interlinked packages. To capture these packages I put multiple recipes in one PR: https://github.com/conda-forge/staged-recipes/pull/8066. I know this is not recommended practice but in this case it would be useful. The build [fails](https://circleci.com/gh/conda-forge/staged-recipes/36682?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) however, because even though it states:

```
Resolved dependencies, will be built in the following order:
    dtoolcore-3.8.0-on-linux-64
    dtool_cli-0.7.0-on-linux-64
    dtool_config-0.1.1-on-linux-64
    dtool_info-0.13.0-on-linux-64
    dtool_http-0.2.0-on-linux-64
    dtool_symlink-0.3.0-on-linux-64
    dtool_create-0.22.0-on-linux-64
    dtool_s3-0.4.1-on-linux-64
```

it actually builds the packages in *lexical order*, so `dtool_create` is built before the `dtool_symlink` it depends on.

**Comment by chrisburr** [comment]
I think this has been fixed by 57403e5cf21d986fc77b0136b62f6981e5247861.

Thanks for creating the issue!
