### ISSUE TITLE
Packaging rpm2cpio wrapper shell script

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#8241]
The Anaconda CDTs are currently using an [`rpm2cpio` wrapper shell script]( https://www.redhat.com/archives/rpm-list/2003-June/msg00367.html ). Currently this is [vendored in each recipe]( https://github.com/AnacondaRecipes/aggregate/blob/22dbbd60c5b9f2433e274aa98986a4673a7d641b/libsm-cos6-x86_64/rpm2cpio ). This seems a bit tricky from a maintenance standpoint should any modification be needed to this script. Would it be reasonable for us to just package the `rpm2cpio` wrapper script so we can use it in CDTs as needed?

cc @mingwandroid

**Comment by mingwandroid** [comment]
conda-build unpacks the rpms now anyway since libarchive was added so we don't need any of this. Deleting this from `conda skeleton rpm` gets my vote.

**Comment by jakirkham** [comment]
Ah ok. That's good to know. In that case, I'd withdraw this suggestion. Thanks for sharing that Ray.

On a different note, is this documented somewhere? If not, is there a good place for us to document it?

**Comment by mingwandroid** [comment]
No not really. Libarchive supports so many filters and formats (filters * formats) that listing them all would be a bit verbose. Generally speaking, if you ever find a valid archive and conda-build doesn't handle it, then that is a bug.

**Comment by jakirkham** [comment]
Have raised issue ( https://github.com/conda/conda-build/issues/3492 ) to follow-up on the `conda skeleton rpm` point. Please update if I've missed anything.

As to the documentation, didn't realize CDTs could be so easily generated. So wanted to document that somewhere, but wasn't sure where would be best. Any thoughts?

**Comment by mingwandroid** [comment]
One issue with CDTs, I think I change a `lib64` directory to `lib` and I shouldn't do that, or if I do do that, then I need to push through and change it in other files too (e.g. `.pc` files).

I cannot remember which package I ran into this with though. Scanning the skeleton code may prove informative.

**Comment by mingwandroid** [comment]
(it was probably updating Qt on Linux to 5.12)

**Comment by hmaarrfk** [comment]
So what is the correct script now to generate CDTs? I would like to create one for libusb(1)

**Comment by jakirkham** [comment]
Let’s finish the discussion in issue ( https://github.com/conda-forge/conda-forge.github.io/issues/783 ) first. Then we can start packaging these.
