### ISSUE TITLE
libpng version on conda-forge incompatible with latest qt 4.8.7 build 3 on OS X

### ISSUE THREAD

**Issue by grlee77** [conda-forge/staged-recipes#862]
On OS X, if I use qt from the defaults channel, I also have to use libpng >=1.6.22 to avoid errors such as:

```
Library not loaded: @rpath/libpng16.16.dylib
  Referenced from: /Users/lee8rx/anaconda/envs/_test/lib/libQtGui.4.8.7.dylib
  Reason: Incompatible library version: libQtGui.4.dylib requires version 39.0.0 or later, but libpng16.16.dylib provides version 38.0.0
```

see, also the test failure on #687

**Comment by ocefpaf** [comment]
@grlee77 I am pinning `libpng` properly all across matplotlib's dependencies, but I just merge the last one (I hope!). Let me bump matplotlib's build and see if we can fix that...

**Comment by ocefpaf** [comment]
@grlee77 pinning on our side did not work. It seems that we would need to either build `qt` with our `libpng` or re-build everything in `conda-forge` with the same `libpng` used in `qt` from defaults.

**Comment by grlee77** [comment]
either way sounds like a pain :(
IIRC Qt takes too long to build and times out on the CI services, so I guess that leaves updating feedstocks requiring `libpng` (currently around dozen?) to >=1.6.22?

**Comment by ocefpaf** [comment]
> either way sounds like a pain :(

Yep. I would love to find a way to build `qt` with a `conda-forge` recipe though. Even if it is in a local trusted machine (@msarahan :wink: ) and then uploaded manually to `conda-forge`. That is a break from how we do things, but it would help us move forward.

Ping: @pelson here who might have another idea on how to proceed.

PS: `qt` is also blocking package that are built with `conda-forge`'s newer `jpeg`.

**Comment by grlee77** [comment]
I am +1 on making exceptions to allow manual uploading for a handful of packages such as Qt or VTK that exceed the build time limits 

also, don't feel obligated to resolve this immediately on my account.  I will largely be out of office over the next two weeks.

**Comment by jakirkham** [comment]
Closing as this should no longer be an issue.
