### ISSUE TITLE
_r-mutex feedstock creation failed, all subsequent builds are also failing

### ISSUE THREAD

**Issue by fhoehle** [conda-forge/staged-recipes#8703]
Hi,

feedstock creation of the `_r-mutex` recipe (recently merged) [failed](https://travis-ci.org/conda-forge/staged-recipes/builds/552655986#L961). An empty repository was created, [_r-mutex](https://github.com/conda-forge/_r-mutex-feedstock). All subsequent builds are failing. :-(  I have no idea how to fix it. 
Can anybody held?
Anything I can do from my side?

Thanks!

**Comment by fhoehle** [comment]
cc @conda-forge/staged-recipes

**Comment by dbast** [comment]
Seems the conversion was successful, see https://github.com/conda-forge/_r-mutex-feedstock

The appveyor is failing to build + upload, but that is a different issue.

Can the recipe be `noarch: generic`?

**Comment by dbast** [comment]
It was also removed from master here https://github.com/conda-forge/staged-recipes/commit/5b81bc83c23214164f7bea7a983c915e43f7627d

**Comment by fhoehle** [comment]
@dbast yes sure, the recipe is definitely `generic`! Thanks! I'll update.

**Comment by isuruf** [comment]
Fixed by https://github.com/conda-forge/conda-smithy/pull/1100
