### ISSUE TITLE
Package wasmer

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/staged-recipes#8817]
`wasmer` is:
```
...a $X library for executing WebAssembly binaries:

Easy to use: The wasmer API mimics the standard WebAssembly API,
Fast: wasmer executes the WebAssembly modules at native speed,
Safe: All calls to WebAssembly will be fast, but more importantly, completely 
      safe and sandboxed.
```

...where it looks like `$X` can be replaced by:
```
- Rust
- C/C++
- PHP
- Python
- Ruby
- Go
```

links:
- https://pypi.org/project/wasmer/
- https://wasmer.io/
- https://news.ycombinator.com/item?id=19670826

related feedstocks:
- https://github.com/conda-forge/staged-recipes/pull/8816
- https://github.com/conda-forge/snapshottest-feedstock/pull/1

**Comment by bollwyvl** [comment]
As of a few days ago, (some parts) of `wasmer@master` will compile with `rust` stable. Some of the language-specific extensions (notably python) still require nightly. Still very interesting!

**Comment by bollwyvl** [comment]
It looks like wasmer is working up to release a `1.0.0` (currently in alpha). Now that our rust situation is a bit more normalized, it's probably worth taking another shot at this...

**Comment by bollwyvl** [comment]
[Wasmer 1.0 is out](https://medium.com/wasmer/wasmer-1-0-3f86ca18c043)! I'll probably take a look at this soon, don't know how much has changed since #9311

**Comment by wolfv** [comment]
@bollwyvl count me in! very interested in this as well!

**Comment by bollwyvl** [comment]
@wolfv  my current best-effort is here: https://github.com/conda-forge/staged-recipes/pull/13622

- wasmer expects a newer osx, so kinda hard blocked there
- haven't tried windows :blush: 
- haven't done the whole third-party license dance, sorted, though have made pretty good progress on e.g. [geckodriver](https://github.com/conda-forge/geckodriver-feedstock/blob/master/recipe/meta.yaml) on tightening up that process

I think to get it really working to my satisfaction, at least [wasmer-python](https://github.com/wasmerio/wasmer-python) would need to be tackled... having at least the runtime (and maybe `wapm`) up would be huge.

**Comment by wolfv** [comment]
Awesome. I've been thinking we should have a wasm architecture for conda and ship our core library stack for wasm as well. 
I played around with emscripten and emcc and it seems quite doable :)

But there are also a lot of unsolved questions

**Comment by bollwyvl** [comment]
> have a wasm architecture for conda 

I don't know enough to know what it would mean for it to be a new architecture, a new `noarch: wasm`, a new channel, or who knows what. I feel like, even if the _toolchain_ lives on conda-forge, if this was ever going to the browser, then it would have to be its own channel, e.g. `wasm-forge` somehow... though maybe this is more of a "metachannel" problem.

> and ship our core library stack for wasm as well

I think this is a very worthy goal. To my knowledge, there isn't a "The Package Manager" for webassembly: wasmer has `wamp`, and pyodide has... it's own thing. On jyve, which only targets the browser, I just (ab)use `npm`/`webpack`. Whether we're talking a baseline of `conda-on-pyodide` or `microwamba`, it seems like it would be a significant step forward if it worked with all/most of the existing conda tooling e.g. `conda-lock`, and could be a "free" output of a feedstock, after a migration.

**Comment by bollwyvl** [comment]
If anybody's tracking this, but not the current 1.0.1 PR (#13622), it's ready for review!

**Comment by bollwyvl** [comment]
Welp, we did it: https://github.com/conda-forge/wasmer-feedstock

Please chime in over there, anybody listening, if you have things you want to see... and better still if you can help! There's a lot to do!
