### ISSUE TITLE
Conda-build 1.21.2 does not run test phase

### ISSUE THREAD

**Issue by Korijn** [conda-forge/staged-recipes#884]
The test phase is no longer running in the latest conda-build. I guess we have to pin the version to one that works (1.21.0 is the last one that works properly for me).

Lots of regressions and bugs over the last two weeks. :/

**Comment by jjhelmus** [comment]
As far as I know `conda build` still runs the test phase, just the package that gets installed in the test environment may not be the one that was just built.  This has been reported upstream, conda/conda-build#1051.

**Comment by msarahan** [comment]
Yeah, I'm pretty sure enough of the tests have inverted logic (make sure that this raises an exception when things go wrong) that tests are definitely running.  This may also be related to https://github.com/conda/conda-build/issues/1032 - where conda-build does not error out when it can't create an environment.

**Comment by Korijn** [comment]
Not on my (Windows) machine (and AppVeyor)! I'll put up a reproducing example tomorrow.

**Comment by jjhelmus** [comment]
You are likely running into a different bug than I was thinking of @Korijn, sorry for the confusion.  If you can provide an example I think it would be beneficial to us all.

**Comment by jakirkham** [comment]
Is this still an issue? do we have a reproducer or build log? If so, can we please raise this upstream? If not, can we please close it?

**Comment by jakirkham** [comment]
As we are now (and for some time) have been on `conda-build` 2, I don't think this is an issue any longer. Am closing it out.
