### ISSUE TITLE
OS X "El Capitan": DYLD_LIBRARY_PATH not working unless SIP is turned off

### ISSUE THREAD

**Issue by frol** [conda-forge/staged-recipes#913]
I would like to just bring awareness of that `DYLD_LIBRARY_PATH` or `DYLD_FALLBACK_LIBRARY_PATH` are not working in OS X 10.11 "El Capitan" unless [System Integrity Protection (SIP)](https://en.wikipedia.org/wiki/System_Integrity_Protection) is turned off.

While it is possible to [disable SIP](http://www.macworld.com/article/2986118/security/how-to-modify-system-integrity-protection-in-el-capitan.html), it is certainly not the best way.

I'm quite new to OS X "features", so forgive me if I'm too late for the party.

**Comment by RSully** [comment]
I haven't used conda on OSX yet (I plan to), but what problems does this cause?

**Comment by frol** [comment]
@RSully `DYLD_LIBRARY_PATH` are usually used in recipes as a workaround when `RPATH` is not set correctly and package relies on conda prefix detection/patching, so it needs a help to find shared libraries installed into conda environment when executing tests, for example.

**Comment by dopplershift** [comment]
To be clear, `DYLD_LIBRARY_PATH` and `DYLD_FALLBACK_LIBRARY_PATH` (and all other `DYLD*` environment variables) are only disabled by SIP for protected binaries--like those in `/usr/bin`.  This means you can't pass them to things that use OSX's bash (like autotools), but they do work for passing to python (and even bash) so long as they aren't the system copies. This is one reason we use cmake to build `libnetcdf`.

**Comment by pelson** [comment]
Thanks for the info @frol. Are there issues we need to address, or is this a general "handy packager info" tidbit? If the latter, perhaps we should start pulling these together into a single document... interested in taking that on in https://github.com/conda-forge/conda-forge.github.io?

In the interests of keeping the issue tracker in some order, I'm going to go ahead and close the issue, but am definitely interested in using issues like this to help us build out our docs.

Thanks!
