### ISSUE TITLE
Restructure feedstock generation

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#915]
We should restructure feedstock generation so that it goes through the whole process with one feedstock and removes it immediately (including pushing the change). This should reduce the need to manually clear staged-recipes when a problem occurs part way. It should also make it easier to determine which recipe is failing and how.

cc @RSully @ocefpaf @pelson

**Comment by pelson** [comment]
Sadly this is how it used to work, but we changed it because TravisCI API regularly froze up on calling the "refresh list of repos" endpoint too frequently. In short, I don't think we can do this, as much as the logic is sound.

**Comment by jakirkham** [comment]
Thanks for the history lesson, @pelson. Must have been before my time or I missed/forgotten the change.

Is there some way we can change the proposal to be more accommodating of this constraint? The best I can think of is to fail more gracefully, later, and with a clearer message. Basically, IMHO if we can't clear all the recipes automatically, we would be better off clearing at least some of them (if possible). Also, it would help if this failure would be accompanied with a message say which recipe failed and what step it failed. Thoughts? Alternative proposals?

**Comment by pelson** [comment]
The pertinent diff https://github.com/conda-forge/staged-recipes/commit/c20d1c2bb97b64b8a7c4517d56c6fea95062edec#diff-bdaf499dbec1907aa39a82f9e198d443.

> Alternative proposals?

Indeed. A very sound question 😄 . Technically, now that we know what we know, and have got our own services such as the linter, it would be perfectly achievable to drop the whole CI thing for moving recipes out into their own feedstocks and just stand up a watching service which does it for us.

I'm not going to do anything about this proposal currently - I'm fairly comfortable with the approach currently taken, though I do completely agree that it would be *preferable* to change the order, in practice it doesn't work as well as the current approach.

**Comment by jakirkham** [comment]
So, the main thing to me is that Travis CI's API is getting pretty unreliable and that it may sporadically get one package done or not. Right now we are taking these out manually when we see they are done. I would much rather we take the one completed one and remove it automatically even if the rest aren't complete and Travis CI's API is totally uncooperative.

cc @ocefpaf

**Comment by jakirkham** [comment]
So now that we reuse the Travis CI token, would it actually be practical to do one removal commit per conversion?

Sorry to keep raising this, but it is an acute pain point of staged-recipes and it would be great if we could address it somehow.

**Comment by jakirkham** [comment]
Maybe PR ( https://github.com/conda-forge/staged-recipes/pull/1466 ) will act as a practical solution to this problem.

**Comment by pelson** [comment]
> So now that we reuse the Travis CI token, would it actually be practical to do one removal commit per conversion?

We sure could. Pretty much just nuking the second for loop should do the trick.

**Comment by jakirkham** [comment]
Oh, so do you think it is worth bother with PR ( https://github.com/conda-forge/staged-recipes/pull/1466 )?

**Comment by jakirkham** [comment]
So I took a look at this and I think it may be a bit more work that just removing that loop. Part of it is we need to cleanup the team management code to just make things easier to reason about and manage. ( https://github.com/conda-forge/conda-smithy/issues/297 ) The rest of it should be pretty straightforward once that is done.
