### ISSUE TITLE
Travis CI API issues (backlogged recipes)

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#923]
We are waiting for conversion to go through. Travis CI seems quite slow to start this process. As that has gotten a couple pings, I'm opening an issue here to track status of this issue.

If you have PR on staged-recipes that you are working on actively, please try merging with `master` and removing any recipes from the directory `recipes` that you are not proposing. Commit those changes and push.

**Comment by jakirkham** [comment]
Seems PR ( https://github.com/conda-forge/staged-recipes/pull/757 ) needs some configuration changes before we go ahead. As a result, that is blocking a successful run on staged-recipes, but is not the cause of the long build delay. Am reverting the change with PR ( https://github.com/conda-forge/staged-recipes/pull/926 ), which should fix this issue.

**Comment by jakirkham** [comment]
Reopening until we have actually cleared the backlog. However, measures have been put in place to address it.

**Comment by jakirkham** [comment]
Well, there was an issue with one recipe/`conda-build`, which we resolved with this PR ( https://github.com/conda-forge/staged-recipes/pull/928 ). However, now we find ourselves rate-limited part way through the process. Will remove the completely converted recipes so as to lessen the load in `masters` and people's PRs.

**Comment by jakirkham** [comment]
We have converted some of the feedstocks to recipes completely. However, we were immediately rate-limited, which blocked the process from completing. I have gone back through and checked to see which ones completed successfully. Those that converted fine have been manually removed via this PR ( https://github.com/conda-forge/staged-recipes/pull/929 ). Hopefully, the rest will be resolved in the next conversion. If not, we will do more manually removals until they are cleared.

**Comment by jakirkham** [comment]
Appears one round of manual removals was not enough. We were rate limited again. This PR ( https://github.com/conda-forge/staged-recipes/pull/930 ) does some more manual removals. As there are only 4 recipes left, I'm hopeful we won't need to do this again. 🍀

**Comment by jakirkham** [comment]
We finished our GitHub rate limit when PR ( https://github.com/conda-forge/staged-recipes/pull/929 ) was merged. So, we need to wait ~20mins before restarting the remainder for feedstock conversion.

**Comment by jakirkham** [comment]
Restarting to clear the remainder.

**Comment by jakirkham** [comment]
Had some issues connecting to Travis CI's API. Maybe this [comment]( https://github.com/conda-forge/staged-recipes/issues/900#issuecomment-229246693 ) is relevant. We should revisit this issue, @pelson.

**Comment by jakirkham** [comment]
Ran into the Travis CI API issue again. Have removed the affected recipe via this PR ( https://github.com/conda-forge/staged-recipes/pull/932 ) as it already went through conversion completely.

**Comment by jakirkham** [comment]
Yeah, this is not going away. Now we are hitting it with `python-snappy`. Unfortunately that one is not fully converted. So, we are stuck. I suppose we could remove and readd things in different orders to clear. However, I simply don't have the time to do that. Looks like it is time for a `conda-smithy` bugfix release.

```
CI Summary for conda-forge/python-snappy-feedstock (can take ~30s):
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==0.10.4', 'console_scripts', 'conda-smithy')()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 228, in main
    args.subcommand_func(args)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 156, in __call__
    ci_register.add_project_to_travis(owner, repo)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 147, in add_project_to_travis
    response.raise_for_status()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.travis-ci.org/auth/github
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 186, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmpphm2uuxo__feedstocks/python-snappy-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

cc @pelson

**Comment by jakirkham** [comment]
Maybe we can try this PR ( https://github.com/conda-forge/conda-smithy/pull/204 )?

**Comment by pelson** [comment]
We have drawn the conclusion, based on testing within conda-smithy, that the TravisCI API is currently broken and will be raising it with them. I do not believe we are in a position to merge anything to staged-recipes until this is resolved (or we cease registering with TravisCI).

**Comment by jakirkham** [comment]
Please read the above comment @conda-forge/core.

**Comment by jakirkham** [comment]
I'm going to try restarting Travis CI to see if it will behave better this time. It has been 3hrs since the last run it failed on.

**Comment by jakirkham** [comment]
Nope. Failed again with the same error.

Did Travis CI get back to you, @pelson?

**Comment by jakirkham** [comment]
Though it does appear that `python-snappy` completed feedstock conversion ~3hrs ago. Let's get that one out of here then. Maybe we will get lucky and the rest will clear. 🙏 👼 🍀

**Comment by jakirkham** [comment]
No such luck. We are still having feedstock conversion issues. It is just now we are having them with `redis-py`. At least there is one less recipe sitting in `master`.

**Comment by pelson** [comment]
So it has worked periodically? Even more weird.

**Comment by jakirkham** [comment]
Yeah, I really don't get it. This is one of the reasons I have been giving issue ( https://github.com/conda-forge/staged-recipes/issues/915 ) more thought of late and also this comment ( https://github.com/conda-forge/staged-recipes/pull/849#issuecomment-229942441 ).

For instance, last night we had so many recipes awaiting conversion that builds were taking up to the max time for simple PRs (e.g. pure Python packages with few dependencies and import tests). This actually slowed are ability to try to clear things. Partially as I was unwilling to straight cancel people's builds to do so (fearing outlash).

**Comment by jakirkham** [comment]
FWIW it seems these eventually did clear. 🎉 Though I'm not sure we are not just going to hit this again as soon as we merge. 😒

**Comment by jakirkham** [comment]
Added the aforementioned comment to this issue ( https://github.com/conda-forge/staged-recipes/issues/942 ).

**Comment by jakirkham** [comment]
Appears we are having the same problems again with Travis CI. Reopening...

**Comment by jakirkham** [comment]
Manually removing one recipe that was converted ( https://github.com/conda-forge/staged-recipes/pull/945 ).

**Comment by jakirkham** [comment]
After many retries of running Travis CI, it has finally cleared the remaining recipes.

**Comment by jakirkham** [comment]
Seems to be back. Reopening...

**Comment by jakirkham** [comment]
Problem has been temporarily resolved. The remaining recipes cleared. Closing...

**Comment by jakirkham** [comment]
It seems to be acting more reliably now. Not really sure what changed though. 😕

Also, should note that 1 or 2 recipes normally seem to clear ATM. Though many of the problems had previously IIRC included bigger batches of recipes. Maybe there is something funky with the number of repos we are creating at a time and syncing with Travis CI. Perhaps we need a timeout (or longer timeout) at some point in our process. Something to think about anyways.

**Comment by jakirkham** [comment]
Still have no idea what caused the previous issues, but things are currently rolling smoothly through staged-recipes. Not going to question it, just going to take the win.

**Comment by jakirkham** [comment]
Looks like this is back with `pyferret`. Going to reopen and try retriggering. Feel free to close if this fixes it.

cc @ocefpaf

**Comment by jakirkham** [comment]
Looks like the Travis CI API issue went away after the restart. :confused:

**Comment by jakirkham** [comment]
Appears `botocore` and `postgresql` got stuck thanks to the same Travis CI API issue. Going to restart to see if that fixes it. Feel free to close if it does and I have not.

**Comment by jakirkham** [comment]
Seems the last restart did not fix it. Trying again.

**Comment by jakirkham** [comment]
Appears the third time was a charm. 🍀 Closing until this bites us again. 🐊

**Comment by jakirkham** [comment]
Appears we have another Travis CI API issue w.r.t `win_unicode_console`. Re-opening and restarting.

cc @ocefpaf (for awareness)

**Comment by jakirkham** [comment]
I've added a fresh Travis CI issue ( https://github.com/travis-ci/travis-ci/issues/6284 ) and cc'd you on the ticket @pelson. Let's see if we can figure this out.

**Comment by jakirkham** [comment]
FYI first restart failed. Trying a second one. Though if that doesn't work, maybe someone else can retry later.

**Comment by jakirkham** [comment]
...and a third restart.

**Comment by jakirkham** [comment]
Going to try and clear the completely converted recipes (`alabaster`) with PR ( https://github.com/conda-forge/staged-recipes/pull/989 )

**Comment by jakirkham** [comment]
Still failed because of Travis CI's API (just like the other failures mentioned here). Restarted...

**Comment by jakirkham** [comment]
This is a new one. Still an issue with the Travis CI API, but there is another issue coming out.

```
Repository created, please edit conda-forge.yml to configure the upload channels
and afterwards call 'conda smithy register-github'
fatal: Cannot update paths and switch to branch 'master' at the same time.
Did you intend to checkout 'upstream_with_token/master' which can not be resolved as commit?
Switched to a new branch 'master'
CI Summary for conda-forge/win_unicode_console-feedstock (can take ~30s):
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==0.10.4', 'console_scripts', 'conda-smithy')()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 228, in main
    args.subcommand_func(args)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 156, in __call__
    ci_register.add_project_to_travis(owner, repo)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 147, in add_project_to_travis
    response.raise_for_status()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.travis-ci.org/auth/github
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 186, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmpznykboxq__feedstocks/win_unicode_console-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

**Comment by jakirkham** [comment]
Restarted it several times, which I did not record here as it was getting to noisy. Suffice it to say it took many tries, but it appears to now have cleared.

**Comment by jakirkham** [comment]
Happening again with `setuptools`. Trying to restart.

**Comment by jakirkham** [comment]
Tried a few restarts. No luck yet. 😞

**Comment by jakirkham** [comment]
So, I guess someone restarted it and it cleared. However we now have a new recipe stuck for the same reason. Have restarted it to see if we can clear it.

**Comment by jakirkham** [comment]
Yeah, that's pretty vague. `setuptools` cleared thanks to an assist from @pelson. However, `bob.bio.face` and then soon after `cliff` are stuck due to the same Travis CI API issue we have seen before.

**Comment by jakirkham** [comment]
Ooph. So, the last restart did manage to connect to Travis CI once and then failed on a subsequent connection. However, it was still using `conda-smithy` version `1.0.0`. I have checked to see that `conda-smithy` version `1.0.1` builds are now available for Linux (which they are) and restarted Travis CI. Maybe this next restart will carry them through. 🍀

**Comment by jakirkham** [comment]
Seems this is functioning again for the moment.

**Comment by jakirkham** [comment]
Appears this issue has resurfaced.

**Comment by jakirkham** [comment]
Restarting current build on `master` to see if that will fix it.

**Comment by jakirkham** [comment]
So, this was fixed for a bit, but is now back with `hachoir-core` and `hyperspy`. Going to try restarting.

**Comment by jakirkham** [comment]
Fixed by restart by @patricksnape.

**Comment by jakirkham** [comment]
This is a new one. It's like something went wrong after the sync. 😕

```
Repository registered at github, now call 'conda smithy register-ci'
CI Summary for conda-forge/gperf-feedstock (can take ~30s):
 * Travis doesn't know about the repo, synching (takes a few seconds).
 * Registered on travis-ci
404 Client Error: Not Found for url: https://api.travis-ci.org/repos/conda-forge/gperf-feedstock/key
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 186, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmpiaevjr08__feedstocks/gperf-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

**Comment by jakirkham** [comment]
Restarting seems to have fixed it.

**Comment by jakirkham** [comment]
Same key issue as last time. Going to try restarting.

```
Repository registered at github, now call 'conda smithy register-ci'
CI Summary for conda-forge/zwatershed-feedstock (can take ~30s):
 * Travis doesn't know about the repo, synching (takes a few seconds).
 * Registered on travis-ci
404 Client Error: Not Found for url: https://api.travis-ci.org/repos/conda-forge/zwatershed-feedstock/key
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 186, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmputxy28zh__feedstocks/zwatershed-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

**Comment by jakirkham** [comment]
Restarting fixed it.

**Comment by jakirkham** [comment]
Well, I would say `conda-smithy` needs a fix.

```
Repository registered at github, now call 'conda smithy register-ci'
CI Summary for conda-forge/metafone-feedstock (can take ~30s):
 * Travis doesn't know about the repo, synching (takes a few seconds).
 * Registered on travis-ci
404 Client Error: Not Found for url: https://api.travis-ci.org/repos/conda-forge/metafone-feedstock/key
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 186, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmpdwekouwi__feedstocks/metafone-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

**Comment by jakirkham** [comment]
This is really special. After restarting I got this issue. This was after adding half of the feedstocks. Our rate limit was low. So maybe that is related. Fortunately it was just about to reset. So, will remove the converted ones and try restarting again.

```
[master 67b8111] Re-render the feedstock after CI registration.
 3 files changed, 12 insertions(+), 1 deletion(-)
 rewrite conda-forge.yml (100%)
rm 'recipes/probableparsing/meta.yaml'
CI Summary for conda-forge/python-crfsuite-feedstock (can take ~30s):
 * Registered on travis-ci
 * conda-forge/python-crfsuite-feedstock enabled on CircleCI
 * conda-forge/python-crfsuite-feedstock has been enabled on appveyor
python-crfsuite-feedstock     : Current setting for skipBranchesWithoutAppveyorYml = False.
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==1.0.1', 'console_scripts', 'conda-smithy')()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 236, in main
    args.subcommand_func(args)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 167, in __call__
    ci_register.add_conda_linting(owner, repo)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 284, in add_conda_linting
    hook_by_url = {hook['config'].get('url'): hook for hook in registered
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 285, in <dictcomp>
    if 'url' in hook['config']}
TypeError: string indices must be integers
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 186, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmpoyhooet9__feedstocks/python-crfsuite-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

**Comment by jakirkham** [comment]
See this PR ( https://github.com/conda-forge/staged-recipes/pull/1103 ) for removing the converted recipes.

**Comment by jakirkham** [comment]
Fixed after removal of converted recipes and restart.

**Comment by jakirkham** [comment]
Same sort of error.

```
Repository registered at github, now call 'conda smithy register-ci'
CI Summary for conda-forge/hachoir-metadata-feedstock (can take ~30s):
 * Travis doesn't know about the repo, synching (takes a few seconds).
 * Registered on travis-ci
404 Client Error: Not Found for url: https://api.travis-ci.org/repos/conda-forge/hachoir-metadata-feedstock/key
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 186, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmpc7txkfjo__feedstocks/hachoir-metadata-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

**Comment by jakirkham** [comment]
Again fixed by restart.

**Comment by jakirkham** [comment]
Restarting had fixed. Sorry forgot to close.

**Comment by jakirkham** [comment]
Also, last merge went through cleanly without needing a restart. Maybe it was a temporary issue?

**Comment by mwcraig** [comment]
> last merge went through cleanly without needing a restart. Maybe it was a temporary issue?

Sadly, going through cleanly without a restart does seem to be a temporary thing ;) (nothing is hung up now, just could resist the irony...)

**Comment by jakirkham** [comment]
😭  No it's totally true. I don't know how this got so flaky, but we do seem to be having a lot of issues regularly.

**Comment by jakirkham** [comment]
...but we got a second one through without issues. Maybe...

**Comment by jakirkham** [comment]
Happened with `hiveplot`. 😞 Restarting...

**Comment by jakirkham** [comment]
Restarting fixed it per usual.

**Comment by jakirkham** [comment]
Happened with `perfsync` too.

**Comment by jakirkham** [comment]
Restating fixed it.

**Comment by jakirkham** [comment]
FYI if you find this thread noisy please unsubscribe. I'm trying to keep this in one issue so that is an option. Though I would like to document the problems we are having. I think knowing the types of problems and frequency is very helpful for determining which ones deserve our attention.

**Comment by jakirkham** [comment]
So, I got ambitious and merged a ton of recipes. Unfortunately, it seems Travis CI's API is balking. Restarted a few times without luck thus far. Seems akin to the old [issue]( https://github.com/conda-forge/staged-recipes/issues/923#issuecomment-229826566 ) we had been having.

**Comment by jakirkham** [comment]
Clearing the converted recipes with this PR ( https://github.com/conda-forge/staged-recipes/pull/1113 ) as conversion is still failing for the rest.

**Comment by jakirkham** [comment]
Just for reference, here is the error I'm seeing.

```
Repository created, please edit conda-forge.yml to configure the upload channels
and afterwards call 'conda smithy register-github'
fatal: Cannot update paths and switch to branch 'master' at the same time.
Did you intend to checkout 'upstream_with_token/master' which can not be resolved as commit?
Switched to a new branch 'master'
CI Summary for conda-forge/addict-feedstock (can take ~30s):
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==1.0.1', 'console_scripts', 'conda-smithy')()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 236, in main
    args.subcommand_func(args)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 158, in __call__
    ci_register.add_project_to_travis(owner, repo)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 165, in add_project_to_travis
    headers = travis_headers()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 59, in travis_headers
    response.raise_for_status()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.travis-ci.org/auth/github
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 186, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmpdeltwzu7__feedstocks/addict-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

**Comment by pelson** [comment]
Just opened #1114 which should solve these issues (exchanging this problem for a need for a recurring update of the token - I do not know at what frequency that will be).

**Comment by jakirkham** [comment]
Fixed after a later rerun and handling some GitHub Rate Limit issues ( https://github.com/conda-forge/staged-recipes/issues/1116 ).

**Comment by jakirkham** [comment]
Ran into the [key issue]( https://github.com/conda-forge/staged-recipes/issues/923#issuecomment-233678164 ) again. Trying to restart.

**Comment by jakirkham** [comment]
Got a Travis CI API auth failure when restarting. 😩

**Comment by jakirkham** [comment]
Going to try your PR ( https://github.com/conda-forge/staged-recipes/pull/1114 ), @pelson. Really just tired of seeing this error. Let's see if this helps.

**Comment by jakirkham** [comment]
Had to make a minor tweak to it. See this PR ( https://github.com/conda-forge/staged-recipes/pull/1124 ).

**Comment by jakirkham** [comment]
So, it ran into the Travis CI key issue again. Though it didn't run into the Travis CI auth issue. Partial win?

**Comment by jakirkham** [comment]
Same key issue. It is really weird as I have no problem getting access to this myself.

**Comment by jakirkham** [comment]
Actually, I think I misread it. Must have log blindness. Seems this is failing due to an authentication issue. In other words, this Travis CI API token is already expired. Will revert the change for now. Maybe we should coordinate the next fix so this isn't an issue.

**Comment by jakirkham** [comment]
Happy to close this issue. Thanks for the assist, @pelson.

**Comment by jakirkham** [comment]
Was really hoping to never look at this issue again. See the following traceback. Going to try restarting.

```
Repository registered at github, now call 'conda smithy register-ci'
CI Summary for conda-forge/python-gnupg-feedstock (can take ~30s):
 * Travis doesn't know about the repo, synching (takes a few seconds).
 * Registered on travis-ci
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==1.0.3', 'console_scripts', 'conda-smithy')()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 236, in main
    args.subcommand_func(args)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 159, in __call__
    ci_register.travis_token_update_conda_forge_config(args.feedstock_directory, owner, repo)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 226, in travis_token_update_conda_forge_config
    travis_encrypt_binstar_token(slug, item)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 253, in travis_encrypt_binstar_token
    r.raise_for_status()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.travis-ci.org/repos/conda-forge/python-gnupg-feedstock/key
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 186, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmp1gn377l2__feedstocks/python-gnupg-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

**Comment by jakirkham** [comment]
Restarting fixed this issue per usual. Strange that we are seeing it again.

**Comment by jakirkham** [comment]
Apparently having issues registering on CircleCI now. 😕 

```
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==1.0.3', 'console_scripts', 'conda-smithy')()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 236, in main
    args.subcommand_func(args)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 162, in __call__
    ci_register.add_project_to_circle(owner, repo)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 94, in add_project_to_circle
    response.raise_for_status()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://circleci.com/api/v1/project/conda-forge/newrelic-feedstock/follow?circle-token=xxx
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 186, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmp5bijff_t__feedstocks/newrelic-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

**Comment by jakirkham** [comment]
Looks like restarting fixed that issue. Worth keeping an eye out for more CircleCI registration issues.
