### ISSUE TITLE
gtk3

### ISSUE THREAD

**Issue by stuarteberg** [conda-forge/staged-recipes#9314]
conda-forge already has a package for `gtk2`, but does not yet have `gtk3`.

@pkgw, I noticed that you already have personal recipes for `gtk3` (and the required dependencies) for both Mac and Linux.  Do you think they would make a good starting point for someone to make an official conda-forge feedstock?

From your recipe, it appears the following new packages would be needed in `conda-forge`:

```
$ conda list -n test-gtk3 | grep -v conda-forge
# packages in environment at /miniforge/envs/test-gtk3:
#
# Name                    Version                   Build  Channel
at-spi2-atk               2.26.2               h2fbb542_0    pkgw-forge
at-spi2-core              2.28.0               h2fbb542_0    pkgw-forge
epoxy                     1.5.2                         0    pkgw-forge
gtk3                      3.22.30              h7a40bec_0    pkgw-forge
```

Any quick thoughts or guidance you might have would be appreciated, just to make sure we don't jump down the wrong path.  Thanks!

**Comment by pkgw** [comment]
Yeah, they should be an adequate starting point. A lot of work would be needed if one wanted to add Windows as a supported OS, though.

I recently added Wayland support to my packages; the current list of needed deps is in the file [ORDERED.md](https://github.com/pkgw/conda-recipes/blob/master/ORDERED.md#the-gtk-3-stack) in my repo.

We've definitely talked about this before, and gotten stuck debating package names and whatnot. I forget where that discussion all happened, but it would be worth digging up since it was fairly extensive as I recall.

**Comment by stuarteberg** [comment]
Thanks for your thoughts, @pkgw.

>A lot of work would be needed if one wanted to add Windows as a supported OS, though.

Good to know.  Fortunately, I personally don't need Windows support.

>We've definitely talked about this before ... it would be worth digging up

Could [this be the discussion][1] you're thinking of?

[1]: https://github.com/conda-forge/pygobject-feedstock/issues/8

>the current list of needed deps is in the file [ORDERED.md][2] in my repo.

[2]: https://github.com/pkgw/conda-recipes/blob/master/ORDERED.md#the-gtk-3-stack

Thanks for the pointer!  It's interesting to see another developer's setup for building a large stack of conda packages.  If you're curious, I have a [similar repo][fcr] for my own stack.  Like you, I maintain a [docker container][fcb] for building Linux packages, but I haven't yet tried using a VM for my OSX builds.  I might have to try out your Vagrantfile some time.

BTW, you may be interested in the [little tool I use to build those recipes][pcs].  It helps automate some of the tedious steps involved in building the stack.

[fcr]: https://github.com/janelia-flyem/flyem-conda-recipes
[pcs]: https://github.com/ilastik/publish-conda-stack
[fcb]: https://github.com/janelia-flyem/flyem-build-container

**Comment by pkgw** [comment]
@stuarteberg Thanks for the pointers! The Vagrantfile for macOS is almost not worth it; as you may know, you're only allowed to run macOS VM images on macOS hardware, so it helps with some of the encapsulation/reproducibility but that's it.

**Comment by ryanvolz** [comment]
I took a stab at this over at #10979. Any help is most welcome.

**Comment by isuruf** [comment]
Thanks @ryanvolz
