### ISSUE TITLE
Add jupyter-book to conda-forge

### ISSUE THREAD

**Issue by sodre** [conda-forge/staged-recipes#9315]
This is a package request for [jupyter-book](https://jupyter.org/jupyter-book/intro). This is an interesting package because is a python package that generates a [jekyll skeleton](https://github.com/jupyter/jupyter-book/tree/master/jupyter_book/book_template).

I am adding a package request because [it appears](https://github.com/eventmachine/eventmachine/issues/879) @chrispyles and @ctrueden were trying to use jupyter-book in conda, and we just got an experimental version of [jekyll](https://github.com/conda-forge/rb-jekyll-feedstock) in conda-forge.

I identified the following [ruby runtime dependencies](https://github.com/jupyter/jupyter-book/blob/29bac6cedcd687df5d1c80b76515f0214ebc1d50/jupyter_book/book_template/Gemfile#L3-L10)
<details>
  <summary>ruby dependencies</summary>

  - [x] [rb-github-pages](https://rubygems.org/gems/github-pages) 198 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-github-pages.svg)](https://anaconda.org/conda-forge/rb-github-pages)
    - [x] rb-activesupport 4.2.11.1 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-activesupport.svg)](https://anaconda.org/conda-forge/rb-activesupport)
      - [x] rb-minitest  [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-minitest.svg)](https://anaconda.org/conda-forge/rb-minitest)
      - [x] rb-thread_safe [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-tzinfo.svg)](https://anaconda.org/conda-forge/rb-thread_safe)
      - [x] rb-tzinfo [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-tzinfo.svg)](https://anaconda.org/conda-forge/rb-tzinfo)
    - [x] github-pages-health-check = 1.16.1 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-github-pages-health-check.svg)](https://anaconda.org/conda-forge/rb-github-pages-health-check)
    - [x] jekyll = 3.8.5 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll.svg)](https://anaconda.org/conda-forge/rb-jekyll)
    - [x] jekyll-avatar = 0.6.0 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-avatar.svg)](https://anaconda.org/conda-forge/rb-jekyll-avatar)
    - [x] jekyll-coffeescript = 1.1.1 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-coffeescript.svg)](https://anaconda.org/conda-forge/rb-jekyll-coffeescript)
    - [x] jekyll-commonmark-ghpages = 0.1.5 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-commonmark-ghpages.svg)](https://anaconda.org/conda-forge/rb-jekyll-commonmark-ghpages)
    - [x] jekyll-default-layout = 0.1.4 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-default-layout.svg)](https://anaconda.org/conda-forge/rb-jekyll-default-layout)
    - [x] jekyll-feed = 0.11.0 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-feed.svg)](https://anaconda.org/conda-forge/rb-jekyll-feed)
    - [x] jekyll-gist = 1.5.0 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-gist.svg)](https://anaconda.org/conda-forge/rb-jekyll-gist)
    - [x] jekyll-github-metadata = 2.12.1 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-github-metadata.svg)](https://anaconda.org/conda-forge/rb-jekyll-github-metadata)
    - [x] jekyll-mentions = 1.4.1 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-mentions.svg)](https://anaconda.org/conda-forge/rb-jekyll-mentions)
    - [x] jekyll-optional-front-matter = 0.3.0 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-optional-front-matter.svg)](https://anaconda.org/conda-forge/rb-jekyll-optional-front-matter)
    - [x] jekyll-paginate = 1.1.0 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-paginate.svg)](https://anaconda.org/conda-forge/rb-jekyll-paginate)
    - [x] jekyll-readme-index = 0.2.0 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-readme-index.svg)](https://anaconda.org/conda-forge/rb-jekyll-readme-index)
    - [x] jekyll-redirect-from = 0.14.0 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-redirect-from.svg)](https://anaconda.org/conda-forge/rb-jekyll-redirect-from)
    - [x] jekyll-relative-links = 0.6.0 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-relative-links.svg)](https://anaconda.org/conda-forge/rb-jekyll-relative-links)
    - [x] jekyll-remote-theme = 0.3.1 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-remote-theme.svg)](https://anaconda.org/conda-forge/rb-jekyll-remote-theme)
    - [x] jekyll-sass-converter = 1.5.2 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-sass-converter.svg)](https://anaconda.org/conda-forge/rb-jekyll-sass-converter)
    - [x] jekyll-seo-tag = 2.5.0 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-seo-tag.svg)](https://anaconda.org/conda-forge/rb-jekyll-seo-tag)
    - [x] jekyll-sitemap = 1.2.0  [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-sitemap.svg)](https://anaconda.org/conda-forge/rb-jekyll-sitemap) 
    - [x] jekyll-swiss = 0.4.0 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-swiss.svg)](https://anaconda.org/conda-forge/rb-jekyll-swiss) 
    - [x] jekyll-theme-architect = 0.1.1 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-theme-architect.svg)](https://anaconda.org/conda-forge/rb-jekyll-theme-architect) 
    - [x] jekyll-theme-cayman = 0.1.1 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-theme-cayman.svg)](https://anaconda.org/conda-forge/rb-jekyll-theme-cayman) 
    - [x] jekyll-theme-dinky = 0.1.1 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-theme-dinky.svg)](https://anaconda.org/conda-forge/rb-jekyll-theme-dinky) 
    - [x] jekyll-theme-hacker = 0.1.1 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-theme-hacker.svg)](https://anaconda.org/conda-forge/rb-jekyll-theme-hacker) 
    - [x] jekyll-theme-leap-day = 0.1.1 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-theme-leap-day.svg)](https://anaconda.org/conda-forge/rb-jekyll-theme-leap-day) 
    - [x] jekyll-theme-merlot = 0.1.1 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-theme-merlot.svg)](https://anaconda.org/conda-forge/rb-jekyll-theme-merlot) 
    - [x] jekyll-theme-midnight = 0.1.1 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-theme-midnight.svg)](https://anaconda.org/conda-forge/rb-jekyll-theme-midnight) 
    - [x] jekyll-theme-minimal = 0.1.1 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-theme-minimal.svg)](https://anaconda.org/conda-forge/rb-jekyll-theme-minimal) 
    - [x] jekyll-theme-modernist = 0.1.1 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-theme-modernist.svg)](https://anaconda.org/conda-forge/rb-jekyll-theme-modernist) 
    - [x] jekyll-theme-primer = 0.5.3 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-theme-primer.svg)](https://anaconda.org/conda-forge/rb-jekyll-theme-primer) 
    - [x] jekyll-theme-slate = 0.1.1 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-theme-slate.svg)](https://anaconda.org/conda-forge/rb-jekyll-theme-slate) 
    - [x] jekyll-theme-tactile = 0.1.1 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-theme-tactile.svg)](https://anaconda.org/conda-forge/rb-jekyll-theme-tactile) 
    - [x] jekyll-theme-time-machine = 0.1.1 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-theme-time-machine.svg)](https://anaconda.org/conda-forge/rb-jekyll-theme-time-machine) 
    - [x] jekyll-titles-from-headings = 0.5.1 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-titles-from-headings.svg)](https://anaconda.org/conda-forge/rb-jekyll-titles-from-headings)
    - [x] jemoji = 0.10.2 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jemoji.svg)](https://anaconda.org/conda-forge/rb-jemoji)
    - [x] kramdown = 1.17.0 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-kramdown.svg)](https://anaconda.org/conda-forge/rb-kramdown)
    - [x] liquid = 4.0.0 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-liquid.svg)](https://anaconda.org/conda-forge/rb-liquid)
    - [x] listen = 3.1.5 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-listen.svg)](https://anaconda.org/conda-forge/rb-listen)
    - [x] mercenary ~> 0.3 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-mercenary.svg)](https://anaconda.org/conda-forge/rb-mercenary)
    - [x] minima = 2.5.0 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-minima.svg)](https://anaconda.org/conda-forge/rb-minima)
    - [x] rb-nokogiri [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-nokogiri.svg)](https://anaconda.org/conda-forge/rb-nokogiri)
    - [x] rouge = 2.2.1 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-rouge.svg)](https://anaconda.org/conda-forge/rb-rouge)
    - [x] terminal-table ~> 1.4 [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-terminal-table.svg)](https://anaconda.org/conda-forge/rb-terminal-table)
  - [x] [rb-jekyll-feed  ~> 0.6](https://github.com/conda-forge/rb-jekyll-feed-feedstock)  [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-feed.svg)](https://anaconda.org/conda-forge/rb-jekyll-feed)
  - [x] [rb-jekyll-redirect-from](https://rubygems.org/gems/jekyll-redirect-from) [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-redirect-from.svg)](https://anaconda.org/conda-forge/rb-jekyll-redirect-from)
  - [x] [rb-jekyll-scholar](https://rubygems.org/gems/jekyll-scholar) [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll-scholar.svg)](https://anaconda.org/conda-forge/rb-jekyll-scholar)
    - [x] rb-bibtex-ruby [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-bibtex-ruby.svg)](https://anaconda.org/conda-forge/rb-bibtex-ruby)
    - [x] rb-citeproc-ruby [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-citeproc-ruby.svg)](https://anaconda.org/conda-forge/rb-citeproc-ruby)
    - [x] rb-csl-styles [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-csl-styles.svg)](https://anaconda.org/conda-forge/rb-csl-styles)
    - [x] rb-jekyll  [![Conda Version](https://img.shields.io/conda/vn/conda-forge/rb-jekyll.svg)](https://anaconda.org/conda-forge/rb-jekyll)
</details>

**Comment by ctrueden** [comment]
I was trying to use the [`github-pages` gem](https://help.github.com/en/articles/setting-up-your-github-pages-site-locally-with-jekyll#keeping-your-site-up-to-date-with-the-github-pages-gem), which depends on `nokogiri`, which needs to build native extensions.

**Comment by sodre** [comment]
@ctrueden, github-pages gem will be a lot of work! I'll start by building the dependencies that have native extensions. Are you running on osx by any chance?

**Comment by sodre** [comment]
@ctrueden, you should be able to install nokogiri from conda-forge now...

**Comment by ctrueden** [comment]
Wow @sodre, you are a powerhouse. The new `rb-github-pages` conda package works for me for  developing my GitHub-Pages-based sites locally from within a conda environment. It was as simple as:

```
conda create -n gh-pages rb-github-pages
conda activate gh-pages
bundle install
bundle exec jekyll serve
```

Thank you so much for all your hard work!

**Comment by sodre** [comment]
@ctrueden, I am glad it worked!

**Comment by sodre** [comment]
@krinsman, Are you trying to use Jupyter Book with Conda? If so, this is the issue to follow.

**Comment by krinsman** [comment]
@sodre Yeah, I was trying to do exactly that. Thanks for the ping!

**Comment by ma-sadeghi** [comment]
I wonder what the status of this issue is. Is there a reason jupyter-book is not on conda-forge yet?

**Comment by phaustin** [comment]
see https://github.com/conda-forge/staged-recipes/pull/12516#issuecomment-763272722

**Comment by moorepants** [comment]
jupyter-book will now be available, as per this PR https://github.com/conda-forge/staged-recipes/pull/13989

**Comment by phaustin** [comment]
hallelujah!
