### ISSUE TITLE
Add snakemake to conda-forge

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/staged-recipes#9353]
Just another potential recipe for the pile: [`snakemake`](https://bitbucket.org/snakemake/snakemake/src/master/) is a workflow manager that combines general make patterns and python. There's a bioconda build but nothing as yet on default.

**Comment by dbast** [comment]
There have been discussions in the past in some PRs. The last one was https://github.com/conda-forge/staged-recipes/pull/7899

**Comment by pmlandwehr** [comment]
Looks like the maintainer is by-and-large against it. I disagree, but if they have a fixed position on it that's probably that for now. :(
