### ISSUE TITLE
Package CythonGSL

### ISSUE THREAD

**Issue by mmb90** [conda-forge/staged-recipes#938]
I have a package ([SLDA](https://github.com/Savvysherpa/slda)) that I'd like to put on conda-forge but it depends on [CythonGSL](https://github.com/twiecki/CythonGSL) which is not available on conda-forge. I'd be happy to help make a recipe for CythonGSL. Thoughts @twiecki (author of CythonGSL)?

**Comment by twiecki** [comment]
Sure, that sounds great. Do we need to merge anything into CythonGSL?

**Comment by mmb90** [comment]
No, I don't think we will have to. I'll find some time in the next few days and make the recipe for it. If all goes well you won't have to do anything but I'll let you know if I need help. I'll add both of us as recipe maintainers. Thanks.

**Comment by pelson** [comment]
Definitely no objections from doing this 👍 
In the interests of reducing the noise, I'm going to close this issue. Feel free to continue discussing here, and if you have any questions, happy to be pinged.

Thanks,
