### ISSUE TITLE
Pushing to regro-cf-autotick-bot branch

### ISSUE THREAD

**Issue by micknudsen** [conda-forge/staged-recipes#9522]
I was recently asked by the `regro-cf-autotick-bot` to [review a PR](https://github.com/conda-forge/slicedimage-feedstock/pull/1). It needs a few changes, and the PR page says:

> Add more commits by pushing to the 4.0.4 branch on regro-cf-autotick-bot/slicedimage-feedstock.

However, when I follow the instructions, I get the following:

```
$ git push --set-upstream origin regro-cf-autotick-bot-4.0.4
fatal: remote error:
  You can't push to git://github.com/regro-cf-autotick-bot/slicedimage-feedstock.git
  Use https://github.com/regro-cf-autotick-bot/slicedimage-feedstock.git
```

and when I switch to `https`, I am prompted for username and password (which are then rejected).

I may be missing something obvious here. This is my first time trying to update a recipe.

**Comment by xhochy** [comment]
FYI: These issues are best reported at https://github.com/conda-forge/conda-forge.github.io/ (can someone transfer it there?)

You can only push to the branch the PR was made from, which is in your case `4.0.4` (you used the wrong one in your example). All other branches will lead to a permission denied. Also you should try to use the ssh remote, i.e. `git@github.com:conda-forge/slicedimage-feedstock.git` (without `git://`) to push this.

A more convenient alternative would be to use [hub](https://github.com/github/hub) which can checkout the correct branch with remote: `hub pr checkout 12` where 12 is the ID of the PR.

**Comment by micknudsen** [comment]
Thanks for your help. Somehow I managed to overcomplicate things instead of just `pushing to 4.0.4 branch on regro-cf-autotick-bot/slicedimage-feedstock` as I was told...
