### ISSUE TITLE
PyPi tarball link in example meta.yaml?

### ISSUE THREAD

**Issue by aewallin** [conda-forge/staged-recipes#9619]
ping @conda-forge/staged-recipes

the example meta.yaml tries to build an URL from the package name and version like so:
https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz

but it seems PyPi has changed and the download URLs are formatted as, for example:
https://files.pythonhosted.org/packages/b9/63/3a998237dde66b844a5f3d0d90f62dcfde668ed5f0fc8257c7d57023f8b4/AllanTools-2019.9.tar.gz

FWIW the "b9" and "63" might come from the beginning of the BLAKE2-256 hash.
and that is followed by the SHA256.

**Comment by isuruf** [comment]
No, they haven't changed it. For eg: https://pypi.io/packages/source/A/AllanTools/AllanTools-2019.9.tar.gz works.

**Comment by rsokl** [comment]
I am also [hitting this issue](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=79895&view=logs&jobId=10bda42a-d420-5c28-a43f-bc4e66405e5c&taskId=bef775d0-a1a2-55a3-9721-17147029baf0&lineStart=459&lineEnd=459&colStart=1&colEnd=110).

Project: https://pypi.org/project/custom-inherit/

Generated link (broken): https://pypi.io/packages/source/c/custom-inherit/custom-inherit-2.2.1.tar.gz

Link that actually works: https://files.pythonhosted.org/packages/1a/d8/48d163780fc3e71b6eef1a33bda8282e28dafc8dc08ccbbec1c8e848f926/custom_inherit-2.2.1.tar.gz

**Comment by isuruf** [comment]
Following works https://pypi.io/packages/source/c/custom-inherit/custom_inherit-2.2.1.tar.gz

**Comment by rsokl** [comment]
This was not working earlier (a separate person verified this) - it might be  useful to figure out why this doesn't seem to always work.
