### ISSUE TITLE
Adding CUDA builds

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#9773]
For use cases like building CUDA enabled packages, it would be useful to respect and use multiple Docker images based on those listed in `conda_build_config.yaml`'s `docker_image` variant.

**Comment by jakirkham** [comment]
I think we will need to figure out what all needs to be built and then extract out portions based on which `docker_image` is used. That way we can build everything that requires one `docker_image` in that image and then proceed to the next one. Though not entirely sure how we do this extract part. If other people have thoughts, please feel free to chime in. 🙂

**Comment by isuruf** [comment]
Instead of using different docker images, we can just use one docker image and install nvcc using https://github.com/conda-forge/cudatoolkit-dev-feedstock/

**Comment by jakirkham** [comment]
From a technical point, it's probably better if we can use the same strategy in both places (feedstocks and staged-recipes) lest we run into bugs that occur only in one of the environments and not the other.

**Comment by isuruf** [comment]
We could use the same installation in the linux-anvil-cuda images without relying on the cuda installation from nvidia.

**Comment by jakirkham** [comment]
It can be a little tricky to install the toolchain correctly. So there's some value in having the toolchain preinstalled in the Docker image ready to go. Plus there's a really good support story there.

**Comment by isuruf** [comment]
> It can be a little tricky to install the toolchain correctly.

AFAIK, `cudatoolkit-dev` works fine.

**Comment by jakirkham** [comment]
FWIW that was more of a general comment. Not about `cudatoolkit-dev` specifically.

**Comment by jakirkham** [comment]
We could also just add a few more Azure builds that use these other images. Even if most of the time they are not used.

**Comment by jakirkham** [comment]
...or perhaps even just one job that cycles through the different CUDA builds.

**Comment by jakirkham** [comment]
FWIW I started some work on this last point in PR ( https://github.com/conda-forge/staged-recipes/pull/9804 ). Probably could use some help from others.

**Comment by isuruf** [comment]
> We could also just add a few more Azure builds that use these other images. Even if most of the time they are not used.

This is not scalable. @scopatz and others wanted to add CentOS 7 docker images and this means we'll have to do 4 x 2 (4 for each cuda version, 2 for each centos version, etc).

Is it hard to get docker on docker working?

**Comment by jakirkham** [comment]
Have you looked at the PR?

**Comment by isuruf** [comment]
You mean https://github.com/conda-forge/staged-recipes/pull/9804 ?

**Comment by jakirkham** [comment]
Yes

**Comment by isuruf** [comment]
Isn't it creating 3 more jobs?

**Comment by jakirkham** [comment]
Please take a look at the PR.

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/conda-forge/staged-recipes/pull/13469 )
