### ISSUE TITLE
Github limit reached

### ISSUE THREAD

**Issue by 183amir** [conda-forge/staged-recipes#993]
I don't why everytime I merge this damned `bob.ip.flandmark` it breaks the master while it is green in its pull request but here we go: https://travis-ci.org/conda-forge/staged-recipes/jobs/143516959
There is also an empty repository here: https://github.com/conda-forge/bob.ip.flandmark-feedstock
Sorry for the inconvenience but could you guys fix it please?

**Comment by patricksnape** [comment]
I re-ran the travis job and the repo is now populated.

**Comment by 183amir** [comment]
Thank you. I re-ran it too but I think I should have waited first.

**Comment by jakirkham** [comment]
Yeah, this is less than ideal. Was it actually GitHub API rate limiting or was it Travis CI API issues. We have been having a lot of the latter lately and are trying to sort it out.

**Comment by 183amir** [comment]
This one failed too with the same error: https://travis-ci.org/conda-forge/staged-recipes/jobs/143872253
I think I need to wait a few hours and run it again.

**Comment by jakirkham** [comment]
So, the previous problem may have been the GitHub API rate limit. However, the problem shown in this last build is a different problem and is due the Travis CI API being a bit flaky. This is evidenced by this line. We are tracking these problems in a different issue ( https://github.com/conda-forge/staged-recipes/issues/923 ). As a result, am going to close this one out. Hope that is ok.

```
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.travis-ci.org/auth/github
```
