### ISSUE TITLE
Error while running run_docker_build.sh

### ISSUE THREAD

**Issue by mwilson8** [conda-forge/staged-recipes#9961]
When executing `staged-recipes/.circleci/run_docker_build.sh`,  I've gotten this error multiple times, even after rebasing from the upstream master 
```Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
+ export FEEDSTOCK_ROOT=/home/conda/staged-recipes
+ FEEDSTOCK_ROOT=/home/conda/staged-recipes
+ export CI_SUPPORT=/home/conda/staged-recipes/.ci_support
+ CI_SUPPORT=/home/conda/staged-recipes/.ci_support
/home/conda/staged-recipes/.circleci/build_steps.sh: line 48: CONFIG: unbound variable
```
https://github.com/conda-forge/staged-recipes/blob/master/.circleci/build_steps.sh#L48

I'm unsure of how to fix this @conda-forge/staged-recipes

**Comment by isuruf** [comment]
cc @jakirkham

**Comment by jakirkham** [comment]
We could set the `CONFIG` to a default if it is not set by the user.

**Comment by mwilson8** [comment]
Can I export `CONFIG` to solve this problem? If so, what value?

**Comment by mwilson8** [comment]
`export CONFIG="osx64"` seems to have it working for me

**Comment by Midnighter** [comment]
I just run into this problem as well when trying to test a recipe locally. Could this be documented somewhere? I don't see any mention of it at https://conda-forge.org/docs/maintainer/adding_pkgs.html#running-tests-locally-for-staged-recipes

**Comment by beckermr** [comment]
Yes. Let’s add docs

**Comment by Midnighter** [comment]
I'm happy to make a PR but I'm not sure to which repo.

**Comment by beckermr** [comment]
Ahhhh to the conda forge GitHub io repo that holds the main documentation.
